# -*- coding: utf-8 -*-
"""
Generates, from the resolved model (workbook + catalogue), the schema of
Khalidiyah's forms (Khaldia_2_reviewed.xlsx):

  0156  khalidiyah_forms_option_lists     the ref_khld_* tables, the first lists
  0157  khalidiyah_forms_option_lists_2   the other lists, and the check over all
  0158  khalidiyah_forms_shared           person.other_id_number, attachment.field_code,
                                          the question map, the file fields, the rules
                                          between fields as data, and their trigger
  0159  khalidiyah_forms_tables           the first tables
  0160  khalidiyah_forms_tables_2         the other tables, the junctions, RLS, the
                                          standard triggers, the indexes, the check

and, from what the catalogue says changed after the build (its ADDED,
`was`, `published` and ORDER_SINCE entries -- model.build(upto=...)):

  0165  khalidiyah_partner_volunteers     F214 (does a partner provide
                                          volunteers) and F215 (a volunteer's
                                          partner association), their rules
  0167  khalidiyah_publish_campaigns_sessions
                                          is_published on FORM-07 and FORM-14,
                                          and both on the public page

0156-0160 are generated from the model as it stood at 0164, so the files
already applied are reproduced whatever the catalogue has gained since.

Split so each is small enough to apply through the MCP as one exact text,
and so no transaction runs out of lock slots (0153's header).

Run from the repository root:  python supabase/khalidiyah/gen_schema.py
Writes LF only (newline=''), per CLAUDE.md rule 5, as PENDING_<nnnn>_<name>.sql.
Once a file is applied and renamed to its ledger version it is never
rewritten: the script checks it still reproduces it byte for byte instead,
and fails if it does not -- a later change is a later migration.
"""
import glob, json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import catalogue as C
from model import build

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
m = build(upto='0164')


def q(s):
    return "'" + s.replace("'", "''") + "'"


FORM_OF = {fm.table: fm for fm in m.forms.values()}
PERSON_TABLES = [fm.table for fm in m.forms.values() if any(f.kind == 'ident' for f in fm.fields)]
USED = list(m.lists_used)
HALF = (len(USED) + 1) // 2
TABLE_SPLIT = C.TABLES.index('khld_guidance_session')   # 0159 up to it, 0160 from it
OPT_TABLES = [t for t in C.TABLES if m.questions[t]]


# ═══ 0156 / 0157 — the lists ════════════════════════════════════════════════
def list_inserts(lists):
    out = []
    for l in lists:
        out.append('\n-- ref_khld_%s (%s)\n' % (l, ', '.join(m.lists_used[l])))
        out.append('insert into public.ref_khld_%s (code, label_en, label_ar, sort_order, allows_free_text) values\n' % l)
        rows = ['  (%s, %s, %s, %d, %s)' % (q(C.code_of(c)), q(en), q(ar), i, 'true' if C.free(c) else 'false')
                for i, (c, en, ar) in enumerate(C.LISTS[l], start=1)]
        out.append(',\n'.join(rows) + ';\n')
    return ''.join(out)


def lists_sql_1():
    n_opts = sum(len(C.LISTS[l]) for l in USED)
    n_free = sum(1 for l in USED for c, _e, _a in C.LISTS[l] if C.free(c))
    return """-- ═══════════════════════════════════════════════════════════════════════════
--  0156 — Khalidiyah's forms, the option lists: one ref_khld_* table per list
--
--  GENERATED by supabase/khalidiyah/gen_schema.py from workbook.py (the one
--  reading of Khaldia_2_reviewed.xlsx) and catalogue.py. Do not edit; edit
--  the catalogue and regenerate. This file creates all %(n)d tables and seeds
--  the first %(h)d; 0157 seeds the rest and checks all of them.
--
--  %(n)d lists, %(o)d options, both labels verbatim from the 'Forms needed' sheet
--  in the sheet's order. model.py holds every option to the option cell of
--  every field that reads it, both ways: an option the sheet does not have
--  fails the build, and so does text in a cell no option accounts for.
--  Three fields have no option cell of their own and read a list by the
--  reviewer's note: F060 (Yes / No, a boolean), F061 (the nationality list
--  "as in other forms") and F148 ("options = FORM-12 <F064> list").
--
--  Same shape as every ref_ table (0002, 0122, 0141): code, label_en,
--  label_ar, sort_order, is_active, allows_free_text, the standard block and
--  triggers, read by everyone signed in, written by a coordinator. A list the
--  sheets repeat on several forms, English and Arabic alike, exists once
--  (sex, nationality, disability, id_type, product_type, event_status ...).
--  allows_free_text is true for %(f)d options, every "Other": the record's
--  <field>_other column, or a junction row's option_other, must say what it
--  was (the "Other (please specify)" convention, OQ-53).
--
--  Yes / No questions are boolean columns and the 1-5 scales integer
--  columns, both labelled from the sheet in the locale, not lists.
-- ═══════════════════════════════════════════════════════════════════════════

do $outer$
declare t text;
begin
  foreach t in array array[
%(names)s
  ] loop
    execute format($f$
      create table public.%%I (
        id               uuid primary key default gen_random_uuid(),
        code             text not null unique,
        label_en         text not null,
        label_ar         text not null,
        sort_order       int  not null default 0,
        is_active        boolean not null default true,
        allows_free_text boolean not null default false,
        created_at       timestamptz not null default now(),
        updated_at       timestamptz not null default now(),
        created_by       uuid references auth.users(id),
        deleted_at       timestamptz
      )$f$, t);
    execute format('create index %%1$s_created_by_idx on public.%%1$I (created_by)', t);
    perform public.attach_standard_triggers(t);
    execute format('alter table public.%%I enable row level security', t);
    execute format($f$create policy ref_read on public.%%I
      for select to authenticated using (true)$f$, t);
    execute format($f$create policy ref_write on public.%%I
      for all to authenticated
      using (public.is_coordinator())
      with check (public.is_coordinator())$f$, t);
  end loop;
end $outer$;
""" % dict(n=len(USED), h=HALF, o=n_opts, f=n_free,
           names=',\n'.join("    'ref_khld_%s'" % l for l in USED)) + list_inserts(USED[:HALF])


def lists_sql_2():
    checks = ',\n'.join("    ('%s', %d, %d)" % (l, len(C.LISTS[l]), sum(1 for c, _e, _a in C.LISTS[l] if C.free(c))) for l in USED)
    return """-- ═══════════════════════════════════════════════════════════════════════════
--  0157 — Khalidiyah's forms, the option lists, the rest (0156's header)
--
--  GENERATED by supabase/khalidiyah/gen_schema.py. The last %(r)d lists, then
--  the check over all %(n)d: every list has exactly the sheet's options and
--  free-text flags, RLS, and its two policies.
-- ═══════════════════════════════════════════════════════════════════════════
""" % dict(r=len(USED) - HALF, n=len(USED)) + list_inserts(USED[HALF:]) + """
-- ── verification ─────────────────────────────────────────────────────────
do $verify$
declare
  r record;
  v_n int;
  v_free int;
begin
  for r in select * from (values
%(checks)s
  ) as x(list, n, free) loop
    execute format('select count(*), count(*) filter (where allows_free_text) from public.%%I where deleted_at is null', 'ref_khld_' || r.list)
      into v_n, v_free;
    if v_n <> r.n or v_free <> r.free then
      raise exception '0157: ref_khld_%% has %% options (%% free text), expected %% (%%)', r.list, v_n, v_free, r.n, r.free;
    end if;
  end loop;
  select count(*) into v_n from pg_class c join pg_namespace s on s.oid = c.relnamespace
   where s.nspname = 'public' and c.relkind = 'r' and c.relname like 'ref\\_khld\\_%%'
     and c.relrowsecurity and (select count(*) from pg_policy p where p.polrelid = c.oid) = 2;
  if v_n <> %(n)d then
    raise exception '0157: %% of %(n)d lists have RLS and both policies', v_n;
  end if;
end $verify$;
""" % dict(checks=checks, n=len(USED))


# ═══ 0158 — what the tables share ═══════════════════════════════════════════
def when_text(f, mm=None):
    mm = mm or m
    parts = []
    for (gid, values) in f.when:
        g = mm.field(gid)
        if g.kind in ('select', 'id_type'):
            labels = [e for c, e, _a in C.LISTS[g.list] if C.code_of(c) in values]
            parts.append('%s is %s' % (gid, ' or '.join(labels)))
        elif g.kind == 'bool':
            parts.append('%s is %s' % (gid, 'Yes' if values == ['true'] else 'No'))
        else:
            parts.append('%s names an activity' % gid)
    return ' and '.join(parts)


def condition(gid, values, mm=None):
    g = (mm or m).field(gid)
    if g.kind in ('select', 'id_type'):
        return {'column': g.col, 'list': g.list, 'codes': values}
    if g.kind == 'bool':
        return {'column': g.col, 'bool': values == ['true']}
    if g.kind == 'record' and values == ['__record__']:
        return {'column': g.col, 'present': True}
    raise ValueError('%s: no rule for %s %s' % (gid, g.kind, values))


def rule_data(mm):
    """The khld_field_rule rows of a model: (table, field) -> (column, required, conditions json, when_text)."""
    out = {}
    for fm in mm.forms.values():
        for f in fm.fields:
            if f.kind in ('multi', 'records') and (f.when or f.required):
                target = 'option:%s' % f.key if f.kind == 'multi' else 'partners'
                conds = [condition(g, v, mm) for g, v in f.when]
                out[(fm.table, f.fid)] = (target, f.required, json.dumps(conds, separators=(',', ':')), when_text(f, mm) or 'always')
                continue
            if not f.when or not f.col or f.kind in ('multi', 'records', 'file', 'shown', 'stamp', 'reference'):
                continue
            if any(mm.field(g).kind == 'record' and v == ['__extra__'] for g, v in f.when):
                continue       # F182: the CHECK khld_contribution_one_contributor says it
            conds = [condition(g, v, mm) for g, v in f.when]
            out[(fm.table, f.fid)] = (f.col, f.required, json.dumps(conds, separators=(',', ':')), when_text(f, mm))
    return out


def rule_row(key, r):
    (t, fid), (col, req, conds, text) = key, r
    return "  (%s, %s, %s, %s, %s, %s)" % (q(t), q(fid), q(col), 'true' if req else 'false', q(conds), q(text))


def rule_rows():
    return [rule_row(k, r) for k, r in rule_data(m).items()]


def shared_sql():
    qrows = ["  (%s, %s, %s, 'option')" % (q(t + '_option'), q(qc), q(lst)) for t in C.TABLES for (qc, lst) in m.questions[t]]
    frows = ['  (%s, %s, %d, %s)' % (q(t), q(fid), mx, 'true' if req else 'false') for (t, fid, mx, req, when) in m.files]
    rules = rule_rows()
    return """-- ═══════════════════════════════════════════════════════════════════════════
--  0158 — Khalidiyah's forms, what the tables share: a third identifier on
--         person, the field a file answers, the question map, the file
--         fields, and the rules between fields as data
--
--  GENERATED by supabase/khalidiyah/gen_schema.py from the catalogue.
--
--  ── person.other_id_number ──
--
--  The three ID-type lists (F144, F151, F156) offer "Other ID", and a person
--  with neither a national ID nor a UNHCR number could not be saved
--  (person_has_identifier). A third identifier is added beside the other
--  two: normalised like the UNHCR number, unique, immutable like them
--  (guard_person_national_id, extended from its LIVE body), no format
--  checked -- no source gives one (06_OPEN_QUESTIONS.md). Sahel Horan and
--  Ramtha never write it, and nothing they read changes.
--
--  ── attachment.field_code ──
--
--  A file-upload field (F017 meeting minutes, F120 attendance sheet ...) is
--  evidence on the record, and the row says which field it answers. Null for
--  every attachment outside Khalidiyah. khld_file_field says which fields
--  take files and how many ("5 max"); guard_khld_attachment_field holds an
--  attachment to it. attachment_entity_type_known gains the new tables,
--  appended to its live definition (a name the retired forms already used
--  is not named twice; the retired names stay for the row that names one).
--
--  ── the rules between fields ──
--
--  Every "Dependency" the sheet states ("if F029 = Yes", "if F126 = Held",
--  "if F194 in (Established, Updated)" ...) is one row of khld_field_rule,
--  generated from the catalogue entry the screen reads too: the field is
--  required while its answer is chosen (when the sheet marks it required),
--  and BLANK while it is not -- a stray value on a branch not taken is
--  refused (the lesson of the first forms, KHALIDIYAH_REPORT.md section 7).
--  FORM-19's consent (F158, "if no then end survey") governs every other
--  answer on that form the same way. guard_khld_rules reads the rows for
--  the table it fires on, so the rule lives once, as data; each refusal is
--  named khld_<field>_required / khld_<field>_not_applicable. The three
--  rules that look at another table -- a person registered on the form the
--  sheet names, a partner who confirmed (F174), a market that was held
--  (F207) -- are written out below. The rules a row trigger cannot see (a
--  multi-select or a partner list that must or must not have rows) are
--  checked by save_khld_record after the children are written (0161).
-- ═══════════════════════════════════════════════════════════════════════════

create temp table _0158_attachment_check_before on commit drop as
  select pg_get_constraintdef(oid) as def
    from pg_constraint where conrelid = 'public.attachment'::regclass and conname = 'attachment_entity_type_known';

-- ── 1. person: a third identifier ─────────────────────────────────────────
alter table public.person add column other_id_number text;
alter table public.person add constraint other_id_number_not_blank check (other_id_number is null or btrim(other_id_number) <> '');
alter table public.person drop constraint person_has_identifier;
alter table public.person add constraint person_has_identifier
  check (national_id is not null or unhcr_number is not null or other_id_number is not null);
create unique index person_other_id_number_key on public.person (other_id_number) where other_id_number is not null;
comment on column public.person.other_id_number is
  'An identity document that is neither a Jordanian national ID nor a UNHCR registration '
  '("Other ID", Khalidiyah FORM-12 / -15 / -17). Trimmed, upper-cased, inner spaces '
  'collapsed; no format checked. Unique; immutable once set. 0158.';

create function public.normalise_person_other_id_number()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.other_id_number is not null then
    new.other_id_number := nullif(upper(regexp_replace(btrim(new.other_id_number), '\\s+', ' ', 'g')), '');
  end if;
  return new;
end $$;
revoke all on function public.normalise_person_other_id_number() from public, anon, authenticated;
create trigger trg_person_other_id_normalise before insert or update of other_id_number on public.person
  for each row execute function public.normalise_person_other_id_number();

-- from its LIVE body (pg_get_functiondef, 26 September 2026), a third branch
create or replace function public.guard_person_national_id()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
begin
  if new.national_id is distinct from old.national_id
     and coalesce(public.current_role()::text, 'participant') not in ('coordinator', 'super_admin') then
    raise exception 'national_id cannot be changed';
  end if;
  if new.unhcr_number is distinct from old.unhcr_number
     and coalesce(public.current_role()::text, 'participant') not in ('coordinator', 'super_admin') then
    raise exception 'unhcr_number cannot be changed';
  end if;
  if new.other_id_number is distinct from old.other_id_number
     and coalesce(public.current_role()::text, 'participant') not in ('coordinator', 'super_admin') then
    raise exception 'other_id_number cannot be changed';
  end if;
  return new;
end $function$;

-- ── 2. evidence: the field a file answers ─────────────────────────────────
alter table public.attachment add column field_code text
  constraint attachment_field_code_shape check (field_code is null or field_code ~ '^F[0-9]{3}$');
create index attachment_entity_field_idx on public.attachment (entity_type, entity_id, field_code);
comment on column public.attachment.field_code is
  'The Khalidiyah Field ID a file answers (F017, F120 ...); null for every other attachment. 0158.';

do $check$
declare
  v_def  text;
  v_add  text := '';
  v_name text;
begin
  select def into v_def from _0158_attachment_check_before;
  if v_def !~ '^CHECK \\(\\(entity_type = ANY \\(ARRAY\\[' or v_def !~ '\\]\\)\\)\\)$' then
    raise exception '0158: attachment_entity_type_known is not the shape this migration appends to: %%', v_def;
  end if;
  foreach v_name in array array[%(tables)s] loop
    if position(format('''%%s''::text', v_name) in v_def) = 0 then
      v_add := v_add || format(', %%L::text', v_name);
    end if;
  end loop;
  v_def := regexp_replace(v_def, '\\]\\)\\)\\)$', v_add || '])))');
  execute 'alter table public.attachment drop constraint attachment_entity_type_known';
  execute 'alter table public.attachment add constraint attachment_entity_type_known ' || v_def;
end $check$;

create table public.khld_file_field (
  table_name  text not null,
  field_code  text not null check (field_code ~ '^F[0-9]{3}$'),
  max_files   int  not null check (max_files between 1 and 20),
  required    boolean not null,
  primary key (table_name, field_code)
);
alter table public.khld_file_field enable row level security;
create policy khld_file_field_read on public.khld_file_field for select to authenticated using (true);
revoke insert, update, delete on public.khld_file_field from anon, authenticated;
comment on table public.khld_file_field is
  'The file-upload fields of the Khalidiyah forms: table, Field ID, how many files (the sheet''s '
  '"5 max"), whether the sheet requires one. Generated from the catalogue. 0158.';
insert into public.khld_file_field (table_name, field_code, max_files, required) values
%(files)s;

create function public.guard_khld_attachment_field()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_max int;
  v_n   int;
begin
  if new.field_code is null or new.deleted_at is not null then
    return new;
  end if;
  select f.max_files into v_max from public.khld_file_field f
   where f.table_name = new.entity_type and f.field_code = new.field_code;
  if v_max is null then
    raise exception '%% is not a file field of %%', new.field_code, new.entity_type
      using errcode = 'check_violation', constraint = 'attachment_field_code_known';
  end if;
  select count(*) into v_n from public.attachment a
   where a.entity_type = new.entity_type and a.entity_id = new.entity_id and a.field_code = new.field_code
     and a.deleted_at is null and a.id <> new.id;
  if v_n >= v_max then
    raise exception '%% takes at most %% files', new.field_code, v_max
      using errcode = 'check_violation', constraint = 'attachment_field_code_max_files';
  end if;
  return new;
end $$;
revoke all on function public.guard_khld_attachment_field() from public, anon, authenticated;
create trigger trg_attachment_khld_field before insert or update of field_code, deleted_at on public.attachment
  for each row execute function public.guard_khld_attachment_field();

-- ── 3. the question map (read by guard_khld_option, 0144) ─────────────────
create table public.khld_question_list (
  table_name    text not null,
  question_code text not null,
  list_name     text not null,
  kind          text not null check (kind in ('option')),
  primary key (table_name, question_code)
);
alter table public.khld_question_list enable row level security;
create policy khld_question_list_read on public.khld_question_list for select to authenticated using (true);
revoke insert, update, delete on public.khld_question_list from anon, authenticated;
comment on table public.khld_question_list is
  'Which ref_khld_ list each multi-select question of each khld_*_option junction reads. '
  'Read by guard_khld_option (0144). Generated from the catalogue. 0158.';
insert into public.khld_question_list (table_name, question_code, list_name, kind) values
%(questions)s;

-- ── 4. the rules between fields, as data ──────────────────────────────────
create table public.khld_field_rule (
  table_name   text not null,
  field_code   text not null,
  column_name  text not null,
  required     boolean not null,
  conditions   jsonb not null,
  when_text    text not null,
  primary key (table_name, field_code)
);
alter table public.khld_field_rule enable row level security;
create policy khld_field_rule_read on public.khld_field_rule for select to authenticated using (true);
revoke insert, update, delete on public.khld_field_rule from anon, authenticated;
comment on table public.khld_field_rule is
  'One row per sheet Dependency, and per required multi-select: the field belongs to the answer '
  'the conditions describe -- [{column, list, codes}] a select whose code is one of these, '
  '[{column, bool}] a boolean, [{column, present}] a link that is set -- all of which must hold '
  '(none: always). Required while they hold when the sheet marks it required; blank while they '
  'do not. column_name is a column (guard_khld_rules), option:<question> (the rows of that '
  'multi-select) or partners (the partner junction), both checked by save_khld_record after the '
  'children are written (0161). Generated from the catalogue. 0158.';
insert into public.khld_field_rule (table_name, field_code, column_name, required, conditions, when_text) values
%(rules)s;

-- Do the conditions of a rule hold for a row? An unanswered governing
-- answer means "not chosen": the field it governs must then be blank.
create function public.khld_rule_on(p_row jsonb, p_conditions jsonb)
returns boolean
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  c      jsonb;
  v_code text;
begin
  for c in select value from jsonb_array_elements(p_conditions) loop
    if c ? 'list' then
      v_code := null;
      if p_row ->> (c ->> 'column') is not null then
        execute format('select code from public.%%I where id = $1', 'ref_khld_' || (c ->> 'list'))
          into v_code using (p_row ->> (c ->> 'column'))::uuid;
      end if;
      if not coalesce(v_code in (select jsonb_array_elements_text(c -> 'codes')), false) then
        return false;
      end if;
    elsif c ? 'bool' then
      if not coalesce((p_row ->> (c ->> 'column'))::boolean = (c ->> 'bool')::boolean, false) then
        return false;
      end if;
    elsif (p_row ->> (c ->> 'column')) is null then
      return false;
    end if;
  end loop;
  return true;
end $$;
revoke all on function public.khld_rule_on(jsonb, jsonb) from public, anon;
grant execute on function public.khld_rule_on(jsonb, jsonb) to authenticated;

create function public.guard_khld_rules()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row  jsonb := to_jsonb(new);
  r      record;
  v_on   boolean;
begin
  for r in select * from public.khld_field_rule
            where table_name = tg_table_name and column_name !~ ':' and column_name <> 'partners' loop
    v_on := public.khld_rule_on(v_row, r.conditions);
    if v_on and r.required and (v_row ->> r.column_name) is null then
      raise exception '%% is required when %%', r.field_code, r.when_text
        using errcode = 'check_violation', constraint = 'khld_' || lower(r.field_code) || '_required';
    end if;
    if not v_on and (v_row ->> r.column_name) is not null then
      raise exception '%% belongs to the answer "%%", which is not chosen, so it must be blank', r.field_code, r.when_text
        using errcode = 'check_violation', constraint = 'khld_' || lower(r.field_code) || '_not_applicable';
    end if;
  end loop;

  -- The four rules that look at another table. Each reads NEW's columns
  -- inside its own table's branch: PL/pgSQL prepares a whole condition, so a
  -- column another table does not have may not appear in a test that fires
  -- on it, even behind a false tg_table_name.
  if tg_table_name in ('khld_market_attendance', 'khld_producer_survey') then
    -- F112 / F206: a vendor registered on FORM-17
    if not exists (select 1 from public.khld_vendor_application s
                    where s.person_id = new.person_id and s.municipality_id = new.municipality_id and s.deleted_at is null) then
      raise exception '%%: the person must be registered on FORM-17', case tg_table_name when 'khld_market_attendance' then 'F112' else 'F206' end
        using errcode = 'check_violation', constraint = 'khld_person_registered';
    end if;
  end if;
  if tg_table_name = 'khld_enterprise_support' then
    -- F197: an owner who asked on FORM-15
    if not exists (select 1 from public.khld_enterprise_request s
                    where s.person_id = new.person_id and s.municipality_id = new.municipality_id and s.deleted_at is null) then
      raise exception 'F197: the enterprise owner must have an attendance request on FORM-15'
        using errcode = 'check_violation', constraint = 'khld_person_registered';
    end if;
  end if;
  if tg_table_name = 'khld_partner_survey' then
    -- F174: "prepopulated <F004> where F116 = Yes"
    if not exists (select 1 from public.khld_partner_contact c
                    where c.partner_id = new.partner_id and c.partnership_confirmed and c.deleted_at is null) then
      raise exception 'F174: the partner must have confirmed the partnership (FORM-04 F116 = Yes)'
        using errcode = 'check_violation', constraint = 'khld_f174_confirmed_partner';
    end if;
  end if;
  if tg_table_name = 'khld_producer_survey' then
    -- F207: "prepopulated FORM-16 <F091> where F154 = Held"
    if not exists (select 1 from public.khld_market k join public.ref_khld_event_status s on s.id = k.status_id
                    where k.id = new.market_id and s.code = 'held' and k.deleted_at is null) then
      raise exception 'F207: the market must be one that was held (FORM-16 F154 = Held)'
        using errcode = 'check_violation', constraint = 'khld_f207_market_held';
    end if;
  end if;
  return new;
end $$;
revoke all on function public.guard_khld_rules() from public, anon, authenticated;
comment on function public.guard_khld_rules() is
  'BEFORE INSERT OR UPDATE on the Khalidiyah tables: the khld_field_rule rows of the table, '
  'and the four rules that look at another table. 0158.';

-- ── 5. the review of a public volunteer registration, stamped ─────────────
create function public.khld_stamp_review()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.application_status is distinct from old.application_status then
    new.reviewed_by := auth.uid();
    new.reviewed_on := now();
  end if;
  return new;
end $$;
revoke all on function public.khld_stamp_review() from public, anon, authenticated;

-- ── verification ─────────────────────────────────────────────────────────
do $verify$
declare
  v_old text;
  v_new text;
  v_name text;
begin
  -- the attachment check kept every table it named, in order, and names the new ones
  select def into v_old from _0158_attachment_check_before;
  select pg_get_constraintdef(oid) into v_new from pg_constraint
   where conrelid = 'public.attachment'::regclass and conname = 'attachment_entity_type_known';
  if position(regexp_replace(v_old, '\\]\\)\\)\\)$', '') in v_new) <> 1 then
    raise exception '0158: the attachment check was not appended to: %%', v_new;
  end if;
  foreach v_name in array array[%(tables)s] loop
    if position(format('''%%s''::text', v_name) in v_new) = 0 then
      raise exception '0158: the attachment check does not name %%', v_name;
    end if;
  end loop;
  -- a person with an other ID alone can be saved and is normalised; one with none cannot
  begin
    insert into public.person (full_name, other_id_number, date_of_birth) values ('0158 probe', ' ab  12 ', '1990-01-01');
    if not exists (select 1 from public.person where other_id_number = 'AB 12') then
      raise exception '0158: other_id_number was not normalised';
    end if;
    raise exception using errcode = 'P0158', message = 'rollback';
  exception when sqlstate 'P0158' then null;
  end;
  begin
    insert into public.person (full_name, date_of_birth) values ('0158 probe', '1990-01-01');
    raise exception '0158: a person with no identifier was saved';
  exception when check_violation then
    if sqlerrm !~ 'person_has_identifier' then raise; end if;
  end;
  if exists (select 1 from public.person where full_name = '0158 probe') then
    raise exception '0158: probe rows survived the rollback';
  end if;
  if (select count(*) from public.khld_field_rule) <> %(n_rules)d or (select count(*) from public.khld_file_field) <> %(n_files)d
     or (select count(*) from public.khld_question_list) <> %(n_q)d then
    raise exception '0158: the rule, file-field or question rows are not the catalogue''s';
  end if;
end $verify$;
""" % dict(tables=', '.join(q(t) for t in C.TABLES), files=',\n'.join(frows), questions=',\n'.join(qrows),
           rules=',\n'.join(rules), n_rules=len(rules), n_files=len(frows), n_q=len(qrows))


# ═══ 0159 / 0160 — the tables ═══════════════════════════════════════════════
def col_line(name, sqltype, notnull, ref):
    tail = ''
    if ref == '@person':
        tail = ' references public.person(id)'
    elif ref == 'now()':
        tail = ' default now()'
    elif ref == 'default false':
        tail = ' default false'
    elif ref and not ref.startswith('@'):
        tail = ' references public.ref_khld_%s(id)' % ref
    return '  %s %s%s%s,' % (name, sqltype, ' not null' if notnull else '', tail)


def table_ddl(t):
    fm = FORM_OF[t]
    meta = fm.meta
    cols = m.columns[t]
    L = ['create table public.%s (' % t,
         '  id uuid primary key default gen_random_uuid(),',
         '  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),']
    if meta.get('ref'):
        L.append('  reference text,')
    if t in PERSON_TABLES:
        L.append('  person_id uuid not null references public.person(id),')
    for (name, sqltype, notnull, ref, comment) in cols:
        L.append(col_line(name, sqltype, notnull, ref))
    if m.published(meta):
        L.append('  is_published boolean not null default false,')
    if meta.get('public'):
        L.append("  application_status text not null default 'approved' check (application_status in ('submitted', 'approved', 'rejected')),")
        L.append('  submitted_publicly boolean not null default false,')
        L.append('  reviewed_by uuid references auth.users(id),')
        L.append('  reviewed_on timestamptz,')
    L += ['  client_uuid uuid unique,',
          '  created_at timestamptz not null default now(),',
          '  updated_at timestamptz not null default now(),',
          '  created_by uuid references auth.users(id) default auth.uid(),',
          '  deleted_at timestamptz,',
          '  constraint %s_id_municipality_key unique (id, municipality_id),' % t]
    if meta.get('ref'):
        L.append('  constraint %s_reference_key unique (municipality_id, reference),' % t)
    for (name, sqltype, notnull, ref, comment) in cols:
        if ref and ref.startswith('@') and ref != '@person':
            L.append('  constraint %s_%s_fkey foreign key (%s, municipality_id) references public.%s(id, municipality_id),' % (t, name, name, ref[1:]))
    for f in fm.fields:
        if f.col and f.kind in ('int', 'money') and 'min' in f.spec:
            L.append('  constraint %s_%s_min check (%s >= %d),' % (t, f.col, f.col, f.spec['min']))
        if f.col and f.kind == 'percent':
            L.append('  constraint %s_%s_0_100 check (%s between 0 and 100),' % (t, f.col, f.col))
        if f.col and f.kind == 'likert':
            L.append('  constraint %s_%s_1_5 check (%s between 1 and 5),' % (t, f.col, f.col))
        if f.kind == 'bool' and f.spec.get('must_be_true'):
            L.append('  constraint %s_%s_yes check (%s is true),' % (t, f.col, f.col))
        if f.kind == 'occasion':
            L.append('  constraint %s_one_occasion check ((campaign_id is null) <> (activity_id is null)),' % t)
    for (tt, name, expr, why) in C.CHECKS:
        if tt == t:
            L.append('  constraint %s check (%s),' % (name, expr))
    L[-1] = L[-1].rstrip(',')
    L.append(');')
    for (tt, uname, expr, where) in C.UNIQUES:
        if tt == t:
            L.append('create unique index %s on public.%s %s%s;' % (uname, t, expr, (' where ' + where) if where else ''))
    L.append('comment on table public.%s is %s;' % (t, q('%s -- %s (%s). 0159.' % (' + '.join(fm.sheets), fm.title_en, meta['short'][0]))))
    if meta.get('ref'):
        prefix, width, datecol = meta['ref']
        args = [q(prefix), q(str(width))] + ([q(datecol)] if datecol else [])
        L.append('create trigger trg_%s_reference before insert on public.%s for each row execute function public.khld_assign_reference(%s);' % (t, t, ', '.join(args)))
    names = [c[0] for c in cols]
    triples = ["'%s:ref_khld_%s:%s'" % (n, r, n[:-3] + '_other') for (n, st, nn, r, c) in cols
               if r and not r.startswith('@') and r not in ('now()', 'default false') and n.endswith('_id') and n[:-3] + '_other' in names]
    if triples:
        L.append('create trigger trg_%s_other before insert or update on public.%s for each row execute function public.guard_rmth_other(%s);' % (t, t, ', '.join(triples)))
    rules = {f.fid for f in fm.fields if f.when and f.col and f.kind not in ('multi', 'records', 'file', 'shown', 'stamp', 'reference')}
    if rules or t in ('khld_market_attendance', 'khld_producer_survey', 'khld_enterprise_support', 'khld_partner_survey'):
        L.append('create trigger trg_%s_rules before insert or update on public.%s for each row execute function public.guard_khld_rules();' % (t, t))
    if meta.get('public'):
        L.append('create trigger trg_%s_review before update on public.%s for each row execute function public.khld_stamp_review();' % (t, t))
    return '\n'.join(L) + '\n'


def tables_sql_1():
    return """-- ═══════════════════════════════════════════════════════════════════════════
--  0159 — Khalidiyah's forms, the tables (the first %(a)d of %(n)d; 0160 the rest)
--
--  GENERATED by supabase/khalidiyah/gen_schema.py from workbook.py (the one
--  reading of Khaldia_2_reviewed.xlsx) and catalogue.py. Do not edit.
--
--  ── ONE TABLE PER FORM ──
--
--  The reviewed workbook has 24 forms. FORM-03 holds one field (F010, the
--  attempt ID) and the reviewer's note says to merge it into FORM-04, so the
--  two are one table, khld_partner_contact, and F010 is its reference,
--  issued by the database (KHLD-ATT-NN). Every other form is its own table,
--  whose comment names it. Every column is a field of the form; which one is
--  catalogue.FIELDS (Field ID -> kind and column), from which the screens,
--  the locale files and this file are all generated.
--
--  ── WHAT IS NOT A COLUMN ──
--
--  A multi-select is a khld_<table>_option row per tick (question_code = the
--  Field ID in lower case, guard_khld_option). F118 and F131 (partners at a
--  meeting, on an activity) are junction rows. A file upload is an attachment
--  whose field_code is the Field ID (0158). The person fields of FORM-12,
--  FORM-15 and FORM-17 -- name, sex, date of birth, identifier, phone -- are
--  `person`, one person one row (hard rule 6), through khld_ensure_person
--  (0161); the record keeps the ID TYPE the form chose (F144 / F151 / F156),
--  which is how the shared definitions tell a refugee ("ID type = UNHCR
--  registration"). F069 and F111 are the name of the person picked, shown.
--  F012 and F159 ("(Auto gen.) date/time") default to the moment of saving.
--
--  ── THE SHEET'S VALIDATION COLUMN ──
--
--  CHECK constraints: the 0-100 percentages, F040 + F041 = 100 and F042 +
--  F043 = 100 (the reviewer's note on those fields), Jordanian%% + Syrian%%
--  <= 100, completed <= agreed, action days within the campaign's dates, the
--  1-5 scales, the minimums (>= 1, >= 0), dates in order, one contributor,
--  one occasion. The Dependency column is khld_field_rule (0158).
--
--  ── WHO WRITES WHAT ──
--
--  FORM-12 is also a public form: the municipality's owner decided on 26
--  September 2026 that volunteers register themselves. khld_volunteer
--  carries application_status: a staff entry is approved when saved, a
--  public one arrives 'submitted' (khld_register_volunteer, 0161) and counts
--  only once staff approve it -- SO3-0's denominator is "all registered
--  volunteers", and an unreviewed public form would let anyone move it.
--  F060 "if no then disqualified" is a CHECK: a volunteer is a resident. No
--  guardian block: the reviewed FORM-12 asks for none and the owner chose to
--  follow the sheet (06_OPEN_QUESTIONS.md). The three questionnaires
--  (FORM-19, -20, -24) are written by any staff role, enumerators included
--  (is_staff); every other table by coordinators and data entry (can_write).
--
--  ── UNIQUENESS ──
--
--  Entities are unique GLOBALLY, deleted rows included -- a partner per name,
--  a volunteer per person -- so re-entering a deleted one is a restore,
--  never a second row. Things someone took part in are unique while live: a
--  request per person per session, an application per person per market,
--  one attendance a day.
--
--  ── EVERY TABLE ──
--
--  municipality_id (default my_municipality(); the composite (id,
--  municipality_id) key; every link to another Khalidiyah table is a
--  COMPOSITE foreign key and the only key on that pair, so PostgREST sees one
--  relationship and never answers 300), the standard block, client_uuid. The
--  standard triggers, RLS, the junctions' DELETE policy and an index on
--  every foreign key are added in 0160, over all the tables at once.
-- ═══════════════════════════════════════════════════════════════════════════
""" % dict(a=TABLE_SPLIT, n=len(C.TABLES)) + ''.join('\n' + table_ddl(t) for t in C.TABLES[:TABLE_SPLIT])


def option_ddl(t):
    fk = C.CHILD_FK[t]
    j = t + '_option'
    return """create table public.%(j)s (
  %(fk)s uuid not null,
  municipality_id uuid not null default public.my_municipality(),
  question_code text not null,
  option_id uuid not null,
  option_other text,
  created_at timestamptz not null default now(),
  primary key (%(fk)s, question_code, option_id),
  constraint %(j)s_%(fk)s_fkey foreign key (%(fk)s, municipality_id) references public.%(t)s(id, municipality_id)
);
create trigger trg_%(j)s_guard before insert or update on public.%(j)s for each row execute function public.guard_khld_option();
""" % dict(j=j, fk=fk, t=t)


def junction_ddl(j, parent, fk, target, f):
    return """create table public.%(j)s (
  %(fk)s uuid not null,
  partner_id uuid not null,
  municipality_id uuid not null default public.my_municipality(),
  created_at timestamptz not null default now(),
  primary key (%(fk)s, partner_id),
  constraint %(j)s_%(fk)s_fkey foreign key (%(fk)s, municipality_id) references public.%(parent)s(id, municipality_id),
  constraint %(j)s_partner_id_fkey foreign key (partner_id, municipality_id) references public.%(target)s(id, municipality_id)
);
comment on table public.%(j)s is %(c)s;
""" % dict(j=j, fk=fk, parent=parent, target=target, c=q('%s %s: one row per partner (FORM-02). 0160.' % (f.fid, f.label_en)))


def tables_sql_2():
    rows = ["    (%s, %s, false)" % (q(t), q(FORM_OF[t].meta['writer'])) for t in C.TABLES]
    rows += ["    (%s, %s, true)" % (q(t + '_option'), q(FORM_OF[t].meta['writer'])) for t in OPT_TABLES]
    rows += ["    (%s, %s, true)" % (q(j), q(FORM_OF[parent].meta['writer'])) for (j, parent, fk, target, f) in m.junctions]
    n_child = len(OPT_TABLES) + len(m.junctions)
    return ("""-- ═══════════════════════════════════════════════════════════════════════════
--  0160 — Khalidiyah's forms, the tables (the last %(b)d; 0159's header), the
--         junctions, and what every table gets
--
--  GENERATED by supabase/khalidiyah/gen_schema.py. Do not edit.
--
--  Then, over all %(n)d tables and their %(c)d junctions at once: the standard
--  triggers (updated_at, audit, soft delete, no hard delete; audit alone on
--  a junction, which is replaced by delete-then-insert), RLS with the
--  municipality gate on USING and WITH CHECK, a DELETE policy on the
--  junctions and nowhere else (the seventh register row), and an index on
--  every foreign key that has none -- found from pg_constraint, so a key the
--  tables gain cannot be missed.
-- ═══════════════════════════════════════════════════════════════════════════
""" % dict(b=len(C.TABLES) - TABLE_SPLIT, n=len(C.TABLES), c=n_child)
        + ''.join('\n' + table_ddl(t) for t in C.TABLES[TABLE_SPLIT:])
        + '\n-- ── the option junctions ──\n' + ''.join('\n' + option_ddl(t) for t in OPT_TABLES)
        + '\n-- ── the partner junctions ──\n' + ''.join('\n' + junction_ddl(*x) for x in m.junctions)
        + """
-- ── the standard triggers, RLS, the junctions' DELETE policy ─────────────
do $secure$
declare
  r record;
  v_writer text;
begin
  for r in select * from (values
%(rows)s
  ) as t(tbl, writer, is_child) loop
    v_writer := format('public.%%I()', r.writer);
    if r.is_child then
      execute format('create trigger trg_%%1$s_audit after insert or update or delete on public.%%1$I '
                     'for each row execute function public.audit_row()', r.tbl);
    else
      perform public.attach_standard_triggers(r.tbl);
    end if;
    execute format('alter table public.%%I enable row level security', r.tbl);
    execute format('create policy %%1$s_read on public.%%1$I for select to authenticated '
                   'using (public.can_see_municipality(municipality_id))', r.tbl);
    execute format('create policy %%1$s_insert on public.%%1$I for insert to authenticated '
                   'with check (%%2$s and public.can_see_municipality(municipality_id))', r.tbl, v_writer);
    execute format('create policy %%1$s_update on public.%%1$I for update to authenticated '
                   'using (%%2$s and public.can_see_municipality(municipality_id)) '
                   'with check (%%2$s and public.can_see_municipality(municipality_id))', r.tbl, v_writer);
    if r.is_child then
      execute format('create policy %%1$s_delete on public.%%1$I for delete to authenticated '
                     'using (%%2$s and public.can_see_municipality(municipality_id))', r.tbl, v_writer);
    end if;
  end loop;
end $secure$;

-- ── an index on every foreign key, and on municipality_id and created_by ──
do $index$
declare
  r record;
begin
  for r in
    select c.relname as tbl, a.attname as col
      from pg_class c join pg_namespace s on s.oid = c.relnamespace
      join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
     where s.nspname = 'public' and c.relkind = 'r' and c.relname like 'khld\\_%%'
       and c.relname not in ('khld_reference_counter', 'khld_question_list', 'khld_file_field', 'khld_field_rule')
       and (a.attname in ('municipality_id', 'created_by')
            or exists (select 1 from pg_constraint k where k.conrelid = c.oid and k.contype = 'f' and k.conkey[1] = a.attnum))
       and not exists (select 1 from pg_index i where i.indrelid = c.oid and i.indkey[0] = a.attnum)
     order by 1, 2
  loop
    execute format('create index %%I on public.%%I (%%I)', r.tbl || '_' || r.col || '_idx', r.tbl, r.col);
  end loop;
end $index$;

-- ── verification ─────────────────────────────────────────────────────────
do $verify$
declare
  v_n   int;
  v_bad text;
begin
  select count(*), string_agg(c.relname, ', ') into v_n, v_bad
    from pg_class c join pg_namespace s on s.oid = c.relnamespace
   where s.nspname = 'public' and c.relkind = 'r' and c.relname like 'khld\\_%%'
     and c.relname not in ('khld_reference_counter', 'khld_question_list', 'khld_file_field', 'khld_field_rule')
     and (not c.relrowsecurity
          or not exists (select 1 from pg_attribute a where a.attrelid = c.oid and a.attname = 'municipality_id')
          or not exists (select 1 from pg_policy p where p.polrelid = c.oid and p.polcmd = 'r')
          or not exists (select 1 from pg_policy p where p.polrelid = c.oid and p.polcmd = 'a')
          or not exists (select 1 from pg_policy p where p.polrelid = c.oid and p.polcmd = 'w'));
  if v_n <> 0 then raise exception '0160: %% tables lack RLS, a policy or municipality_id: %%', v_n, v_bad; end if;
  select count(*) into v_n from pg_class c join pg_namespace s on s.oid = c.relnamespace
   where s.nspname = 'public' and c.relkind = 'r' and c.relname like 'khld\\_%%'
     and c.relname not in ('khld_reference_counter', 'khld_question_list', 'khld_file_field', 'khld_field_rule');
  if v_n <> %(all)d then raise exception '0160: %% khld tables, expected %(all)d', v_n; end if;
  select count(*) into v_n from pg_policy p join pg_class c on c.oid = p.polrelid
   where c.relname like 'khld\\_%%' and p.polcmd = 'd';
  if v_n <> %(c)d then raise exception '0160: %% DELETE policies, expected %(c)d (the junctions)', v_n; end if;
  select count(*), string_agg(format('%%s.%%s', c.conrelid::regclass, c.conname), ', ') into v_n, v_bad
    from pg_constraint c
   where c.contype = 'f' and c.conrelid::regclass::text like 'khld\\_%%'
     and not exists (select 1 from pg_index i where i.indrelid = c.conrelid and i.indkey[0] = c.conkey[1]);
  if v_n <> 0 then raise exception '0160: unindexed foreign keys: %%', v_bad; end if;
  -- the standard triggers are on every table, and the audit trigger on every junction
  select count(*), string_agg(c.relname, ', ') into v_n, v_bad
    from pg_class c join pg_namespace s on s.oid = c.relnamespace
   where s.nspname = 'public' and c.relkind = 'r' and c.relname like 'khld\\_%%'
     and c.relname not in ('khld_reference_counter', 'khld_question_list', 'khld_file_field', 'khld_field_rule')
     and not exists (select 1 from pg_trigger t where t.tgrelid = c.oid and t.tgname = 'trg_' || c.relname || '_audit');
  if v_n <> 0 then raise exception '0160: tables without an audit trigger: %%', v_bad; end if;
end $verify$;
""" % dict(rows=',\n'.join(rows), all=len(rows), c=n_child))


# ═══ after the build — what the catalogue says changed, migration by migration ══
def delta(old, new):
    """What `new` has that `old` did not: columns, rule rows, publish flags."""
    cols = []
    for t in C.TABLES:
        have = {c[0] for c in old.columns[t]}
        cols += [(t, c) for c in new.columns[t] if c[0] not in have]
    r_old, r_new = rule_data(old), rule_data(new)
    gone = [k for k in r_old if k not in r_new]
    if gone:
        raise SystemExit('a later migration would drop rule rows %s; write that one by hand' % gone)
    added = [(k, r_new[k]) for k in r_new if k not in r_old]
    changed = [(k, r_old[k], r_new[k]) for k in r_new if k in r_old and r_old[k] != r_new[k]]
    pub = [fm.table for fm in new.forms.values() if new.published(fm.meta) and not old.published(fm.meta)]
    jn = lambda mm: [(j, parent, fk, target, f.fid) for (j, parent, fk, target, f) in mm.junctions]
    for q_old, q_new in ((old.questions, new.questions), (jn(old), jn(new)), (old.files, new.files)):
        if q_old != q_new:
            raise SystemExit('a later migration adds a multi-select, a partner list or a file field; teach delta() first')
    return cols, added, changed, pub


def add_column_sql(t, col, new):
    name, sqltype, notnull, ref, comment = col
    f = next(f for fm in new.forms.values() for f in fm.fields if fm.table == t and f.col == name)
    L = ['alter table public.%s add column %s %s;' % (t, name, sqltype)]
    if ref and ref.startswith('@') and ref != '@person':
        L.append('alter table public.%s add constraint %s_%s_fkey foreign key (%s, municipality_id) references public.%s(id, municipality_id);'
                 % (t, t, name, name, ref[1:]))
        L.append('create index %s_%s_idx on public.%s (%s);' % (t, name, t, name))
    elif ref and not ref.startswith('@') and ref not in ('now()', 'default false'):
        L.append('alter table public.%s add constraint %s_%s_fkey foreign key (%s) references public.ref_khld_%s(id);' % (t, t, name, name, ref))
        L.append('create index %s_%s_idx on public.%s (%s);' % (t, name, t, name))
    L.append('comment on column public.%s.%s is %s;' % (t, name, q('%s (added at the owner\'s request, 28 September 2026). 0165.' % comment)))
    if notnull:
        # a required answer on a table that already has rows: every NEW row
        # answers it, and an answer once given is never taken back; the rows
        # saved before the question existed stay unanswered until edited
        # (the edit screen requires it) -- nothing is guessed for them
        L.append('create trigger trg_%s_%s_answered before insert or update of %s on public.%s for each row '
                 'execute function public.guard_khld_answered(%s, %s);' % (t, name, name, t, q(name), q(f.fid)))
    if f.spec.get('volunteers'):
        L.append('create trigger trg_%s_%s_volunteers before insert or update of %s on public.%s for each row '
                 'execute function public.guard_khld_partner_provides_volunteers(%s, %s);' % (t, name, name, t, q(name), q(f.fid)))
    return '\n'.join(L)


def partner_volunteers_sql():
    old, new = build(upto='0164'), build(upto='0165')
    cols, added, changed, pub = delta(old, new)
    if pub:
        raise SystemExit('0165 publishes nothing')
    upd = []
    for (t, fid), (col, req, conds, text), (col2, req2, conds2, text2) in changed:
        upd.append("update public.khld_field_rule set column_name = %s, required = %s, conditions = %s, when_text = %s\n"
                   " where table_name = %s and field_code = %s;" % (q(col2), 'true' if req2 else 'false', q(conds2), q(text2), q(t), q(fid)))
    ins = [rule_row(k, r) for k, r in added]
    n_rules = len(rule_data(new))
    return """-- ═══════════════════════════════════════════════════════════════════════════
--  0165 — Khalidiyah: which partners provide volunteers (F214), and a
--         volunteer's partner association (F215)
--
--  GENERATED by supabase/khalidiyah/gen_schema.py from the catalogue's
--  ADDED and `was` entries (model.build(upto='0165') against '0164').
--
--  The municipality's owner asked on 28 September 2026 for a yes / no on
--  the partners form -- will this partner provide volunteers -- and, on the
--  volunteer form, for the partners who answered yes to be the choices when
--  a volunteer's affiliation is "CSO / association", listed partners only.
--  Neither is in Khaldia_2_reviewed.xlsx, so their Field IDs continue after
--  the sheet's last (F213) and their wording is the owner's request put into
--  words (06_OPEN_QUESTIONS.md OQ-72).
--
--  ── F214, khld_partner.provides_volunteers ──
--
--  Required on the form. The partners saved before the question existed
--  have no answer and none is guessed: a NOT NULL would need one, so
--  guard_khld_answered requires it of every new row and refuses to take an
--  answer back, and an old row is answered when it is next edited.
--
--  ── F215, khld_volunteer.affiliation_partner_id ──
--
--  Asked when F145 is "CSO / association", and then required; F146 (the
--  name typed) is no longer asked for a CSO -- the partner IS the name. Both
--  are khld_field_rule rows, read by guard_khld_rules (0158): F146's row is
--  updated, F215's added. The partner must be live, of the volunteer's
--  municipality (the composite key) and one that provides volunteers
--  (guard_khld_partner_provides_volunteers). A partner who later answers no
--  does not block the edits of a volunteer already linked to them: the
--  guard reads the partner only when the link is set or changed.
--
--  The one volunteer saved before this (a staff entry, CSO, a typed name)
--  keeps its row; its next edit asks for a listed partner and blanks the
--  typed name, which is what the rule says of every CSO volunteer now.
--
--  The public form's side -- the list of those partners, and the
--  registration that carries the choice -- is 0166.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. a required answer on a table with rows ─────────────────────────────
create function public.guard_khld_answered()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_col text := tg_argv[0];
  v_fid text := tg_argv[1];
begin
  if (to_jsonb(new) ->> v_col) is null
     and (tg_op = 'INSERT' or (to_jsonb(old) ->> v_col) is not null) then
    raise exception '%% is required', v_fid
      using errcode = 'check_violation', constraint = 'khld_' || lower(v_fid) || '_required';
  end if;
  return new;
end $$;
revoke all on function public.guard_khld_answered() from public, anon, authenticated;
comment on function public.guard_khld_answered() is
  'BEFORE INSERT OR UPDATE OF <column>: a field added after its table had rows (catalogue.ADDED) '
  'is required of every new row and cannot be blanked once answered; rows from before stay '
  'unanswered until edited. Refuses as khld_<field>_required. 0165.';

-- ── 2. a partner who provides volunteers ──────────────────────────────────
create function public.guard_khld_partner_provides_volunteers()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_col text := tg_argv[0];
  v_fid text := tg_argv[1];
  v_id  uuid := (to_jsonb(new) ->> v_col)::uuid;
begin
  if v_id is null or (tg_op = 'UPDATE' and v_id is not distinct from (to_jsonb(old) ->> v_col)::uuid) then
    return new;
  end if;
  if not exists (select 1 from public.khld_partner p
                  where p.id = v_id and p.municipality_id = new.municipality_id
                    and p.provides_volunteers and p.deleted_at is null) then
    raise exception '%%: the partner must be one that provides volunteers (FORM-02 F214 = Yes)', v_fid
      using errcode = 'check_violation', constraint = 'khld_' || lower(v_fid) || '_provides_volunteers';
  end if;
  return new;
end $$;
revoke all on function public.guard_khld_partner_provides_volunteers() from public, anon, authenticated;
comment on function public.guard_khld_partner_provides_volunteers() is
  'BEFORE INSERT OR UPDATE OF <column>: a partner picked where only partners who provide '
  'volunteers are listed (F215) is one -- live, same municipality, F214 = Yes. Read when the '
  'link is set or changed. Security definer, as guard_khld_rules: the partner is read whoever '
  'saves. Refuses as khld_<field>_provides_volunteers. 0165.';

-- ── 3. the columns ────────────────────────────────────────────────────────
%(cols)s

-- ── 4. the rules between fields ───────────────────────────────────────────
%(upd)s
insert into public.khld_field_rule (table_name, field_code, column_name, required, conditions, when_text) values
%(ins)s;

-- ── verification: the catalogue's rows, and the rules driven, discarded ───
do $verify$
declare
  v_khld uuid := '00000000-0000-4000-8000-0000000000b2';
  v_yes  uuid;
  v_no   uuid;
  v_pid  uuid;
  v_vol  uuid;
  v_row  jsonb;
begin
  if (select count(*) from public.khld_field_rule) <> %(n_rules)d then
    raise exception '0165: the rule rows are not the catalogue''s';
  end if;

  -- a new partner must answer F214
  begin
    insert into public.khld_partner (municipality_id, name, phone, partner_type_id, partner_category_id)
    select v_khld, '0165 probe partner', '0790000165', (select id from public.ref_khld_partner_type limit 1),
           (select id from public.ref_khld_partner_category where code = 'local_association');
    raise exception '0165: a partner without F214 was saved';
  exception when check_violation then
    if sqlerrm !~ '^F214 is required' then raise; end if;
  end;

  begin
    insert into public.khld_partner (municipality_id, name, phone, partner_type_id, partner_category_id, provides_volunteers)
    select v_khld, '0165 probe yes', '0790000165', (select id from public.ref_khld_partner_type limit 1),
           (select id from public.ref_khld_partner_category where code = 'local_association'), true
    returning id into v_yes;
    insert into public.khld_partner (municipality_id, name, phone, partner_type_id, partner_category_id, provides_volunteers)
    select v_khld, '0165 probe no', '0790000166', (select id from public.ref_khld_partner_type limit 1),
           (select id from public.ref_khld_partner_category where code = 'local_association'), false
    returning id into v_no;
    -- an answer cannot be taken back
    begin
      update public.khld_partner set provides_volunteers = null where id = v_yes;
      raise exception '0165: an F214 answer was blanked';
    exception when check_violation then
      if sqlerrm !~ '^F214 is required' then raise; end if;
    end;

    insert into public.person (other_id_number, full_name, date_of_birth, sex) values ('0165 PROBE', '0165 probe', '2000-01-01', 'female')
    returning id into v_pid;
    v_row := jsonb_build_object(
      'municipality_id', v_khld, 'person_id', v_pid,
      'id_type_id', (select id from public.ref_khld_id_type where code = 'other_id'),
      'is_resident', true,
      'nationality_id', (select id from public.ref_khld_nationality where code = 'jordanian'),
      'disability_id', (select id from public.ref_khld_disability where code = 'no_difficulty'),
      'situation_id', (select id from public.ref_khld_situation where code = 'employee'),
      'photo_consent', true,
      'affiliation_id', (select id from public.ref_khld_affiliation where code = 'cso'));

    -- CSO without a partner: F215 required
    begin
      insert into public.khld_volunteer (municipality_id, person_id, id_type_id, is_resident, nationality_id, disability_id,
                                         situation_id, photo_consent, affiliation_id)
      select (r).municipality_id, (r).person_id, (r).id_type_id, true, (r).nationality_id, (r).disability_id, (r).situation_id, true,
             (r).affiliation_id
        from (select jsonb_populate_record(null::public.khld_volunteer, v_row) as r) x;
      raise exception '0165: a CSO volunteer without a partner was saved';
    exception when check_violation then
      if sqlerrm !~ '^F215 is required' then raise; end if;
    end;
    -- CSO with a typed name: F146 not asked
    begin
      insert into public.khld_volunteer (municipality_id, person_id, id_type_id, is_resident, nationality_id, disability_id,
                                         situation_id, photo_consent, affiliation_id, affiliation_partner_id, affiliation_name)
      select (r).municipality_id, (r).person_id, (r).id_type_id, true, (r).nationality_id, (r).disability_id, (r).situation_id, true,
             (r).affiliation_id, v_yes, 'typed'
        from (select jsonb_populate_record(null::public.khld_volunteer, v_row) as r) x;
      raise exception '0165: a CSO volunteer with a typed name was saved';
    exception when check_violation then
      if sqlerrm !~ '^F146 belongs' then raise; end if;
    end;
    -- a partner who does not provide volunteers is refused
    begin
      insert into public.khld_volunteer (municipality_id, person_id, id_type_id, is_resident, nationality_id, disability_id,
                                         situation_id, photo_consent, affiliation_id, affiliation_partner_id)
      select (r).municipality_id, (r).person_id, (r).id_type_id, true, (r).nationality_id, (r).disability_id, (r).situation_id, true,
             (r).affiliation_id, v_no
        from (select jsonb_populate_record(null::public.khld_volunteer, v_row) as r) x;
      raise exception '0165: a partner who provides no volunteers was accepted';
    exception when check_violation then
      if sqlerrm !~ '^F215: the partner must be one that provides volunteers' then raise; end if;
    end;
    -- one who does is accepted
    insert into public.khld_volunteer (municipality_id, person_id, id_type_id, is_resident, nationality_id, disability_id,
                                       situation_id, photo_consent, affiliation_id, affiliation_partner_id)
    select (r).municipality_id, (r).person_id, (r).id_type_id, true, (r).nationality_id, (r).disability_id, (r).situation_id, true,
           (r).affiliation_id, v_yes
      from (select jsonb_populate_record(null::public.khld_volunteer, v_row) as r) x
    returning id into v_vol;
    -- the partner answers no later: the volunteer's other edits still save,
    -- with the link in the SET list as save_khld_record writes it
    update public.khld_partner set provides_volunteers = false where id = v_yes;
    update public.khld_volunteer set photo_consent = false, affiliation_partner_id = v_yes where id = v_vol;
    if not exists (select 1 from public.khld_volunteer where id = v_vol and not photo_consent) then
      raise exception '0165: the edit of a linked volunteer did not save';
    end if;
    raise exception using errcode = 'P0165', message = 'rollback the probes';
  exception when sqlstate 'P0165' then null;
  end;
  if exists (select 1 from public.khld_partner where name like '0165 probe%%') then
    raise exception '0165: probe rows survived the rollback';
  end if;
end $verify$;
""" % dict(cols='\n'.join(add_column_sql(t, c, new) for t, c in cols), upd='\n'.join(upd),
           ins=',\n'.join(ins), n_rules=n_rules)


def publish_sql():
    old, new = build(upto='0166'), build(upto='0167')
    cols, added, changed, pub = delta(old, new)
    if cols or added or changed:
        raise SystemExit('0167 publishes; it adds no field and no rule')
    if pub != ['khld_campaign', 'khld_guidance_session']:
        raise SystemExit('0167 is written for FORM-07 and FORM-14; the catalogue publishes %s' % pub)
    alters = '\n'.join('alter table public.%s add column is_published boolean not null default false;\n'
                       'comment on column public.%s.is_published is %s;'
                       % (t, t, q('On the public page (v_public_khld_whats_on) until it ends; flipped by a coordinator on the '
                                  'record\'s page, never a form field. 0167.')) for t in pub)
    return """-- ═══════════════════════════════════════════════════════════════════════════
--  0167 — Khalidiyah: volunteer campaigns (FORM-07) and counselling sessions
--         (FORM-14) published on the public page
--
--  GENERATED by supabase/khalidiyah/gen_schema.py from the catalogue's
--  `published` entries (model.build(upto='0167') against '0166').
--
--  The municipality's owner found on 28 September 2026 that a volunteer
--  campaign and a counselling session did not appear on the public page
--  once created, and that neither had a way to publish it. Activities
--  (FORM-08) and markets (FORM-16) have had both since 0159 / 0163; these
--  two now have the same: is_published, false until a coordinator flips it
--  on the record's page (save_khld_record refuses it as a form column, 0161,
--  as it does the other two), and a branch each in the public view.
--
--  ── v_public_khld_whats_on ──
--
--  From its last definition, 0163's (generated by gen_views.py; grep -l
--  "view public.v_public_khld_whats_on" supabase/migrations/*.sql lists
--  0152, 0153 and 0163), its twelve columns unchanged in name, type and
--  order, and two appended: end_date (every kind has one) and apply_until
--  -- the last day to apply, for a campaign (F027) and a session (F077),
--  null for an activity or a market, whose sheets ask the public to apply
--  for nothing. The same four filters on the new branches: published, not
--  deleted, the municipality active, not yet ended. A campaign's type is
--  its F125 answers, in the list's order; a session's is its topic (F149).
--  Nothing else about either is published: no sponsor, no executing
--  entity, no status, no counts. `create or replace` keeps the grants; they
--  are stated again below so this file says who reads the view.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. the flag ───────────────────────────────────────────────────────────
%(alters)s

-- ── 2. the public page ────────────────────────────────────────────────────
create or replace view public.v_public_khld_whats_on
with (security_invoker = false) as
select a.id,
       'activity'::text as kind,
       a.activity_name as title,
       a.start_date as on_date,
       null::text as time_from,
       null::text as time_to,
       null::text as place_en,
       null::text as place_ar,
       t.label_en as type_en,
       t.label_ar as type_ar,
       a.description,
       m.slug as municipality_slug,
       a.end_date,
       null::date as apply_until
  from public.khld_activity a
  join public.municipality m on m.id = a.municipality_id and m.is_active and m.deleted_at is null
  left join public.ref_khld_activity_type t on t.id = a.activity_type_id
 where a.is_published and a.deleted_at is null and a.end_date >= current_date
union all
select k.id,
       'market'::text,
       k.name,
       k.start_date,
       null::text,
       null::text,
       null::text,
       null::text,
       o.label_en,
       o.label_ar,
       k.description,
       m.slug,
       k.end_date,
       null::date
  from public.khld_market k
  join public.municipality m on m.id = k.municipality_id and m.is_active and m.deleted_at is null
  left join public.ref_khld_market_occasion o on o.id = k.occasion_id
 where k.is_published and k.deleted_at is null and k.end_date >= current_date
union all
select c.id,
       'campaign'::text,
       c.campaign_name,
       c.start_date,
       null::text,
       null::text,
       null::text,
       null::text,
       ct.type_en,
       ct.type_ar,
       c.description,
       m.slug,
       c.end_date,
       c.applications_close
  from public.khld_campaign c
  join public.municipality m on m.id = c.municipality_id and m.is_active and m.deleted_at is null
  left join lateral (
    select string_agg(r.label_en, ', ' order by r.sort_order) as type_en,
           string_agg(r.label_ar, '، ' order by r.sort_order) as type_ar
      from public.khld_campaign_option x
      join public.ref_khld_campaign_activity_type r on r.id = x.option_id
     where x.campaign_id = c.id and x.question_code = 'f125'
  ) ct on true
 where c.is_published and c.deleted_at is null and c.end_date >= current_date
union all
select g.id,
       'session'::text,
       g.title,
       g.start_date,
       null::text,
       null::text,
       null::text,
       null::text,
       s.label_en,
       s.label_ar,
       g.description,
       m.slug,
       g.end_date,
       g.applications_close
  from public.khld_guidance_session g
  join public.municipality m on m.id = g.municipality_id and m.is_active and m.deleted_at is null
  left join public.ref_khld_session_topic s on s.id = g.topic_id
 where g.is_published and g.deleted_at is null and g.end_date >= current_date;

revoke all on public.v_public_khld_whats_on from public, anon, authenticated;
grant select on public.v_public_khld_whats_on to anon, authenticated;

-- ── verification: as anon, discarded ─────────────────────────────────────
do $verify$
declare
  v_khld uuid := '00000000-0000-4000-8000-0000000000b2';
  v_camp uuid;
  v_sess uuid;
  v_hide uuid;
  v_n    int;
begin
  insert into public.khld_campaign (municipality_id, campaign_name, start_date, end_date, applications_open, applications_close,
                                    description, has_sponsor, status_id, is_published)
  values (v_khld, '0167 probe campaign', current_date + 3, current_date + 4, current_date, current_date + 2, 'probe', false,
          (select id from public.ref_khld_event_status where code = 'planned'), true)
  returning id into v_camp;
  insert into public.khld_campaign_option (campaign_id, municipality_id, question_code, option_id)
  select v_camp, v_khld, 'f125', id from public.ref_khld_campaign_activity_type where code in ('cleaning', 'planting');
  insert into public.khld_guidance_session (municipality_id, title, start_date, end_date, applications_open, applications_close,
                                            description, executing_entity, topic_id, is_core, is_published)
  values (v_khld, '0167 probe session', current_date + 3, current_date + 9, current_date, current_date + 2, 'probe', 'probe',
          (select id from public.ref_khld_session_topic where code = 'licensing'), true, true)
  returning id into v_sess;
  insert into public.khld_guidance_session (municipality_id, title, start_date, end_date, applications_open, applications_close,
                                            description, executing_entity, topic_id, is_core)
  values (v_khld, '0167 probe unpublished', current_date + 3, current_date + 9, current_date, current_date + 2, 'probe', 'probe',
          (select id from public.ref_khld_session_topic where code = 'basics'), true)
  returning id into v_hide;

  set local role anon;
  if not exists (select 1 from public.v_public_khld_whats_on
                  where id = v_camp and kind = 'campaign' and title = '0167 probe campaign'
                    and type_en = 'Cleaning, Planting and afforestation' and apply_until = current_date + 2
                    and end_date = current_date + 4) then
    raise exception '0167: anon does not see the published campaign as written';
  end if;
  if not exists (select 1 from public.v_public_khld_whats_on
                  where id = v_sess and kind = 'session' and type_en = 'Licensing requirements' and apply_until = current_date + 2) then
    raise exception '0167: anon does not see the published session as written';
  end if;
  if exists (select 1 from public.v_public_khld_whats_on where id = v_hide) then
    raise exception '0167: an unpublished session is on the public page';
  end if;
  reset role;
  -- unpublished: gone, and anon writes nothing
  update public.khld_campaign set is_published = false where id = v_camp;
  set local role anon;
  select count(*) into v_n from public.v_public_khld_whats_on where id = v_camp;
  reset role;
  if v_n <> 0 then
    raise exception '0167: an unpublished campaign is on the public page';
  end if;
  if has_table_privilege('anon', 'public.v_public_khld_whats_on', 'insert') then
    raise exception '0167: anon may write the public view';
  end if;
  raise exception using errcode = 'P0167', message = 'rollback the probes';
exception when sqlstate 'P0167' then
  null;
end $verify$;
""" % dict(alters=alters)


FILES = [
    ('0156', 'khalidiyah_forms_option_lists', lists_sql_1),
    ('0157', 'khalidiyah_forms_option_lists_2', lists_sql_2),
    ('0158', 'khalidiyah_forms_shared', shared_sql),
    ('0159', 'khalidiyah_forms_tables', tables_sql_1),
    ('0160', 'khalidiyah_forms_tables_2', tables_sql_2),
    ('0165', 'khalidiyah_partner_volunteers', partner_volunteers_sql),
    ('0167', 'khalidiyah_publish_campaigns_sessions', publish_sql),
]

if __name__ == '__main__':
    bad = False
    for nnnn, name, fn in FILES:
        text = fn()
        applied = [p for p in glob.glob(os.path.join(ROOT, 'supabase', 'migrations', '*_%s_%s.sql' % (nnnn, name)))
                   if not os.path.basename(p).startswith('PENDING_')]
        if applied:
            same = open(applied[0], encoding='utf-8', newline='').read() == text
            print('%s applied as %s: %s' % (nnnn, os.path.basename(applied[0]), 'reproduced byte for byte' if same else 'DIFFERS'))
            bad = bad or not same
        else:
            path = os.path.join(ROOT, 'supabase', 'migrations', 'PENDING_%s_%s.sql' % (nnnn, name))
            with open(path, 'w', encoding='utf-8', newline='') as fh:
                fh.write(text)
            print('wrote', os.path.relpath(path, ROOT), len(text.encode('utf-8')), 'bytes')
    sys.exit(1 if bad else 0)
