# -*- coding: utf-8 -*-
"""
Generates supabase/migrations/PENDING_0162_khalidiyah_forms_indicator_views.sql:
the 21 indicator views of the reviewed workbook's 'Calculation formulas'
sheet, the framework rows brought to it (each indicator's formula is the
sheet's "Formula (from fields)", verbatim; SO2-C2's name is the framework
sheet's new one), v_indicator_actual with the 21 branches back, and the
three views the app reads (status, second figures, the public page).

The views are written here by hand, one per indicator, each under the
sheet's own formula; only the framework text is read from the workbook.
Run from the repository root:  python supabase/khalidiyah/gen_views.py
"""
import glob, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from workbook import load_calculations, load_framework

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
CALC = load_calculations()
HEAD, FRAME = load_framework()


def q(s):
    return "'" + s.replace("'", "''") + "'"


# indicator code -> (view, data_source table)
VIEWS = [
    ('IMP-0', 'v_ind_khld_imp_0', 'khld_park_survey'), ('SO1-0', 'v_ind_khld_so1_0', 'khld_partner_survey'),
    ('A1', 'v_ind_khld_a1', 'khld_milestone_record'), ('A2', 'v_ind_khld_a2', 'khld_meeting'),
    ('A3', 'v_ind_khld_a3', 'khld_contribution'), ('B1', 'v_ind_khld_b1', 'khld_milestone_record'),
    ('SO2-0', 'v_ind_khld_so2_0', 'khld_park_survey'), ('C1', 'v_ind_khld_c1', 'khld_rehab_report'),
    ('C2', 'v_ind_khld_c2', 'khld_campaign'), ('D1', 'v_ind_khld_d1', 'khld_activity'),
    ('D2', 'v_ind_khld_d2', 'khld_activity_attendance'), ('SO3-0', 'v_ind_khld_so3_0', 'khld_volunteer_attendance'),
    ('E1', 'v_ind_khld_e1', 'khld_committee_meeting'), ('F1', 'v_ind_khld_f1', 'khld_milestone_record'),
    ('F2', 'v_ind_khld_f2', 'khld_volunteer'), ('F3', 'v_ind_khld_f3', 'khld_campaign'),
    ('SO4-0', 'v_ind_khld_so4_0', 'khld_producer_survey'), ('G1', 'v_ind_khld_g1', 'khld_enterprise_support'),
    ('G2', 'v_ind_khld_g2', 'khld_enterprise_support'), ('H1', 'v_ind_khld_h1', 'khld_market'),
    ('H2', 'v_ind_khld_h2', 'khld_market_attendance'),
]


def full(code):
    return 'KHLD-' + (code if code in ('IMP-0',) else ({'SO1-0': 'SO1-0', 'SO2-0': 'SO2-0', 'SO3-0': 'SO3-0', 'SO4-0': 'SO4-0'}.get(code) or
            {'A': 'SO1-', 'B': 'SO1-', 'C': 'SO2-', 'D': 'SO2-', 'E': 'SO3-', 'F': 'SO3-', 'G': 'SO4-', 'H': 'SO4-'}[code[0]] + code))


def formula(code):
    return CALC[full(code)]['formula']


def framework_name(code):
    for r in FRAME:
        if r and r[0] == full(code):
            return r[2]
    raise KeyError(code)


def sheet(code):
    """The sheet's formula and frequency as an SQL comment block."""
    c = CALC[full(code)]
    out = []
    for label, text in (('formula', c['formula']), ('frequency', c['frequency'])):
        lines, cur, first = [], '--    %s: "' % label, True
        for w in text.split():
            if len(cur) + len(w) + 1 > 78:
                lines.append(cur)
                cur, first = '--      ', True
            cur += ('' if first else ' ') + w
            first = False
        lines.append(cur + '"')
        out += lines
    return '\n'.join(out)


SQL = r"""-- ═══════════════════════════════════════════════════════════════════════════
--  0162 — Khalidiyah's 21 indicator views from the reviewed workbook's
--         'Calculation formulas' sheet
--
--  GENERATED by supabase/khalidiyah/gen_views.py (the views by hand, one per
--  indicator under the sheet's own formula; the framework text read from the
--  workbook). One view per indicator, the shape of the other forty:
--  (period_code, actual, denominator, municipality_id), anchored on
--  `municipality m where m.code = 'KHLD'`, joined to data on
--  municipality_id as well as on date (0114), live rows only.
--
--  ── THE WINDOW EACH READS ──
--
--  The sheet's shared definition: "Every indicator is filtered on its date
--  field within the reporting quarter / year; cumulative indicators use date
--  <= report date." Each indicator's Frequency column says which it is, and
--  the view for a quarter reads, up to that quarter's end:
--
--    the year to date   the annual ones -- IMP-0, SO1-0, SO2-0, SO4-0
--                       (surveys "in reporting year"), A3 ("F183 in
--                       reporting year"), C2 ("F024 in reporting year")
--    everything to date the cumulative ones -- A2 ("F016 <= report date"),
--                       D1 ("cumulative from Dec 2026"), D2, F2, F3, G1, G2,
--                       H1, H2 ("cumulative"), C1 ("latest report"), SO3-0
--                       ("annual / end of period", over all registered)
--    the milestones     A1, B1, E1, F1: 1 from the quarter of the first
--                       record that establishes them, 0 before it
--
--  A quarter that has not begun reads nothing (NULL), never a repeat of the
--  total to date. The dashboard shows the current quarter, so every figure
--  on it is the sheet's to-date or year-to-date number. The date field of
--  each record is the sheet's own (F016, F183, F024, F031, F037, F068, F092,
--  F110, F159, F173, F198, F205); F159 is a timestamp, read in Amman's time.
--
--  ── WHAT EACH COUNTS ──
--
--    ratios      IMP-0 (F166 in 4-5 over F166 answered; consent, resident),
--                SO2-0 (F170 in 4-5 over F170 answered; consent), SO1-0 and
--                SO4-0 (the latest response per partner / producer in the
--                quarter; Yes over surveyed) -- x100, one decimal, NULL when
--                the denominator is 0
--    records     A2 (coordination meetings with partners whose attendance
--                sheet F120 is filed), C2 (campaigns held), D1 (activities
--                held, from 1 December 2026), H2 (vendor attendances at
--                markets held -- participations)
--    sums        A3 (JOD, F186), D2 (F039 at held activities), F3 (F127
--                of campaigns held), H1 (F094 of markets held -- days)
--    people      F2 (volunteers with an attendance, on the first), G1
--                (owners who attended all four core topics, on the day the
--                fourth was reached), G2 (owners with a support, on the first)
--    latest      C1 (F122 of the latest report on or before the quarter's
--                end, over its F121)
--    milestones  A1, B1, F1 (FORM-22: the status and all four components),
--                E1 (a founding meeting with its minutes filed, FORM-11, or
--                FORM-22's record)
--
--  A public volunteer registration counts once staff approve it
--  (application_status, 0159). Every choice the sheet leaves open is in
--  06_OPEN_QUESTIONS.md, not decided silently here: SO3-0's denominator
--  (the sheet's own, all registered volunteers), G1's simplification (the
--  four core topics; cycles are not defined), D1's bazaar exclusion (not
--  applied: no field says an activity is also a FORM-16 market).
--
--  ── THE SECOND FIGURES, AND WHAT CANNOT COMPUTE ──
--
--  v_khld_indicator_unique carries the figures the sheet asks for beside the
--  main one: A3's number of contributions, H1's number of markets ("report
--  both markets and days"), H2's unique vendors ("unique F112"). Every
--  indicator computes, so v_khld_indicator_status names no reason; it keeps
--  its columns because every dashboard reads it.
--
--  ── v_indicator_actual ──
--
--  Recreated from its CURRENT definition (0153's) with the 21 Khalidiyah
--  branches back, in 0163; that migration asserts every Sahel Horan and
--  Ramtha row is unchanged, and revokes the leaf views and the helpers from
--  every client role. Split in two only for the size of one applied text.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── the framework, brought to the reviewed workbook ───────────────────────
%(framework)s

-- ── helpers ───────────────────────────────────────────────────────────────

-- The milestones: the first date each is established, per the sheet.
-- A1 / B1: F194 Established or Updated and all four F190 / F191 ticked.
-- F1: F194 Established and all four F193 ticked. E1: a FORM-11 founding
-- meeting (F142 Yes) with its minutes (F052) filed, or a FORM-22 record
-- with F194 Established.
create view public.v_khld_milestone_established as
select x.municipality_id, x.milestone, min(x.on_date) as established_on
  from (
    select r.municipality_id, ms.code as milestone, r.status_date as on_date
      from public.khld_milestone_record r
      join public.ref_khld_milestone ms on ms.id = r.milestone_id
      join public.ref_khld_milestone_status st on st.id = r.status_id
     where r.deleted_at is null and r.status_date is not null
       and ((ms.code in ('so1_a1', 'so1_b1') and st.code in ('established', 'updated'))
            or (ms.code in ('so3_e1', 'so3_f1') and st.code = 'established'))
       and (ms.code = 'so3_e1'
            or (select count(distinct o.option_id) from public.khld_milestone_record_option o
                 where o.milestone_record_id = r.id
                   and o.question_code = case ms.code when 'so1_a1' then 'f190' when 'so1_b1' then 'f191' else 'f193' end)
               = case ms.code
                   when 'so1_a1' then (select count(*) from public.ref_khld_components_a1 where deleted_at is null and is_active)
                   when 'so1_b1' then (select count(*) from public.ref_khld_components_b1 where deleted_at is null and is_active)
                   else (select count(*) from public.ref_khld_components_f1 where deleted_at is null and is_active) end)
    union all
    select c.municipality_id, 'so3_e1', c.meeting_date
      from public.khld_committee_meeting c
     where c.deleted_at is null and c.is_founding
       and exists (select 1 from public.attachment a
                    where a.entity_type = 'khld_committee_meeting' and a.entity_id = c.id
                      and a.field_code = 'F052' and a.deleted_at is null)
  ) x
 group by x.municipality_id, x.milestone;

-- A volunteer's attendances at live campaigns and activities; approved,
-- live volunteers only (SO3-0, SO3-F2).
create view public.v_khld_volunteer_occasion as
select a.municipality_id, a.volunteer_id, coalesce(a.campaign_id, a.activity_id) as occasion_id, a.report_date
  from public.khld_volunteer_attendance a
  join public.khld_volunteer v on v.id = a.volunteer_id and v.deleted_at is null and v.application_status = 'approved'
  join public.person p on p.id = v.person_id and p.deleted_at is null
 where a.deleted_at is null
   and (exists (select 1 from public.khld_campaign k where k.id = a.campaign_id and k.deleted_at is null)
        or exists (select 1 from public.khld_activity k where k.id = a.activity_id and k.deleted_at is null));

-- SO4-G1: an owner completes on the day the fourth core topic is attended
-- (the sheet's simplification: "completed = attended all 4 core topics").
create view public.v_khld_guidance_completed as
select t.municipality_id, t.person_id, max(t.first_on) as completed_on
  from (
    select s.municipality_id, s.person_id, tp.code as topic, min(s.support_date) as first_on
      from public.khld_enterprise_support s
      join public.ref_khld_support_type st on st.id = s.support_type_id and st.code = 'guidance'
      join public.khld_guidance_session g on g.id = s.session_id and g.deleted_at is null and g.is_core
      join public.ref_khld_session_topic tp on tp.id = g.topic_id and tp.code in ('basics', 'licensing', 'hygiene', 'marketing')
      join public.person p on p.id = s.person_id and p.deleted_at is null
     where s.deleted_at is null and s.attended
     group by s.municipality_id, s.person_id, tp.code
  ) t
 group by t.municipality_id, t.person_id
having count(distinct t.topic) = 4;

-- ── IMP-0 ·
%(IMP-0)s
create view public.v_ind_khld_imp_0 as
select rp.code as period_code,
       case when count(s.id) = 0 then null::numeric
            else round(100.0 * count(*) filter (where s.interaction_score >= 4) / count(s.id), 1) end as actual,
       count(s.id)::numeric as denominator,
       m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join public.khld_park_survey s
    on s.municipality_id = m.id and s.deleted_at is null and s.consent and s.is_resident
   and s.interaction_score is not null
   and (s.surveyed_at at time zone 'Asia/Amman')::date between date_trunc('year', rp.end_date)::date and rp.end_date
   and rp.start_date <= current_date
 where m.code = 'KHLD'
 group by m.id, rp.code;

-- ── SO1-0 ·
%(SO1-0)s
create view public.v_ind_khld_so1_0 as
select rp.code as period_code,
       case when count(l.partner_id) = 0 then null::numeric
            else round(100.0 * count(*) filter (where l.overall_effective) / count(l.partner_id), 1) end as actual,
       count(l.partner_id)::numeric as denominator,
       m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join lateral (
    select distinct on (s.partner_id) s.partner_id, s.overall_effective
      from public.khld_partner_survey s
      join public.khld_partner p on p.id = s.partner_id and p.deleted_at is null
     where s.municipality_id = m.id and s.deleted_at is null
       and s.survey_date between date_trunc('year', rp.end_date)::date and rp.end_date
       and rp.start_date <= current_date
     order by s.partner_id, s.survey_date desc, s.created_at desc
  ) l on true
 where m.code = 'KHLD'
 group by m.id, rp.code;

-- ── A1 ·
%(A1)s
create view public.v_ind_khld_a1 as
select rp.code as period_code,
       case when rp.start_date > current_date then null when e.established_on <= rp.end_date then 1 else 0 end::numeric as actual,
       null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join public.v_khld_milestone_established e on e.municipality_id = m.id and e.milestone = 'so1_a1'
 where m.code = 'KHLD';

-- ── A2 ·
%(A2)s
create view public.v_ind_khld_a2 as
select rp.code as period_code, case when rp.start_date > current_date then null else count(x.id) end::numeric as actual, null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join (public.khld_meeting x
             join public.ref_khld_meeting_type t on t.id = x.meeting_type_id and t.code = 'partner_coordination')
    on x.municipality_id = m.id and x.deleted_at is null and x.meeting_date <= rp.end_date
   and exists (select 1 from public.attachment a
                where a.entity_type = 'khld_meeting' and a.entity_id = x.id and a.field_code = 'F120' and a.deleted_at is null)
 where m.code = 'KHLD'
 group by m.id, rp.code, rp.start_date;

-- ── A3 ·
%(A3)s
create view public.v_ind_khld_a3 as
select rp.code as period_code, case when rp.start_date > current_date then null else coalesce(sum(x.value_jod), 0) end::numeric as actual, null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join public.khld_contribution x
    on x.municipality_id = m.id and x.deleted_at is null
   and x.date_received between date_trunc('year', rp.end_date)::date and rp.end_date
 where m.code = 'KHLD'
 group by m.id, rp.code, rp.start_date;

-- ── B1 ·
%(B1)s
create view public.v_ind_khld_b1 as
select rp.code as period_code,
       case when rp.start_date > current_date then null when e.established_on <= rp.end_date then 1 else 0 end::numeric as actual,
       null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join public.v_khld_milestone_established e on e.municipality_id = m.id and e.milestone = 'so1_b1'
 where m.code = 'KHLD';

-- ── SO2-0 ·
%(SO2-0)s
create view public.v_ind_khld_so2_0 as
select rp.code as period_code,
       case when count(s.id) = 0 then null::numeric
            else round(100.0 * count(*) filter (where s.satisfaction_score >= 4) / count(s.id), 1) end as actual,
       count(s.id)::numeric as denominator,
       m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join public.khld_park_survey s
    on s.municipality_id = m.id and s.deleted_at is null and s.consent
   and s.satisfaction_score is not null
   and (s.surveyed_at at time zone 'Asia/Amman')::date between date_trunc('year', rp.end_date)::date and rp.end_date
   and rp.start_date <= current_date
 where m.code = 'KHLD'
 group by m.id, rp.code;

-- ── C1 ·
%(C1)s
create view public.v_ind_khld_c1 as
select rp.code as period_code,
       case when rp.start_date > current_date then null else l.completed_count end::numeric as actual,
       case when rp.start_date > current_date then null else l.agreed_total end::numeric as denominator,
       m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join lateral (
    select r.completed_count, r.agreed_total
      from public.khld_rehab_report r
     where r.municipality_id = m.id and r.deleted_at is null and r.report_date <= rp.end_date
     order by r.report_date desc, r.created_at desc
     limit 1
  ) l on true
 where m.code = 'KHLD';

-- ── C2 ·
%(C2)s
create view public.v_ind_khld_c2 as
select rp.code as period_code, case when rp.start_date > current_date then null else count(x.id) end::numeric as actual, null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join (public.khld_campaign x join public.ref_khld_event_status s on s.id = x.status_id and s.code = 'held')
    on x.municipality_id = m.id and x.deleted_at is null
   and x.start_date between date_trunc('year', rp.end_date)::date and rp.end_date
 where m.code = 'KHLD'
 group by m.id, rp.code, rp.start_date;

-- ── D1 ·
%(D1)s
create view public.v_ind_khld_d1 as
select rp.code as period_code, case when rp.start_date > current_date then null else count(x.id) end::numeric as actual, null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join (public.khld_activity x join public.ref_khld_event_status s on s.id = x.status_id and s.code = 'held')
    on x.municipality_id = m.id and x.deleted_at is null and x.start_date >= date '2026-12-01'
   and x.start_date <= rp.end_date
 where m.code = 'KHLD'
 group by m.id, rp.code, rp.start_date;

-- ── D2 ·
%(D2)s
create view public.v_ind_khld_d2 as
select rp.code as period_code, case when rp.start_date > current_date then null else coalesce(sum(x.total_participants), 0) end::numeric as actual, null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join (public.khld_activity_attendance x
             join public.khld_activity a on a.id = x.activity_id and a.deleted_at is null
             join public.ref_khld_event_status s on s.id = a.status_id and s.code = 'held')
    on x.municipality_id = m.id and x.deleted_at is null and x.report_date <= rp.end_date
 where m.code = 'KHLD'
 group by m.id, rp.code, rp.start_date;

%(PARTB)s-- ── SO3-0 ·
%(SO3-0)s
create view public.v_ind_khld_so3_0 as
select rp.code as period_code,
       case when rp.start_date > current_date or count(v.id) = 0 then null::numeric
            else round(100.0 * count(*) filter (
                   where (select count(distinct o.occasion_id) from public.v_khld_volunteer_occasion o
                           where o.volunteer_id = v.id and o.report_date <= rp.end_date) >= 2) / count(v.id), 1) end as actual,
       case when rp.start_date > current_date then null::numeric else count(v.id)::numeric end as denominator,
       m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join (public.khld_volunteer v join public.person p on p.id = v.person_id and p.deleted_at is null)
    on v.municipality_id = m.id and v.deleted_at is null and v.application_status = 'approved'
   and (v.created_at at time zone 'Asia/Amman')::date <= rp.end_date
 where m.code = 'KHLD'
 group by m.id, rp.code, rp.start_date;

-- ── E1 ·
%(E1)s
create view public.v_ind_khld_e1 as
select rp.code as period_code,
       case when rp.start_date > current_date then null when e.established_on <= rp.end_date then 1 else 0 end::numeric as actual,
       null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join public.v_khld_milestone_established e on e.municipality_id = m.id and e.milestone = 'so3_e1'
 where m.code = 'KHLD';

-- ── F1 ·
%(F1)s
create view public.v_ind_khld_f1 as
select rp.code as period_code,
       case when rp.start_date > current_date then null when e.established_on <= rp.end_date then 1 else 0 end::numeric as actual,
       null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join public.v_khld_milestone_established e on e.municipality_id = m.id and e.milestone = 'so3_f1'
 where m.code = 'KHLD';

-- ── F2 ·
%(F2)s
create view public.v_ind_khld_f2 as
select rp.code as period_code, case when rp.start_date > current_date then null else count(f.volunteer_id) end::numeric as actual, null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join (select o.municipality_id, o.volunteer_id, min(o.report_date) as first_on
               from public.v_khld_volunteer_occasion o group by o.municipality_id, o.volunteer_id) f
    on f.municipality_id = m.id and f.first_on <= rp.end_date
 where m.code = 'KHLD'
 group by m.id, rp.code, rp.start_date;

-- ── F3 ·
%(F3)s
create view public.v_ind_khld_f3 as
select rp.code as period_code, case when rp.start_date > current_date then null else coalesce(sum(x.action_days), 0) end::numeric as actual, null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join (public.khld_campaign x join public.ref_khld_event_status s on s.id = x.status_id and s.code = 'held')
    on x.municipality_id = m.id and x.deleted_at is null and x.start_date <= rp.end_date
 where m.code = 'KHLD'
 group by m.id, rp.code, rp.start_date;

-- ── SO4-0 ·
%(SO4-0)s
create view public.v_ind_khld_so4_0 as
select rp.code as period_code,
       case when count(l.person_id) = 0 then null::numeric
            else round(100.0 * count(*) filter (where l.increased_opportunities) / count(l.person_id), 1) end as actual,
       count(l.person_id)::numeric as denominator,
       m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join lateral (
    select distinct on (s.person_id) s.person_id, s.increased_opportunities
      from public.khld_producer_survey s
      join public.person p on p.id = s.person_id and p.deleted_at is null
     where s.municipality_id = m.id and s.deleted_at is null
       and s.survey_date between date_trunc('year', rp.end_date)::date and rp.end_date
       and rp.start_date <= current_date
     order by s.person_id, s.survey_date desc, s.created_at desc
  ) l on true
 where m.code = 'KHLD'
 group by m.id, rp.code;

-- ── G1 ·
%(G1)s
create view public.v_ind_khld_g1 as
select rp.code as period_code, case when rp.start_date > current_date then null else count(c.person_id) end::numeric as actual, null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join public.v_khld_guidance_completed c
    on c.municipality_id = m.id and c.completed_on <= rp.end_date
 where m.code = 'KHLD'
 group by m.id, rp.code, rp.start_date;

-- ── G2 ·
%(G2)s
create view public.v_ind_khld_g2 as
select rp.code as period_code, case when rp.start_date > current_date then null else count(f.person_id) end::numeric as actual, null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join (
    select s.municipality_id, s.person_id, min(s.support_date) as first_on
      from public.khld_enterprise_support s
      join public.ref_khld_support_type st on st.id = s.support_type_id
      join public.person p on p.id = s.person_id and p.deleted_at is null
     where s.deleted_at is null and (st.code <> 'guidance' or s.attended)
     group by s.municipality_id, s.person_id
  ) f on f.municipality_id = m.id and f.first_on <= rp.end_date
 where m.code = 'KHLD'
 group by m.id, rp.code, rp.start_date;

-- ── H1 ·
%(H1)s
create view public.v_ind_khld_h1 as
select rp.code as period_code, case when rp.start_date > current_date then null else coalesce(sum(x.actual_days), 0) end::numeric as actual, null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join (public.khld_market x join public.ref_khld_event_status s on s.id = x.status_id and s.code = 'held')
    on x.municipality_id = m.id and x.deleted_at is null and x.start_date <= rp.end_date
 where m.code = 'KHLD'
 group by m.id, rp.code, rp.start_date;

-- ── H2 ·
%(H2)s
create view public.v_ind_khld_h2 as
select rp.code as period_code, case when rp.start_date > current_date then null else count(x.id) end::numeric as actual, null::numeric as denominator, m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id
  left join (public.khld_market_attendance x
             join public.khld_market k on k.id = x.market_id and k.deleted_at is null
             join public.ref_khld_event_status s on s.id = k.status_id and s.code = 'held'
             join public.person p on p.id = x.person_id and p.deleted_at is null)
    on x.municipality_id = m.id and x.deleted_at is null and x.report_date <= rp.end_date
 where m.code = 'KHLD'
 group by m.id, rp.code, rp.start_date;

-- ── the second figures ────────────────────────────────────────────────────
-- A3: the number of contributions; H1: the number of markets held; H2:
-- unique vendors (F112) with an attendance at a market held, on the first.
create or replace view public.v_khld_indicator_unique as
select x.code, rp.code as period_code,
       case x.code
         when 'A3' then (select count(*) from public.khld_contribution c
                          where c.municipality_id = m.id and c.deleted_at is null
                            and c.date_received between date_trunc('year', rp.end_date)::date and rp.end_date)
         when 'H1' then (select count(*) from public.khld_market k
                           join public.ref_khld_event_status s on s.id = k.status_id and s.code = 'held'
                          where k.municipality_id = m.id and k.deleted_at is null
                            and k.start_date <= rp.end_date)
         when 'H2' then (select count(*) from (
                           select a.person_id, min(a.report_date) as first_on
                             from public.khld_market_attendance a
                             join public.khld_market k on k.id = a.market_id and k.deleted_at is null
                             join public.ref_khld_event_status s on s.id = k.status_id and s.code = 'held'
                             join public.person p on p.id = a.person_id and p.deleted_at is null
                            where a.municipality_id = m.id and a.deleted_at is null
                            group by a.person_id) f
                          where f.first_on <= rp.end_date)
       end::numeric as unique_actual,
       m.id as municipality_id
  from public.municipality m
  join public.reporting_period rp on rp.municipality_id = m.id and rp.start_date <= current_date
  cross join (values ('A3'), ('H1'), ('H2')) x(code)
 where m.code = 'KHLD'
   and (auth.uid() is null or public.is_staff() or public."current_role"() = 'partner_viewer')
   and (auth.uid() is null or public.can_see_municipality(m.id));

-- ── what cannot compute: nothing, and the columns stay for the dashboard ──
create or replace view public.v_khld_indicator_status as
select i.municipality_id, i.code, i.full_code, null::text as reason, null::text as detail, null::text as milestone_code
  from public.indicator i
  join public.municipality m on m.id = i.municipality_id and m.code = 'KHLD'
 where (auth.uid() is null or public.is_staff() or public."current_role"() = 'partner_viewer')
   and (auth.uid() is null or public.can_see_municipality(i.municipality_id));

-- ── the public page: published activities (FORM-08) and markets (FORM-16)
--    that have not ended; titles, dates, types and descriptions only.
--    A definer view over base tables, the four filters in the view itself
--    (0120, 0152). The forms have no time or place fields.
create or replace view public.v_public_khld_whats_on
with (security_invoker = false) as
select a.id,
       'activity'::text as kind,
       a.activity_name as title,
       a.start_date as on_date,
       null::text as time_from,
       null::text as time_to,
       null::text as place_en,
       null::text as place_ar,
       t.label_en as type_en,
       t.label_ar as type_ar,
       a.description,
       m.slug as municipality_slug
  from public.khld_activity a
  join public.municipality m on m.id = a.municipality_id and m.is_active and m.deleted_at is null
  left join public.ref_khld_activity_type t on t.id = a.activity_type_id
 where a.is_published and a.deleted_at is null and a.end_date >= current_date
union all
select k.id,
       'market'::text,
       k.name,
       k.start_date,
       null::text,
       null::text,
       null::text,
       null::text,
       o.label_en,
       o.label_ar,
       k.description,
       m.slug
  from public.khld_market k
  join public.municipality m on m.id = k.municipality_id and m.is_active and m.deleted_at is null
  left join public.ref_khld_market_occasion o on o.id = k.occasion_id
 where k.is_published and k.deleted_at is null and k.end_date >= current_date;

-- ── v_indicator_actual: 0153's definition plus the 21 branches ────────────
create or replace view public.v_indicator_actual as
select code, period_code, actual, denominator, municipality_id
  from (
    select 'IMP-0'::text as code, period_code, actual, denominator, municipality_id from public.v_ind_imp_0
    union all select 'A1',   period_code, actual, denominator, municipality_id from public.v_ind_a1
    union all select 'A1.2', period_code, actual, denominator, municipality_id from public.v_ind_a1_2
    union all select 'A1.3', period_code, actual, denominator, municipality_id from public.v_ind_a1_3
    union all select 'B1',   period_code, actual, denominator, municipality_id from public.v_ind_b1
    union all select 'B1.1', period_code, actual, denominator, municipality_id from public.v_ind_b1_1
    union all select 'B1.2', period_code, actual, denominator, municipality_id from public.v_ind_b1_2
    union all select 'C1',   period_code, actual, denominator, municipality_id from public.v_ind_c1
    union all select 'C1.1', period_code, actual, denominator, municipality_id from public.v_ind_c1_1
    union all select 'C1.2', period_code, actual, denominator, municipality_id from public.v_ind_c1_2
    union all select 'C1.3', period_code, actual, denominator, municipality_id from public.v_ind_c1_3
    union all select 'D0.1', period_code, actual, denominator, municipality_id from public.v_ind_d0_1
    union all select 'D0.2', period_code, actual, denominator, municipality_id from public.v_ind_d0_2
    union all select 'E0.1', period_code, actual, denominator, municipality_id from public.v_ind_e0_1
    union all select 'E0.2', period_code, actual, denominator, municipality_id from public.v_ind_e0_2
    union all select 'F0.1', period_code, actual, denominator, municipality_id from public.v_ind_f0_1
    union all select 'G0.1', period_code, actual, denominator, municipality_id from public.v_ind_g0_1
    union all select 'G0.2', period_code, actual, denominator, municipality_id from public.v_ind_g0_2
    union all select 'G0.3', period_code, actual, denominator, municipality_id from public.v_ind_g0_3
    union all select 'G0.4', period_code, actual, denominator, municipality_id from public.v_ind_g0_4
    -- Ramtha (0132)
    union all select 'IMP-0', period_code, actual, denominator, municipality_id from public.v_ind_rmth_imp_0
    union all select 'SO1-0', period_code, actual, denominator, municipality_id from public.v_ind_rmth_so1_0
    union all select 'A1.2',  period_code, actual, denominator, municipality_id from public.v_ind_rmth_a1_2
    union all select 'A1.3',  period_code, actual, denominator, municipality_id from public.v_ind_rmth_a1_3
    union all select 'B1',    period_code, actual, denominator, municipality_id from public.v_ind_rmth_b1
    union all select 'B1.1',  period_code, actual, denominator, municipality_id from public.v_ind_rmth_b1_1
    union all select 'B1.2',  period_code, actual, denominator, municipality_id from public.v_ind_rmth_b1_2
    union all select 'SO2-0', period_code, actual, denominator, municipality_id from public.v_ind_rmth_so2_0
    union all select 'C1',    period_code, actual, denominator, municipality_id from public.v_ind_rmth_c1
    union all select 'C1.1',  period_code, actual, denominator, municipality_id from public.v_ind_rmth_c1_1
    union all select 'C1.2',  period_code, actual, denominator, municipality_id from public.v_ind_rmth_c1_2
    union all select 'SO3-0', period_code, actual, denominator, municipality_id from public.v_ind_rmth_so3_0
    union all select 'E0.1',  period_code, actual, denominator, municipality_id from public.v_ind_rmth_e0_1
    union all select 'E0.2',  period_code, actual, denominator, municipality_id from public.v_ind_rmth_e0_2
    union all select 'E0.3',  period_code, actual, denominator, municipality_id from public.v_ind_rmth_e0_3
    union all select 'F0.1',  period_code, actual, denominator, municipality_id from public.v_ind_rmth_f0_1
    union all select 'F0.2',  period_code, actual, denominator, municipality_id from public.v_ind_rmth_f0_2
    -- Khalidiyah (0162, 0163)
%(branches)s
  ) x
 where (auth.uid() is null or public.is_staff() or public."current_role"() = 'partner_viewer')
   and (auth.uid() is null or public.can_see_municipality(municipality_id));

-- ── grants: the leaves and helpers to nobody; the three read views as before ──
do $grants$
declare v text;
begin
  for v in select c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
            where n.nspname = 'public' and c.relkind = 'v'
              and (c.relname like 'v\_ind\_khld\_%%' or c.relname in ('v_khld_milestone_established', 'v_khld_volunteer_occasion', 'v_khld_guidance_completed'))
  loop
    execute format('revoke all on public.%%I from public, anon, authenticated', v);
  end loop;
end $grants$;
revoke all on public.v_khld_indicator_unique, public.v_khld_indicator_status, public.v_public_khld_whats_on from public, anon;
grant select on public.v_khld_indicator_unique, public.v_khld_indicator_status to authenticated;
grant select on public.v_public_khld_whats_on to anon, authenticated;

-- ── verification ─────────────────────────────────────────────────────────
do $verify$
declare
  v_n int;
begin
  -- Sahel Horan's and Ramtha's figures, every row, unchanged
  select count(*) into v_n from (
    (select * from _0163_actual_before
     except all
     select * from public.v_indicator_actual
      where municipality_id in ('00000000-0000-4000-8000-00000000005a', '00000000-0000-4000-8000-0000000000a1'))
    union all
    (select * from public.v_indicator_actual
      where municipality_id in ('00000000-0000-4000-8000-00000000005a', '00000000-0000-4000-8000-0000000000a1')
     except all
     select * from _0163_actual_before)) d;
  if v_n <> 0 then
    raise exception '0163: %% Sahel Horan / Ramtha indicator rows changed', v_n;
  end if;
  -- 21 Khalidiyah indicators, one row per period each, no period doubled
  select count(*) into v_n from public.v_indicator_actual where municipality_id = '00000000-0000-4000-8000-0000000000b2';
  if v_n <> 21 * (select count(*) from public.reporting_period where municipality_id = '00000000-0000-4000-8000-0000000000b2') then
    raise exception '0163: %% Khalidiyah rows in v_indicator_actual, expected 21 per period', v_n;
  end if;
  if exists (select 1 from public.v_indicator_actual where municipality_id = '00000000-0000-4000-8000-0000000000b2'
              group by code, period_code having count(*) > 1) then
    raise exception '0163: a Khalidiyah indicator has two rows for one period';
  end if;
  -- every indicator names its view, and the view exists
  if exists (select 1 from public.indicator i join public.municipality m on m.id = i.municipality_id and m.code = 'KHLD'
              where to_regclass('public.' || i.view_name) is null) then
    raise exception '0163: an indicator names a view that does not exist';
  end if;
  -- the leaves are revoked from authenticated (0114's lesson: a create view re-grants)
  if exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
              where n.nspname = 'public' and c.relname like 'v\_ind\_khld\_%%'
                and has_table_privilege('authenticated', c.oid, 'select')) then
    raise exception '0163: a Khalidiyah leaf view is readable by authenticated';
  end if;
  -- the public view answers anon
  set local role anon;
  perform 1 from public.v_public_khld_whats_on;
  reset role;
end $verify$;
"""


def framework_sql():
    lines = []
    for code, view, table in VIEWS:
        lines.append("update public.indicator i set formula = %s, data_source = %s, view_name = %s\n"
                     "  from public.municipality m where m.id = i.municipality_id and m.code = 'KHLD' and i.code = %s;"
                     % (q(formula(code)), q(table), q(view), q(code)))
    lines.append("-- SO2-C2's statement is the reviewed framework sheet's")
    lines.append("update public.indicator i set name_en = %s\n"
                 "  from public.municipality m where m.id = i.municipality_id and m.code = 'KHLD' and i.code = 'C2';"
                 % q(framework_name('C2')))
    return '\n'.join(lines)


PARTB_HEAD = """-- ═══════════════════════════════════════════════════════════════════════════
--  0163 — Khalidiyah's indicator views, the rest (0162's header), the second
--         figures, the status and public views, and v_indicator_actual
--
--  GENERATED by supabase/khalidiyah/gen_views.py.
-- ═══════════════════════════════════════════════════════════════════════════

create temp table _0163_actual_before on commit drop as
  select * from public.v_indicator_actual
   where municipality_id in ('00000000-0000-4000-8000-00000000005a', '00000000-0000-4000-8000-0000000000a1');

"""


def build():
    parts = {code: sheet(code) for code, _v, _t in VIEWS}
    parts['framework'] = framework_sql()
    parts['branches'] = '\n'.join("    union all select %-8s period_code, actual, denominator, municipality_id from public.%s"
                                  % (q(code) + ',', view) for code, view, _t in VIEWS)
    parts['PARTB'] = '\x00SPLIT\x00'
    text = SQL % parts
    a, b = text.split('\x00SPLIT\x00')
    return [('0162_khalidiyah_forms_indicator_views', a.rstrip('\n') + '\n'), ('0163_khalidiyah_forms_indicator_views_2', PARTB_HEAD + b)]


if __name__ == '__main__':
    bad = False
    for name, text in build():
        applied = [p for p in glob.glob(os.path.join(ROOT, 'supabase', 'migrations', '*_%s.sql' % name))
                   if not os.path.basename(p).startswith('PENDING_')]
        if applied:
            same = open(applied[0], encoding='utf-8', newline='').read() == text
            print('%s applied as %s: %s' % (name[:4], os.path.basename(applied[0]), 'reproduced byte for byte' if same else 'DIFFERS'))
            bad = bad or not same
            continue
        path = os.path.join(ROOT, 'supabase', 'migrations', 'PENDING_%s.sql' % name)
        with open(path, 'w', encoding='utf-8', newline='') as fh:
            fh.write(text)
        print('wrote', os.path.relpath(path, ROOT), len(text.encode('utf-8')), 'bytes')
    sys.exit(1 if bad else 0)
