# -*- coding: utf-8 -*-
"""
The seventeen Ramtha forms, field by field, from RMTH_indicator_forms.xlsx.

This is the catalogue that gen_forms.py turns into
  app/src/rmth/forms.generated.ts        the definitions the screens render
  app/src/locales/en/rmth.json           English: every label VERBATIM from the sheet
  app/src/locales/ar/rmth.json           Arabic: drafted here (the workbook has none)

Every `row` below names a field label exactly as the sheet has it; the generator
looks it up in the sheet and FAILS if it is not there, so a label cannot drift
from the workbook. The enumerator's note (column 3) is pulled from the sheet as
the field's help text; where a row has a note, `help_ar` is required here.

Field types (what the screen renders and what the save payload carries):
  nid          national ID -> person.national_id          nid_confirm  re-entry, must match
  person_name  -> person.full_name (locked when on file)  person_phone -> person.phone
  person_sex   -> person.sex (Male / Female, verbatim)    age          -> column age_years (+ person)
  text / area / number / date / month / phone             plain columns
  select       one ref_rmth_* list (+ `other` column)     multi        one option-junction question (+ other)
  bool         a two-option decision on a boolean column  choice       a fixed text/int column with listed values
  record       a picker over another Ramtha table         records      several (a junction payload)
  parts        several columns under one sheet row        grid         B1's support-criticality grid
  services     E0.1's live services with dates            readonly     assigned or derived by the database
"""

FORMS = {}

# The Arabic for each form's "Required disaggregation" line, keyed by form id.
#
# Separate from form() rather than a ninth positional argument, because the
# English side comes from the SHEET (gen_forms reads the row) while this side
# has no sheet to read: RMTH_indicator_forms.xlsx is English only. The
# framework workbook's "Arabic Copy" sheet does carry Arabic disaggregation,
# but for a DIFFERENT indicator list -- the plan is explicit that the two lists
# do not correspond and must not be mapped onto each other. So the terms below
# are taken from that sheet's VOCABULARY (الجنس، الفئة العمرية، الجنسية / فئة
# الهشاشة، القطاع، نوع التدريب، نوع الفعالية) applied to the form list's own
# lines, which keeps the Municipality's wording without borrowing its figures.
#
# gen_forms.py asserts every form id has an entry, so adding an eighteenth form
# cannot leave its disaggregation in English.
# A SHORT English name for each form, for the sidebar only.
#
# The English `title` is the sheet's indicator statement verbatim, which is
# right on the form page and wrong in a nav rail: "# of short-term intensive
# training cycles delivered whose content was jointly developed with
# private-sector partners" is a paragraph, and seventeen of them are a wall.
# Arabic already had a short name (`title_ar`), so the two languages disagreed
# about what the sidebar is for -- English got the statement, Arabic got the
# name.
#
# The statement is NOT paraphrased away: it stays as the page heading and the
# indicator line. This is an additional label, used in exactly one place.
#
# gen_forms.py asserts every form id has an entry.
SHORT_EN = {
    'imp0':  'Sustained engagement',
    'so10':  'Employability after networking',
    'a12':   'Networking events',
    'a13':   'Vocational guidance sessions',
    'b1':    'Project implementers',
    'b11':   'Specialised training programmes',
    'b12':   'Proposals approved',
    'so20':  'Placement after training',
    'so2c1': 'Training that supported the journey',
    'c11':   'Training cycles delivered',
    'c12':   'Training completions',
    'so30':  'Regular income',
    'e01':   'Specialised incubators',
    'e02':   'Incubation services',
    'e03':   'Incubator-design training',
    'f01':   'Entrepreneurship training',
    'f02':   'Entrepreneurship programmes',
}

DISAGG_AR = {
    'imp0':  'الجنس؛ العمر؛ الجنسية؛ فئة الهشاشة؛ نوع المسار',
    'so10':  'الجنس؛ العمر؛ الجنسية؛ فئة الهشاشة؛ نوع الفعالية التي حضرها',
    'a12':   'نوع الفعالية؛ جنس المشاركين وأعمارهم',
    'a13':   'موضوع الجلسة؛ الفئة المستهدفة؛ جنس المشاركين وأعمارهم',
    'b1':    'القطاع؛ نوع المشروع؛ نوع مكوّن الدعم',
    'b11':   'التخصص؛ قطاع المشروع المرتبط؛ نوع الشريك',
    'b12':   'القطاع؛ القطاع الفرعي؛ نوع المقترح؛ نوع الجهة المقدِّمة',
    'so20':  'الجنس؛ العمر؛ الجنسية؛ فئة الهشاشة؛ الدورة التدريبية؛ نوع الإلحاق',
    'so2c1': 'الجنس؛ العمر؛ الدورة التدريبية؛ نوع الدعم المُبلَّغ عنه',
    'c11':   'القطاع أو المهنة؛ نوع الشريك؛ نمط التنفيذ',
    'c12':   'الجنس؛ العمر؛ الجنسية؛ فئة الهشاشة؛ نوع التدريب',
    'so30':  'الجنس؛ العمر؛ الجنسية؛ فئة الهشاشة؛ القطاع؛ نوع الدعم المُتلقّى',
    'e01':   'مجال التخصص؛ ترتيب الاستضافة؛ نوع الشريك',
    'e02':   'الجنس؛ العمر؛ الجنسية؛ فئة الهشاشة؛ القطاع؛ نوع الخدمة؛ مرحلة المشروع',
    'e03':   'الجنس؛ العمر؛ نوع الجهة؛ دور المشارك',
    'f01':   'الجنس؛ العمر؛ الجنسية؛ فئة الهشاشة؛ نوع التدريب؛ مرحلة المشروع',
    'f02':   'القطاع؛ نوع التدريب (النمط)؛ الفئة المستهدفة والمستوى؛ نوع الشريك',
}


def form(fid, sheet, indicator, table, title_ar, calc_ar, who_ar, when_ar, fixed=None, filter_=None, sections=()):
    assert fid not in FORMS
    FORMS[fid] = dict(id=fid, sheet=sheet, indicator=indicator, table=table, title_ar=title_ar,
                      calc_ar=calc_ar, who_ar=who_ar, when_ar=when_ar,
                      fixed=fixed or {}, filter=filter_ or {}, sections=list(sections))

def sec(row, title_ar, *fields):
    return dict(row=row, title_ar=title_ar, fields=list(fields))

def fld(row, key, type_, label_ar, help_ar=None, **cfg):
    d = dict(row=row, key=key, type=type_, label_ar=label_ar, help_ar=help_ar)
    d.update(cfg)
    return d

# ── shared identification blocks ─────────────────────────────────────────
def ident_full(with_confirm=True, confirm_note=False, nid_note_ar=None):
    fs = [fld('National ID', 'national_id', 'nid', 'الرقم الوطني', nid_note_ar, required=True)]
    if with_confirm:
        fs.append(fld('National ID (validation - re-enter)', 'national_id_confirm', 'nid_confirm',
                      'الرقم الوطني (للتحقق - أعد الإدخال)', 'يجب أن يطابق الحقل أعلاه.' if confirm_note else None, required=True))
    fs.append(fld('Full name', 'full_name', 'person_name', 'الاسم الكامل', required=True))
    return fs

SEX = fld('Gender', 'sex', 'person_sex', 'الجنس', 'للتفصيل.', required=True,
          options=[('male', 'Male', 'ذكر'), ('female', 'Female', 'أنثى')])
AGE = fld('Age', 'age_years', 'age', 'العمر', 'للتفصيل.', required=True)
AGE_DERIVED = fld('Age', 'age_years', 'age', 'العمر',
                  'للتفصيل. سجّل الرقم؛ تُشتق الفئات العمرية عند الإبلاغ.', required=True)
NAT = fld('Nationality', 'nationality_id', 'select', 'الجنسية', 'للتفصيل.',
          ref='nationality', other='nationality_other', required=True)
VUL = fld('Vulnerability category', 'vulnerability', 'multi', 'فئة الهشاشة',
          'للتفصيل. اختر كل ما ينطبق - قد يقع الشخص في أكثر من فئة.', question='vulnerability', required=True)
VUL_PLAIN = fld('Vulnerability category', 'vulnerability', 'multi', 'فئة الهشاشة', 'للتفصيل.',
                question='vulnerability', required=True)
PHONE = fld('Phone number', 'phone', 'person_phone', 'رقم الهاتف')
ENUM = fld('Enumerator name', 'enumerator_name', 'text', 'اسم الباحث/ة')
COMPLETED_ON = fld('Date this record was completed', 'completed_on', 'date', 'تاريخ إكمال هذا السجل')
EVIDENCE = lambda q, ar, help_ar=None, row='Evidence on file': fld(row, q, 'multi', ar, help_ar, question=q)

# ═══════════════════════════════════════════════════════════════════════════
form('imp0', 'IMP-0_Sustained_engagement', 'RMTH-IMP-0', 'rmth_outcome_survey',
     'الانخراط المستدام في العمل أو الدخل',
     'عدّ وليس نسبة: المستفيدون الفريدون (حسب الرقم الوطني) الذين تأكد انخراطهم المستدام لمدة X شهراً متتالياً على الأقل. يُحتسب كل منهم مرة واحدة فقط مهما كان عدد التدريبات أو آليات الدعم التي حصل عليها. الهدف: 65 شخصاً خلال 3 سنوات. بند مفتوح: تكتب خطة العمل الصيغة الحسابية كنسبة؛ يجب التأكد مع إينابل من أن العدّ هو ما يُبلَّغ عنه.',
     'جهة تنسيق الرصد والتقييم في البلدية، عبر الهاتف أو زيارة ميدانية',
     'في كل جولة متابعة بعد بلوغ المستفيد نقطة X شهراً؛ يُبلَّغ عنه في نهاية المشروع',
     fixed={'survey_kind': 'imp_0'}, filter_={'survey_kind': 'imp_0'}, sections=[
  sec('IDENTIFICATION', 'التعريف',
      *ident_full(confirm_note=True, nid_note_ar='المفتاح الفريد لإزالة التكرار عبر جميع النماذج.'),
      PHONE, SEX, AGE_DERIVED, NAT, VUL),
  sec('PATHWAY AND ENTRY POINT', 'المسار ونقطة الدخول',
      fld('Through which Municipality-facilitated opportunity did this person FIRST access economic support?',
          'pathway_id', 'select', 'من خلال أي فرصة سهّلتها البلدية حصل هذا الشخص لأول مرة على دعم اقتصادي؟',
          'التفصيل حسب نوع المسار، وفق فئات خطة العمل. سجّل أول وصول فقط.',
          ref='imp0_pathway', other='pathway_other', required=True),
      fld('Reference of that opportunity', 'pathway_refs', 'parts', 'مرجع تلك الفرصة',
          'يربط هذا السجل بنموذج المخرجات الذي سجّل الشخص أولاً. لكل خيار مسار أعلاه معرّف هنا، بما في ذلك مسار التدريب الداخلي أو المقابلة المسهَّلة، الذي يُتتبع عبر معرّف الفعالية أو الجلسة.',
          parts=[('pathway_event_id', 'record', 'Event or Session ID (RMTH-EV- / RMTH-VG-...)', 'معرّف الفعالية أو الجلسة (RMTH-EV- / RMTH-VG-...)', dict(table='rmth_event')),
                 ('pathway_proposal_id', 'record', 'Proposal / Project ID (RMTH-PP-...)', 'معرّف المقترح / المشروع (RMTH-PP-...)', dict(table='rmth_proposal')),
                 ('pathway_cycle_id', 'record', 'Training cycle reference (RMTH-TC- / RMTH-EP-...)', 'مرجع دورة التدريب (RMTH-TC- / RMTH-EP-...)', dict(table='rmth_training_cycle')),
                 ('pathway_incubator_id', 'record', 'Incubator ID (RMTH-IN-...)', 'معرّف الحاضنة (RMTH-IN-...)', dict(table='rmth_incubator')),
                 ('pathway_enterprise_id', 'record', 'Enterprise ID (RMTH-EN-...)', 'معرّف المشروع (RMTH-EN-...)', dict(table='rmth_enterprise'))]),
      fld('Month and year of first access', 'first_access_month', 'month', 'شهر وسنة أول وصول',
          'يبدأ احتساب قاعدة X شهراً من هنا.', required=True)),
  sec('SUSTAINED ENGAGEMENT', 'الانخراط المستدام',
      fld('Which follow-up round is this?', 'round_id', 'select', 'أي جولة متابعة هذه؟', ref='imp0_round', required=True),
      fld('Date of this contact', 'contact_date', 'date', 'تاريخ هذا التواصل', required=True),
      fld('Are you currently engaged in paid employment, self-employment or an income-generating activity?',
          'engaged_id', 'select', 'هل أنت حالياً منخرط/ة في عمل مأجور أو عمل حر أو نشاط مدرّ للدخل؟',
          'لا تتخطَّ سؤال الأشهر أدناه عندما تكون الإجابة "لا، توقفت". فمن كان منخرطاً 12 شهراً وتوقف الشهر الماضي لا يزال مستوفياً للتعريف.',
          ref='imp0_engaged', required=True),
      fld('In what capacity are you engaged, or were you engaged?', 'capacity_id', 'select',
          'بأي صفة أنت منخرط/ة، أو كنت منخرطاً/ة؟',
          'لا يُحتسب العمل اليومي أو العرضي إلا إذا كان متواصلاً، وفقاً لاستثناء خطة العمل للأعمال قصيرة الأجل أو المؤقتة أو لمرة واحدة.',
          ref='imp0_capacity'),
      fld('Number of CONSECUTIVE months engaged, with no break of a month or longer', 'consecutive_months', 'number',
          'عدد الأشهر المتتالية للانخراط، دون انقطاع لشهر أو أكثر',
          'سجّل الرقم لا الفئة، حتى يمكن تطبيق المعيار أدناه أياً كانت قيمة X المتفق عليها. لمن توقف، سجّل الأشهر المكتملة قبل التوقف.',
          sub='Number of whole months', sub_ar='عدد الأشهر الكاملة', required=True),
      fld('If no longer engaged: month and year of stopping, and main reason', 'stopped', 'parts',
          'إن لم يعد منخرطاً: شهر وسنة التوقف والسبب الرئيسي',
          'اختياري - للتعلّم وإدارة البرنامج. ليس جزءاً من عدّ المؤشر.',
          parts=[('stopped_month', 'month', 'Month and year', 'الشهر والسنة', {}),
                 ('imp0_stop_reason_id', 'select', 'Reason', 'السبب', dict(ref='imp0_stop_reason', other='imp0_stop_reason_other'))])),
  sec('VERIFICATION AND COUNTING', 'التحقق والعدّ',
      fld('Sustained engagement criterion met?', 'imp0_criterion_id', 'select', 'هل استوفي معيار الانخراط المستدام؟',
          'هذا الحقل ينتج عدّ المؤشر. يجب أن يتبع حسابياً من حقل الأشهر أعلاه. بند مفتوح: اتفق على قيمة X مع البلدية قبل الاستخدام الأول.',
          ref='imp0_criterion', required=True, counting=True),
      fld('How was this verified, and what is on file?', 'imp0_verification', 'multi', 'كيف تم التحقق، وما الموجود في الملف؟',
          'الإفادة الذاتية وحدها أضعف المصادر؛ اسعَ للحصول على وثيقة واحدة على الأقل حيثما أمكن.',
          question='imp0_verification'),
      fld('Has this National ID already been counted for this indicator in a previous round?', 'counted_under_id', 'readonly',
          'هل سبق احتساب هذا الرقم الوطني لهذا المؤشر في جولة سابقة؟',
          'يمنع العدّ المزدوج. يُحتسب كل مستفيد مرة واحدة فقط، وفق خطة العمل.',
          derived='counted_under'),
      ENUM),
])

# ═══════════════════════════════════════════════════════════════════════════
form('so10', 'SO1-0_Employability', 'RMTH-SO1-0', 'rmth_outcome_survey',
     'قابلية التشغيل بعد فرص التشبيك',
     'عدد الأشخاص الفريدين المستوفين لحد قابلية التشغيل: إلحاق مؤكد، أو خطوة واحدة على الأقل قابلة للتحقق (حضور مقابلة، تلقي عرض، بدء تدريب داخلي أو إلحاق، الالتحاق بتدريب) مع خطوة أخرى من القائمة. يُحتسب مرة واحدة لكل شخص. بند مفتوح: يجب تأكيد هذا الحد مع البلدية - مؤشر النتيجة المقابل في خطة العمل يعدّ التوظيف المؤكد فقط.',
     'جهة تنسيق الرصد والتقييم في البلدية، بمتابعة هاتفية',
     'بعد ثلاثة إلى ستة أشهر من الفعالية التي حضرها',
     fixed={'survey_kind': 'so1_0'}, filter_={'survey_kind': 'so1_0'}, sections=[
  sec('IDENTIFICATION', 'التعريف',
      *ident_full(with_confirm=False, nid_note_ar='مفتاح إزالة التكرار؛ يجب أن يطابق كشف حضور الفعالية.'),
      PHONE, SEX, AGE, NAT, VUL_PLAIN),
  sec('NETWORKING OPPORTUNITY ATTENDED', 'فرصة التشبيك التي حضرها',
      fld('Which event is this follow-up attributed to?', 'event_id', 'record', 'إلى أي فعالية تُنسب هذه المتابعة؟',
          'فعالية واحدة فقط. هذا هو مفتاح التفصيل حسب نوع الفعالية.',
          sub='Single Event ID (RMTH-EV-...) or Session ID (RMTH-VG-...)', sub_ar='معرّف فعالية واحدة (RMTH-EV-...) أو معرّف جلسة (RMTH-VG-...)',
          table='rmth_event', required=True),
      fld('Type of that event', 'so10_event_type_id', 'select', 'نوع تلك الفعالية', 'التفصيل حسب نوع الفعالية.',
          ref='so10_event_type', required=True),
      fld('Date of that event', 'event_date', 'readonly', 'تاريخ تلك الفعالية',
          'ينبغي أن تكون المتابعة بعد ثلاثة أشهر على الأقل من هذا التاريخ.', derived='event_date'),
      fld('Any other Municipality-facilitated events attended since?', 'other_events', 'text',
          'هل حضر/ت أي فعاليات أخرى سهّلتها البلدية منذ ذلك الحين؟',
          'اختياري - للتعلّم وإدارة البرنامج. ليس جزءاً من عدّ المؤشر.',
          sub='Event or Session IDs', sub_ar='معرّفات الفعاليات أو الجلسات')),
  sec('EMPLOYABILITY CHANGE', 'التغير في قابلية التشغيل',
      fld('Was the person reached?', 'reached_id', 'select', 'هل تم الوصول إلى الشخص؟',
          'يُستبعد من لم يتم الوصول إليهم من العدّ ومن أي نسبة. سجّل المحاولات.',
          ref='reached', required=True),
      fld('Since attending, which VERIFIABLE steps have you taken?', 'so10_verifiable_step', 'multi',
          'منذ الحضور، ما الخطوات القابلة للتحقق التي اتخذتها؟',
          'يلزم بند واحد على الأقل هنا لاستيفاء الحد. يمكن التحقق من هذه البنود لدى صاحب عمل أو جهة مضيفة أو سجل تدريب.',
          question='so10_verifiable_step'),
      fld('Since attending, which other steps have you taken?', 'so10_other_step', 'multi',
          'منذ الحضور، ما الخطوات الأخرى التي اتخذتها؟',
          'إفادة ذاتية. بند واحد هنا، مع خطوة واحدة قابلة للتحقق أعلاه، يستوفي الحد.',
          question='so10_other_step'),
      fld('What are you doing now?', 'current_status_id', 'select', 'ماذا تفعل/ين الآن؟',
          'الخيارات الأربعة الأولى تُعدّ إلحاقاً مؤكداً يستوفي الحد بمفرده.',
          ref='so10_current_status')),
  sec('SCORING AND EVIDENCE', 'التقييم والأدلة',
      fld('Employability threshold met?', 'so10_threshold_id', 'readonly', 'هل استوفي حد قابلية التشغيل؟',
          'هذا الحقل ينتج عدّ المؤشر. يجب أن يتبع من الأسئلة الثلاثة أعلاه، لا أن يُقدَّر بشكل منفصل.',
          derived='so10_threshold', counting=True),
      fld('Has this National ID already been counted for this indicator?', 'counted_under_id', 'readonly',
          'هل سبق احتساب هذا الرقم الوطني لهذا المؤشر؟', 'يُحتسب مرة واحدة لكل شخص.', derived='counted_under'),
      EVIDENCE('so10_evidence', 'الأدلة في الملف'),
      fld('Enumerator name and date of contact', 'enumerator', 'parts', 'اسم الباحث/ة وتاريخ التواصل',
          parts=[('enumerator_name', 'text', 'Name', 'الاسم', {}), ('contact_date', 'date', 'Date', 'التاريخ', {})])),
])

# ═══════════════════════════════════════════════════════════════════════════
form('a12', 'SO1-A1.2_Networking_event', 'RMTH-SO1-A1.2', 'rmth_event',
     'فعاليات التشبيك بما فيها الأيام الوظيفية',
     'عدد فعاليات التشبيك الموثقة المنفذة. تُحتسب كل فعالية مرة واحدة. الفعالية المشتركة تُحتسب 1 هنا و1 تحت RMTH-SO1-A1.3؛ ولا يجوز أبداً جمع المؤشرين، لأن خطة العمل تعاملهما كمؤشر واحد بهدف واحد هو 4 سنوياً.',
     'الموظف البلدي الذي نظّم الفعالية أو شارك في تنظيمها',
     'خلال أسبوع من الفعالية؛ يُبلَّغ عنه ربع سنوياً',
     fixed={'event_kind': 'networking'}, filter_={'event_kind': 'networking'}, sections=[
  sec('EVENT IDENTIFICATION', 'تعريف الفعالية',
      fld('Event ID', 'reference', 'readonly', 'معرّف الفعالية', sub='(RMTH-EV-YYYY-000)', sub_ar='(RMTH-EV-YYYY-000)', derived='reference'),
      fld('Event title', 'title', 'text', 'عنوان الفعالية', required=True),
      fld('Type of event', 'event_type_id', 'select', 'نوع الفعالية', 'التفصيل حسب نوع الفعالية.',
          ref='a12_event_type', other='event_type_other', required=True),
      fld('Is this event solely a vocational guidance session?', 'solely_guidance', 'bool',
          'هل هذه الفعالية جلسة توجيه مهني فقط؟',
          'هذا الحقل يقرر ما إذا كان السجل ينتمي إلى هنا، وبالتالي ينتج عدّ المؤشر: كل سجل تكون إجابته لا يُحتسب فعالية واحدة. الفعالية المشتركة تُسجَّل هنا وأيضاً كجلسة تحت RMTH-SO1-A1.3؛ ثم يُبلَّغ عن المؤشرين بشكل منفصل، ولا يُجمعان أبداً.',
          options=[('false', 'No - it is a networking event, record it here', 'لا - إنها فعالية تشبيك، سجّلها هنا'),
                   ('true', 'Yes - record it under RMTH-SO1-A1.3 instead and do not create a record here', 'نعم - سجّلها تحت RMTH-SO1-A1.3 بدلاً من ذلك ولا تنشئ سجلاً هنا')],
          required=True, counting=True),
      fld('Date of the event', 'dates', 'parts', 'تاريخ الفعالية',
          parts=[('start_date', 'date', 'Start date', 'تاريخ البدء', dict(required=True)),
                 ('end_date', 'date', 'End date', 'تاريخ الانتهاء', dict(required=True))]),
      fld('Location', 'location', 'text', 'الموقع'),
      fld('Organised by', 'organised_by_id', 'select', 'الجهة المنظمة', ref='a12_organised_by'),
      fld('Partner organisation(s) and type', 'partners', 'parts', 'المنظمة/المنظمات الشريكة ونوعها',
          parts=[('partner_names', 'text', 'Name(s)', 'الاسم/الأسماء', {}),
                 ('a12_partner_type', 'multi', 'Type', 'النوع', dict(question='a12_partner_type'))])),
  sec('PARTICIPATION', 'المشاركة',
      fld('Number of employers or companies taking part', 'employers_count', 'number', 'عدد أصحاب العمل أو الشركات المشاركة',
          'ينبغي أن يحضر صاحب عمل واحد على الأقل في فعالية مسجّلة كفعالية تشبيك أو يوم وظيفي.'),
      fld('Number of attendees', 'attendees', 'parts', 'عدد الحاضرين',
          'التفصيل حسب جنس المشاركين مطلوب في خطة العمل.',
          parts=[('attendees_total', 'number', 'Total', 'الإجمالي', {}),
                 ('attendees_women', 'number', 'Of whom women', 'منهم نساء', {}),
                 ('attendees_men', 'number', 'Of whom men', 'منهم رجال', {}),
                 ('attendees_non_jordanian', 'number', 'Of whom non-Jordanian', 'منهم غير أردنيين', {}),
                 ('attendees_disability', 'number', 'Of whom persons with disability', 'منهم أشخاص من ذوي الإعاقة', {})]),
      fld('Age breakdown of attendees', 'age_bands', 'parts', 'التوزيع العمري للحاضرين',
          'الفئات نفسها المستخدمة في نماذج الأفراد، حتى يمكن مطابقة بيانات الفعالية مع بيانات الأفراد.',
          parts=[('age_under_18', 'number', 'Under 18', 'دون 18', {}),
                 ('age_18_24', 'number', '18-24', '18-24', {}),
                 ('age_25_35', 'number', '25-35', '25-35', {}),
                 ('age_36_45', 'number', '36-45', '36-45', {}),
                 ('age_46_plus', 'number', '46 and above', '46 فأكثر', {})])),
  sec('EVIDENCE', 'الأدلة',
      EVIDENCE('a12_evidence', 'الأدلة في الملف',
               'كشف الحضور والصور هما الحد الأدنى الذي تسميه خطة العمل. يجب أن يحمل كشف الحضور الأرقام الوطنية حتى يمكن متابعة الحاضرين تحت RMTH-SO1-0.'),
      fld('Municipal focal point', 'focal_point', 'parts', 'جهة التنسيق البلدية',
          parts=[('focal_point_name', 'text', 'Name', 'الاسم', {}), ('focal_point_phone', 'phone', 'Phone', 'الهاتف', {})]),
      COMPLETED_ON),
])

# ═══════════════════════════════════════════════════════════════════════════
form('a13', 'SO1-A1.3_Guidance_session', 'RMTH-SO1-A1.3', 'rmth_event',
     'جلسات التوجيه المهني',
     'عدد جلسات التوجيه المهني الموثقة المنفذة. تُحتسب كل جلسة مرة واحدة. الجلسة المنعقدة ضمن فعالية تشبيك أكبر تُحتسب 1 هنا، وتُحتسب تلك الفعالية 1 تحت RMTH-SO1-A1.2؛ ولا يجوز أبداً جمع المؤشرين.',
     'موظف التوجيه المهني في البلدية أو الميسّر الذي قدّم الجلسة',
     'خلال أسبوع من الجلسة؛ يُبلَّغ عنه ربع سنوياً',
     fixed={'event_kind': 'guidance'}, filter_={'event_kind': 'guidance'}, sections=[
  sec('SESSION IDENTIFICATION', 'تعريف الجلسة',
      fld('Session ID', 'reference', 'readonly', 'معرّف الجلسة',
          'كل سجل مكتمل ينتج وحدة واحدة من عدّ المؤشر: جلسة واحدة، سجل واحد، معرّف واحد. لا يوجد حقل فرز إضافي، فلا تفتح سجلاً لجلسة أُلغيت أو لم تنعقد.',
          sub='(RMTH-VG-YYYY-000)', sub_ar='(RMTH-VG-YYYY-000)', derived='reference', counting=True),
      fld('Session title or topic', 'title', 'text', 'عنوان الجلسة أو موضوعها', required=True),
      fld('Date of the session', 'start_date', 'date', 'تاريخ الجلسة', required=True, mirror='end_date'),
      fld('Duration', 'duration_hours', 'number', 'المدة', sub='Number of hours', sub_ar='عدد الساعات', step='0.5'),
      fld('Location and modality', 'where', 'parts', 'الموقع والطريقة',
          parts=[('location', 'text', 'Location', 'الموقع', {}),
                 ('modality_id', 'select', 'Modality', 'الطريقة', dict(ref='modality_ipob'))]),
      fld('Was the session standalone, or part of a larger event?', 'parent_event_id', 'record',
          'هل كانت الجلسة مستقلة أم جزءاً من فعالية أكبر؟',
          'سجّل معرّف الفعالية الأم حتى يمكن مطابقة السجلين. لا تنشئ سجل RMTH-SO1-A1.2 ثانياً لهذه الجلسة.',
          table='rmth_event', kind={'event_kind': 'networking'},
          empty='Standalone session', empty_ar='جلسة مستقلة',
          sub='Part of a larger networking event - parent Event ID', sub_ar='جزء من فعالية تشبيك أكبر - معرّف الفعالية الأم')),
  sec('CONTENT AND DELIVERY', 'المحتوى والتقديم',
      fld('Delivered by', 'delivered_by_id', 'select', 'مقدَّمة من', ref='a13_delivered_by', other='delivered_by_other'),
      fld('Topics covered', 'a13_topic', 'multi', 'المواضيع المغطاة', 'التفصيل حسب الموضوع.', question='a13_topic'),
      fld('Target group', 'target_group_id', 'select', 'الفئة المستهدفة', 'للتفصيل.', ref='a13_target_group', other='target_group_other')),
  sec('PARTICIPATION AND EVIDENCE', 'المشاركة والأدلة',
      fld('Number of participants', 'attendees', 'parts', 'عدد المشاركين',
          'التفصيل حسب الجنس مطلوب في خطة العمل.',
          parts=[('attendees_total', 'number', 'Total', 'الإجمالي', {}),
                 ('attendees_women', 'number', 'Of whom women', 'منهم نساء', {}),
                 ('attendees_men', 'number', 'Of whom men', 'منهم رجال', {}),
                 ('attendees_non_jordanian', 'number', 'Of whom non-Jordanian', 'منهم غير أردنيين', {}),
                 ('attendees_disability', 'number', 'Of whom persons with disability', 'منهم أشخاص من ذوي الإعاقة', {})]),
      fld('Age breakdown of participants', 'age_bands', 'parts', 'التوزيع العمري للمشاركين',
          'الفئات نفسها المستخدمة في نماذج الأفراد.',
          parts=[('age_under_18', 'number', 'Under 18', 'دون 18', {}),
                 ('age_18_24', 'number', '18-24', '18-24', {}),
                 ('age_25_35', 'number', '25-35', '25-35', {}),
                 ('age_36_45', 'number', '36-45', '36-45', {}),
                 ('age_46_plus', 'number', '46 and above', '46 فأكثر', {})]),
      EVIDENCE('a13_evidence', 'الأدلة في الملف',
               'يجب أن يحمل كشف الحضور الأرقام الوطنية حتى يمكن متابعة المشاركين تحت RMTH-SO1-0.'),
      fld('Facilitator name', 'facilitator_name', 'text', 'اسم الميسّر/ة'),
      COMPLETED_ON),
])

# ═══════════════════════════════════════════════════════════════════════════
form('b1', 'SO1-B1_Support_criticality', 'RMTH-SO1-B1', 'rmth_project_implementer',
     'أهمية الدعم البلدي لمنفذي المشاريع',
     'البسط: المنفذون الذين قيّموا مكوّن دعم واحداً على الأقل بأنه "أساسي". المقام: المنفذون الذين تلقوا مكوّن دعم بلدي واحداً على الأقل، وتم التواصل معهم، وأجابوا. يُستبعد من تعذّر الوصول إليهم أو رفضوا من الاثنين. المنفذ الذي يدير عدة مشاريع معتمدة يُحتسب مرة واحدة. يُضرب في 100.',
     'جهة تنسيق الرصد والتقييم في البلدية، بمقابلة مع المنفذ',
     'بعد ستة إلى اثني عشر شهراً من بدء تشغيل المشروع',
     sections=[
  sec('IMPLEMENTER AND PROJECT', 'المنفذ والمشروع',
      fld('Implementing entity', 'entity', 'parts', 'الجهة المنفذة',
          parts=[('entity_name', 'text', 'Name', 'الاسم', dict(required=True)),
                 ('entity_type_id', 'select', 'Type', 'النوع', dict(ref='b1_implementer_type'))]),
      fld('Is this the first record for this implementer?', 'first_record_of_id', 'record',
          'هل هذا أول سجل لهذا المنفذ؟',
          'يعدّ المقام المنفذين لا المشاريع. الجهة التي تدير ثلاثة مشاريع معتمدة تدخل المقام مرة واحدة.',
          table='rmth_project_implementer', empty='Yes - include in the denominator', empty_ar='نعم - أدرجه في المقام',
          sub='No - already surveyed under record', sub_ar='لا - سبق استطلاعه تحت السجل'),
      fld('Approved proposal / project ID(s) held by this implementer', 'proposal_ids', 'records',
          'معرّفات المقترحات / المشاريع المعتمدة لدى هذا المنفذ',
          'يربط بسجلات الاعتماد تحت RMTH-SO1-B1.2.',
          table='rmth_proposal', payload='proposal_ids', sub='(RMTH-PP-YYYY-000, list all)', sub_ar='(RMTH-PP-YYYY-000، اذكر الجميع)'),
      fld('Project title(s)', 'project_titles', 'text', 'عنوان/عناوين المشروع'),
      fld('Project type', 'project_type_id', 'select', 'نوع المشروع',
          'للتفصيل. إذا كان لدى المنفذ عدة مشاريع، سجّل الرئيسي.',
          ref='project_type', other='project_type_other'),
      fld('Sector', 'sector_id', 'select', 'القطاع', 'للتفصيل.', ref='sector', other='sector_other'),
      fld('Respondent name, role and phone', 'respondent', 'parts', 'اسم المجيب ودوره وهاتفه',
          'يجب أن يكون المجيب شخصاً يدير المشروع يومياً.',
          parts=[('respondent_name', 'text', 'Name', 'الاسم', {}),
                 ('respondent_role', 'text', 'Role', 'الدور', {}),
                 ('respondent_phone', 'phone', 'Phone', 'الهاتف', {})]),
      fld('Was the implementer reached?', 'reached_id', 'select', 'هل تم الوصول إلى المنفذ؟',
          'المقابلات المكتملة فقط تدخل المقام.', ref='b1_reached', required=True),
      fld('Date of this interview', 'interviewed_on', 'date', 'تاريخ هذه المقابلة'),
      fld('Enters the denominator?', 'enters_denominator', 'readonly', 'هل يدخل المقام؟',
          'هذا الحقل ينتج المقام. اشتقّه من الحقول الثلاثة أعلاه بدلاً من تركها لتُجمع عند الجدولة. أكمل شبكة الدعم أولاً ثم عد إلى هذا الحقل.',
          derived='enters_denominator', counting=True)),
  sec('SUPPORT COMPONENTS AND HOW CRITICAL EACH WAS', 'مكوّنات الدعم ومدى أهمية كل منها',
      fld("Support-criticality grid: for EACH component below, record whether it was received and, if so, how important it was to the implementer's ability to operate",
          'support', 'grid', 'شبكة أهمية الدعم: لكل مكوّن أدناه، سجّل ما إذا تم استلامه، وإن كان كذلك، مدى أهميته لقدرة المنفذ على العمل',
          'رتّب هذا كشبكة، صف لكل مكوّن، قبل الرقمنة. التقييمات لكل مكوّن هي ما يعطي التفصيل حسب نوع مكوّن الدعم؛ خلية نصية واحدة لن تحتويها.',
          components='support_component', ratings='support_rating'),
      fld('Did this implementer receive at least one component of municipal support?', 'received_any', 'readonly',
          'هل تلقى هذا المنفذ مكوّن دعم بلدي واحداً على الأقل؟',
          'المنفذ الذي لم يتلقَّ شيئاً لا يمكن سؤاله عمّا إذا كان أي شيء أساسياً.',
          derived='received_any'),
      fld("Was at least one component rated 'Essential'?", 'any_essential', 'readonly',
          'هل قُيِّم مكوّن واحد على الأقل بأنه "أساسي"؟',
          'هذا الحقل ينتج البسط. يجب أن يتبع من الشبكة أعلاه، لا أن يُسأل بشكل منفصل.',
          derived='any_essential', counting=True),
      fld('Which single component was the most essential?', 'most_essential_component_id', 'select',
          'ما المكوّن الوحيد الأكثر أهمية؟', 'التفصيل حسب نوع مكوّن الدعم.',
          ref='support_component', empty='none was essential', empty_ar='لم يكن أي منها أساسياً'),
      fld('If no component was essential, what support would have made the difference?', 'would_have_helped', 'area',
          'إن لم يكن أي مكوّن أساسياً، فما الدعم الذي كان سيُحدث الفرق؟',
          'اسأل فقط إذا كانت الإجابة أعلاه لا. اختياري - للتعلّم وإدارة البرنامج. ليس جزءاً من عدّ المؤشر.')),
  sec('STATUS AND EVIDENCE', 'الحالة والأدلة',
      fld('Is the project currently operating?', 'operating_status_id', 'select', 'هل المشروع يعمل حالياً؟',
          'القدرة على العمل هي موضوع المؤشر، لذا فهذا هو سياق التقييم.', ref='b1_operating_status'),
      EVIDENCE('b1_evidence', 'الأدلة في الملف'),
      ENUM),
])

# ═══════════════════════════════════════════════════════════════════════════
form('b11', 'SO1-B1.1_Specialised_prog', 'RMTH-SO1-B1.1', 'rmth_training_programme',
     'برامج التدريب المتخصصة المصممة للمشاريع المعتمدة',
     'عدد البرامج المستوفية للاختبارين معاً: (أ) التخصص صناعي أو زراعي أو إداري، و(ب) البرنامج موثق كمصمم وفق المتطلبات الفنية لمشروع معتمد واحد على الأقل. يُحتسب كل برنامج مرة واحدة.',
     'جهة تنسيق التدريب في البلدية، مع الشريك الذي شارك في تطوير المحتوى',
     'عند اكتمال تطوير البرنامج؛ يُبلَّغ عنه ربع سنوياً',
     fixed={'programme_type': 'specialised'}, filter_={'programme_type': 'specialised'}, sections=[
  sec('PROGRAMME IDENTIFICATION', 'تعريف البرنامج',
      fld('Programme reference', 'reference', 'readonly', 'مرجع البرنامج', sub='(RMTH-TP-YYYY-000)', sub_ar='(RMTH-TP-YYYY-000)', derived='reference'),
      fld('Programme title', 'title', 'text', 'عنوان البرنامج', required=True),
      fld('Specialisation', 'specialisation_id', 'select', 'التخصص',
          'البرامج الصناعية والزراعية والإدارية فقط هي التي تُحتسب لهذا المؤشر.',
          ref='b11_specialisation', other='specialisation_other', required=True),
      fld('Occupation or skill set targeted', 'occupation', 'text', 'المهنة أو مجموعة المهارات المستهدفة',
          sub='(open text, for example CNC operator, greenhouse technician, warehouse clerk)',
          sub_ar='(نص حر، مثلاً مشغّل CNC، فني بيوت بلاستيكية، كاتب مستودع)')),
  sec('LINK TO AN APPROVED PROJECT', 'الربط بمشروع معتمد',
      fld('Which approved project(s) does this programme serve?', 'proposal_ids', 'records',
          'أي مشروع/مشاريع معتمدة يخدمها هذا البرنامج؟',
          'مطلوب. البرنامج غير المرتبط بمشروع معتمد لا يُحتسب لهذا المؤشر.',
          table='rmth_proposal', payload='proposal_ids', required=True,
          sub='Proposal / Project ID(s) (RMTH-PP-...)', sub_ar='معرّفات المقترحات / المشاريع (RMTH-PP-...)'),
      fld('Sector of the linked project(s)', 'linked_sector_id', 'select', 'قطاع المشروع/المشاريع المرتبطة',
          'للتفصيل. استخدم القائمة نفسها المستخدمة في RMTH-SO1-B1.2 حتى يمكن الجدولة المتقاطعة بينهما.',
          ref='sector', other='linked_sector_other'),
      fld("How were the project's technical requirements identified?", 'b11_requirements_method', 'multi',
          'كيف تم تحديد المتطلبات الفنية للمشروع؟',
          'يجب توثيق طريقة واحدة على الأقل حتى يُعدّ البرنامج مصمماً وفق المتطلبات.',
          question='b11_requirements_method'),
      fld('Reference of the requirements document', 'requirements_document', 'text', 'مرجع وثيقة المتطلبات',
          'هذا هو الدليل على أن البرنامج مصمم خصيصاً لا عام.',
          sub='(document title and date)', sub_ar='(عنوان الوثيقة وتاريخها)'),
      fld('Tailoring criterion met?', 'tailoring_met', 'bool', 'هل استوفي معيار التصميم الخاص؟',
          'هذا الحقل ينتج عدّ المؤشر.',
          options=[('true', 'Yes - linked to an approved project and requirements documented', 'نعم - مرتبط بمشروع معتمد والمتطلبات موثقة'),
                   ('false', 'No', 'لا')], counting=True)),
  sec('DEVELOPMENT PARTNER', 'شريك التطوير',
      fld('Developed with', 'developed_with_id', 'select', 'طُوِّر مع', 'التفصيل حسب نوع الشريك.', ref='b11_developed_with'),
      fld('Partner name(s)', 'partner_names', 'text', 'اسم/أسماء الشريك'),
      fld('Total hours and modality', 'hours_modality', 'parts', 'إجمالي الساعات والطريقة',
          'هوية برنامج دنيا، حتى يمكن مطابقة المرجع مع سجلات التنفيذ.',
          parts=[('total_hours', 'number', 'Total hours', 'إجمالي الساعات', dict(step='0.5')),
                 ('b11_modality_id', 'select', 'Modality', 'الطريقة', dict(ref='b11_modality'))])),
  sec('EVIDENCE', 'الأدلة',
      EVIDENCE('b11_evidence', 'الأدلة في الملف', 'تسمّي خطة العمل المواد التدريبية دليلاً لمؤشرات تطوير البرامج.'),
      COMPLETED_ON),
])

# ═══════════════════════════════════════════════════════════════════════════
form('b12', 'SO1-B1.2_Proposal_approval', 'RMTH-SO1-B1.2', 'rmth_proposal',
     'المقترحات المعتمدة للتنفيذ',
     'عدد المقترحات التي قرارها "معتمد للتنفيذ" أو "معتمد بشروط". تُسجَّل المقترحات المؤجلة أو المرفوضة أو التي لا تزال قيد المراجعة لكنها لا تُحتسب. يُحتسب كل مقترح مرة واحدة، عند أول اعتماد.',
     'أمين سر لجنة المراجعة أو الاستثمار البلدية',
     'عند كل قرار للجنة؛ يُبلَّغ عنه ربع سنوياً',
     sections=[
  sec('PROPOSAL IDENTIFICATION', 'تعريف المقترح',
      fld('Proposal ID', 'reference', 'readonly', 'معرّف المقترح',
          'عند الاعتماد يصبح هذا المعرّف نفسه معرّف المشروع المستخدم في RMTH-SO1-B1 وRMTH-SO1-B1.1.',
          sub='(RMTH-PP-YYYY-000)', sub_ar='(RMTH-PP-YYYY-000)', derived='reference'),
      fld('Proposal title', 'title', 'text', 'عنوان المقترح', required=True),
      fld('Submitted by', 'submitter', 'parts', 'مقدَّم من', 'التفصيل حسب نوع الجهة المقدِّمة.',
          parts=[('submitted_by_name', 'text', 'Name of entity or person', 'اسم الجهة أو الشخص', dict(required=True)),
                 ('submitter_type_id', 'select', 'Type', 'النوع', dict(ref='b12_submitter_type', required=True))]),
      fld('Contact person and phone', 'contact', 'parts', 'الشخص المسؤول والهاتف',
          parts=[('contact_name', 'text', 'Name', 'الاسم', {}), ('contact_phone', 'phone', 'Phone', 'الهاتف', {})]),
      fld('Date submitted', 'submitted_on', 'date', 'تاريخ التقديم', required=True),
      fld('Proposal type', 'proposal_type_id', 'select', 'نوع المقترح', 'للتفصيل.', ref='project_type', other='proposal_type_other'),
      fld('Sector and sub-sector', 'sectors', 'parts', 'القطاع والقطاع الفرعي', 'للتفصيل.',
          parts=[('sector_id', 'select', 'Sector', 'القطاع', dict(ref='sector', other='sector_other')),
                 ('sub_sector', 'text', 'Sub-sector', 'القطاع الفرعي', {})])),
  sec('DECISION', 'القرار',
      fld('Municipal support requested', 'b12_support_requested', 'multi', 'الدعم البلدي المطلوب',
          'يغذّي شبكة مكوّنات الدعم في RMTH-SO1-B1.', question='b12_support_requested'),
      fld('Decision', 'decision_id', 'select', 'القرار',
          'هذا الحقل ينتج عدّ المؤشر. الخياران الأولان فقط يُحتسبان.',
          ref='b12_decision', counting=True),
      fld('Date of decision', 'decided_on', 'date', 'تاريخ القرار'),
      fld('Approving body and decision reference', 'approval', 'parts', 'الجهة المعتمِدة ومرجع القرار',
          'مرجع القرار هو الدليل الأساسي لهذا المؤشر.',
          parts=[('approving_body_id', 'select', 'Body', 'الجهة', dict(ref='b12_approving_body')),
                 ('decision_reference', 'text', 'Decision reference number', 'رقم مرجع القرار', {})]),
      fld('If approved with conditions, what are the conditions?', 'conditions', 'area', 'إذا اعتُمد بشروط، فما هي الشروط؟',
          'اختياري - للتعلّم وإدارة البرنامج. ليس جزءاً من عدّ المؤشر.'),
      ),
  sec('EVIDENCE', 'الأدلة',
      EVIDENCE('b12_evidence', 'الأدلة في الملف',
               'تسمّي خطة العمل تقارير البلدية والصور والشهادات أدلةً لمؤشر المشروع المقابل.'),
      COMPLETED_ON),
])

# ═══════════════════════════════════════════════════════════════════════════
form('so20', 'SO2-0_3month_placement', 'RMTH-SO2-0', 'rmth_outcome_survey',
     'الإلحاق خلال ثلاثة أشهر من إتمام الدورة',
     'البسط: المتمّون الذين بدأ إلحاقهم بعمل أو تدريب داخلي خلال ثلاثة أشهر من تاريخ انتهاء الدورة. المقام: المتمّون في كشف RMTH-SO2-C1.2 لتلك الدورة الذين بلغوا نقطة الثلاثة أشهر وتم الوصول إليهم للمتابعة. يُضرب في 100. بند مفتوح: يجب التأكد مع البلدية مما إذا كان العمل الحر يُحتسب إلحاقاً؛ نص المؤشر يقول عمل أو تدريب داخلي.',
     'جهة تنسيق الرصد والتقييم في البلدية، بمتابعة هاتفية',
     'بعد ثلاثة أشهر من انتهاء كل دورة تدريب',
     fixed={'survey_kind': 'so2_0'}, filter_={'survey_kind': 'so2_0'}, sections=[
  sec('IDENTIFICATION', 'التعريف',
      *ident_full(nid_note_ar='يجب أن يطابق سجل الإتمام تحت RMTH-SO2-C1.2.'),
      PHONE, SEX, AGE, NAT, VUL_PLAIN),
  sec('TRAINING CYCLE AND ELIGIBILITY', 'دورة التدريب والأهلية',
      fld('Training cycle reference and title', 'cycle_id', 'record', 'مرجع دورة التدريب وعنوانها', 'التفصيل حسب الدورة.',
          table='rmth_training_cycle', kind={'cycle_kind': 'employability'}, required=True,
          sub='Reference (RMTH-TC-...)', sub_ar='المرجع (RMTH-TC-...)'),
      fld('Date the cycle was completed', 'cycle_end', 'readonly', 'تاريخ إتمام الدورة',
          'تُحتسب نافذة الثلاثة أشهر من هذا التاريخ.', derived='cycle_end'),
      fld('Has the three-month point been reached?', 'three_month_reached', 'readonly', 'هل بُلغت نقطة الثلاثة أشهر؟',
          'المتمّون الذين تجاوزوا نقطة الثلاثة أشهر فقط يدخلون المقام.', derived='three_month_reached'),
      fld('Date of this follow-up contact', 'contact_date', 'date', 'تاريخ تواصل المتابعة هذا', required=True),
      fld('Was the person reached?', 'reached_id', 'select', 'هل تم الوصول إلى الشخص؟',
          'يُستبعد من تعذّر الوصول إليهم من المقام. سجّل المحاولات حتى يمكن الإبلاغ عن معدل الاستجابة إلى جانب النسبة.',
          ref='reached', required=True)),
  sec('PLACEMENT', 'الإلحاق',
      fld('Since completing the cycle, have you been placed in any of the following?', 'so20_placement_type', 'multi',
          'منذ إتمام الدورة، هل أُلحقت بأي مما يلي؟',
          'يُحتسب العمل والتدريب الداخلي والتدريب أثناء العمل والتلمذة المهنية. يُسجَّل العمل الحر بشكل منفصل في حقل البسط أدناه بانتظار قرار البلدية.',
          question='so20_placement_type'),
      fld('Month and year the placement started', 'placement_start_month', 'month', 'شهر وسنة بدء الإلحاق',
          'قارن مع تاريخ انتهاء الدورة لتطبيق قاعدة الثلاثة أشهر.'),
      fld('Placement outcome within three months of completing the cycle', 'so20_outcome_id', 'select',
          'نتيجة الإلحاق خلال ثلاثة أشهر من إتمام الدورة',
          'هذا الحقل ينتج البسط. إبقاء العمل الحر في سطر مستقل يعني أن البسط يمكن إعادة احتسابه بأي من الطريقتين بعد قرار البلدية.',
          ref='so20_outcome', counting=True),
      fld('Employer or host organisation', 'employer', 'parts', 'صاحب العمل أو الجهة المضيفة',
          parts=[('employer_name', 'text', 'Name', 'الاسم', {}),
                 ('employer_sector', 'text', 'Sector', 'القطاع', {}),
                 ('placement_title', 'text', 'Job or placement title', 'المسمى الوظيفي أو مسمى الإلحاق', {})]),
      fld('Was the placement facilitated by the Municipality or its partners?', 'facilitated_by_id', 'select',
          'هل سهّلت البلدية أو شركاؤها الإلحاق؟', ref='so20_facilitated_by'),
      fld('Arrangement and working time', 'arrangement', 'parts', 'الترتيب ووقت العمل',
          parts=[('arrangement_id', 'select', 'Arrangement', 'الترتيب', dict(ref='so20_arrangement')),
                 ('working_time_id', 'select', 'Working time', 'وقت العمل', dict(ref='so20_working_time'))]),
      fld('If not placed, what is the main obstacle?', 'obstacle_id', 'select', 'إن لم يُلحق، فما العقبة الرئيسية؟',
          'اختياري - للتعلّم وإدارة البرنامج. ليس جزءاً من عدّ المؤشر.',
          ref='so20_obstacle', other='obstacle_other')),
  sec('VERIFICATION', 'التحقق',
      fld('How was the placement verified, and what is on file?', 'so20_verification', 'multi',
          'كيف تم التحقق من الإلحاق، وما الموجود في الملف؟',
          'الإفادة الذاتية وحدها أضعف المصادر؛ اسعَ للحصول على وثيقة واحدة حيثما أمكن.',
          question='so20_verification'),
      ENUM),
])

# ═══════════════════════════════════════════════════════════════════════════
form('so2c1', 'SO2-C1_Trainee_feedback', 'RMTH-SO2-C1', 'rmth_outcome_survey',
     'رأي المتدربين في دعم التدريب لمسارهم الوظيفي',
     'البسط: المتدربون الذين أجابوا "نعم، بشكل كبير" أو "نعم، إلى حد ما" على السؤال الرئيسي. المقام: المتدربون في كشف إتمام RMTH-SO2-C1.2 للدورة الذين تم التواصل معهم والوصول إليهم. يُستبعد من تعذّر الوصول إليهم أو رفضوا من الاثنين. يُضرب في 100.',
     'جهة تنسيق الرصد والتقييم في البلدية، عبر الهاتف أو في جلسة متابعة',
     'بعد ثلاثة إلى ستة أشهر من انتهاء دورة التدريب',
     fixed={'survey_kind': 'so2_c1'}, filter_={'survey_kind': 'so2_c1'}, sections=[
  sec('IDENTIFICATION', 'التعريف',
      *ident_full(with_confirm=False, nid_note_ar='يربط بسجل الإتمام تحت RMTH-SO2-C1.2.'),
      PHONE, SEX, AGE,
      fld('Training cycle reference, title and completion date', 'cycle_id', 'record',
          'مرجع دورة التدريب وعنوانها وتاريخ إتمامها', 'التفصيل حسب الدورة.',
          table='rmth_training_cycle', kind={'cycle_kind': 'employability'}, required=True,
          sub='Reference (RMTH-TC-...)', sub_ar='المرجع (RMTH-TC-...)')),
  sec('CONTACT OUTCOME', 'نتيجة التواصل',
      fld('Date of this feedback contact', 'contact_date', 'date', 'تاريخ تواصل التغذية الراجعة هذا', required=True),
      fld('Was the trainee reached?', 'reached_id', 'select', 'هل تم الوصول إلى المتدرب/ة؟',
          'يجب أن يكون لكل متدرب في كشف الإتمام سجل هنا، سواء تم الوصول إليه أم لا. من تم الوصول إليهم فقط يدخلون المقام؛ أبلغ عن معدل الاستجابة إلى جانب النسبة.',
          ref='reached', required=True)),
  sec('HEADLINE QUESTION', 'السؤال الرئيسي',
      fld('Overall, did the training support your employment journey?', 'headline_id', 'select',
          'بشكل عام، هل دعم التدريب مسارك الوظيفي؟',
          'هذا السؤال الوحيد ينتج البسط: الخياران الأولان يُحتسبان. يحدد المقامَ حقلُ نتيجة التواصل أعلاه.',
          ref='so2c1_headline', counting=True)),
  sec('IN WHAT WAY', 'بأي طريقة',
      fld('In what way did the training support you?', 'so2c1_support_way', 'multi', 'بأي طريقة دعمك التدريب؟',
          'اسأل فقط إذا كانت الإجابة الرئيسية نعم. هذا يعطي التفصيل حسب نوع الدعم.',
          question='so2c1_support_way'),
      fld('If the training did NOT support your employment journey, why not?', 'why_not_id', 'select',
          'إذا لم يدعم التدريب مسارك الوظيفي، فلماذا؟',
          'اسأل فقط إذا كانت الإجابة الرئيسية لا. هذا ما يخبر البلدية بما يجب تغييره.',
          ref='so2c1_why_not', other='why_not_other')),
  sec('CLOSING', 'الختام',
      EVIDENCE('so2c1_evidence', 'الأدلة في الملف',
               'كشف الإتمام هو ما يثبّت المقام، لذا يجب حفظه مع سجلات التغذية الراجعة للدورة.'),
      ENUM),
])

# ═══════════════════════════════════════════════════════════════════════════
form('c11', 'SO2-C1.1_Training_cycle', 'RMTH-SO2-C1.1', 'rmth_training_cycle',
     'دورات التدريب المكثفة قصيرة الأمد المطوّرة بالاشتراك',
     'عدد الدورات المستوفية للاختبارين معاً: (أ) قصيرة الأمد ومكثفة وفق التعريف المتفق عليه، و(ب) محتوى مطوَّر بالاشتراك مع منشأة واحدة على الأقل من القطاع الخاص ومؤسسة أكاديمية أو مهنية واحدة على الأقل، مع أدلة موثقة. بند مفتوح: حدّد حدود "قصيرة الأمد ومكثفة" مع البلدية قبل الاستخدام الأول.',
     'جهة تنسيق التدريب في البلدية',
     'عند اكتمال كل دورة؛ يُبلَّغ عنه ربع سنوياً',
     fixed={'cycle_kind': 'employability'}, filter_={'cycle_kind': 'employability'}, sections=[
  sec('CYCLE IDENTIFICATION', 'تعريف الدورة',
      fld('Cycle reference', 'reference', 'readonly', 'مرجع الدورة',
          'يُستخدم هذا المرجع في RMTH-SO2-C1.2 وRMTH-SO2-C1 وRMTH-SO2-0.',
          sub='(RMTH-TC-YYYY-000)', sub_ar='(RMTH-TC-YYYY-000)', derived='reference'),
      fld('Cycle title', 'title', 'text', 'عنوان الدورة', required=True),
      fld('Sector or occupation targeted', 'sector_id', 'select', 'القطاع أو المهنة المستهدفة', 'للتفصيل.',
          ref='c11_sector', other='sector_other'),
      fld('Start and end dates', 'dates', 'parts', 'تاريخا البدء والانتهاء',
          parts=[('start_date', 'date', 'Start', 'البدء', dict(required=True)),
                 ('end_date', 'date', 'End', 'الانتهاء', dict(required=True))]),
      fld('Duration and intensity', 'intensity', 'parts', 'المدة والكثافة',
          'سجّل الأرقام الخام حتى يمكن تطبيق اختبار "قصيرة الأمد ومكثفة" أدناه أياً كانت الحدود المتفق عليها.',
          parts=[('contact_hours', 'number', 'Total contact hours', 'إجمالي ساعات التدريب', dict(step='0.5')),
                 ('weeks', 'number', 'Number of weeks', 'عدد الأسابيع', dict(step='0.5')),
                 ('hours_per_week', 'number', 'Hours per week', 'الساعات في الأسبوع', dict(step='0.5'))]),
      fld('Does the cycle meet the agreed definition of short-term intensive?', 'short_term_intensive', 'readonly',
          'هل تستوفي الدورة التعريف المتفق عليه لـ"قصيرة الأمد ومكثفة"؟',
          'اكتب الحدود المتفق عليها هنا بعد تحديدها مع البلدية، مثلاً "بما لا يزيد على X أسبوعاً وبما لا يقل عن Y ساعة تدريب أسبوعياً"، واشتقّ هذه الإجابة من الأرقام أعلاه.',
          derived='short_term_intensive'),
      fld('Delivery modality and location', 'delivery', 'parts', 'طريقة التقديم والموقع', 'التفصيل حسب الطريقة.',
          parts=[('modality_id', 'select', 'Modality', 'الطريقة', dict(ref='c11_modality')),
                 ('location', 'text', 'Location', 'الموقع', {})])),
  sec('JOINT DEVELOPMENT OF THE CONTENT', 'التطوير المشترك للمحتوى',
      fld('Private sector establishment(s) that took part in developing the content', 'private', 'parts',
          'منشأة/منشآت القطاع الخاص التي شاركت في تطوير المحتوى',
          'يلزم منشأة واحدة على الأقل من القطاع الخاص حتى تُحتسب الدورة.',
          parts=[('private_partner_names', 'text', 'Name(s)', 'الاسم/الأسماء', {}),
                 ('c11_private_contribution', 'multi', 'How they contributed', 'كيف ساهمت', dict(question='c11_private_contribution'))]),
      fld('Academic or vocational institution(s) that took part in developing the content', 'academic', 'parts',
          'المؤسسة/المؤسسات الأكاديمية أو المهنية التي شاركت في تطوير المحتوى',
          'يلزم مؤسسة أكاديمية أو مهنية واحدة على الأقل حتى تُحتسب الدورة.',
          parts=[('academic_partner_names', 'text', 'Name(s)', 'الاسم/الأسماء', {}),
                 ('academic_type_id', 'select', 'Type', 'النوع', dict(ref='c11_academic_type')),
                 ('c11_academic_contribution', 'multi', 'How they contributed', 'كيف ساهمت', dict(question='c11_academic_contribution'))]),
      fld('Evidence of joint development', 'c11_joint_evidence', 'multi', 'أدلة التطوير المشترك',
          'يلزم وثيقة واحدة على الأقل. المشاركة الشفهية وحدها لا تكفي.',
          question='c11_joint_evidence'),
      fld('Joint development criterion met?', 'joint_development_met', 'bool', 'هل استوفي معيار التطوير المشترك؟',
          'هذا الحقل، مع اختبار "قصيرة الأمد ومكثفة"، ينتج عدّ المؤشر.',
          options=[('true', 'Yes - at least one private sector establishment AND one academic or vocational institution, with documentary evidence', 'نعم - منشأة واحدة على الأقل من القطاع الخاص ومؤسسة أكاديمية أو مهنية واحدة، مع أدلة موثقة'),
                   ('false', 'No', 'لا')], counting=True)),
  sec('DELIVERY AND EVIDENCE', 'التنفيذ والأدلة',
      fld('Number of trainees', 'trainees', 'parts', 'عدد المتدربين',
          'يُسجَّل المتمّون فردياً تحت RMTH-SO2-C1.2؛ هذه المجاميع هي للمطابقة.',
          parts=[('enrolled_count', 'number', 'Enrolled', 'الملتحقون', {}),
                 ('completed_count', 'number', 'Completed', 'المتمّون', {}),
                 ('completed_women', 'number', 'Of whom women', 'منهم نساء', {})]),
      EVIDENCE('c11_evidence', 'الأدلة في الملف'),
      COMPLETED_ON),
])

# ═══════════════════════════════════════════════════════════════════════════
form('c12', 'SO2-C1.2_Completion', 'RMTH-SO2-C1.2', 'rmth_training_enrolment',
     'إتمام برامج التدريب المرتبطة بالتشغيل',
     'عدد السجلات التي إجابة "هل استوفى هذا الشخص معايير الإتمام؟" فيها نعم. تعرّف خطة العمل المتمّ بأنه من يكمل التدريب ويُقيَّم جاهزاً للعمل. أبلغ عن الرقمين: إجمالي الإتمامات، والمتمّون الفريدون حسب الرقم الوطني (حقل إزالة التكرار أدناه يعطي الثاني).',
     'المدرب أو جهة تنسيق التدريب في البلدية، في نهاية كل دورة',
     'عند إغلاق كل دورة؛ يُبلَّغ عنه ربع سنوياً',
     filter_={'enrolment_kind': 'employability'}, sections=[
  sec('IDENTIFICATION', 'التعريف',
      *ident_full(confirm_note=True, nid_note_ar='مفتاح إزالة التكرار عبر جميع النماذج.'),
      SEX, AGE, NAT, VUL_PLAIN,
      fld('Phone number', 'phone', 'person_phone', 'رقم الهاتف',
          'مطلوب لمتابعة الإلحاق بعد ثلاثة أشهر تحت RMTH-SO2-0 واستبيان التغذية الراجعة تحت RMTH-SO2-C1.')),
  sec('TRAINING', 'التدريب',
      fld('Training cycle reference and title', 'cycle_id', 'record', 'مرجع دورة التدريب وعنوانها',
          table='rmth_training_cycle', kind={'cycle_kind': 'employability'}, required=True,
          sub='Reference (RMTH-TC-...)', sub_ar='المرجع (RMTH-TC-...)'),
      fld('Type of training', 'c12_training_type_id', 'select', 'نوع التدريب', 'التفصيل حسب نوع التدريب.', ref='c12_training_type'),
      fld('Training start and end dates', 'cycle_dates', 'readonly', 'تاريخا بدء التدريب وانتهائه', derived='cycle_dates')),
  sec('COMPLETION AND JOB-READINESS', 'الإتمام والجاهزية للعمل',
      fld('Attendance rate', 'attendance_pct', 'number', 'نسبة الحضور', sub='Percentage of sessions attended', sub_ar='نسبة الجلسات التي حضرها', unit='%'),
      fld('Pre-test and post-test scores', 'tests', 'parts', 'درجتا الاختبار القبلي والبعدي',
          'تسمّي خطة العمل نتائج الاستبيان القبلي/البعدي دليلاً لهذا المؤشر.',
          parts=[('pre_test', 'number', 'Pre-test out of 100', 'الاختبار القبلي من 100', {}),
                 ('post_test', 'number', 'Post-test out of 100', 'الاختبار البعدي من 100', {})]),
      fld('Final assessment result', 'assessment_result_id', 'select', 'نتيجة التقييم النهائي', ref='assessment_result'),
      fld('Assessed as job-ready by the trainer?', 'job_ready', 'bool', 'هل قيّمه المدرب جاهزاً للعمل؟',
          'تعرّف خطة العمل المتمّ بأنه من يكمل ويُقيَّم جاهزاً للعمل. لا يوجد خيار "جزئياً" عمداً، لأن الإجابة الوسطى لا يمكن احتسابها.',
          options=[('true', 'Yes', 'نعم'), ('false', 'No', 'لا')]),
      fld('For on-the-job trainees: employer evaluation received?', 'employer_eval', 'parts',
          'للمتدربين أثناء العمل: هل استُلم تقييم صاحب العمل؟',
          'تسمّي خطة العمل تقييمات أصحاب العمل طريقةً لجمع البيانات. لا يستطيع المدرب تقييم المتدرب أثناء العمل؛ صاحب العمل المضيف هو من يفعل.',
          parts=[('employer_evaluation_id', 'select', '', '', dict(ref='c12_employer_evaluation')),
                 ('employer_evaluation_note', 'text', 'date and assessor', 'التاريخ والمقيّم', {})]),
      fld('Did this person meet the completion criteria?', 'met_criteria', 'bool', 'هل استوفى هذا الشخص معايير الإتمام؟',
          'هذا الحقل ينتج عدّ المؤشر. اكتب القاعدة المتفق عليها هنا قبل الاستخدام الأول، مثلاً "نعم فقط إذا كان الحضور 75% على الأقل والتقييم النهائي ناجح والجاهزية للعمل نعم". بند مفتوح: أكّد القاعدة مع البلدية.',
          options=[('true', 'Yes', 'نعم'), ('false', 'No', 'لا')], counting=True, rule='c12_completion_rule'),
      fld('Certificate issued?', 'certificate', 'parts', 'هل صدرت الشهادة؟',
          parts=[('certificate_issued', 'bool', '', '', dict(options=[('true', 'Yes', 'نعم'), ('false', 'No', 'لا')])),
                 ('certificate_number', 'text', 'certificate number', 'رقم الشهادة', {})]),
      fld('Has this National ID already completed a cycle counted under this indicator?', 'counted_under_id', 'readonly',
          'هل سبق لهذا الرقم الوطني إتمام دورة محتسبة تحت هذا المؤشر؟',
          'يتيح للبلدية الإبلاغ عن المتمّين الفريدين إلى جانب إجمالي الإتمامات، ويغذّي عدّ الأثر بعد إزالة التكرار.',
          derived='counted_under')),
  sec('EVIDENCE', 'الأدلة',
      EVIDENCE('c12_evidence', 'الأدلة في الملف'),
      fld('Trainer name', 'trainer_name', 'text', 'اسم المدرب/ة')),
])

# ═══════════════════════════════════════════════════════════════════════════
form('so30', 'SO3-0_Regular_income', 'RMTH-SO3-0', 'rmth_outcome_survey',
     'الدخل المنتظم نتيجة برامج ريادة الأعمال',
     'عدد الأشخاص الفريدين (حسب الرقم الوطني) الذين تأكد كسبهم دخلاً من مشروع مدعوم في أربعة أشهر على الأقل من الأشهر الستة الأخيرة. يُحتسب مرة واحدة لكل شخص. بند مفتوح: أكّد قاعدة أربعة من ستة أشهر مع البلدية.',
     'جهة تنسيق الرصد والتقييم في البلدية، عبر الهاتف أو زيارة ميدانية',
     'سنوياً، وفي كل جولة متابعة بعد الدعم',
     fixed={'survey_kind': 'so3_0'}, filter_={'survey_kind': 'so3_0'}, sections=[
  sec('IDENTIFICATION', 'التعريف',
      *ident_full(nid_note_ar='مفتاح إزالة التكرار.'),
      PHONE, SEX, AGE, NAT, VUL_PLAIN),
  sec('SUPPORT RECEIVED', 'الدعم المتلقى',
      fld('Which entrepreneurship support did this person receive?', 'so30_support', 'multi',
          'ما دعم ريادة الأعمال الذي تلقاه هذا الشخص؟',
          'التفصيل حسب نوع الدعم. التدريب على تصميم الحاضنات غير مدرج هنا: فهو يؤهل الموظفين لإدارة الحاضنات ولا يجعل المشاركين فيه روّاد أعمال.',
          question='so30_support'),
      fld('Reference of that support', 'support_refs', 'parts', 'مرجع ذلك الدعم',
          'المشاريع المحتضنة تحمل بالفعل رقم RMTH-EN من RMTH-SO3-E0.2. للمشروع المنزلي، أو المشروع الصغير المدعوم، أو المتدرب الذي لم يدخل حاضنة قط، أصدر رقم RMTH-EN هنا، مرة واحدة لكل مشروع.',
          parts=[('incubator_id', 'record', 'Incubator ID (RMTH-IN-...)', 'معرّف الحاضنة (RMTH-IN-...)', dict(table='rmth_incubator')),
                 ('enterprise_id', 'record', 'Enterprise ID (RMTH-EN-...)', 'معرّف المشروع (RMTH-EN-...)', dict(table='rmth_enterprise', create=True)),
                 ('programme_id', 'record', 'Entrepreneurship programme reference (RMTH-EP-...)', 'مرجع برنامج ريادة الأعمال (RMTH-EP-...)', dict(table='rmth_training_programme', kind={'programme_type': 'entrepreneurship'}))]),
      fld('Enterprise or activity name and sector', 'enterprise', 'parts', 'اسم المشروع أو النشاط وقطاعه', 'التفصيل حسب القطاع.',
          parts=[('enterprise_name', 'text', 'Name', 'الاسم', {}),
                 ('so30_sector_id', 'select', 'Sector', 'القطاع', dict(ref='so30_sector', other='so30_sector_other'))]),
      fld('Role of this person in the activity', 'role_id', 'select', 'دور هذا الشخص في النشاط', ref='so30_role'),
      fld('Month and year the activity started earning', 'earning_since_month', 'month', 'شهر وسنة بدء النشاط في تحقيق الدخل')),
  sec('REGULARITY OF INCOME', 'انتظام الدخل',
      fld('In how many of the last six months did you earn income from this activity?', 'months_of_six', 'number',
          'في كم شهراً من الأشهر الستة الأخيرة كسبت دخلاً من هذا النشاط؟',
          'هذا ما يجعل الدخل "منتظماً". سجّل الرقم لا الفئة.',
          sub='Number of months out of six', sub_ar='عدد الأشهر من ستة', required=True, max=6),
      fld('Regular income criterion met?', 'so30_criterion_id', 'select', 'هل استوفي معيار الدخل المنتظم؟',
          'هذا الحقل ينتج عدّ المؤشر. يجب أن يتبع من الرقم أعلاه.',
          ref='so30_criterion', required=True, counting=True),
      fld('Compared with before the support, is your income from this activity higher or lower?', 'income_change_id', 'select',
          'مقارنة بما قبل الدعم، هل دخلك من هذا النشاط أعلى أم أقل؟',
          'اختياري - للتعلّم وإدارة البرنامج. ليس جزءاً من عدّ المؤشر.', ref='so30_income_change'),
      fld('If income has stopped, when and why?', 'stopped', 'parts', 'إذا توقف الدخل، فمتى ولماذا؟',
          'اختياري - للتعلّم وإدارة البرنامج. ليس جزءاً من عدّ المؤشر.',
          parts=[('income_stopped_month', 'month', 'Month and year', 'الشهر والسنة', {}),
                 ('so30_stop_reason_id', 'select', 'Reason', 'السبب', dict(ref='so30_stop_reason', other='so30_stop_reason_other'))])),
  sec('VERIFICATION', 'التحقق',
      fld('How was the income verified, and what is on file?', 'so30_verification', 'multi',
          'كيف تم التحقق من الدخل، وما الموجود في الملف؟',
          'اسعَ إلى مصدر واحد على الأقل غير الإفادة الذاتية حيثما أمكن.', question='so30_verification'),
      fld('Has this National ID already been counted for this indicator?', 'counted_under_id', 'readonly',
          'هل سبق احتساب هذا الرقم الوطني لهذا المؤشر؟', 'يُحتسب مرة واحدة لكل شخص.', derived='counted_under'),
      fld('Enumerator name and date', 'enumerator', 'parts', 'اسم الباحث/ة والتاريخ',
          parts=[('enumerator_name', 'text', 'Name', 'الاسم', {}), ('contact_date', 'date', 'Date', 'التاريخ', {})])),
])

# ═══════════════════════════════════════════════════════════════════════════
form('e01', 'SO3-E0.1_Incubator_setup', 'RMTH-SO3-E0.1', 'rmth_incubator',
     'إنشاء حاضنات الأعمال المتخصصة',
     'عدد الحاضنات التي (أ) متخصصة في مجال عالي الأثر و(ب) تأكد إنشاؤها وتشغيلها وفق المعايير 1 إلى 5 أدناه. وفق تعريف خطة العمل، يُتتبع قبول الدفعة الأولى لكنه ليس شرطاً لاحتساب الحاضنة منشأة.',
     'جهة التنسيق البلدية للتنمية الاقتصادية',
     'في كل مرحلة من مراحل الإنشاء؛ يُبلَّغ عنه ربع سنوياً',
     sections=[
  sec('INCUBATOR IDENTIFICATION', 'تعريف الحاضنة',
      fld('Incubator ID', 'reference', 'readonly', 'معرّف الحاضنة', sub='(RMTH-IN-YYYY-000)', sub_ar='(RMTH-IN-YYYY-000)', derived='reference'),
      fld('Incubator name', 'name', 'text', 'اسم الحاضنة', required=True),
      fld('Specialisation field', 'field_id', 'select', 'مجال التخصص',
          'الحاضنة العامة دون تخصص لا تُحتسب لهذا المؤشر.', ref='e01_field', other='field_other'),
      fld('Host arrangement', 'host_id', 'select', 'ترتيب الاستضافة', 'للتفصيل.', ref='e01_host'),
      fld('Partner institutions and their role', 'partners', 'parts', 'المؤسسات الشريكة ودورها',
          'يحدد المؤشر التعاون مع الجامعات والقطاع الخاص. التفصيل حسب نوع الشريك.',
          parts=[('partner_university', 'text', 'University or academic institution', 'الجامعة أو المؤسسة الأكاديمية', {}),
                 ('partner_private', 'text', 'Private sector partner(s)', 'شريك/شركاء القطاع الخاص', {}),
                 ('e01_partner_role', 'multi', 'Role', 'الدور', dict(question='e01_partner_role'))])),
  sec('ESTABLISHMENT CHECKLIST (CRITERIA 1 TO 5 DECIDE THE COUNT)', 'قائمة التحقق من الإنشاء (المعايير 1 إلى 5 تقرر العدّ)',
      fld('1. Physical or virtual space identified and prepared', 'c1', 'parts', '1. مساحة فعلية أو افتراضية محددة ومجهزة',
          parts=[('c1_id', 'select', '', '', dict(ref='e01_c1')),
                 ('c1_location', 'text', 'Location', 'الموقع', {}),
                 ('c1_date', 'date', 'Date', 'التاريخ', {})]),
      fld('2. Governance arrangement approved', 'c2', 'parts', '2. ترتيب الحوكمة معتمد',
          parts=[('c2_id', 'select', '', '', dict(ref='e01_c2')),
                 ('c2_reference', 'text', 'Decision reference', 'مرجع القرار', {}),
                 ('c2_date', 'date', 'Date', 'التاريخ', {})]),
      fld('3. Operational plan and service catalogue in place', 'c3', 'parts', '3. خطة تشغيلية ودليل خدمات جاهزان',
          parts=[('c3_id', 'select', '', '', dict(ref='e01_c3')),
                 ('c3_date', 'date', 'Date', 'التاريخ', {})]),
      fld('4. Staff or focal point assigned', 'c4', 'parts', '4. موظفون أو جهة تنسيق معيّنون',
          parts=[('c4_id', 'select', '', '', dict(ref='e01_c4')),
                 ('c4_staff_count', 'number', 'Number of staff', 'عدد الموظفين', {})]),
      fld('5. Core incubation services launched', 'services_live', 'services', '5. خدمات الاحتضان الأساسية أُطلقت',
          'تتطلب خطة العمل بدء خدمات الاحتضان الأساسية. خدمتان فعّالتان هما الحد، لذا يمكن قراءة المعيار 5 مباشرة بدلاً من تقديره.',
          services='e01_service', sub='Services live (select all, with the date each began)', sub_ar='الخدمات الفعّالة (اختر الجميع، مع تاريخ بدء كل منها)',
          criterion='Criterion 5: two or more services live - met; one service live - not met; no service live - not met',
          criterion_ar='المعيار 5: خدمتان أو أكثر فعّالتان - مستوفى؛ خدمة واحدة فعّالة - غير مستوفى؛ لا خدمة فعّالة - غير مستوفى')),
  sec('STATUS AND EVIDENCE', 'الحالة والأدلة',
      fld('Is the incubator established and operational?', 'established_id', 'select', 'هل الحاضنة منشأة وتعمل؟',
          'هذا الحقل ينتج عدّ المؤشر. "تحقق" فقط هو الذي يُحتسب.',
          ref='e01_status', other='established_other', counting=True),
      fld('Date achieved', 'achieved_on', 'date', 'تاريخ التحقق'),
      fld('First cohort admitted', 'cohort', 'parts', 'قُبلت الدفعة الأولى',
          'يُتتبع لإدارة البرنامج وللربط بـ RMTH-SO3-E0.2. ليس شرطاً للعدّ.',
          parts=[('first_cohort_admitted', 'bool', '', '', dict(options=[('true', 'Yes', 'نعم'), ('false', 'Not yet', 'ليس بعد')])),
                 ('first_cohort_count', 'number', 'Number of enterprises', 'عدد المشاريع', {}),
                 ('first_cohort_date', 'date', 'Date', 'التاريخ', {})]),
      EVIDENCE('e01_evidence', 'الأدلة في الملف', 'تسمّي خطة العمل الصور وتقرير المشروع أدلةً للحاضنة.'),
      COMPLETED_ON),
])

# ═══════════════════════════════════════════════════════════════════════════
form('e02', 'SO3-E0.2_Incubation_service', 'RMTH-SO3-E0.2', 'rmth_incubation_service',
     'المشاركون المتلقون لخدمات الاحتضان',
     'عدد المشاركين الفريدين (حسب الرقم الوطني) الذين تلقوا خدمة احتضان واحدة على الأقل. يُحتسب كل مشارك مرة واحدة مهما كان عدد الخدمات التي يتلقاها.',
     'جهة تنسيق الحاضنة، من سجل الخدمات',
     'عند القبول ويُحدَّث عند كل خدمة؛ يُبلَّغ عنه ربع سنوياً',
     sections=[
  sec('IDENTIFICATION', 'التعريف',
      *ident_full(nid_note_ar='مفتاح إزالة التكرار.'),
      SEX, AGE, NAT, VUL_PLAIN,
      fld('Phone number', 'phone', 'person_phone', 'رقم الهاتف', 'مطلوب لمتابعة الدخل المنتظم تحت RMTH-SO3-0.')),
  sec('ENTERPRISE AND ADMISSION', 'المشروع والقبول',
      fld('Incubator ID and name', 'incubator_id', 'record', 'معرّف الحاضنة واسمها', 'يربط بسجل الحاضنة تحت RMTH-SO3-E0.1.',
          table='rmth_incubator', required=True, sub='ID (RMTH-IN-...)', sub_ar='المعرّف (RMTH-IN-...)'),
      fld('Enterprise ID', 'enterprise_id', 'record', 'معرّف المشروع',
          'معرّف واحد لكل مشروع لا لكل شخص: عند قبول شريكين مؤسسين، يصدر السجل الأول المعرّف ويعيد الثاني استخدامه. المشروع الذي لا يدخل حاضنة قط يُعطى رقم RMTH-EN في نموذج RMTH-SO3-0 بدلاً من ذلك.',
          table='rmth_enterprise', create=True, sub='(RMTH-EN-YYYY-000)', sub_ar='(RMTH-EN-YYYY-000)'),
      fld('Enterprise or business idea name', 'enterprise_name', 'readonly', 'اسم المشروع أو فكرة العمل', derived='enterprise_name'),
      fld('Date of admission or first service', 'admitted_on', 'date', 'تاريخ القبول أو أول خدمة',
          'هذا التاريخ يضع المشارك في ربع سنة الإبلاغ.', required=True),
      fld('Stage of the enterprise at admission', 'stage_id', 'select', 'مرحلة المشروع عند القبول', 'للتفصيل.', ref='e02_stage'),
      fld('Sector', 'sector_id', 'select', 'القطاع', 'للتفصيل.', ref='e02_sector', other='sector_other')),
  sec('SERVICES RECEIVED', 'الخدمات المتلقاة',
      fld('Which incubation services has this participant received?', 'e02_service', 'multi',
          'ما خدمات الاحتضان التي تلقاها هذا المشارك؟',
          'يجب تسجيل خدمة واحدة على الأقل حتى يُحتسب المشارك. التفصيل حسب نوع الخدمة.',
          question='e02_service', required=True, counting=True),
      fld("Is this the participant's first time receiving incubation services from the Municipality?", 'counted_under_id', 'readonly',
          'هل هذه المرة الأولى التي يتلقى فيها المشارك خدمات احتضان من البلدية؟',
          'هذا الحقل يزيل التكرار من العدّ.', derived='counted_under'),
      fld('Current status in the incubator', 'status_id', 'select', 'الحالة الحالية في الحاضنة',
          'اختياري - للتعلّم وإدارة البرنامج. ليس جزءاً من عدّ المؤشر.', ref='e02_status')),
  sec('EVIDENCE', 'الأدلة',
      EVIDENCE('e02_evidence', 'الأدلة في الملف'),
      fld('Incubator focal point and date', 'focal', 'parts', 'جهة تنسيق الحاضنة والتاريخ',
          parts=[('focal_point_name', 'text', 'Name', 'الاسم', {}), ('completed_on', 'date', 'Date', 'التاريخ', {})])),
])

# ═══════════════════════════════════════════════════════════════════════════
form('e03', 'SO3-E0.3_Incub_design_train', 'RMTH-SO3-E0.3', 'rmth_training_enrolment',
     'المشاركون المدرَّبون على تصميم الحاضنات',
     'عدد السجلات التي إجابة "هل استوفى هذا الشخص معايير الإتمام؟" فيها نعم. أبلغ عن إجمالي الإتمامات والمشاركين الفريدين حسب الرقم الوطني معاً.',
     'المدرب أو جهة تنسيق التدريب في البلدية',
     'عند إغلاق كل دورة؛ يُبلَّغ عنه ربع سنوياً',
     filter_={'enrolment_kind': 'incubator_design'}, sections=[
  sec('IDENTIFICATION', 'التعريف',
      *ident_full(with_confirm=False, nid_note_ar='مفتاح إزالة التكرار.'),
      SEX, AGE, PHONE,
      fld('Organisation and role', 'organisation', 'parts', 'المنظمة والدور',
          'البعد الأساسي لهذا المؤشر: من الذي يُؤهَّل لتصميم الحاضنات وإدارتها. التفصيل حسب نوع المنظمة والدور.',
          parts=[('organisation_name', 'text', 'Organisation', 'المنظمة', {}),
                 ('org_type_id', 'select', 'Type', 'النوع', dict(ref='e03_org_type')),
                 ('org_role', 'text', 'Role', 'الدور', {})])),
  sec('TRAINING CYCLE', 'دورة التدريب',
      fld('Training cycle reference and title', 'cycle_id', 'record', 'مرجع دورة التدريب وعنوانها',
          'RMTH-ID هي البادئة لدورات تصميم الحاضنات، تمييزاً لها عن دورات التشغيل RMTH-TC وبرامج ريادة الأعمال RMTH-EP.',
          table='rmth_training_cycle', kind={'cycle_kind': 'incubator_design'}, required=True,
          sub='Reference (RMTH-ID-YYYY-000)', sub_ar='المرجع (RMTH-ID-YYYY-000)'),
      fld('Dates and total hours', 'cycle_dates', 'readonly', 'التواريخ وإجمالي الساعات', derived='cycle_dates_hours'),
      fld('Delivered by', 'delivered_by', 'readonly', 'مقدَّمة من', derived='cycle_delivered_by'),
      fld('Modules covered', 'modules', 'readonly', 'الوحدات المغطاة',
          'هذا هو اختبار المحتوى للمؤشر، لا إضافة اختيارية: يجب تسجيل وحدة تصميم واحدة على الأقل، وإلا فالدورة ليست تدريباً على تصميم الحاضنات ولا يُحتسب المشارك.',
          derived='cycle_modules')),
  sec('COMPLETION', 'الإتمام',
      fld('Attendance rate', 'attendance_pct', 'number', 'نسبة الحضور', sub='Percentage of sessions attended', sub_ar='نسبة الجلسات التي حضرها', unit='%'),
      fld('Pre-test and post-test knowledge scores', 'tests', 'parts', 'درجتا اختبار المعرفة القبلي والبعدي',
          parts=[('pre_test', 'number', 'Pre-test out of 100', 'الاختبار القبلي من 100', {}),
                 ('post_test', 'number', 'Post-test out of 100', 'الاختبار البعدي من 100', {})]),
      fld('Did this person meet the completion criteria?', 'met_criteria', 'bool', 'هل استوفى هذا الشخص معايير الإتمام؟',
          'هذا الحقل ينتج عدّ المؤشر. يجب أن تتضمن القاعدة اختبار المحتوى: وحدة واحدة على الأقل من وحدات تصميم الحاضنات مسجلة أعلاه. اكتب القاعدة الكاملة المتفق عليها هنا قبل الاستخدام الأول، مثلاً "حضور 75% على الأقل، واختبار بعدي 60 على الأقل، وتغطية وحدة تصميم واحدة على الأقل".',
          options=[('true', 'Yes', 'نعم'), ('false', 'No', 'لا')], counting=True, rule='e03_completion_rule'),
      fld('Certificate issued?', 'certificate', 'parts', 'هل صدرت الشهادة؟',
          parts=[('certificate_issued', 'bool', '', '', dict(options=[('true', 'Yes', 'نعم'), ('false', 'No', 'لا')])),
                 ('certificate_number', 'text', 'certificate number', 'رقم الشهادة', {})]),
      fld('Has this National ID already been counted for this indicator?', 'counted_under_id', 'readonly',
          'هل سبق احتساب هذا الرقم الوطني لهذا المؤشر؟',
          'يتيح للبلدية الإبلاغ عن المشاركين الفريدين إلى جانب إجمالي الإتمامات.', derived='counted_under')),
  sec('EVIDENCE', 'الأدلة',
      EVIDENCE('e03_evidence', 'الأدلة في الملف'),
      fld('Trainer name and date', 'trainer', 'parts', 'اسم المدرب/ة والتاريخ',
          parts=[('trainer_name', 'text', 'Name', 'الاسم', {}), ('completed_on', 'date', 'Date', 'التاريخ', {})])),
])

# ═══════════════════════════════════════════════════════════════════════════
form('f01', 'SO3-F0.1_Entrep_completion', 'RMTH-SO3-F0.1', 'rmth_training_enrolment',
     'المشاركون المدرَّبون في ريادة الأعمال',
     'عدد السجلات التي إجابة "هل أتم هذا الشخص التدريب بنجاح؟" فيها نعم. تعرّفهم خطة العمل بأنهم المشاركون الذين أتموا بنجاح تدريباً في ممارسات الإنتاج ومعايير الجودة ومهارات الإدارة الأساسية ذات الصلة بنوع مشروعهم. أبلغ عن إجمالي الإتمامات والمشاركين الفريدين حسب الرقم الوطني معاً.',
     'المدرب أو جهة تنسيق التدريب في البلدية، في نهاية كل برنامج',
     'عند إغلاق كل برنامج؛ يُبلَّغ عنه ربع سنوياً',
     filter_={'enrolment_kind': 'entrepreneurship'}, sections=[
  sec('IDENTIFICATION', 'التعريف',
      *ident_full(nid_note_ar='مفتاح إزالة التكرار.'),
      SEX, AGE, NAT, VUL_PLAIN,
      fld('Phone number', 'phone', 'person_phone', 'رقم الهاتف', 'مطلوب لمتابعة الدخل المنتظم تحت RMTH-SO3-0.')),
  sec('PROGRAMME AND ENTERPRISE', 'البرنامج والمشروع',
      fld('Programme reference and title', 'cycle_id', 'record', 'مرجع البرنامج وعنوانه',
          'يربط بسجل البرنامج تحت RMTH-SO3-F0.2.',
          table='rmth_training_cycle', kind={'cycle_kind': 'entrepreneurship'}, required=True,
          sub='Reference (RMTH-EP-...)', sub_ar='المرجع (RMTH-EP-...)'),
      fld('Type of training', 'f01_training_type_id', 'select', 'نوع التدريب',
          'التفصيل حسب نوع التدريب، كما تتطلب خطة العمل.', ref='f01_training_type'),
      fld('Training start and end dates', 'cycle_dates', 'readonly', 'تاريخا بدء التدريب وانتهائه', derived='cycle_dates'),
      fld('Enterprise status at the start of the training', 'enterprise_status_id', 'select',
          'حالة المشروع عند بدء التدريب', 'للتفصيل.', ref='f01_enterprise_status'),
      fld('Enterprise type or sector', 'enterprise_sector_id', 'select', 'نوع المشروع أو قطاعه',
          'تتطلب خطة العمل أن يكون المحتوى ذا صلة بنوع مشروع المشارك.',
          ref='f01_sector', other='enterprise_sector_other')),
  sec('MODULES AND COMPLETION', 'الوحدات والإتمام',
      fld('Modules completed', 'f01_module', 'multi', 'الوحدات المكتملة',
          'ممارسات الإنتاج ومعايير الجودة والإدارة الأساسية هي الثلاث التي تسميها خطة العمل صراحة.',
          question='f01_module'),
      fld('Attendance rate', 'attendance_pct', 'number', 'نسبة الحضور', sub='Percentage of sessions attended', sub_ar='نسبة الجلسات التي حضرها', unit='%'),
      fld('Final assessment result', 'assessment_result_id', 'select', 'نتيجة التقييم النهائي', ref='assessment_result'),
      fld('Did this person successfully complete the training?', 'met_criteria', 'bool', 'هل أتم هذا الشخص التدريب بنجاح؟',
          'هذا الحقل ينتج عدّ المؤشر. يجب أن تتضمن القاعدة اختبار المحتوى من خطة العمل: يجب أن تظهر واحدة على الأقل من ممارسات الإنتاج أو معايير الجودة أو إدارة الأعمال في الوحدات المكتملة أعلاه. اكتب القاعدة الكاملة المتفق عليها هنا قبل الاستخدام الأول، مثلاً "حضور 75% على الأقل، وتقييم نهائي ناجح، وإتمام مجال واحد على الأقل من المجالات الثلاثة المذكورة".',
          options=[('true', 'Yes', 'نعم'), ('false', 'No', 'لا')], counting=True, rule='f01_completion_rule'),
      fld('Certificate issued?', 'certificate', 'parts', 'هل صدرت الشهادة؟',
          parts=[('certificate_issued', 'bool', '', '', dict(options=[('true', 'Yes', 'نعم'), ('false', 'No', 'لا')])),
                 ('certificate_number', 'text', 'certificate number', 'رقم الشهادة', {})]),
      fld('Has this National ID already been counted for this indicator?', 'counted_under_id', 'readonly',
          'هل سبق احتساب هذا الرقم الوطني لهذا المؤشر؟',
          'يتيح للبلدية الإبلاغ عن المشاركين الفريدين إلى جانب إجمالي الإتمامات.', derived='counted_under')),
  sec('EVIDENCE', 'الأدلة',
      EVIDENCE('f01_evidence', 'الأدلة في الملف', 'تسمّي خطة العمل كشوف الحضور وشهادات الإتمام أدلةً.'),
      fld('Trainer name', 'trainer_name', 'text', 'اسم المدرب/ة')),
])

# ═══════════════════════════════════════════════════════════════════════════
form('f02', 'SO3-F0.2_Entrep_programme', 'RMTH-SO3-F0.2', 'rmth_training_programme',
     'برامج التدريب المطوّرة في ريادة الأعمال',
     'عدد البرامج التي إجابة "هل اكتمل تطوير البرنامج؟" فيها نعم. يُحتسب كل برنامج مرة واحدة. بند مفتوح: تعرّف خطة العمل المؤشر المقابل بعدد جلسات التدريب المنفذة، كل واحدة مرة بغض النظر عن عدد المشاركين. يسجّل سجل التنفيذ أدناه كل دورة حتى يمكن الإبلاغ عن الرقم بأي من الطريقتين بعد اتفاق إينابل والبلدية على القراءة الحاكمة.',
     'جهة تنسيق التدريب في البلدية، مع الشريك الذي طوّر المحتوى',
     'عند اكتمال تطوير البرنامج، ويُحدَّث عند كل تنفيذ؛ يُبلَّغ عنه ربع سنوياً',
     fixed={'programme_type': 'entrepreneurship'}, filter_={'programme_type': 'entrepreneurship'}, sections=[
  sec('PROGRAMME IDENTIFICATION', 'تعريف البرنامج',
      fld('Programme reference', 'reference', 'readonly', 'مرجع البرنامج',
          'يُستخدم هذا المرجع في RMTH-SO3-F0.1 وRMTH-SO3-0.',
          sub='(RMTH-EP-YYYY-000)', sub_ar='(RMTH-EP-YYYY-000)', derived='reference'),
      fld('Programme title', 'title', 'text', 'عنوان البرنامج', required=True),
      fld('Target group and level', 'target', 'parts', 'الفئة المستهدفة والمستوى', 'للتفصيل.',
          parts=[('level_id', 'select', 'Level', 'المستوى', dict(ref='f02_level')),
                 ('group_id', 'select', 'Group', 'الفئة', dict(ref='f02_group'))]),
      fld('Sector focus', 'sector_focus_id', 'select', 'التركيز القطاعي', 'للتفصيل.', ref='f02_sector', other='sector_focus_other')),
  sec('DEVELOPMENT', 'التطوير',
      fld('Developed by', 'developed_by_id', 'select', 'طُوِّر بواسطة', ref='f02_developed_by'),
      fld('Partner name and type', 'partner', 'parts', 'اسم الشريك ونوعه', 'التفصيل حسب نوع الشريك.',
          parts=[('partner_names', 'text', 'Name', 'الاسم', {}),
                 ('partner_type_id', 'select', 'Type', 'النوع', dict(ref='f02_partner_type'))]),
      fld('What was the content based on?', 'f02_content_basis', 'multi', 'على ماذا بُني المحتوى؟', question='f02_content_basis'),
      fld('Reference of the needs assessment or source document', 'source_document', 'text',
          'مرجع تقييم الاحتياجات أو الوثيقة المصدر',
          'الدليل على أن البرنامج طُوِّر فعلاً لا أُعيدت تسميته فقط.',
          sub='(document title and date)', sub_ar='(عنوان الوثيقة وتاريخها)')),
  sec('CONTENT AND READINESS', 'المحتوى والجاهزية',
      fld('Modules included', 'f02_module', 'multi', 'الوحدات المتضمنة',
          'ينبغي أن تطابق الوحدات المسجلة كمكتملة تحت RMTH-SO3-F0.1.', question='f02_module'),
      fld('Total hours, sessions and modality', 'hours', 'parts', 'إجمالي الساعات والجلسات والطريقة',
          parts=[('total_hours', 'number', 'Total hours', 'إجمالي الساعات', dict(step='0.5')),
                 ('sessions_count', 'number', 'Number of sessions', 'عدد الجلسات', {}),
                 ('f02_modality_id', 'select', 'Modality', 'الطريقة', dict(ref='modality_ipob'))]),
      fld('Which materials have been produced?', 'f02_material', 'multi', 'ما المواد التي أُنتجت؟',
          'يُعدّ البرنامج مطوَّراً عند وجود المنهاج ودليل المدرب على الأقل.', question='f02_material'),
      fld('Programme development complete?', 'development_complete_id', 'select', 'هل اكتمل تطوير البرنامج؟',
          'هذا الحقل ينتج عدّ المؤشر وفق قراءة البرامج.', ref='f02_complete', counting=True)),
  sec('DELIVERY LOG', 'سجل التنفيذ',
      fld('Every delivery of this programme', 'deliveries', 'deliveries', 'كل تنفيذ لهذا البرنامج',
          'أضف صفاً في كل مرة يُنفَّذ فيها البرنامج. هذا السجل هو ما يتيح الإبلاغ عن المؤشر كجلسات منفذة، وفق تعريف خطة العمل، إلى جانب البرامج المطوّرة.',
          sub='One row per cycle delivered', sub_ar='صف لكل دورة منفذة'),
      fld('Total deliveries to date', 'deliveries_total', 'readonly', 'إجمالي مرات التنفيذ حتى تاريخه',
          'الرقم الذي يُبلَّغ عنه إذا كانت قراءة خطة العمل القائمة على الجلسات هي الحاكمة.', derived='deliveries_total')),
  sec('EVIDENCE', 'الأدلة',
      EVIDENCE('f02_evidence', 'الأدلة في الملف', 'تسمّي خطة العمل المواد التدريبية دليلاً لهذا المؤشر.'),
      COMPLETED_ON),
])

if __name__ == '__main__':
    n = sum(len(s['fields']) for f in FORMS.values() for s in f['sections'])
    print(len(FORMS), 'forms,', n, 'fields')
