# -*- coding: utf-8 -*-
"""
Writes 0176, Ramtha's option lists for the seven forms of
RMTH_Forms_and_Calculations_v2.xlsx, from model.build().

Run from the repository root:  python supabase/ramtha/gen_lists.py

Before the migration is applied it writes PENDING_0176_...; once the file has
been renamed to its ledger version it REFUSES to change it and only reports
whether the catalogue still reproduces it byte for byte. Writes LF only
(newline=''), per CLAUDE.md rule 5.
"""
import glob, io, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import model  # noqa: E402

MIGRATIONS = os.path.normpath(os.path.join(HERE, '..', 'migrations'))
NAME = '0176_ramtha_forms_option_lists.sql'


def q(s):
    return "'" + s.replace("'", "''") + "'"


def render(m):
    lists = m['lists']
    n_lists = len(lists)
    n_opts = sum(len(v['options']) for v in lists.values())
    n_free = sum(1 for v in lists.values() for o in v['options'] if o[3])
    out = []
    out.append("""-- ═══════════════════════════════════════════════════════════════════════════
--  0176 — Ramtha's option lists for the seven forms of
--         RMTH_Forms_and_Calculations_v2.xlsx
--
--  GENERATED by supabase/ramtha/gen_lists.py from workbook.py (the one
--  reading of the workbook) and catalogue.py. Do not edit; edit the
--  catalogue and regenerate.
--
--  One ref_rmth_* table per response list of the "Forms Needed" sheet, %(n_lists)d
--  lists and %(n_opts)d options. Both labels are the sheet's own cells, VERBATIM:
--  this workbook, unlike the first one (0122), gives every option in
--  Arabic as well, so nothing here is drafted. The code beside each option
--  is the catalogue's; the generator checks the catalogue's English against
--  the cell before writing either.
--
--  Two sheets' fields share a list only where their options are identical,
--  option for option, in both languages: PJ-03 and AC-06 (sector) are one
--  table. "Yes - No" questions are boolean columns, not lists.
--
--  ── WHAT THE SHEET LEAVES OPEN ──
--
--  A bare "Other" (nationality, sector, training topic) takes a
--  specification -- %(n_free)d options allow free text, the convention of OQ-53:
--  an "Other" that cannot say what it was is a figure nobody can
--  disaggregate. "Other stakeholder" names a category and takes none.
--  "None" in AC-08 and FU-03 is exclusive (the sheet's Validation column);
--  save_rmth_record refuses it beside another tick (0178).
--
--  Like every other ref_ table: RLS on, read by every signed-in role,
--  written by a coordinator, the standard triggers, no hard delete.
-- ═══════════════════════════════════════════════════════════════════════════

do $outer$
declare t text;
begin
  foreach t in array array[
""" % dict(n_lists=n_lists, n_opts=n_opts, n_free=n_free))
    out.append(",\n".join("    " + q('ref_rmth_' + k) for k in lists))
    out.append("""
  ] loop
    execute format($f$
      create table public.%I (
        id               uuid primary key default gen_random_uuid(),
        code             text not null unique,
        label_en         text not null,
        label_ar         text not null,
        sort_order       int  not null default 0,
        is_active        boolean not null default true,
        allows_free_text boolean not null default false,
        created_at       timestamptz not null default now(),
        updated_at       timestamptz not null default now(),
        created_by       uuid references auth.users(id),
        deleted_at       timestamptz
      )$f$, t);

    perform public.attach_standard_triggers(t);

    execute format('alter table public.%I enable row level security', t);
    execute format($f$create policy ref_read on public.%I
      for select to authenticated using (true)$f$, t);
    execute format($f$create policy ref_write on public.%I
      for all to authenticated
      using (public.is_coordinator())
      with check (public.is_coordinator())$f$, t);
  end loop;
end $outer$;

""")
    for key, v in lists.items():
        tbl = 'ref_rmth_' + key
        out.append("-- ── %s (%s) ──\n" % (tbl, ', '.join(v['used_by'])))
        out.append("insert into public.%s (code, label_en, label_ar, sort_order, allows_free_text) values\n" % tbl)
        rows = []
        for i, (code, en, ar, free) in enumerate(v['options'], 1):
            rows.append("  (%s, %s, %s, %d, %s)" % (q(code), q(en), q(ar), i, 'true' if free else 'false'))
        out.append(",\n".join(rows) + ";\n\n")

    names = ", ".join(q('ref_rmth_' + k) for k in lists)
    out.append("""-- ── verification ──────────────────────────────────────────────────────────
do $verify$
declare
  v_tables int;
  v_rows   int;
  v_bad    int;
  v_free   int;
begin
  select count(*) into v_tables from pg_tables where schemaname = 'public' and tablename like 'ref\\_rmth\\_%%';
  if v_tables <> %(n_lists)d then
    raise exception '0176: expected %(n_lists)d ref_rmth_ tables, found %%', v_tables;
  end if;

  -- every table has RLS, two policies, the four standard triggers, and rows
  select count(*) into v_bad
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relname like 'ref\\_rmth\\_%%' and c.relkind = 'r'
     and (not c.relrowsecurity
          or (select count(*) from pg_policy p where p.polrelid = c.oid) <> 2
          or (select count(*) from pg_trigger tg where tg.tgrelid = c.oid and not tg.tgisinternal) <> 4);
  if v_bad <> 0 then
    raise exception '0176: %% ref_rmth_ tables are missing RLS, a policy or a trigger', v_bad;
  end if;

  execute (
    select 'select ' || string_agg(format('(select count(*) from public.%%I)', tablename), ' + ')
      from pg_tables where schemaname = 'public' and tablename in (%(names)s))
    into v_rows;
  if v_rows <> %(n_opts)d then
    raise exception '0176: expected %(n_opts)d option rows, found %%', v_rows;
  end if;

  execute (
    select 'select ' || string_agg(format('(select count(*) from public.%%I where allows_free_text)', tablename), ' + ')
      from pg_tables where schemaname = 'public' and tablename in (%(names)s))
    into v_free;
  if v_free <> %(n_free)d then
    raise exception '0176: expected %(n_free)d free-text options, found %%', v_free;
  end if;
end $verify$;
""" % dict(n_lists=n_lists, n_opts=n_opts, n_free=n_free, names=names))
    return "".join(out)


def main():
    text = render(model.build())
    applied = [p for p in glob.glob(os.path.join(MIGRATIONS, '*_' + NAME)) if not os.path.basename(p).startswith('PENDING_')]
    if applied:
        cur = io.open(applied[0], encoding='utf-8', newline='').read()
        if cur != text:
            raise SystemExit('gen_lists: %s is applied and the catalogue no longer reproduces it. '
                             'A later change is a later migration.' % os.path.basename(applied[0]))
        print('reproduces', os.path.basename(applied[0]))
        return
    path = os.path.join(MIGRATIONS, 'PENDING_' + NAME)
    io.open(path, 'w', encoding='utf-8', newline='').write(text)
    print('wrote', path)


if __name__ == '__main__':
    main()
