// GENERATED by supabase/khalidiyah/gen_forms.py from Khaldia_2_reviewed.xlsx
// (workbook.py) and supabase/khalidiyah/catalogue.py. Do not edit; edit the
// catalogue and regenerate. Labels live in locales/{en,ar}/khld.json under
// forms.<id>.fields.<Field ID>; option labels are ref_khld_* rows in the database.
import type { KhldFormDef } from './types'

export const KHLD_FORMS = {
  "form01": {
    "id": "form01",
    "sheets": [
      "FORM-01"
    ],
    "table": "khld_focal_point",
    "group": "partnerships",
    "writer": "can_write",
    "indicators": [
      "KHLD-SO1-A1"
    ],
    "list": [
      "F001",
      "F002",
      "F003"
    ],
    "fields": [
      {
        "id": "F001",
        "kind": "text",
        "column": "focal_point_name",
        "required": true
      },
      {
        "id": "F002",
        "kind": "text",
        "column": "phone",
        "required": true,
        "ltr": true
      },
      {
        "id": "F003",
        "kind": "date",
        "column": "assigned_on",
        "required": true
      }
    ]
  },
  "form02": {
    "id": "form02",
    "sheets": [
      "FORM-02"
    ],
    "table": "khld_partner",
    "group": "partnerships",
    "writer": "can_write",
    "indicators": [
      "KHLD-SO1-A1",
      "KHLD-SO1-A2",
      "KHLD-SO1-A3",
      "KHLD-SO1-0"
    ],
    "list": [
      "F004",
      "F006",
      "F115"
    ],
    "fields": [
      {
        "id": "F004",
        "kind": "text",
        "column": "name",
        "required": true
      },
      {
        "id": "F005",
        "kind": "text",
        "column": "phone",
        "required": true,
        "ltr": true
      },
      {
        "id": "F006",
        "kind": "select",
        "column": "partner_type_id",
        "required": true,
        "list": "partner_type"
      },
      {
        "id": "F007",
        "kind": "area",
        "column": "expected_contribution"
      },
      {
        "id": "F008",
        "kind": "text",
        "column": "contact_position"
      },
      {
        "id": "F009",
        "kind": "text",
        "column": "email",
        "ltr": true
      },
      {
        "id": "F115",
        "kind": "select",
        "column": "partner_category_id",
        "required": true,
        "list": "partner_category",
        "other": "partner_category_other"
      }
    ]
  },
  "form04": {
    "id": "form04",
    "sheets": [
      "FORM-03",
      "FORM-04"
    ],
    "table": "khld_partner_contact",
    "group": "partnerships",
    "writer": "can_write",
    "reference": "KHLD-ATT",
    "indicators": [
      "KHLD-SO1-A1",
      "KHLD-SO1-0"
    ],
    "list": [
      "F010",
      "F011",
      "F013",
      "F015"
    ],
    "fields": [
      {
        "id": "F010",
        "kind": "reference",
        "column": "reference"
      },
      {
        "id": "F011",
        "kind": "record",
        "column": "partner_id",
        "required": true,
        "table": "khld_partner"
      },
      {
        "id": "F012",
        "kind": "stamp",
        "column": "attempted_at"
      },
      {
        "id": "F013",
        "kind": "select",
        "column": "attempt_case_id",
        "required": true,
        "list": "attempt_case"
      },
      {
        "id": "F014",
        "kind": "area",
        "column": "notes"
      },
      {
        "id": "F015",
        "kind": "select",
        "column": "evaluation_id",
        "required": true,
        "when": [
          {
            "field": "F013",
            "values": [
              "contacted"
            ]
          }
        ],
        "list": "attempt_evaluation"
      },
      {
        "id": "F116",
        "kind": "bool",
        "column": "partnership_confirmed",
        "required": true,
        "when": [
          {
            "field": "F015",
            "values": [
              "interested"
            ]
          }
        ]
      }
    ]
  },
  "form05": {
    "id": "form05",
    "sheets": [
      "FORM-05"
    ],
    "table": "khld_meeting",
    "group": "partnerships",
    "writer": "can_write",
    "reference": "KHLD-MTG",
    "indicators": [
      "KHLD-SO1-A2",
      "KHLD-SO1-B1",
      "KHLD-SO2-C1",
      "KHLD-SO1-0"
    ],
    "list": [
      "F016",
      "F117",
      "F119"
    ],
    "fields": [
      {
        "id": "F016",
        "kind": "date",
        "column": "meeting_date",
        "required": true
      },
      {
        "id": "F017",
        "kind": "file",
        "required": true,
        "maxFiles": 5
      },
      {
        "id": "F018",
        "kind": "area",
        "column": "summary"
      },
      {
        "id": "F019",
        "kind": "bool",
        "column": "priorities_identified",
        "required": true
      },
      {
        "id": "F117",
        "kind": "select",
        "column": "meeting_type_id",
        "required": true,
        "list": "meeting_type",
        "other": "meeting_type_other"
      },
      {
        "id": "F118",
        "kind": "records",
        "required": true,
        "table": "khld_partner"
      },
      {
        "id": "F119",
        "kind": "int",
        "column": "attendees_count",
        "required": true,
        "min": 1
      },
      {
        "id": "F120",
        "kind": "file",
        "required": true,
        "maxFiles": 5
      }
    ]
  },
  "form20": {
    "id": "form20",
    "sheets": [
      "FORM-20"
    ],
    "table": "khld_partner_survey",
    "group": "partnerships",
    "writer": "is_staff",
    "indicators": [
      "KHLD-SO1-0"
    ],
    "list": [
      "F173",
      "F174",
      "F179"
    ],
    "fields": [
      {
        "id": "F173",
        "kind": "date",
        "column": "survey_date",
        "required": true
      },
      {
        "id": "F174",
        "kind": "record",
        "column": "partner_id",
        "required": true,
        "table": "khld_partner",
        "confirmed": true
      },
      {
        "id": "F175",
        "kind": "text",
        "column": "respondent_position",
        "required": true
      },
      {
        "id": "F176",
        "kind": "select",
        "column": "respondent_sex_id",
        "required": true,
        "list": "sex"
      },
      {
        "id": "F177",
        "kind": "likert",
        "column": "coordination_score",
        "required": true,
        "scale": "agree"
      },
      {
        "id": "F178",
        "kind": "likert",
        "column": "joint_planning_score",
        "required": true,
        "scale": "agree"
      },
      {
        "id": "F179",
        "kind": "bool",
        "column": "overall_effective",
        "required": true
      },
      {
        "id": "F180",
        "kind": "area",
        "column": "suggestions"
      }
    ]
  },
  "form21": {
    "id": "form21",
    "sheets": [
      "FORM-21"
    ],
    "table": "khld_contribution",
    "group": "partnerships",
    "writer": "can_write",
    "reference": "KHLD-CON",
    "indicators": [
      "KHLD-SO1-A3",
      "KHLD-SO1-A1"
    ],
    "list": [
      "F181",
      "F183",
      "F184",
      "F186"
    ],
    "fields": [
      {
        "id": "F181",
        "kind": "record",
        "column": "partner_id",
        "required": true,
        "table": "khld_partner",
        "extra": {
          "code": "other"
        }
      },
      {
        "id": "F182",
        "kind": "text",
        "column": "contributor_name",
        "required": true,
        "when": [
          {
            "field": "F181",
            "values": [
              "__extra__"
            ]
          }
        ]
      },
      {
        "id": "F183",
        "kind": "date",
        "column": "date_received",
        "required": true
      },
      {
        "id": "F184",
        "kind": "select",
        "column": "contribution_type_id",
        "required": true,
        "list": "contribution_type"
      },
      {
        "id": "F185",
        "kind": "area",
        "column": "description",
        "required": true
      },
      {
        "id": "F186",
        "kind": "money",
        "column": "value_jod",
        "required": true,
        "min": 0
      },
      {
        "id": "F187",
        "kind": "select",
        "column": "activity_supported_id",
        "required": true,
        "list": "activity_supported",
        "other": "activity_supported_other"
      },
      {
        "id": "F188",
        "kind": "file",
        "maxFiles": 5
      }
    ]
  },
  "form22": {
    "id": "form22",
    "sheets": [
      "FORM-22"
    ],
    "table": "khld_milestone_record",
    "group": "partnerships",
    "writer": "can_write",
    "indicators": [
      "KHLD-SO1-A1",
      "KHLD-SO1-B1",
      "KHLD-SO3-E1",
      "KHLD-SO3-F1"
    ],
    "list": [
      "F189",
      "F194",
      "F195"
    ],
    "fields": [
      {
        "id": "F189",
        "kind": "select",
        "column": "milestone_id",
        "required": true,
        "list": "milestone"
      },
      {
        "id": "F190",
        "kind": "multi",
        "required": true,
        "when": [
          {
            "field": "F189",
            "values": [
              "so1_a1"
            ]
          }
        ],
        "list": "components_a1",
        "question": "f190"
      },
      {
        "id": "F191",
        "kind": "multi",
        "required": true,
        "when": [
          {
            "field": "F189",
            "values": [
              "so1_b1"
            ]
          }
        ],
        "list": "components_b1",
        "question": "f191"
      },
      {
        "id": "F192",
        "kind": "multi",
        "required": true,
        "when": [
          {
            "field": "F189",
            "values": [
              "so3_e1"
            ]
          }
        ],
        "list": "components_e1",
        "question": "f192"
      },
      {
        "id": "F193",
        "kind": "multi",
        "required": true,
        "when": [
          {
            "field": "F189",
            "values": [
              "so3_f1"
            ]
          }
        ],
        "list": "components_f1",
        "question": "f193"
      },
      {
        "id": "F194",
        "kind": "select",
        "column": "status_id",
        "required": true,
        "list": "milestone_status"
      },
      {
        "id": "F195",
        "kind": "date",
        "column": "status_date",
        "required": true,
        "when": [
          {
            "field": "F194",
            "values": [
              "established",
              "updated"
            ]
          }
        ]
      },
      {
        "id": "F196",
        "kind": "file",
        "required": true,
        "when": [
          {
            "field": "F194",
            "values": [
              "established",
              "updated"
            ]
          }
        ],
        "maxFiles": 5
      }
    ]
  },
  "form06": {
    "id": "form06",
    "sheets": [
      "FORM-06"
    ],
    "table": "khld_rehab_report",
    "group": "park",
    "writer": "can_write",
    "reference": "KHLD-REH",
    "indicators": [
      "KHLD-SO2-C1"
    ],
    "list": [
      "F021",
      "F020",
      "F122"
    ],
    "fields": [
      {
        "id": "F020",
        "kind": "percent",
        "column": "completion_pct",
        "required": true,
        "min": 0,
        "max": 100
      },
      {
        "id": "F021",
        "kind": "date",
        "column": "report_date",
        "required": true
      },
      {
        "id": "F022",
        "kind": "area",
        "column": "accomplished",
        "required": true
      },
      {
        "id": "F121",
        "kind": "int",
        "column": "agreed_total",
        "required": true,
        "min": 1
      },
      {
        "id": "F122",
        "kind": "int",
        "column": "completed_count",
        "required": true,
        "min": 0
      },
      {
        "id": "F123",
        "kind": "multi",
        "required": true,
        "list": "facility_type",
        "question": "f123"
      },
      {
        "id": "F124",
        "kind": "file",
        "required": true,
        "maxFiles": 5
      }
    ]
  },
  "form07": {
    "id": "form07",
    "sheets": [
      "FORM-07"
    ],
    "table": "khld_campaign",
    "group": "park",
    "writer": "can_write",
    "reference": "KHLD-VC",
    "indicators": [
      "KHLD-SO2-C2",
      "KHLD-SO3-F3",
      "KHLD-SO3-F2",
      "KHLD-SO1-A3"
    ],
    "list": [
      "F023",
      "F024",
      "F126",
      "F127"
    ],
    "fields": [
      {
        "id": "F023",
        "kind": "text",
        "column": "campaign_name",
        "required": true
      },
      {
        "id": "F024",
        "kind": "date",
        "column": "start_date",
        "required": true
      },
      {
        "id": "F025",
        "kind": "date",
        "column": "end_date",
        "required": true
      },
      {
        "id": "F026",
        "kind": "date",
        "column": "applications_open",
        "required": true
      },
      {
        "id": "F027",
        "kind": "date",
        "column": "applications_close",
        "required": true
      },
      {
        "id": "F028",
        "kind": "area",
        "column": "description",
        "required": true
      },
      {
        "id": "F029",
        "kind": "bool",
        "column": "has_sponsor",
        "required": true
      },
      {
        "id": "F030",
        "kind": "text",
        "column": "sponsor_name",
        "required": true,
        "when": [
          {
            "field": "F029",
            "values": [
              "true"
            ]
          }
        ]
      },
      {
        "id": "F125",
        "kind": "multi",
        "required": true,
        "list": "campaign_activity_type",
        "question": "f125"
      },
      {
        "id": "F126",
        "kind": "select",
        "column": "status_id",
        "required": true,
        "list": "event_status"
      },
      {
        "id": "F127",
        "kind": "int",
        "column": "action_days",
        "required": true,
        "when": [
          {
            "field": "F126",
            "values": [
              "held"
            ]
          }
        ],
        "min": 1
      },
      {
        "id": "F128",
        "kind": "file",
        "when": [
          {
            "field": "F126",
            "values": [
              "held"
            ]
          }
        ],
        "maxFiles": 5
      }
    ]
  },
  "form08": {
    "id": "form08",
    "sheets": [
      "FORM-08"
    ],
    "table": "khld_activity",
    "group": "park",
    "writer": "can_write",
    "reference": "KHLD-EV",
    "published": true,
    "indicators": [
      "KHLD-SO2-D1",
      "KHLD-SO1-A2",
      "KHLD-SO2-D2"
    ],
    "list": [
      "F129",
      "F031",
      "F034",
      "F130"
    ],
    "fields": [
      {
        "id": "F031",
        "kind": "date",
        "column": "start_date",
        "required": true
      },
      {
        "id": "F032",
        "kind": "date",
        "column": "end_date",
        "required": true
      },
      {
        "id": "F033",
        "kind": "area",
        "column": "description",
        "required": true
      },
      {
        "id": "F034",
        "kind": "select",
        "column": "activity_type_id",
        "required": true,
        "list": "activity_type"
      },
      {
        "id": "F035",
        "kind": "select",
        "column": "target_audience_id",
        "required": true,
        "list": "target_audience"
      },
      {
        "id": "F036",
        "kind": "select",
        "column": "organiser_id",
        "required": true,
        "list": "organiser",
        "other": "organiser_other"
      },
      {
        "id": "F129",
        "kind": "text",
        "column": "activity_name",
        "required": true
      },
      {
        "id": "F130",
        "kind": "select",
        "column": "status_id",
        "required": true,
        "list": "event_status"
      },
      {
        "id": "F131",
        "kind": "records",
        "required": true,
        "when": [
          {
            "field": "F036",
            "values": [
              "municipality_with_partner"
            ]
          }
        ],
        "table": "khld_partner"
      }
    ]
  },
  "form09": {
    "id": "form09",
    "sheets": [
      "FORM-09"
    ],
    "table": "khld_activity_attendance",
    "group": "park",
    "writer": "can_write",
    "indicators": [
      "KHLD-SO2-D2",
      "KHLD-IMP-0",
      "KHLD-SO2-D1"
    ],
    "list": [
      "F037",
      "F038",
      "F039"
    ],
    "fields": [
      {
        "id": "F037",
        "kind": "date",
        "column": "report_date",
        "required": true
      },
      {
        "id": "F038",
        "kind": "record",
        "column": "activity_id",
        "required": true,
        "table": "khld_activity"
      },
      {
        "id": "F039",
        "kind": "int",
        "column": "total_participants",
        "required": true,
        "min": 0
      },
      {
        "id": "F040",
        "kind": "percent",
        "column": "pct_children",
        "required": true,
        "min": 0,
        "max": 100
      },
      {
        "id": "F041",
        "kind": "percent",
        "column": "pct_adults",
        "required": true,
        "min": 0,
        "max": 100
      },
      {
        "id": "F042",
        "kind": "percent",
        "column": "pct_male",
        "required": true,
        "min": 0,
        "max": 100
      },
      {
        "id": "F043",
        "kind": "percent",
        "column": "pct_female",
        "required": true,
        "min": 0,
        "max": 100
      },
      {
        "id": "F044",
        "kind": "percent",
        "column": "pct_disability",
        "required": true,
        "min": 0,
        "max": 100
      },
      {
        "id": "F045",
        "kind": "multi",
        "required": true,
        "list": "nationality",
        "question": "f045"
      },
      {
        "id": "F046",
        "kind": "area",
        "column": "social_media_links"
      },
      {
        "id": "F047",
        "kind": "file",
        "maxFiles": 5
      },
      {
        "id": "F132",
        "kind": "select",
        "column": "counting_method_id",
        "required": true,
        "list": "counting_method"
      },
      {
        "id": "F133",
        "kind": "percent",
        "column": "pct_youth",
        "required": true,
        "min": 0,
        "max": 100
      },
      {
        "id": "F134",
        "kind": "percent",
        "column": "pct_jordanian",
        "required": true,
        "min": 0,
        "max": 100
      },
      {
        "id": "F135",
        "kind": "percent",
        "column": "pct_syrian",
        "required": true,
        "min": 0,
        "max": 100
      },
      {
        "id": "F136",
        "kind": "select",
        "column": "observed_interaction_id",
        "required": true,
        "list": "observed_interaction"
      },
      {
        "id": "F137",
        "kind": "file",
        "when": [
          {
            "field": "F132",
            "values": [
              "attendance_sheet"
            ]
          }
        ],
        "maxFiles": 5
      }
    ]
  },
  "form19": {
    "id": "form19",
    "sheets": [
      "FORM-19"
    ],
    "table": "khld_park_survey",
    "group": "park",
    "writer": "is_staff",
    "indicators": [
      "KHLD-IMP-0",
      "KHLD-SO2-0"
    ],
    "list": [
      "F159",
      "F160",
      "F158"
    ],
    "fields": [
      {
        "id": "F158",
        "kind": "bool",
        "column": "consent",
        "required": true
      },
      {
        "id": "F159",
        "kind": "stamp",
        "column": "surveyed_at"
      },
      {
        "id": "F160",
        "kind": "record",
        "column": "activity_id",
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          }
        ],
        "table": "khld_activity",
        "extra": {
          "code": "general_visit",
          "column": "is_general_visit"
        }
      },
      {
        "id": "F161",
        "kind": "select",
        "column": "sex_id",
        "required": true,
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          }
        ],
        "list": "sex"
      },
      {
        "id": "F162",
        "kind": "select",
        "column": "age_group_id",
        "required": true,
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          }
        ],
        "list": "survey_age_group"
      },
      {
        "id": "F163",
        "kind": "select",
        "column": "nationality_id",
        "required": true,
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          }
        ],
        "list": "nationality",
        "other": "nationality_other"
      },
      {
        "id": "F164",
        "kind": "select",
        "column": "disability_id",
        "required": true,
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          }
        ],
        "list": "disability"
      },
      {
        "id": "F165",
        "kind": "bool",
        "column": "is_resident",
        "required": true,
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          }
        ]
      },
      {
        "id": "F166",
        "kind": "likert",
        "column": "interaction_score",
        "required": true,
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          }
        ],
        "scale": "agree"
      },
      {
        "id": "F167",
        "kind": "bool",
        "column": "shared_participation",
        "required": true,
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          }
        ]
      },
      {
        "id": "F168",
        "kind": "likert",
        "column": "safe_score",
        "required": true,
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          }
        ],
        "scale": "agree"
      },
      {
        "id": "F169",
        "kind": "likert",
        "column": "welcoming_score",
        "required": true,
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          }
        ],
        "scale": "agree"
      },
      {
        "id": "F170",
        "kind": "likert",
        "column": "satisfaction_score",
        "required": true,
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          }
        ],
        "scale": "satisfied"
      },
      {
        "id": "F171",
        "kind": "likert",
        "column": "suitability_score",
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          },
          {
            "field": "F160",
            "values": [
              "__record__"
            ]
          }
        ],
        "scale": "suitable"
      },
      {
        "id": "F172",
        "kind": "area",
        "column": "suggestions",
        "when": [
          {
            "field": "F158",
            "values": [
              "true"
            ]
          }
        ]
      }
    ]
  },
  "form10": {
    "id": "form10",
    "sheets": [
      "FORM-10"
    ],
    "table": "khld_committee_member",
    "group": "volunteer",
    "writer": "can_write",
    "indicators": [
      "KHLD-SO3-E1"
    ],
    "list": [
      "F048",
      "F141",
      "F140"
    ],
    "fields": [
      {
        "id": "F048",
        "kind": "text",
        "column": "member_name",
        "required": true
      },
      {
        "id": "F049",
        "kind": "text",
        "column": "phone",
        "required": true,
        "ltr": true
      },
      {
        "id": "F050",
        "kind": "date",
        "column": "appointed_on",
        "required": true
      },
      {
        "id": "F138",
        "kind": "select",
        "column": "sex_id",
        "required": true,
        "list": "sex"
      },
      {
        "id": "F139",
        "kind": "text",
        "column": "organisation",
        "required": true
      },
      {
        "id": "F140",
        "kind": "select",
        "column": "organisation_type_id",
        "required": true,
        "list": "organisation_type"
      },
      {
        "id": "F141",
        "kind": "select",
        "column": "role_id",
        "required": true,
        "list": "committee_role"
      }
    ]
  },
  "form11": {
    "id": "form11",
    "sheets": [
      "FORM-11"
    ],
    "table": "khld_committee_meeting",
    "group": "volunteer",
    "writer": "can_write",
    "reference": "KHLD-CMT",
    "indicators": [
      "KHLD-SO3-E1",
      "KHLD-SO3-F1"
    ],
    "list": [
      "F051",
      "F142",
      "F143"
    ],
    "fields": [
      {
        "id": "F051",
        "kind": "date",
        "column": "meeting_date",
        "required": true
      },
      {
        "id": "F052",
        "kind": "file",
        "required": true,
        "maxFiles": 5
      },
      {
        "id": "F053",
        "kind": "area",
        "column": "summary"
      },
      {
        "id": "F054",
        "kind": "bool",
        "column": "workplan_discussed",
        "required": true
      },
      {
        "id": "F142",
        "kind": "bool",
        "column": "is_founding",
        "required": true
      },
      {
        "id": "F143",
        "kind": "int",
        "column": "members_present",
        "required": true,
        "min": 1
      }
    ]
  },
  "form12": {
    "id": "form12",
    "sheets": [
      "FORM-12"
    ],
    "table": "khld_volunteer",
    "group": "volunteer",
    "writer": "can_write",
    "reference": "KHLD-VOL",
    "public": true,
    "indicators": [
      "KHLD-SO3-F2",
      "KHLD-SO3-0",
      "KHLD-SO3-F1"
    ],
    "list": [
      "F055",
      "F058",
      "F063"
    ],
    "fields": [
      {
        "id": "F144",
        "kind": "id_type",
        "column": "id_type_id",
        "required": true,
        "list": "id_type"
      },
      {
        "id": "F058",
        "kind": "ident",
        "required": true
      },
      {
        "id": "F055",
        "kind": "person_name",
        "required": true
      },
      {
        "id": "F056",
        "kind": "person_sex",
        "required": true,
        "list": "sex"
      },
      {
        "id": "F057",
        "kind": "dob",
        "required": true
      },
      {
        "id": "F059",
        "kind": "person_phone",
        "required": true
      },
      {
        "id": "F060",
        "kind": "bool",
        "column": "is_resident",
        "required": true,
        "mustBeTrue": true
      },
      {
        "id": "F061",
        "kind": "select",
        "column": "nationality_id",
        "required": true,
        "list": "nationality",
        "other": "nationality_other"
      },
      {
        "id": "F062",
        "kind": "select",
        "column": "disability_id",
        "required": true,
        "list": "disability"
      },
      {
        "id": "F063",
        "kind": "select",
        "column": "situation_id",
        "required": true,
        "list": "situation"
      },
      {
        "id": "F064",
        "kind": "multi",
        "required": true,
        "list": "volunteer_interest",
        "question": "f064"
      },
      {
        "id": "F065",
        "kind": "multi",
        "required": true,
        "list": "weekday",
        "question": "f065"
      },
      {
        "id": "F066",
        "kind": "multi",
        "required": true,
        "list": "time_of_day",
        "question": "f066"
      },
      {
        "id": "F067",
        "kind": "bool",
        "column": "photo_consent",
        "required": true
      },
      {
        "id": "F145",
        "kind": "select",
        "column": "affiliation_id",
        "required": true,
        "list": "affiliation",
        "other": "affiliation_other"
      },
      {
        "id": "F146",
        "kind": "text",
        "column": "affiliation_name",
        "when": [
          {
            "field": "F145",
            "values": [
              "school",
              "university",
              "cso",
              "other"
            ]
          }
        ]
      }
    ]
  },
  "form13": {
    "id": "form13",
    "sheets": [
      "FORM-13"
    ],
    "table": "khld_volunteer_attendance",
    "group": "volunteer",
    "writer": "can_write",
    "indicators": [
      "KHLD-SO3-0",
      "KHLD-SO3-F2",
      "KHLD-SO3-F3",
      "KHLD-SO3-F1"
    ],
    "list": [
      "F068",
      "F070",
      "F147"
    ],
    "fields": [
      {
        "id": "F068",
        "kind": "date",
        "column": "report_date",
        "required": true
      },
      {
        "id": "F070",
        "kind": "record",
        "column": "volunteer_id",
        "required": true,
        "table": "khld_volunteer"
      },
      {
        "id": "F069",
        "kind": "shown",
        "of": "F070"
      },
      {
        "id": "F071",
        "kind": "likert",
        "column": "assessment",
        "required": true,
        "scale": "plain"
      },
      {
        "id": "F072",
        "kind": "area",
        "column": "notes"
      },
      {
        "id": "F147",
        "kind": "occasion",
        "required": true
      },
      {
        "id": "F148",
        "kind": "select",
        "column": "role_id",
        "list": "volunteer_interest",
        "other": "role_other"
      }
    ]
  },
  "form14": {
    "id": "form14",
    "sheets": [
      "FORM-14"
    ],
    "table": "khld_guidance_session",
    "group": "business",
    "writer": "can_write",
    "reference": "KHLD-GS",
    "indicators": [
      "KHLD-SO4-G1",
      "KHLD-SO4-G2"
    ],
    "list": [
      "F073",
      "F074",
      "F149",
      "F150"
    ],
    "fields": [
      {
        "id": "F073",
        "kind": "text",
        "column": "title",
        "required": true
      },
      {
        "id": "F074",
        "kind": "date",
        "column": "start_date",
        "required": true
      },
      {
        "id": "F075",
        "kind": "date",
        "column": "end_date",
        "required": true
      },
      {
        "id": "F076",
        "kind": "date",
        "column": "applications_open",
        "required": true
      },
      {
        "id": "F077",
        "kind": "date",
        "column": "applications_close",
        "required": true
      },
      {
        "id": "F078",
        "kind": "area",
        "column": "description",
        "required": true
      },
      {
        "id": "F079",
        "kind": "text",
        "column": "executing_entity",
        "required": true
      },
      {
        "id": "F149",
        "kind": "select",
        "column": "topic_id",
        "required": true,
        "list": "session_topic",
        "other": "topic_other"
      },
      {
        "id": "F150",
        "kind": "bool",
        "column": "is_core",
        "required": true
      }
    ]
  },
  "form15": {
    "id": "form15",
    "sheets": [
      "FORM-15"
    ],
    "table": "khld_enterprise_request",
    "group": "business",
    "writer": "can_write",
    "indicators": [
      "KHLD-SO4-G1",
      "KHLD-SO4-G2"
    ],
    "list": [
      "F080",
      "F083",
      "F088"
    ],
    "fields": [
      {
        "id": "F151",
        "kind": "id_type",
        "column": "id_type_id",
        "required": true,
        "list": "id_type"
      },
      {
        "id": "F083",
        "kind": "ident",
        "required": true
      },
      {
        "id": "F080",
        "kind": "person_name",
        "required": true
      },
      {
        "id": "F081",
        "kind": "person_sex",
        "required": true,
        "list": "sex"
      },
      {
        "id": "F082",
        "kind": "dob",
        "required": true
      },
      {
        "id": "F084",
        "kind": "person_phone",
        "required": true
      },
      {
        "id": "F085",
        "kind": "bool",
        "column": "is_resident",
        "required": true
      },
      {
        "id": "F086",
        "kind": "select",
        "column": "nationality_id",
        "required": true,
        "list": "nationality",
        "other": "nationality_other"
      },
      {
        "id": "F087",
        "kind": "select",
        "column": "disability_id",
        "required": true,
        "list": "disability"
      },
      {
        "id": "F088",
        "kind": "record",
        "column": "session_id",
        "required": true,
        "table": "khld_guidance_session",
        "window": [
          "start_date",
          "end_date"
        ]
      },
      {
        "id": "F089",
        "kind": "bool",
        "column": "has_business",
        "required": true
      },
      {
        "id": "F090",
        "kind": "select",
        "column": "working_status_id",
        "required": true,
        "list": "working_status"
      },
      {
        "id": "F152",
        "kind": "select",
        "column": "product_type_id",
        "required": true,
        "list": "product_type",
        "other": "product_type_other"
      }
    ]
  },
  "form23": {
    "id": "form23",
    "sheets": [
      "FORM-23"
    ],
    "table": "khld_enterprise_support",
    "group": "business",
    "writer": "can_write",
    "indicators": [
      "KHLD-SO4-G1",
      "KHLD-SO4-G2"
    ],
    "list": [
      "F197",
      "F198",
      "F199"
    ],
    "fields": [
      {
        "id": "F197",
        "kind": "person_ref",
        "column": "person_id",
        "required": true,
        "table": "khld_enterprise_request"
      },
      {
        "id": "F198",
        "kind": "date",
        "column": "support_date",
        "required": true
      },
      {
        "id": "F199",
        "kind": "select",
        "column": "support_type_id",
        "required": true,
        "list": "support_type"
      },
      {
        "id": "F200",
        "kind": "record",
        "column": "session_id",
        "required": true,
        "when": [
          {
            "field": "F199",
            "values": [
              "guidance"
            ]
          }
        ],
        "table": "khld_guidance_session"
      },
      {
        "id": "F201",
        "kind": "bool",
        "column": "attended",
        "required": true,
        "when": [
          {
            "field": "F199",
            "values": [
              "guidance"
            ]
          }
        ]
      },
      {
        "id": "F202",
        "kind": "text",
        "column": "referred_to",
        "required": true,
        "when": [
          {
            "field": "F199",
            "values": [
              "referral"
            ]
          }
        ]
      },
      {
        "id": "F203",
        "kind": "select",
        "column": "provided_by_id",
        "required": true,
        "list": "support_provider"
      },
      {
        "id": "F204",
        "kind": "area",
        "column": "notes"
      }
    ]
  },
  "form16": {
    "id": "form16",
    "sheets": [
      "FORM-16"
    ],
    "table": "khld_market",
    "group": "business",
    "writer": "can_write",
    "reference": "KHLD-MKT",
    "published": true,
    "indicators": [
      "KHLD-SO4-H1",
      "KHLD-SO4-H2",
      "KHLD-SO1-A3"
    ],
    "list": [
      "F091",
      "F092",
      "F154",
      "F094"
    ],
    "fields": [
      {
        "id": "F091",
        "kind": "text",
        "column": "name",
        "required": true
      },
      {
        "id": "F092",
        "kind": "date",
        "column": "start_date",
        "required": true
      },
      {
        "id": "F093",
        "kind": "date",
        "column": "end_date",
        "required": true
      },
      {
        "id": "F094",
        "kind": "int",
        "column": "actual_days",
        "required": true,
        "min": 0
      },
      {
        "id": "F095",
        "kind": "date",
        "column": "applications_open",
        "required": true
      },
      {
        "id": "F096",
        "kind": "date",
        "column": "applications_close",
        "required": true
      },
      {
        "id": "F097",
        "kind": "area",
        "column": "description",
        "required": true
      },
      {
        "id": "F098",
        "kind": "bool",
        "column": "has_sponsor",
        "required": true
      },
      {
        "id": "F099",
        "kind": "text",
        "column": "sponsor_name",
        "required": true,
        "when": [
          {
            "field": "F098",
            "values": [
              "true"
            ]
          }
        ]
      },
      {
        "id": "F100",
        "kind": "int",
        "column": "kiosks_available",
        "required": true,
        "min": 0
      },
      {
        "id": "F153",
        "kind": "select",
        "column": "occasion_id",
        "required": true,
        "list": "market_occasion",
        "other": "occasion_other"
      },
      {
        "id": "F154",
        "kind": "select",
        "column": "status_id",
        "required": true,
        "list": "event_status"
      }
    ]
  },
  "form17": {
    "id": "form17",
    "sheets": [
      "FORM-17"
    ],
    "table": "khld_vendor_application",
    "group": "business",
    "writer": "can_write",
    "indicators": [
      "KHLD-SO4-H2",
      "KHLD-SO4-0"
    ],
    "list": [
      "F101",
      "F104",
      "F155"
    ],
    "fields": [
      {
        "id": "F156",
        "kind": "id_type",
        "column": "id_type_id",
        "required": true,
        "list": "id_type"
      },
      {
        "id": "F104",
        "kind": "ident",
        "required": true
      },
      {
        "id": "F101",
        "kind": "person_name",
        "required": true
      },
      {
        "id": "F102",
        "kind": "person_sex",
        "required": true,
        "list": "sex"
      },
      {
        "id": "F103",
        "kind": "dob",
        "required": true
      },
      {
        "id": "F105",
        "kind": "person_phone",
        "required": true
      },
      {
        "id": "F106",
        "kind": "bool",
        "column": "is_resident",
        "required": true
      },
      {
        "id": "F107",
        "kind": "select",
        "column": "nationality_id",
        "required": true,
        "list": "nationality",
        "other": "nationality_other"
      },
      {
        "id": "F108",
        "kind": "select",
        "column": "disability_id",
        "required": true,
        "list": "disability"
      },
      {
        "id": "F109",
        "kind": "select",
        "column": "product_type_id",
        "required": true,
        "list": "product_type",
        "other": "product_type_other"
      },
      {
        "id": "F155",
        "kind": "record",
        "column": "market_id",
        "required": true,
        "table": "khld_market",
        "window": [
          "applications_open",
          "applications_close"
        ]
      }
    ]
  },
  "form18": {
    "id": "form18",
    "sheets": [
      "FORM-18"
    ],
    "table": "khld_market_attendance",
    "group": "business",
    "writer": "can_write",
    "indicators": [
      "KHLD-SO4-H2"
    ],
    "list": [
      "F110",
      "F157",
      "F112"
    ],
    "fields": [
      {
        "id": "F110",
        "kind": "date",
        "column": "report_date",
        "required": true
      },
      {
        "id": "F157",
        "kind": "record",
        "column": "market_id",
        "required": true,
        "table": "khld_market",
        "window": [
          "start_date",
          "end_date"
        ]
      },
      {
        "id": "F112",
        "kind": "person_ref",
        "column": "person_id",
        "required": true,
        "table": "khld_vendor_application"
      },
      {
        "id": "F111",
        "kind": "shown",
        "of": "F112"
      },
      {
        "id": "F113",
        "kind": "likert",
        "column": "kiosk_rating",
        "required": true,
        "scale": "plain"
      },
      {
        "id": "F114",
        "kind": "area",
        "column": "notes"
      }
    ]
  },
  "form24": {
    "id": "form24",
    "sheets": [
      "FORM-24"
    ],
    "table": "khld_producer_survey",
    "group": "business",
    "writer": "is_staff",
    "indicators": [
      "KHLD-SO4-0"
    ],
    "list": [
      "F205",
      "F206",
      "F207",
      "F208"
    ],
    "fields": [
      {
        "id": "F205",
        "kind": "date",
        "column": "survey_date",
        "required": true
      },
      {
        "id": "F206",
        "kind": "person_ref",
        "column": "person_id",
        "required": true,
        "table": "khld_vendor_application"
      },
      {
        "id": "F207",
        "kind": "record",
        "column": "market_id",
        "required": true,
        "table": "khld_market",
        "held": true
      },
      {
        "id": "F208",
        "kind": "bool",
        "column": "increased_opportunities",
        "required": true
      },
      {
        "id": "F209",
        "kind": "bool",
        "column": "new_customers",
        "required": true
      },
      {
        "id": "F210",
        "kind": "bool",
        "column": "made_sales",
        "required": true
      },
      {
        "id": "F211",
        "kind": "money",
        "column": "sales_value_jod",
        "when": [
          {
            "field": "F210",
            "values": [
              "true"
            ]
          }
        ],
        "min": 0
      },
      {
        "id": "F212",
        "kind": "bool",
        "column": "received_orders"
      },
      {
        "id": "F213",
        "kind": "area",
        "column": "suggestions"
      }
    ]
  }
} as const satisfies Record<string, KhldFormDef>

export type KhldFormId = keyof typeof KHLD_FORMS
export const KHLD_FORM_IDS = Object.keys(KHLD_FORMS) as KhldFormId[]

/** The sidebar's groups, in the sheet's order (Page En / Page Ar). */
export const KHLD_GROUPS = ["partnerships", "park", "volunteer", "business"] as const

/** The form carrying each indicator's main source (the Calculation formulas sheet). */
export const KHLD_INDICATOR_FORM: Readonly<Record<string, KhldFormId>> = {
  "IMP-0": "form19",
  "SO1-0": "form20",
  "A1": "form22",
  "A2": "form05",
  "A3": "form21",
  "B1": "form22",
  "SO2-0": "form19",
  "C1": "form06",
  "C2": "form07",
  "D1": "form08",
  "D2": "form09",
  "SO3-0": "form13",
  "E1": "form11",
  "F1": "form22",
  "F2": "form12",
  "F3": "form07",
  "SO4-0": "form24",
  "G1": "form23",
  "G2": "form23",
  "H1": "form16",
  "H2": "form18"
}
