# -*- coding: utf-8 -*-
"""
Generates the three option-list migrations from the resolved model:

  supabase/migrations/PENDING_0141_khalidiyah_option_lists.sql    tables + first third
  supabase/migrations/PENDING_0142_khalidiyah_option_lists_2.sql  second third
  supabase/migrations/PENDING_0143_khalidiyah_option_lists_3.sql  last third + verification

Run from the repository root:  python supabase/khalidiyah/gen_0141.py
Writes LF only (newline=''), per CLAUDE.md rule 5.
"""
import io, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from model import build
from catalogue import LISTS_ADDED_LATER

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..'))
# v1 is history: it writes into v1/out/, never over the live migrations or app files
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'out')
os.makedirs(OUT, exist_ok=True)


def q(s):
    return "'" + s.replace("'", "''") + "'"


m = build()
lists = {k: v for k, v in m.lists.items() if k not in LISTS_ADDED_LATER}
n_lists = len(lists)
n_opts = sum(len(l.options) for l in lists.values())
n_shared = sum(1 for l in lists.values() if len(l.used_by) > 1)
n_free = sum(1 for l in lists.values() for o in l.options if o[3])

HEADER = """-- ═══════════════════════════════════════════════════════════════════════════
--  0141 — Khalidiyah's option lists: one ref_khld_* table per response list
--
--  Every response-option list in Khalidiyah_Indicator_Data_Collection_Forms.xlsx,
--  one table each, BOTH labels verbatim from the sheet in the sheet's order:
--  this is the first framework to arrive with its Arabic written, so nothing
--  here is drafted (plan 5.7). %(n_lists)d lists, %(n_opts)d options. Generated by
--  supabase/khalidiyah/gen_0141.py from workbook.py (the one reading of the
--  sheets) and catalogue.py (the structure); do not edit by hand. Split
--  across 0141, 0142 and 0143 only because each is applied through the MCP
--  as one pasted text: 0141 creates every table and seeds the first third
--  of the lists, 0142 and 0143 seed the rest, and 0143 carries the
--  verification over all %(n_lists)d.
--
--  ── WHY ONE TABLE PER LIST ──
--
--  0002, 0075 and 0122 made one table per list for the same reason: a
--  single-select column gets a real foreign key into the list it may hold,
--  and the application's ref machinery (useRefTable, refLabel, the "Other"
--  companion column) reads any table of this shape unchanged.
--
--  ── WHAT IS SHARED ──
--
--  %(n_shared)d lists are used by more than one sheet and exist once (sex,
--  age_group, nationality, disability, neighbourhood, agree_scale,
--  checklist_status, product_type, sales_band, partner_type, ...). Two
--  sheets share a table only when every option, English AND Arabic, matches;
--  a3's contributor_type differs from partner_type by one option and is its
--  own table. None of the shared Sahel Horan or Ramtha lists is reused
--  (plan 5.8): a row added to a shared list appears in the other two
--  municipalities' dropdowns.
--
--  ── THREE KINDS OF LIST ──
--
--  Response options (a single- or multi-select), the checklist statuses of
--  a milestone item (codes START with in_place / partly / not_in_place /
--  not_accepted, and khld_milestone_status in 0145 reads the status from the
--  code prefix, so an item whose sheet says "In place — written decision"
--  still evaluates as In place), and the CELLS of a "by ..." count field
--  (plan 5.2: a child row per cell, never a column per cell, never JSON) --
--  a2.orgs_by_type, d2.by_age_sex, e1.members_by_type and so on. The rating
--  matrix of SO2-0 is two cell lists (the nine facilities, the four ratings).
--
--  ── "OTHER" AND THE BLANKS ──
--
--  allows_free_text is true for %(n_free)d options: every option whose sheet
--  text carries a blank ("Yes — names: ____", "Cancelled — reason: ____"),
--  says (specify) or describe, or is a bare "Other". The blank is the
--  sheet's own signal that the option needs a detail, and the detail lives
--  in the record's <field>_other column, required by guard_rmth_other /
--  guard_khld_option when such an option is chosen (CLAUDE.md, "Other
--  (please specify)"). A bare "Other" is treated the same way as a
--  decision, recorded in 06_OPEN_QUESTIONS.md (OQ-53): an "Other" that
--  cannot say what it was is the OQ-28 defect, and the sheets are not
--  consistent about writing "(specify)". Where a blank is typed instead --
--  a date, a number, a second select -- the option list carries NO free
--  text and the typed column beside it holds the value (catalogue.py's
--  parts): the session dates of SO4-G1, the number of children on IMP-0,
--  the priority rank on SO2-C1.
--
--  ── THE DISABILITY QUESTION ──
--
--  Khalidiyah asks disability functionally (the Washington Group short
--  set: "Do you have difficulty doing any of the following — seeing,
--  hearing, walking or climbing steps, remembering or concentrating,
--  self-care, communicating?") with four degrees and "Prefer not to say".
--  Sahel Horan's list is plain labels, because that workbook named no
--  instrument; the asymmetry is deliberate and recorded (plan 5.8, OQ-54)
--  so nobody harmonises the two later.
-- ═══════════════════════════════════════════════════════════════════════════

do $outer$
declare t text;
begin
  foreach t in array array[
""" % dict(n_lists=n_lists, n_opts=n_opts, n_shared=n_shared, n_free=n_free)

DDL_LOOP = """
  ] loop
    execute format($f$
      create table public.%I (
        id               uuid primary key default gen_random_uuid(),
        code             text not null unique,
        label_en         text not null,
        label_ar         text not null,
        sort_order       int  not null default 0,
        is_active        boolean not null default true,
        allows_free_text boolean not null default false,
        created_at       timestamptz not null default now(),
        updated_at       timestamptz not null default now(),
        created_by       uuid references auth.users(id),
        deleted_at       timestamptz
      )$f$, t);

    perform public.attach_standard_triggers(t);

    execute format('alter table public.%I enable row level security', t);
    execute format($f$create policy ref_read on public.%I
      for select to authenticated using (true)$f$, t);
    execute format($f$create policy ref_write on public.%I
      for all to authenticated
      using (public.is_coordinator())
      with check (public.is_coordinator())$f$, t);
  end loop;
end $outer$;

"""


def insert_sql(key):
    l = lists[key]
    tbl = "ref_khld_" + key
    kind = ' · checklist statuses' if l.is_checklist else (' · cells' if l.is_cells else '')
    o = ["-- ── %s (%s)%s ──\n" % (tbl, ', '.join(l.used_by), kind),
         "insert into public.%s (code, label_en, label_ar, sort_order, allows_free_text) values\n" % tbl]
    rows = []
    for i, (code, en, ar, free) in enumerate(l.options, 1):
        rows.append("  (%s, %s, %s, %d, %s)" % (q(code), q(en), q(ar), i, 'true' if free else 'false'))
    o.append(",\n".join(rows) + ";\n\n")
    return ''.join(o)


keys = list(lists.keys())
third = (len(keys) + 2) // 3
parts = [keys[:third], keys[third:2 * third], keys[2 * third:]]

names = ['ref_khld_' + k for k in keys]
part1 = HEADER + ",\n".join("    " + q(n) for n in names) + DDL_LOOP
part1 += ''.join(insert_sql(k) for k in parts[0])
part1 += """-- ── verification (this part) ─────────────────────────────────────────────
do $verify$
declare v_tables int;
begin
  select count(*) into v_tables from pg_tables where schemaname = 'public' and tablename like 'ref\\_khld\\_%%';
  if v_tables <> %(n)d then
    raise exception '0141: expected %(n)d ref_khld_ tables, found %%', v_tables;
  end if;
end $verify$;
""" % dict(n=n_lists)

part2 = """-- ═══════════════════════════════════════════════════════════════════════════
--  0142 — Khalidiyah's option lists, second third of the rows
--
--  The tables were created by 0141, which says why and how; this file only
--  seeds lists %d to %d of %d. Generated by supabase/khalidiyah/gen_0141.py;
--  do not edit by hand. Verified in 0143.
-- ═══════════════════════════════════════════════════════════════════════════

""" % (third + 1, 2 * third, n_lists) + ''.join(insert_sql(k) for k in parts[1])

VERIFY3 = """-- ── verification, all three parts ────────────────────────────────────────
do $verify$
declare
  v_tables int;
  v_rows   int;
  v_bad    int;
  v_name   text;
begin
  select count(*) into v_tables from pg_tables where schemaname = 'public' and tablename like 'ref\\_khld\\_%%';
  if v_tables <> %(n_lists)d then
    raise exception '0143: expected %(n_lists)d ref_khld_ tables, found %%', v_tables;
  end if;

  v_rows := 0;
  for v_name in select tablename from pg_tables where schemaname = 'public' and tablename like 'ref\\_khld\\_%%' loop
    execute format('select count(*) from public.%%I', v_name) into v_bad;
    if v_bad = 0 then
      raise exception '0143: %% has no rows', v_name;
    end if;
    v_rows := v_rows + v_bad;
    -- RLS on, both policies, all four standard triggers
    if not exists (select 1 from pg_class c where c.relname = v_name and c.relrowsecurity) then
      raise exception '0143: %% has no RLS', v_name;
    end if;
    if (select count(*) from pg_policy p join pg_class c on c.oid = p.polrelid where c.relname = v_name) <> 2 then
      raise exception '0143: %% does not have exactly two policies', v_name;
    end if;
    if (select count(*) from pg_trigger t join pg_class c on c.oid = t.tgrelid where c.relname = v_name and not t.tgisinternal) <> 4 then
      raise exception '0143: %% does not have the four standard triggers', v_name;
    end if;
  end loop;
  if v_rows <> %(n_opts)d then
    raise exception '0143: expected %(n_opts)d option rows, found %%', v_rows;
  end if;

  -- no label is blank, in either language
  v_bad := 0;
  for v_name in select tablename from pg_tables where schemaname = 'public' and tablename like 'ref\\_khld\\_%%' loop
    execute format('select count(*) from public.%%I where btrim(label_en) = %%L or btrim(label_ar) = %%L', v_name, '', '') into v_rows;
    v_bad := v_bad + v_rows;
  end loop;
  if v_bad <> 0 then
    raise exception '0143: %% options have a blank label', v_bad;
  end if;

  -- every checklist-status list has codes that start with a status the
  -- milestone evaluator understands (0145)
  v_bad := 0;
  for v_name in select tablename from pg_tables where schemaname = 'public'
                 and tablename in (%(checklist_tables)s) loop
    execute format('select count(*) from public.%%I where code !~ %%L', v_name, '^(in_place|partly|not_in_place|not_accepted)') into v_rows;
    v_bad := v_bad + v_rows;
  end loop;
  if v_bad <> 0 then
    raise exception '0143: %% checklist options have a code without a status prefix', v_bad;
  end if;
end $verify$;
""" % dict(n_lists=n_lists, n_opts=n_opts,
           checklist_tables=', '.join(q('ref_khld_' + k) for k, l in lists.items() if l.is_checklist))

part3 = """-- ═══════════════════════════════════════════════════════════════════════════
--  0143 — Khalidiyah's option lists, last third of the rows, and the check
--
--  The tables were created by 0141, which says why and how; this file seeds
--  lists %d to %d and then verifies all %d tables and %d rows. Generated by
--  supabase/khalidiyah/gen_0141.py; do not edit by hand.
-- ═══════════════════════════════════════════════════════════════════════════

""" % (2 * third + 1, n_lists, n_lists, n_opts) + ''.join(insert_sql(k) for k in parts[2]) + VERIFY3

for nnnn, name, text in (('0141', 'khalidiyah_option_lists', part1),
                         ('0142', 'khalidiyah_option_lists_2', part2),
                         ('0143', 'khalidiyah_option_lists_3', part3)):
    path = os.path.join(OUT, '%s_%s.sql' % (nnnn, name))
    with io.open(path, 'w', encoding='utf-8', newline='') as fh:
        fh.write(text)
    print('wrote', path, len(text.encode('utf-8')), 'bytes')
print(n_lists, 'lists', n_opts, 'options', n_free, 'free-text options')
