-- ═══════════════════════════════════════════════════════════════════════════
--  0146 — Khalidiyah's domain tables, second part: the other eleven tables
--
--  0145 says why and how; this file continues it. Generated by
--  supabase/khalidiyah/gen_0145.py; do not edit by hand. Verified in 0147.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── khld_volunteer (f2, KHLD-SO3-F2) ──

create table public.khld_volunteer (
  id                    uuid primary key default gen_random_uuid(),
  municipality_id       uuid not null references public.municipality(id) default public.my_municipality(),
  reference             text,
  person_id             uuid not null references public.person(id),
  reg_date              date not null,
  reg_channel_id        uuid not null references public.ref_khld_f2_reg_channel(id),
  guardian_name         text,
  guardian_relationship text,
  guardian_phone        text,
  guardian_consent_given boolean,
  guardian_consent_date date,
  nationality_id        uuid not null references public.ref_khld_nationality(id),
  disability_id         uuid not null references public.ref_khld_disability(id),
  phone_alternative     text,
  neighbourhood_id      uuid not null references public.ref_khld_neighbourhood(id),
  occupation_status_id  uuid references public.ref_khld_f2_occupation_status(id),
  affiliation_id        uuid not null references public.ref_khld_f2_affiliation(id),
  affiliation_other     text,
  hours_per_month       int,
  transport_id          uuid not null references public.ref_khld_f2_transport(id),
  prior_experience_id   uuid references public.ref_khld_f2_prior_experience(id),
  prior_experience_other text,
  how_heard_id          uuid references public.ref_khld_f2_how_heard(id),
  how_heard_other       text,
  consent_data          boolean not null,
  consent_data_recorded_on timestamptz,
  consent_data_recorded_by uuid,
  consent_photo         boolean not null,
  consent_photo_recorded_on timestamptz,
  consent_photo_recorded_by uuid,
  safety_commitment     boolean not null,
  safety_commitment_recorded_on timestamptz,
  safety_commitment_recorded_by uuid,
  signed_by             text,
  signed_on             date,
  registered_by_name    text,
  registered_by_position text,
  registered_by_organisation text,
  registered_on         date,
  entered_by_name       text,
  entered_on            date,
  client_uuid           uuid unique,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid references auth.users(id) default auth.uid(),
  deleted_at            timestamptz,
  constraint khld_volunteer_id_municipality_key unique (id, municipality_id),
  constraint khld_volunteer_reference_key unique (municipality_id, reference)
);
create index khld_volunteer_municipality_idx on public.khld_volunteer (municipality_id);
create index khld_volunteer_created_by_idx on public.khld_volunteer (created_by);
create index khld_volunteer_person_idx on public.khld_volunteer (person_id);
create index khld_volunteer_reg_channel_id_idx on public.khld_volunteer (reg_channel_id);
create index khld_volunteer_nationality_id_idx on public.khld_volunteer (nationality_id);
create index khld_volunteer_disability_id_idx on public.khld_volunteer (disability_id);
create index khld_volunteer_neighbourhood_id_idx on public.khld_volunteer (neighbourhood_id);
create index khld_volunteer_occupation_status_id_idx on public.khld_volunteer (occupation_status_id);
create index khld_volunteer_affiliation_id_idx on public.khld_volunteer (affiliation_id);
create index khld_volunteer_transport_id_idx on public.khld_volunteer (transport_id);
create index khld_volunteer_prior_experience_id_idx on public.khld_volunteer (prior_experience_id);
create index khld_volunteer_how_heard_id_idx on public.khld_volunteer (how_heard_id);
create unique index khld_volunteer_person_key on public.khld_volunteer (municipality_id, person_id);
comment on column public.khld_volunteer.reg_date is 'Date of registration';
comment on column public.khld_volunteer.reg_channel_id is 'Where was the volunteer registered?';
comment on column public.khld_volunteer.guardian_name is 'Guardian name';
comment on column public.khld_volunteer.guardian_relationship is 'Relationship';
comment on column public.khld_volunteer.guardian_phone is 'Phone';
comment on column public.khld_volunteer.guardian_consent_given is 'Written consent obtained';
comment on column public.khld_volunteer.guardian_consent_date is 'date of consent';
comment on column public.khld_volunteer.nationality_id is 'Nationality / status';
comment on column public.khld_volunteer.disability_id is 'Do you have difficulty doing any of the following: seeing, hearing, walking or climbing steps, remembering or concentrating, self-care, communicating?';
comment on column public.khld_volunteer.phone_alternative is 'Alternative';
comment on column public.khld_volunteer.neighbourhood_id is 'Neighbourhood of residence';
comment on column public.khld_volunteer.occupation_status_id is 'Current status';
comment on column public.khld_volunteer.affiliation_id is 'Is the volunteer registering through an institution or group?';
comment on column public.khld_volunteer.affiliation_other is 'free text for affiliation';
comment on column public.khld_volunteer.hours_per_month is 'Approximate hours per month';
comment on column public.khld_volunteer.transport_id is 'Can you reach the park on your own?';
comment on column public.khld_volunteer.prior_experience_id is 'Have you volunteered before?';
comment on column public.khld_volunteer.prior_experience_other is 'free text for prior_experience';
comment on column public.khld_volunteer.how_heard_id is 'How did you hear about the volunteer programme?';
comment on column public.khld_volunteer.how_heard_other is 'free text for how_heard';
comment on column public.khld_volunteer.consent_data is 'Do you agree that your details may be kept in the municipal volunteer register and used to contact you about volunteer activities?';
comment on column public.khld_volunteer.consent_data_recorded_on is 'when consent_data was recorded';
comment on column public.khld_volunteer.consent_data_recorded_by is 'who recorded consent_data';
comment on column public.khld_volunteer.consent_photo is 'Do you agree that photographs taken during volunteer activities may be used in municipal documentation and reports?';
comment on column public.khld_volunteer.consent_photo_recorded_on is 'when consent_photo was recorded';
comment on column public.khld_volunteer.consent_photo_recorded_by is 'who recorded consent_photo';
comment on column public.khld_volunteer.safety_commitment is 'Do you agree to follow the safety instructions given before each task and the arrangements for use of the park?';
comment on column public.khld_volunteer.safety_commitment_recorded_on is 'when safety_commitment was recorded';
comment on column public.khld_volunteer.safety_commitment_recorded_by is 'who recorded safety_commitment';
comment on column public.khld_volunteer.signed_by is 'Volunteer (or guardian for volunteers under 18)';
comment on column public.khld_volunteer.signed_on is 'date';
comment on column public.khld_volunteer.registered_by_name is 'name';
comment on column public.khld_volunteer.registered_by_position is 'position';
comment on column public.khld_volunteer.registered_by_organisation is 'organisation';
comment on column public.khld_volunteer.registered_on is 'date';
comment on column public.khld_volunteer.entered_by_name is 'name';
comment on column public.khld_volunteer.entered_on is 'date';
create trigger trg_khld_volunteer_reference before insert on public.khld_volunteer
  for each row execute function public.khld_assign_reference('VOL', '4');
create trigger trg_khld_volunteer_other before insert or update on public.khld_volunteer
  for each row execute function public.guard_rmth_other(
    'affiliation_id:ref_khld_f2_affiliation:affiliation_other',
    'prior_experience_id:ref_khld_f2_prior_experience:prior_experience_other',
    'how_heard_id:ref_khld_f2_how_heard:how_heard_other');
create trigger trg_khld_volunteer_stamp before insert or update on public.khld_volunteer
  for each row execute function public.khld_stamp_recorded('consent_data', 'consent_photo', 'safety_commitment');
create trigger trg_khld_volunteer_guardian before insert or update on public.khld_volunteer
  for each row execute function public.guard_khld_guardian();
alter table public.khld_volunteer add constraint khld_volunteer_consent_data_given check (consent_data is true);
alter table public.khld_volunteer add constraint khld_volunteer_safety_commitment_given check (safety_commitment is true);

create table public.khld_volunteer_option (
  volunteer_id     uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  question_code    text not null,
  option_id        uuid not null,
  option_other     text,
  created_at       timestamptz not null default now(),
  primary key (volunteer_id, question_code, option_id),
  constraint khld_volunteer_option_volunteer_id_fkey foreign key (volunteer_id, municipality_id) references public.khld_volunteer(id, municipality_id)
);
create index khld_volunteer_option_municipality_idx on public.khld_volunteer_option (municipality_id);
create trigger trg_khld_volunteer_option_guard before insert or update on public.khld_volunteer_option
  for each row execute function public.guard_khld_option();

-- ── khld_attendance (d2, KHLD-SO2-D2) ──

create table public.khld_attendance (
  id                    uuid primary key default gen_random_uuid(),
  municipality_id       uuid not null references public.municipality(id) default public.my_municipality(),
  activity_id           uuid not null,
  count_method_id       uuid not null references public.ref_khld_d2_count_method(id),
  estimate_by           text,
  estimate_basis        text,
  counters              text not null,
  total_participants    int not null,
  pwd_count             int,
  mothers_children      int,
  first_time            int,
  staff_volunteers      int not null,
  staff_municipal       int,
  staff_partner         int,
  register_attached_id  uuid not null references public.ref_khld_d2_register_attached(id),
  register_attached_other text,
  consent_informed_id   uuid not null references public.ref_khld_d2_consent_informed(id),
  consent_informed_recorded_on timestamptz,
  consent_informed_recorded_by uuid,
  photo_consent_id      uuid not null references public.ref_khld_d2_photo_consent(id),
  photo_consent_recorded_on timestamptz,
  photo_consent_recorded_by uuid,
  duplicate_check_id    uuid not null references public.ref_khld_d2_duplicate_check(id),
  repeat_participants   int,
  entered_by_name       text,
  entered_on            date,
  notes                 text,
  client_uuid           uuid unique,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid references auth.users(id) default auth.uid(),
  deleted_at            timestamptz,
  constraint khld_attendance_id_municipality_key unique (id, municipality_id),
  constraint khld_attendance_activity_id_fkey foreign key (activity_id, municipality_id) references public.khld_activity(id, municipality_id)
);
create index khld_attendance_municipality_idx on public.khld_attendance (municipality_id);
create index khld_attendance_created_by_idx on public.khld_attendance (created_by);
create index khld_attendance_activity_id_idx on public.khld_attendance (activity_id);
create index khld_attendance_count_method_id_idx on public.khld_attendance (count_method_id);
create index khld_attendance_register_attached_id_idx on public.khld_attendance (register_attached_id);
create index khld_attendance_consent_informed_id_idx on public.khld_attendance (consent_informed_id);
create index khld_attendance_photo_consent_id_idx on public.khld_attendance (photo_consent_id);
create index khld_attendance_duplicate_check_id_idx on public.khld_attendance (duplicate_check_id);
create unique index khld_attendance_activity_live on public.khld_attendance (activity_id) where deleted_at is null;
comment on column public.khld_attendance.activity_id is 'Activity reference number (must match form KHLD-SO2-D1)';
comment on column public.khld_attendance.count_method_id is 'Which counting method was used?';
comment on column public.khld_attendance.estimate_by is 'Name and position';
comment on column public.khld_attendance.estimate_basis is 'Basis (e.g. count of seating areas, photographs, average per station)';
comment on column public.khld_attendance.counters is 'Names of the persons who carried out the count';
comment on column public.khld_attendance.total_participants is 'Total number of participants';
comment on column public.khld_attendance.pwd_count is 'Number of participants with a disability';
comment on column public.khld_attendance.mothers_children is 'Number of mothers attending with children';
comment on column public.khld_attendance.first_time is 'Number of participants attending a park activity for the first time';
comment on column public.khld_attendance.staff_volunteers is 'Volunteers';
comment on column public.khld_attendance.staff_municipal is 'Municipal staff';
comment on column public.khld_attendance.staff_partner is 'Partner staff';
comment on column public.khld_attendance.register_attached_id is 'Is an individual attendance register attached (name, sex, age, nationality, signature)?';
comment on column public.khld_attendance.register_attached_other is 'free text for register_attached';
comment on column public.khld_attendance.consent_informed_id is 'Were participants told how their data would be used?';
comment on column public.khld_attendance.consent_informed_recorded_on is 'when consent_informed was recorded';
comment on column public.khld_attendance.consent_informed_recorded_by is 'who recorded consent_informed';
comment on column public.khld_attendance.photo_consent_id is 'Was consent obtained for photography, including guardian consent for children?';
comment on column public.khld_attendance.photo_consent_recorded_on is 'when photo_consent was recorded';
comment on column public.khld_attendance.photo_consent_recorded_by is 'who recorded photo_consent';
comment on column public.khld_attendance.duplicate_check_id is 'Yes / No — not yet done / Not possible with this counting method';
comment on column public.khld_attendance.repeat_participants is 'number of repeat participants identified';
comment on column public.khld_attendance.entered_by_name is 'name';
comment on column public.khld_attendance.entered_on is 'date';
comment on column public.khld_attendance.notes is 'Notes';
create trigger trg_khld_attendance_other before insert or update on public.khld_attendance
  for each row execute function public.guard_rmth_other(
    'register_attached_id:ref_khld_d2_register_attached:register_attached_other');
create trigger trg_khld_attendance_stamp before insert or update on public.khld_attendance
  for each row execute function public.khld_stamp_recorded('consent_informed_id:consent_informed', 'photo_consent_id:photo_consent');

create table public.khld_attendance_count (
  attendance_id    uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  field_code       text not null,
  cell_id          uuid not null,
  count            int not null check (count >= 0),
  created_at       timestamptz not null default now(),
  primary key (attendance_id, field_code, cell_id),
  constraint khld_attendance_count_attendance_id_fkey foreign key (attendance_id, municipality_id) references public.khld_attendance(id, municipality_id)
);
create index khld_attendance_count_municipality_idx on public.khld_attendance_count (municipality_id);
create trigger trg_khld_attendance_count_guard before insert or update on public.khld_attendance_count
  for each row execute function public.guard_khld_count();

-- ── khld_guidance_completion (g1, KHLD-SO4-G1) ──

create table public.khld_guidance_completion (
  id                    uuid primary key default gen_random_uuid(),
  municipality_id       uuid not null references public.municipality(id) default public.my_municipality(),
  sessions_attended_count int,
  completion            text check (completion in ('completed', 'not_completed', 'not_yet_decided')),
  enterprise_id         uuid not null,
  cycle_reference       text,
  cycle_year            uuid references public.ref_khld_g1_cycle_year(id),
  age_group_id          uuid not null references public.ref_khld_age_group(id),
  nationality_id        uuid not null references public.ref_khld_nationality(id),
  disability_id         uuid references public.ref_khld_disability(id),
  neighbourhood_id      uuid references public.ref_khld_neighbourhood(id),
  enterprise_name       text,
  enterprise_status_id  uuid not null references public.ref_khld_g1_enterprise_status(id),
  workers_total         int,
  workers_women         int,
  workers_under_30      int,
  s1_status_id          uuid references public.ref_khld_session_attendance(id),
  s1_date               date,
  s2_status_id          uuid references public.ref_khld_session_attendance(id),
  s2_date               date,
  s3_status_id          uuid references public.ref_khld_g1_s3_hygiene(id),
  s3_date               date,
  s4_status_id          uuid references public.ref_khld_session_attendance(id),
  s4_date               date,
  s5_status_id          uuid references public.ref_khld_session_attendance(id),
  s5_date               date,
  extra_sessions        text,
  non_completion_reason_id uuid not null references public.ref_khld_g1_non_completion_reason(id),
  non_completion_reason_other text,
  venue_id              uuid references public.ref_khld_g1_venue(id),
  venue_other           text,
  most_useful_id        uuid references public.ref_khld_g1_most_useful(id),
  knowledge_check_done  boolean,
  knowledge_score       int,
  knowledge_score_of    int,
  peer_network_id       uuid not null references public.ref_khld_g1_peer_network(id),
  referral_made_id      uuid not null references public.ref_khld_g1_referral_made(id),
  referral_made_other   text,
  certificate_id        uuid not null references public.ref_khld_g1_certificate(id),
  certificate_other     text,
  recorded_by_name      text,
  recorded_by_position  text,
  recorded_on           date,
  client_uuid           uuid unique,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid references auth.users(id) default auth.uid(),
  deleted_at            timestamptz,
  constraint khld_guidance_completion_id_municipality_key unique (id, municipality_id),
  constraint khld_guidance_completion_enterprise_id_fkey foreign key (enterprise_id, municipality_id) references public.khld_enterprise(id, municipality_id)
);
create index khld_guidance_completion_municipality_idx on public.khld_guidance_completion (municipality_id);
create index khld_guidance_completion_created_by_idx on public.khld_guidance_completion (created_by);
create index khld_guidance_completion_enterprise_id_idx on public.khld_guidance_completion (enterprise_id);
create index khld_guidance_completion_cycle_year_idx on public.khld_guidance_completion (cycle_year);
create index khld_guidance_completion_age_group_id_idx on public.khld_guidance_completion (age_group_id);
create index khld_guidance_completion_nationality_id_idx on public.khld_guidance_completion (nationality_id);
create index khld_guidance_completion_disability_id_idx on public.khld_guidance_completion (disability_id);
create index khld_guidance_completion_neighbourhood_id_idx on public.khld_guidance_completion (neighbourhood_id);
create index khld_guidance_completion_enterprise_status_id_idx on public.khld_guidance_completion (enterprise_status_id);
create index khld_guidance_completion_s1_status_id_idx on public.khld_guidance_completion (s1_status_id);
create index khld_guidance_completion_s2_status_id_idx on public.khld_guidance_completion (s2_status_id);
create index khld_guidance_completion_s3_status_id_idx on public.khld_guidance_completion (s3_status_id);
create index khld_guidance_completion_s4_status_id_idx on public.khld_guidance_completion (s4_status_id);
create index khld_guidance_completion_s5_status_id_idx on public.khld_guidance_completion (s5_status_id);
create index khld_guidance_completion_non_completion_reason_id_idx on public.khld_guidance_completion (non_completion_reason_id);
create index khld_guidance_completion_venue_id_idx on public.khld_guidance_completion (venue_id);
create index khld_guidance_completion_most_useful_id_idx on public.khld_guidance_completion (most_useful_id);
create index khld_guidance_completion_peer_network_id_idx on public.khld_guidance_completion (peer_network_id);
create index khld_guidance_completion_referral_made_id_idx on public.khld_guidance_completion (referral_made_id);
create index khld_guidance_completion_certificate_id_idx on public.khld_guidance_completion (certificate_id);
create unique index khld_guidance_completion_enterprise_year_live on public.khld_guidance_completion (enterprise_id, cycle_year) where deleted_at is null;
comment on column public.khld_guidance_completion.enterprise_id is 'Enterprise ID';
comment on column public.khld_guidance_completion.cycle_reference is 'Cycle reference';
comment on column public.khld_guidance_completion.cycle_year is 'Year';
comment on column public.khld_guidance_completion.age_group_id is 'Age group';
comment on column public.khld_guidance_completion.nationality_id is 'Nationality / status';
comment on column public.khld_guidance_completion.disability_id is 'Disability status';
comment on column public.khld_guidance_completion.neighbourhood_id is 'Neighbourhood';
comment on column public.khld_guidance_completion.enterprise_name is 'Trade or product name, if the enterprise has one';
comment on column public.khld_guidance_completion.enterprise_status_id is 'Status of the enterprise at the start of the guidance cycle';
comment on column public.khld_guidance_completion.workers_total is 'Total';
comment on column public.khld_guidance_completion.workers_women is 'Of whom women';
comment on column public.khld_guidance_completion.workers_under_30 is 'Of whom under 30';
comment on column public.khld_guidance_completion.s1_status_id is 'Session 1 — Small business basics: costing, pricing and simple record keeping';
comment on column public.khld_guidance_completion.s1_date is 'date of session 1';
comment on column public.khld_guidance_completion.s2_status_id is 'Session 2 — Licensing and registration requirements for a home-based business';
comment on column public.khld_guidance_completion.s2_date is 'date of session 2';
comment on column public.khld_guidance_completion.s3_status_id is 'Session 3 — Hygiene, food safety and health and safety standards';
comment on column public.khld_guidance_completion.s3_date is 'date of session 3';
comment on column public.khld_guidance_completion.s4_status_id is 'Session 4 — Packaging, labelling and product presentation';
comment on column public.khld_guidance_completion.s4_date is 'date of session 4';
comment on column public.khld_guidance_completion.s5_status_id is 'Session 5 — Marketing, selling channels and market days';
comment on column public.khld_guidance_completion.s5_date is 'date of session 5';
comment on column public.khld_guidance_completion.extra_sessions is 'Any additional or optional sessions attended';
comment on column public.khld_guidance_completion.non_completion_reason_id is 'If the cycle was not completed, what was the main reason?';
comment on column public.khld_guidance_completion.non_completion_reason_other is 'free text for non_completion_reason';
comment on column public.khld_guidance_completion.venue_id is 'Where were the sessions held?';
comment on column public.khld_guidance_completion.venue_other is 'free text for venue';
comment on column public.khld_guidance_completion.most_useful_id is 'Which topic did the owner find most useful?';
comment on column public.khld_guidance_completion.knowledge_check_done is 'Yes / No';
comment on column public.khld_guidance_completion.knowledge_score is 'score';
comment on column public.khld_guidance_completion.knowledge_score_of is 'out of';
comment on column public.khld_guidance_completion.peer_network_id is 'Was the owner enrolled in the peer-to-peer exchange network among producers?';
comment on column public.khld_guidance_completion.referral_made_id is 'Was the owner referred to another organisation or programme?';
comment on column public.khld_guidance_completion.referral_made_other is 'free text for referral_made';
comment on column public.khld_guidance_completion.certificate_id is 'Was a certificate of completion issued?';
comment on column public.khld_guidance_completion.certificate_other is 'free text for certificate';
comment on column public.khld_guidance_completion.recorded_by_name is 'name';
comment on column public.khld_guidance_completion.recorded_by_position is 'position';
comment on column public.khld_guidance_completion.recorded_on is 'date';
create trigger trg_khld_guidance_completion_other before insert or update on public.khld_guidance_completion
  for each row execute function public.guard_rmth_other(
    'non_completion_reason_id:ref_khld_g1_non_completion_reason:non_completion_reason_other',
    'venue_id:ref_khld_g1_venue:venue_other',
    'referral_made_id:ref_khld_g1_referral_made:referral_made_other',
    'certificate_id:ref_khld_g1_certificate:certificate_other');
create trigger trg_khld_guidance_completion_derive before insert or update on public.khld_guidance_completion
  for each row execute function public.khld_derive_completion();

create table public.khld_guidance_completion_option (
  completion_id    uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  question_code    text not null,
  option_id        uuid not null,
  option_other     text,
  created_at       timestamptz not null default now(),
  primary key (completion_id, question_code, option_id),
  constraint khld_guidance_completion_option_completion_id_fkey foreign key (completion_id, municipality_id) references public.khld_guidance_completion(id, municipality_id)
);
create index khld_guidance_completion_option_municipality_idx on public.khld_guidance_completion_option (municipality_id);
create trigger trg_khld_guidance_completion_option_guard before insert or update on public.khld_guidance_completion_option
  for each row execute function public.guard_khld_option();

-- ── khld_enterprise_support (g2, KHLD-SO4-G2) ──

create table public.khld_enterprise_support (
  id                    uuid primary key default gen_random_uuid(),
  municipality_id       uuid not null references public.municipality(id) default public.my_municipality(),
  support_types_count   int,
  enterprise_id         uuid not null,
  first_support_date    date not null,
  sex_id                uuid not null references public.ref_khld_sex(id),
  age_group_id          uuid not null references public.ref_khld_age_group(id),
  nationality_id        uuid not null references public.ref_khld_nationality(id),
  disability_id         uuid references public.ref_khld_disability(id),
  sup_guidance          boolean not null,
  sup_guidance_sessions int,
  sup_guidance_dates    text,
  sup_guidance_provider text,
  sup_licensing_info    boolean not null,
  sup_licensing_info_date date,
  sup_licensing_info_provider text,
  sup_hygiene_id        uuid not null references public.ref_khld_g2_sup_hygiene(id),
  sup_hygiene_date      date,
  sup_hygiene_provider  text,
  sup_referral          boolean not null,
  sup_referral_entity   text,
  sup_referral_purpose  text,
  sup_referral_date     date,
  sup_referral_outcome_id uuid references public.ref_khld_g2_sup_referral_outcome(id),
  sup_peer_network      boolean not null,
  sup_peer_network_date date,
  sup_peer_network_meetings int,
  sup_market_access     boolean not null,
  sup_market_access_refs text,
  sup_market_access_count int,
  sup_inkind            boolean,
  sup_inkind_description text,
  sup_marketing         boolean,
  sup_marketing_description text,
  sup_site_visit        boolean,
  sup_site_visit_count  int,
  sup_site_visit_dates  text,
  sup_other             text,
  status_last_contact_id uuid not null references public.ref_khld_g2_status_last_contact(id),
  outstanding_needs     text not null,
  entered_by_name       text,
  entered_by_organisation text,
  entered_on            date,
  consolidated_by_name  text,
  consolidated_on       date,
  client_uuid           uuid unique,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid references auth.users(id) default auth.uid(),
  deleted_at            timestamptz,
  constraint khld_enterprise_support_id_municipality_key unique (id, municipality_id),
  constraint khld_enterprise_support_enterprise_id_fkey foreign key (enterprise_id, municipality_id) references public.khld_enterprise(id, municipality_id)
);
create index khld_enterprise_support_municipality_idx on public.khld_enterprise_support (municipality_id);
create index khld_enterprise_support_created_by_idx on public.khld_enterprise_support (created_by);
create index khld_enterprise_support_enterprise_id_idx on public.khld_enterprise_support (enterprise_id);
create index khld_enterprise_support_sex_id_idx on public.khld_enterprise_support (sex_id);
create index khld_enterprise_support_age_group_id_idx on public.khld_enterprise_support (age_group_id);
create index khld_enterprise_support_nationality_id_idx on public.khld_enterprise_support (nationality_id);
create index khld_enterprise_support_disability_id_idx on public.khld_enterprise_support (disability_id);
create index khld_enterprise_support_sup_hygiene_id_idx on public.khld_enterprise_support (sup_hygiene_id);
create index khld_enterprise_support_sup_referral_outcome_id_idx on public.khld_enterprise_support (sup_referral_outcome_id);
create index khld_enterprise_support_status_last_contact_id_idx on public.khld_enterprise_support (status_last_contact_id);
create unique index khld_enterprise_support_enterprise_live on public.khld_enterprise_support (enterprise_id) where deleted_at is null;
comment on column public.khld_enterprise_support.enterprise_id is 'Enterprise ID';
comment on column public.khld_enterprise_support.first_support_date is 'Date of the first support received under the Plan';
comment on column public.khld_enterprise_support.sex_id is 'Sex';
comment on column public.khld_enterprise_support.age_group_id is 'Age group';
comment on column public.khld_enterprise_support.nationality_id is 'Nationality / status';
comment on column public.khld_enterprise_support.disability_id is 'Disability status';
comment on column public.khld_enterprise_support.sup_guidance is 'Yes / No';
comment on column public.khld_enterprise_support.sup_guidance_sessions is 'number of sessions';
comment on column public.khld_enterprise_support.sup_guidance_dates is 'Dates';
comment on column public.khld_enterprise_support.sup_guidance_provider is 'Provider';
comment on column public.khld_enterprise_support.sup_licensing_info is 'Yes / No';
comment on column public.khld_enterprise_support.sup_licensing_info_date is 'date';
comment on column public.khld_enterprise_support.sup_licensing_info_provider is 'Provider';
comment on column public.khld_enterprise_support.sup_hygiene_id is 'Yes / No / Not applicable — non-food products';
comment on column public.khld_enterprise_support.sup_hygiene_date is 'date';
comment on column public.khld_enterprise_support.sup_hygiene_provider is 'Provider';
comment on column public.khld_enterprise_support.sup_referral is 'Yes / No';
comment on column public.khld_enterprise_support.sup_referral_entity is 'entity';
comment on column public.khld_enterprise_support.sup_referral_purpose is 'Purpose';
comment on column public.khld_enterprise_support.sup_referral_date is 'Date';
comment on column public.khld_enterprise_support.sup_referral_outcome_id is 'Outcome';
comment on column public.khld_enterprise_support.sup_peer_network is 'Yes / No';
comment on column public.khld_enterprise_support.sup_peer_network_date is 'date';
comment on column public.khld_enterprise_support.sup_peer_network_meetings is 'Number of exchange meetings attended';
comment on column public.khld_enterprise_support.sup_market_access is 'Yes / No';
comment on column public.khld_enterprise_support.sup_market_access_refs is 'market day references';
comment on column public.khld_enterprise_support.sup_market_access_count is 'Number of markets';
comment on column public.khld_enterprise_support.sup_inkind is 'Yes / No';
comment on column public.khld_enterprise_support.sup_inkind_description is 'describe, with estimated value in JOD and provider';
comment on column public.khld_enterprise_support.sup_marketing is 'Yes / No';
comment on column public.khld_enterprise_support.sup_marketing_description is 'describe';
comment on column public.khld_enterprise_support.sup_site_visit is 'Yes / No';
comment on column public.khld_enterprise_support.sup_site_visit_count is 'number of visits';
comment on column public.khld_enterprise_support.sup_site_visit_dates is 'Dates';
comment on column public.khld_enterprise_support.sup_other is 'Any other support provided';
comment on column public.khld_enterprise_support.status_last_contact_id is 'Status of the enterprise at the last contact';
comment on column public.khld_enterprise_support.outstanding_needs is 'Outstanding needs and the support planned next';
comment on column public.khld_enterprise_support.entered_by_name is 'name';
comment on column public.khld_enterprise_support.entered_by_organisation is 'organisation';
comment on column public.khld_enterprise_support.entered_on is 'date';
comment on column public.khld_enterprise_support.consolidated_by_name is 'name';
comment on column public.khld_enterprise_support.consolidated_on is 'date';
create trigger trg_khld_enterprise_support_derive before insert or update on public.khld_enterprise_support
  for each row execute function public.khld_derive_support_types();

create table public.khld_enterprise_support_option (
  support_id       uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  question_code    text not null,
  option_id        uuid not null,
  option_other     text,
  created_at       timestamptz not null default now(),
  primary key (support_id, question_code, option_id),
  constraint khld_enterprise_support_option_support_id_fkey foreign key (support_id, municipality_id) references public.khld_enterprise_support(id, municipality_id)
);
create index khld_enterprise_support_option_municipality_idx on public.khld_enterprise_support_option (municipality_id);
create trigger trg_khld_enterprise_support_option_guard before insert or update on public.khld_enterprise_support_option
  for each row execute function public.guard_khld_option();

-- ── khld_vendor_registration (h2, KHLD-SO4-H2) ──

create table public.khld_vendor_registration (
  id                    uuid primary key default gen_random_uuid(),
  municipality_id       uuid not null references public.municipality(id) default public.my_municipality(),
  vendor_id             uuid not null,
  market_id             uuid not null,
  enterprise_id         uuid,
  nationality_id        uuid not null references public.ref_khld_nationality(id),
  disability_id         uuid not null references public.ref_khld_disability(id),
  neighbourhood_id      uuid not null references public.ref_khld_neighbourhood(id),
  vendor_type_id        uuid not null references public.ref_khld_h2_vendor_type(id),
  vendor_type_other     text,
  licensed_id           uuid not null references public.ref_khld_h2_licensed(id),
  licensed_other        text,
  health_certificate_id uuid not null references public.ref_khld_h2_health_certificate(id),
  health_certificate_other text,
  first_organised_market boolean not null,
  nominated_by_id       uuid not null references public.ref_khld_h2_nominated_by(id),
  stall_number          text not null,
  stall_free            boolean not null,
  stall_fee_jod         numeric(12,3),
  commitment_signed_id  uuid not null references public.ref_khld_h2_commitment_signed(id),
  attended_id           uuid not null references public.ref_khld_h2_attended(id),
  attended_other        text,
  sales_band_id         uuid references public.ref_khld_sales_band(id),
  consent_id            uuid not null references public.ref_khld_h2_consent(id),
  consent_recorded_on   timestamptz,
  consent_recorded_by   uuid,
  signed_by             text,
  signed_on             date,
  registered_by_name    text,
  registered_by_organisation text,
  registered_on         date,
  notes                 text,
  client_uuid           uuid unique,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid references auth.users(id) default auth.uid(),
  deleted_at            timestamptz,
  constraint khld_vendor_registration_id_municipality_key unique (id, municipality_id),
  constraint khld_vendor_registration_vendor_id_fkey foreign key (vendor_id, municipality_id) references public.khld_vendor(id, municipality_id),
  constraint khld_vendor_registration_market_id_fkey foreign key (market_id, municipality_id) references public.khld_market(id, municipality_id),
  constraint khld_vendor_registration_enterprise_id_fkey foreign key (enterprise_id, municipality_id) references public.khld_enterprise(id, municipality_id)
);
create index khld_vendor_registration_municipality_idx on public.khld_vendor_registration (municipality_id);
create index khld_vendor_registration_created_by_idx on public.khld_vendor_registration (created_by);
create index khld_vendor_registration_vendor_id_idx on public.khld_vendor_registration (vendor_id);
create index khld_vendor_registration_market_id_idx on public.khld_vendor_registration (market_id);
create index khld_vendor_registration_enterprise_id_idx on public.khld_vendor_registration (enterprise_id);
create index khld_vendor_registration_nationality_id_idx on public.khld_vendor_registration (nationality_id);
create index khld_vendor_registration_disability_id_idx on public.khld_vendor_registration (disability_id);
create index khld_vendor_registration_neighbourhood_id_idx on public.khld_vendor_registration (neighbourhood_id);
create index khld_vendor_registration_vendor_type_id_idx on public.khld_vendor_registration (vendor_type_id);
create index khld_vendor_registration_licensed_id_idx on public.khld_vendor_registration (licensed_id);
create index khld_vendor_registration_health_certificate_id_idx on public.khld_vendor_registration (health_certificate_id);
create index khld_vendor_registration_nominated_by_id_idx on public.khld_vendor_registration (nominated_by_id);
create index khld_vendor_registration_commitment_signed_id_idx on public.khld_vendor_registration (commitment_signed_id);
create index khld_vendor_registration_attended_id_idx on public.khld_vendor_registration (attended_id);
create index khld_vendor_registration_sales_band_id_idx on public.khld_vendor_registration (sales_band_id);
create index khld_vendor_registration_consent_id_idx on public.khld_vendor_registration (consent_id);
create unique index khld_vendor_registration_market_vendor_live on public.khld_vendor_registration (market_id, vendor_id) where deleted_at is null;
comment on column public.khld_vendor_registration.vendor_id is 'The vendor this registration is for (SO4-H2 fields 2-3: found or created from the identifier)';
comment on column public.khld_vendor_registration.market_id is 'Market reference number and date (must match form 21)';
comment on column public.khld_vendor_registration.enterprise_id is 'Enterprise ID, if the vendor is already in the enterprise support log';
comment on column public.khld_vendor_registration.nationality_id is 'Nationality / status';
comment on column public.khld_vendor_registration.disability_id is 'Do you have difficulty doing any of the following: seeing, hearing, walking or climbing steps, remembering or concentrating, self-care, communicating?';
comment on column public.khld_vendor_registration.neighbourhood_id is 'Neighbourhood of residence';
comment on column public.khld_vendor_registration.vendor_type_id is 'Type of vendor';
comment on column public.khld_vendor_registration.vendor_type_other is 'free text for vendor_type';
comment on column public.khld_vendor_registration.licensed_id is 'Is the activity licensed or registered?';
comment on column public.khld_vendor_registration.licensed_other is 'free text for licensed';
comment on column public.khld_vendor_registration.health_certificate_id is 'For food products: does the vendor hold a health certificate or food safety approval?';
comment on column public.khld_vendor_registration.health_certificate_other is 'free text for health_certificate';
comment on column public.khld_vendor_registration.first_organised_market is 'Is this the vendor''s first time participating in an organised market or exhibition?';
comment on column public.khld_vendor_registration.nominated_by_id is 'How did the vendor come to participate?';
comment on column public.khld_vendor_registration.stall_number is 'Stall or space number allocated';
comment on column public.khld_vendor_registration.stall_free is 'Yes — free of charge / No — fee paid';
comment on column public.khld_vendor_registration.stall_fee_jod is 'fee paid (JOD)';
comment on column public.khld_vendor_registration.commitment_signed_id is 'Has the vendor signed the commitment to hygiene, safety and fair pricing standards?';
comment on column public.khld_vendor_registration.attended_id is 'Did the vendor actually attend on the day?';
comment on column public.khld_vendor_registration.attended_other is 'free text for attended';
comment on column public.khld_vendor_registration.sales_band_id is 'Approximate sales on the day (optional, asked at the end of the market)';
comment on column public.khld_vendor_registration.consent_id is 'Does the vendor consent to their details being kept in the municipal producer register and to being contacted for a follow-up survey, and to photographs being used in municipal reports?';
comment on column public.khld_vendor_registration.consent_recorded_on is 'when consent was recorded';
comment on column public.khld_vendor_registration.consent_recorded_by is 'who recorded consent';
comment on column public.khld_vendor_registration.signed_by is 'Vendor';
comment on column public.khld_vendor_registration.signed_on is 'date';
comment on column public.khld_vendor_registration.registered_by_name is 'name';
comment on column public.khld_vendor_registration.registered_by_organisation is 'organisation';
comment on column public.khld_vendor_registration.registered_on is 'date';
comment on column public.khld_vendor_registration.notes is 'Notes';
create trigger trg_khld_vendor_registration_other before insert or update on public.khld_vendor_registration
  for each row execute function public.guard_rmth_other(
    'vendor_type_id:ref_khld_h2_vendor_type:vendor_type_other',
    'licensed_id:ref_khld_h2_licensed:licensed_other',
    'health_certificate_id:ref_khld_h2_health_certificate:health_certificate_other',
    'attended_id:ref_khld_h2_attended:attended_other');
create trigger trg_khld_vendor_registration_stamp before insert or update on public.khld_vendor_registration
  for each row execute function public.khld_stamp_recorded('consent_id:consent');

create table public.khld_vendor_registration_option (
  registration_id  uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  question_code    text not null,
  option_id        uuid not null,
  option_other     text,
  created_at       timestamptz not null default now(),
  primary key (registration_id, question_code, option_id),
  constraint khld_vendor_registration_option_registration_id_fkey foreign key (registration_id, municipality_id) references public.khld_vendor_registration(id, municipality_id)
);
create index khld_vendor_registration_option_municipality_idx on public.khld_vendor_registration_option (municipality_id);
create trigger trg_khld_vendor_registration_option_guard before insert or update on public.khld_vendor_registration_option
  for each row execute function public.guard_khld_option();

-- ── khld_interaction_survey (imp0, KHLD-IMP-0) ──

create table public.khld_interaction_survey (
  id                    uuid primary key default gen_random_uuid(),
  municipality_id       uuid not null references public.municipality(id) default public.my_municipality(),
  int_date              date not null,
  survey_round_id       uuid not null references public.ref_khld_imp0_survey_round(id),
  enum_name             text not null,
  int_place_id          uuid not null references public.ref_khld_imp0_int_place(id),
  consent_id            uuid not null references public.ref_khld_imp0_consent(id),
  sex_id                uuid not null references public.ref_khld_sex(id),
  age_group_id          uuid not null references public.ref_khld_age_group(id),
  nationality_id        uuid not null references public.ref_khld_nationality(id),
  disability_id         uuid not null references public.ref_khld_disability(id),
  neighbourhood_id      uuid not null references public.ref_khld_neighbourhood(id),
  has_children_id       uuid not null references public.ref_khld_imp0_has_children(id),
  children_count        int,
  visit_freq_id         uuid not null references public.ref_khld_imp0_visit_freq(id),
  mixed_presence_id     uuid references public.ref_khld_imp0_mixed_presence(id),
  new_contact_id        uuid references public.ref_khld_imp0_new_contact(id),
  opportunity_increase_id uuid references public.ref_khld_agree_scale(id),
  joint_activity_id     uuid references public.ref_khld_imp0_joint_activity(id),
  comfort_level_id      uuid references public.ref_khld_imp0_comfort_level(id),
  suitable_women_children_id uuid not null references public.ref_khld_yes_fully_partly_no(id),
  relations_change_id   uuid not null references public.ref_khld_imp0_relations_change(id),
  change_narrative      text not null,
  suggestions           text,
  recontact_id          uuid not null references public.ref_khld_recontact(id),
  recontact_other       text,
  enum_notes            text,
  client_uuid           uuid unique,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid references auth.users(id) default auth.uid(),
  deleted_at            timestamptz,
  constraint khld_interaction_survey_id_municipality_key unique (id, municipality_id)
);
create index khld_interaction_survey_municipality_idx on public.khld_interaction_survey (municipality_id);
create index khld_interaction_survey_created_by_idx on public.khld_interaction_survey (created_by);
create index khld_interaction_survey_survey_round_id_idx on public.khld_interaction_survey (survey_round_id);
create index khld_interaction_survey_int_place_id_idx on public.khld_interaction_survey (int_place_id);
create index khld_interaction_survey_consent_id_idx on public.khld_interaction_survey (consent_id);
create index khld_interaction_survey_sex_id_idx on public.khld_interaction_survey (sex_id);
create index khld_interaction_survey_age_group_id_idx on public.khld_interaction_survey (age_group_id);
create index khld_interaction_survey_nationality_id_idx on public.khld_interaction_survey (nationality_id);
create index khld_interaction_survey_disability_id_idx on public.khld_interaction_survey (disability_id);
create index khld_interaction_survey_neighbourhood_id_idx on public.khld_interaction_survey (neighbourhood_id);
create index khld_interaction_survey_has_children_id_idx on public.khld_interaction_survey (has_children_id);
create index khld_interaction_survey_visit_freq_id_idx on public.khld_interaction_survey (visit_freq_id);
create index khld_interaction_survey_mixed_presence_id_idx on public.khld_interaction_survey (mixed_presence_id);
create index khld_interaction_survey_new_contact_id_idx on public.khld_interaction_survey (new_contact_id);
create index khld_interaction_survey_opportunity_increase_id_idx on public.khld_interaction_survey (opportunity_increase_id);
create index khld_interaction_survey_joint_activity_id_idx on public.khld_interaction_survey (joint_activity_id);
create index khld_interaction_survey_comfort_level_id_idx on public.khld_interaction_survey (comfort_level_id);
create index khld_interaction_survey_suitable_women_children_id_idx on public.khld_interaction_survey (suitable_women_children_id);
create index khld_interaction_survey_relations_change_id_idx on public.khld_interaction_survey (relations_change_id);
create index khld_interaction_survey_recontact_id_idx on public.khld_interaction_survey (recontact_id);
comment on column public.khld_interaction_survey.int_date is 'Date of interview';
comment on column public.khld_interaction_survey.survey_round_id is 'Which annual survey round is this?';
comment on column public.khld_interaction_survey.enum_name is 'Enumerator name';
comment on column public.khld_interaction_survey.int_place_id is 'Where was the respondent interviewed?';
comment on column public.khld_interaction_survey.consent_id is 'Consent read and respondent agrees to take part';
comment on column public.khld_interaction_survey.sex_id is 'Sex of respondent';
comment on column public.khld_interaction_survey.age_group_id is 'Age group';
comment on column public.khld_interaction_survey.nationality_id is 'Nationality / status';
comment on column public.khld_interaction_survey.disability_id is 'Do you have difficulty doing any of the following: seeing, hearing, walking or climbing steps, remembering or concentrating, self-care, communicating?';
comment on column public.khld_interaction_survey.neighbourhood_id is 'Neighbourhood of residence';
comment on column public.khld_interaction_survey.has_children_id is 'Yes — number / No';
comment on column public.khld_interaction_survey.children_count is 'number';
comment on column public.khld_interaction_survey.visit_freq_id is 'In the last 12 months, how often have you visited Al Khalidiyah Public Park?';
comment on column public.khld_interaction_survey.mixed_presence_id is 'During your visits, were people from both the host community and the Syrian refugee community present?';
comment on column public.khld_interaction_survey.new_contact_id is 'During park activities, did you talk to or spend time with people from the other community whom you did not know before?';
comment on column public.khld_interaction_survey.opportunity_increase_id is 'The park gives residents more opportunities to meet and take part in shared community activities than they had before. Do you agree?';
comment on column public.khld_interaction_survey.joint_activity_id is 'Have you taken part in any activity in the park where residents from both communities organised or worked on something together (volunteer day, market, children''s event)?';
comment on column public.khld_interaction_survey.comfort_level_id is 'How comfortable do you feel taking part in park activities alongside people from the other community?';
comment on column public.khld_interaction_survey.suitable_women_children_id is 'Do you consider the park a suitable place for women and children from both communities to spend time?';
comment on column public.khld_interaction_survey.relations_change_id is 'Compared with before the park was rehabilitated and activated, have relations between the host community and Syrian refugees in your area changed?';
comment on column public.khld_interaction_survey.change_narrative is 'In your own words, what has changed for you or your family because of the park and its activities?';
comment on column public.khld_interaction_survey.suggestions is 'What would make the park more welcoming for both communities?';
comment on column public.khld_interaction_survey.recontact_id is 'May we contact you again for next year''s survey?';
comment on column public.khld_interaction_survey.recontact_other is 'free text for recontact';
comment on column public.khld_interaction_survey.enum_notes is 'Enumerator notes and observations';
create trigger trg_khld_interaction_survey_other before insert or update on public.khld_interaction_survey
  for each row execute function public.guard_rmth_other(
    'recontact_id:ref_khld_recontact:recontact_other');

create table public.khld_interaction_survey_option (
  survey_id        uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  question_code    text not null,
  option_id        uuid not null,
  option_other     text,
  created_at       timestamptz not null default now(),
  primary key (survey_id, question_code, option_id),
  constraint khld_interaction_survey_option_survey_id_fkey foreign key (survey_id, municipality_id) references public.khld_interaction_survey(id, municipality_id)
);
create index khld_interaction_survey_option_municipality_idx on public.khld_interaction_survey_option (municipality_id);
create trigger trg_khld_interaction_survey_option_guard before insert or update on public.khld_interaction_survey_option
  for each row execute function public.guard_khld_option();

-- ── khld_partner_survey (so10, KHLD-SO1-0) ──

create table public.khld_partner_survey (
  id                    uuid primary key default gen_random_uuid(),
  municipality_id       uuid not null references public.municipality(id) default public.my_municipality(),
  resp_date             date not null,
  survey_round_id       uuid not null references public.ref_khld_so10_survey_round(id),
  partner_id            uuid not null,
  resp_name             text not null,
  resp_sex_id           uuid references public.ref_khld_sex(id),
  resp_contact          text,
  engagement_since      date not null,
  meetings_attended     int not null,
  focal_point_id        uuid not null references public.ref_khld_so10_focal_point(id),
  q_communication_id    uuid not null references public.ref_khld_agree_scale(id),
  q_roles_id            uuid not null references public.ref_khld_agree_scale(id),
  q_joint_planning_id   uuid not null references public.ref_khld_agree_scale(id),
  q_followup_id         uuid not null references public.ref_khld_agree_scale(id),
  q_transparency_id     uuid not null references public.ref_khld_agree_scale(id),
  q_improved_id         uuid not null references public.ref_khld_agree_scale(id),
  overall_rating_id     uuid not null references public.ref_khld_so10_overall_rating(id),
  duplication_id        uuid not null references public.ref_khld_so10_duplication(id),
  improve_suggestion    text not null,
  continue_intent_id    uuid not null references public.ref_khld_so10_continue_intent(id),
  continue_intent_other text,
  coord_notes           text,
  client_uuid           uuid unique,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid references auth.users(id) default auth.uid(),
  deleted_at            timestamptz,
  constraint khld_partner_survey_id_municipality_key unique (id, municipality_id),
  constraint khld_partner_survey_partner_id_fkey foreign key (partner_id, municipality_id) references public.khld_partner(id, municipality_id)
);
create index khld_partner_survey_municipality_idx on public.khld_partner_survey (municipality_id);
create index khld_partner_survey_created_by_idx on public.khld_partner_survey (created_by);
create index khld_partner_survey_survey_round_id_idx on public.khld_partner_survey (survey_round_id);
create index khld_partner_survey_partner_id_idx on public.khld_partner_survey (partner_id);
create index khld_partner_survey_resp_sex_id_idx on public.khld_partner_survey (resp_sex_id);
create index khld_partner_survey_focal_point_id_idx on public.khld_partner_survey (focal_point_id);
create index khld_partner_survey_q_communication_id_idx on public.khld_partner_survey (q_communication_id);
create index khld_partner_survey_q_roles_id_idx on public.khld_partner_survey (q_roles_id);
create index khld_partner_survey_q_joint_planning_id_idx on public.khld_partner_survey (q_joint_planning_id);
create index khld_partner_survey_q_followup_id_idx on public.khld_partner_survey (q_followup_id);
create index khld_partner_survey_q_transparency_id_idx on public.khld_partner_survey (q_transparency_id);
create index khld_partner_survey_q_improved_id_idx on public.khld_partner_survey (q_improved_id);
create index khld_partner_survey_overall_rating_id_idx on public.khld_partner_survey (overall_rating_id);
create index khld_partner_survey_duplication_id_idx on public.khld_partner_survey (duplication_id);
create index khld_partner_survey_continue_intent_id_idx on public.khld_partner_survey (continue_intent_id);
create unique index khld_partner_survey_partner_round_live on public.khld_partner_survey (partner_id, survey_round_id) where deleted_at is null;
comment on column public.khld_partner_survey.resp_date is 'Date completed';
comment on column public.khld_partner_survey.survey_round_id is 'Survey round';
comment on column public.khld_partner_survey.partner_id is 'Name of partner organisation';
comment on column public.khld_partner_survey.resp_name is 'Name and position of the person responding';
comment on column public.khld_partner_survey.resp_sex_id is 'Sex of respondent';
comment on column public.khld_partner_survey.resp_contact is 'Phone and email';
comment on column public.khld_partner_survey.engagement_since is 'Since when has your organisation been engaged in the Action Plan? (first of the month)';
comment on column public.khld_partner_survey.meetings_attended is 'How many coordination meetings with the Municipality did your organisation attend in the last 12 months?';
comment on column public.khld_partner_survey.focal_point_id is 'Do you have a designated focal point in the Municipality you can reach when needed?';
comment on column public.khld_partner_survey.q_communication_id is 'Communication from the Municipality about park activities is timely and clear.';
comment on column public.khld_partner_survey.q_roles_id is 'Roles and responsibilities between our organisation and the Municipality are clearly defined.';
comment on column public.khld_partner_survey.q_joint_planning_id is 'We are involved in planning park activities, not only informed after decisions are taken.';
comment on column public.khld_partner_survey.q_followup_id is 'The Municipality follows up on the decisions taken in coordination meetings.';
comment on column public.khld_partner_survey.q_transparency_id is 'Our contributions are documented and acknowledged transparently.';
comment on column public.khld_partner_survey.q_improved_id is 'Coordination and collaboration with the Municipality have improved compared with 12 months ago.';
comment on column public.khld_partner_survey.overall_rating_id is 'Overall, how effective is coordination with the Municipality on the Action Plan?';
comment on column public.khld_partner_survey.duplication_id is 'Has the coordination mechanism helped avoid duplication of effort between organisations working in the municipality?';
comment on column public.khld_partner_survey.improve_suggestion is 'What one change would most improve coordination in the coming year?';
comment on column public.khld_partner_survey.continue_intent_id is 'Does your organisation intend to continue contributing to the Action Plan next year?';
comment on column public.khld_partner_survey.continue_intent_other is 'free text for continue_intent';
comment on column public.khld_partner_survey.coord_notes is 'Notes by the community coordinator (for interviewer-administered responses)';
create trigger trg_khld_partner_survey_other before insert or update on public.khld_partner_survey
  for each row execute function public.guard_rmth_other(
    'continue_intent_id:ref_khld_so10_continue_intent:continue_intent_other');

create table public.khld_partner_survey_option (
  survey_id        uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  question_code    text not null,
  option_id        uuid not null,
  option_other     text,
  created_at       timestamptz not null default now(),
  primary key (survey_id, question_code, option_id),
  constraint khld_partner_survey_option_survey_id_fkey foreign key (survey_id, municipality_id) references public.khld_partner_survey(id, municipality_id)
);
create index khld_partner_survey_option_municipality_idx on public.khld_partner_survey_option (municipality_id);
create trigger trg_khld_partner_survey_option_guard before insert or update on public.khld_partner_survey_option
  for each row execute function public.guard_khld_option();

-- ── khld_user_feedback (so20, KHLD-SO2-0) ──

create table public.khld_user_feedback (
  id                    uuid primary key default gen_random_uuid(),
  municipality_id       uuid not null references public.municipality(id) default public.my_municipality(),
  activity_id           uuid not null,
  feedback_date         date not null,
  collection_mode_id    uuid not null references public.ref_khld_so20_collection_mode(id),
  sex_id                uuid not null references public.ref_khld_sex(id),
  age_group_id          uuid not null references public.ref_khld_age_group(id),
  nationality_id        uuid not null references public.ref_khld_nationality(id),
  disability_id         uuid references public.ref_khld_disability(id),
  first_visit           boolean not null,
  overall_satisfaction_id uuid not null references public.ref_khld_so20_overall_satisfaction(id),
  feel_safe_id          uuid not null references public.ref_khld_so20_feel_safe(id),
  feel_welcome_id       uuid not null references public.ref_khld_yes_fully_partly_no(id),
  suitable_women_children_id uuid not null references public.ref_khld_so20_suitable_women_children(id),
  suitable_women_children_other text,
  participate_freely_id uuid not null references public.ref_khld_so20_participate_freely(id),
  activity_suitable_id  uuid not null references public.ref_khld_so20_activity_suitable(id),
  activity_suitable_other text,
  timing_convenient_id  uuid not null references public.ref_khld_so20_timing_convenient(id),
  timing_convenient_other text,
  liked_most            text,
  improve_most          text not null,
  would_return_id       uuid not null references public.ref_khld_so20_would_return(id),
  collected_by          text,
  client_uuid           uuid unique,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid references auth.users(id) default auth.uid(),
  deleted_at            timestamptz,
  constraint khld_user_feedback_id_municipality_key unique (id, municipality_id),
  constraint khld_user_feedback_activity_id_fkey foreign key (activity_id, municipality_id) references public.khld_activity(id, municipality_id)
);
create index khld_user_feedback_municipality_idx on public.khld_user_feedback (municipality_id);
create index khld_user_feedback_created_by_idx on public.khld_user_feedback (created_by);
create index khld_user_feedback_activity_id_idx on public.khld_user_feedback (activity_id);
create index khld_user_feedback_collection_mode_id_idx on public.khld_user_feedback (collection_mode_id);
create index khld_user_feedback_sex_id_idx on public.khld_user_feedback (sex_id);
create index khld_user_feedback_age_group_id_idx on public.khld_user_feedback (age_group_id);
create index khld_user_feedback_nationality_id_idx on public.khld_user_feedback (nationality_id);
create index khld_user_feedback_disability_id_idx on public.khld_user_feedback (disability_id);
create index khld_user_feedback_overall_satisfaction_id_idx on public.khld_user_feedback (overall_satisfaction_id);
create index khld_user_feedback_feel_safe_id_idx on public.khld_user_feedback (feel_safe_id);
create index khld_user_feedback_feel_welcome_id_idx on public.khld_user_feedback (feel_welcome_id);
create index khld_user_feedback_suitable_women_children_id_idx on public.khld_user_feedback (suitable_women_children_id);
create index khld_user_feedback_participate_freely_id_idx on public.khld_user_feedback (participate_freely_id);
create index khld_user_feedback_activity_suitable_id_idx on public.khld_user_feedback (activity_suitable_id);
create index khld_user_feedback_timing_convenient_id_idx on public.khld_user_feedback (timing_convenient_id);
create index khld_user_feedback_would_return_id_idx on public.khld_user_feedback (would_return_id);
comment on column public.khld_user_feedback.activity_id is 'Activity reference number and name';
comment on column public.khld_user_feedback.feedback_date is 'Date';
comment on column public.khld_user_feedback.collection_mode_id is 'How was this feedback collected?';
comment on column public.khld_user_feedback.sex_id is 'Sex';
comment on column public.khld_user_feedback.age_group_id is 'Age group';
comment on column public.khld_user_feedback.nationality_id is 'Nationality / status';
comment on column public.khld_user_feedback.disability_id is 'Do you have difficulty doing any of the following: seeing, hearing, walking or climbing steps, remembering or concentrating, self-care, communicating?';
comment on column public.khld_user_feedback.first_visit is 'Is this your first time attending an activity in Al Khalidiyah Public Park?';
comment on column public.khld_user_feedback.overall_satisfaction_id is 'Overall, how satisfied are you with Al Khalidiyah Public Park as a place for community activities?';
comment on column public.khld_user_feedback.feel_safe_id is 'Do you feel safe in the park during activities?';
comment on column public.khld_user_feedback.feel_welcome_id is 'Is the park welcoming to you and your family regardless of where you are from?';
comment on column public.khld_user_feedback.suitable_women_children_id is 'Is the park a suitable place for women and children to spend time?';
comment on column public.khld_user_feedback.suitable_women_children_other is 'free text for suitable_women_children';
comment on column public.khld_user_feedback.participate_freely_id is 'Did you feel able to take part freely alongside other members of the community?';
comment on column public.khld_user_feedback.activity_suitable_id is 'Was the activity suitable for your needs and those of your children?';
comment on column public.khld_user_feedback.activity_suitable_other is 'free text for activity_suitable';
comment on column public.khld_user_feedback.timing_convenient_id is 'Was the timing of the activity convenient for you?';
comment on column public.khld_user_feedback.timing_convenient_other is 'free text for timing_convenient';
comment on column public.khld_user_feedback.liked_most is 'What did you like most about the park or the activity?';
comment on column public.khld_user_feedback.improve_most is 'What should be improved first?';
comment on column public.khld_user_feedback.would_return_id is 'Would you come again and encourage others to come?';
comment on column public.khld_user_feedback.collected_by is 'Collected by (name) and notes';
create trigger trg_khld_user_feedback_other before insert or update on public.khld_user_feedback
  for each row execute function public.guard_rmth_other(
    'suitable_women_children_id:ref_khld_so20_suitable_women_children:suitable_women_children_other',
    'activity_suitable_id:ref_khld_so20_activity_suitable:activity_suitable_other',
    'timing_convenient_id:ref_khld_so20_timing_convenient:timing_convenient_other');

create table public.khld_user_feedback_option (
  feedback_id      uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  question_code    text not null,
  option_id        uuid not null,
  option_other     text,
  created_at       timestamptz not null default now(),
  primary key (feedback_id, question_code, option_id),
  constraint khld_user_feedback_option_feedback_id_fkey foreign key (feedback_id, municipality_id) references public.khld_user_feedback(id, municipality_id)
);
create index khld_user_feedback_option_municipality_idx on public.khld_user_feedback_option (municipality_id);
create trigger trg_khld_user_feedback_option_guard before insert or update on public.khld_user_feedback_option
  for each row execute function public.guard_khld_option();

-- ── khld_volunteer_tracking (so30, KHLD-SO3-0) ──

create table public.khld_volunteer_tracking (
  id                    uuid primary key default gen_random_uuid(),
  municipality_id       uuid not null references public.municipality(id) default public.my_municipality(),
  volunteer_id          uuid not null,
  period_from           date not null,
  period_to             date,
  status_end_period_id  uuid not null references public.ref_khld_so30_status_end_period(id),
  inactive_reason_id    uuid references public.ref_khld_so30_inactive_reason(id),
  inactive_reason_other text,
  leadership_role_id    uuid references public.ref_khld_so30_leadership_role(id),
  leadership_role_other text,
  recognition_given_id  uuid not null references public.ref_khld_so30_recognition_given(id),
  recognition_given_other text,
  continue_intent_id    uuid not null references public.ref_khld_so30_continue_intent(id),
  verified_by_name      text,
  verified_on           date,
  notes                 text,
  client_uuid           uuid unique,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid references auth.users(id) default auth.uid(),
  deleted_at            timestamptz,
  constraint khld_volunteer_tracking_id_municipality_key unique (id, municipality_id),
  constraint khld_volunteer_tracking_volunteer_id_fkey foreign key (volunteer_id, municipality_id) references public.khld_volunteer(id, municipality_id)
);
create index khld_volunteer_tracking_municipality_idx on public.khld_volunteer_tracking (municipality_id);
create index khld_volunteer_tracking_created_by_idx on public.khld_volunteer_tracking (created_by);
create index khld_volunteer_tracking_volunteer_id_idx on public.khld_volunteer_tracking (volunteer_id);
create index khld_volunteer_tracking_status_end_period_id_idx on public.khld_volunteer_tracking (status_end_period_id);
create index khld_volunteer_tracking_inactive_reason_id_idx on public.khld_volunteer_tracking (inactive_reason_id);
create index khld_volunteer_tracking_leadership_role_id_idx on public.khld_volunteer_tracking (leadership_role_id);
create index khld_volunteer_tracking_recognition_given_id_idx on public.khld_volunteer_tracking (recognition_given_id);
create index khld_volunteer_tracking_continue_intent_id_idx on public.khld_volunteer_tracking (continue_intent_id);
comment on column public.khld_volunteer_tracking.volunteer_id is 'Volunteer ID (as assigned on the registration form)';
comment on column public.khld_volunteer_tracking.period_from is 'From';
comment on column public.khld_volunteer_tracking.period_to is 'to';
comment on column public.khld_volunteer_tracking.status_end_period_id is 'Status of the volunteer at the end of the period';
comment on column public.khld_volunteer_tracking.inactive_reason_id is 'If inactive or withdrawn, what is the main reason?';
comment on column public.khld_volunteer_tracking.inactive_reason_other is 'free text for inactive_reason';
comment on column public.khld_volunteer_tracking.leadership_role_id is 'Has the volunteer taken on a coordinating or team-leader role?';
comment on column public.khld_volunteer_tracking.leadership_role_other is 'free text for leadership_role';
comment on column public.khld_volunteer_tracking.recognition_given_id is 'Has the volunteer received a certificate of appreciation or a symbolic incentive?';
comment on column public.khld_volunteer_tracking.recognition_given_other is 'free text for recognition_given';
comment on column public.khld_volunteer_tracking.continue_intent_id is 'Does the volunteer intend to continue in the coming year?';
comment on column public.khld_volunteer_tracking.verified_by_name is 'name, position';
comment on column public.khld_volunteer_tracking.verified_on is 'date';
comment on column public.khld_volunteer_tracking.notes is 'Notes';
create trigger trg_khld_volunteer_tracking_other before insert or update on public.khld_volunteer_tracking
  for each row execute function public.guard_rmth_other(
    'inactive_reason_id:ref_khld_so30_inactive_reason:inactive_reason_other',
    'leadership_role_id:ref_khld_so30_leadership_role:leadership_role_other',
    'recognition_given_id:ref_khld_so30_recognition_given:recognition_given_other');

create table public.khld_volunteer_tracking_option (
  tracking_id      uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  question_code    text not null,
  option_id        uuid not null,
  option_other     text,
  created_at       timestamptz not null default now(),
  primary key (tracking_id, question_code, option_id),
  constraint khld_volunteer_tracking_option_tracking_id_fkey foreign key (tracking_id, municipality_id) references public.khld_volunteer_tracking(id, municipality_id)
);
create index khld_volunteer_tracking_option_municipality_idx on public.khld_volunteer_tracking_option (municipality_id);
create trigger trg_khld_volunteer_tracking_option_guard before insert or update on public.khld_volunteer_tracking_option
  for each row execute function public.guard_khld_option();

-- ── khld_producer_survey (so40, KHLD-SO4-0) ──

create table public.khld_producer_survey (
  id                    uuid primary key default gen_random_uuid(),
  municipality_id       uuid not null references public.municipality(id) default public.my_municipality(),
  int_date              date not null,
  mode_id               uuid not null references public.ref_khld_so40_mode(id),
  enumerator            text not null,
  respondent_is_vendor_id uuid not null references public.ref_khld_so40_respondent_is_vendor(id),
  vendor_id             uuid not null,
  sex_id                uuid not null references public.ref_khld_sex(id),
  age_group_id          uuid not null references public.ref_khld_age_group(id),
  nationality_id        uuid not null references public.ref_khld_nationality(id),
  disability_id         uuid references public.ref_khld_disability(id),
  neighbourhood_id      uuid references public.ref_khld_neighbourhood(id),
  markets_count         int not null,
  first_organised_market_id uuid not null references public.ref_khld_so40_first_organised_market(id),
  exposure_id           uuid not null references public.ref_khld_so40_exposure(id),
  made_sales_id         uuid not null references public.ref_khld_so40_made_sales(id),
  sales_last_market_id  uuid not null references public.ref_khld_sales_band(id),
  new_customers_id      uuid not null references public.ref_khld_so40_new_customers(id),
  repeat_orders_id      uuid not null references public.ref_khld_so40_repeat_orders(id),
  overall_opportunity_id uuid not null references public.ref_khld_so40_overall_opportunity(id),
  production_change_id  uuid not null references public.ref_khld_so40_production_change(id),
  still_active_id       uuid not null references public.ref_khld_so40_still_active(id),
  stop_reason_id        uuid not null references public.ref_khld_so40_stop_reason(id),
  stop_reason_other     text,
  guidance_received_id  uuid not null references public.ref_khld_so40_guidance_received(id),
  participate_again_id  uuid not null references public.ref_khld_so40_participate_again(id),
  recontact_id          uuid not null references public.ref_khld_recontact(id),
  recontact_other       text,
  quote                 text,
  notes                 text,
  client_uuid           uuid unique,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid references auth.users(id) default auth.uid(),
  deleted_at            timestamptz,
  constraint khld_producer_survey_id_municipality_key unique (id, municipality_id),
  constraint khld_producer_survey_vendor_id_fkey foreign key (vendor_id, municipality_id) references public.khld_vendor(id, municipality_id)
);
create index khld_producer_survey_municipality_idx on public.khld_producer_survey (municipality_id);
create index khld_producer_survey_created_by_idx on public.khld_producer_survey (created_by);
create index khld_producer_survey_mode_id_idx on public.khld_producer_survey (mode_id);
create index khld_producer_survey_respondent_is_vendor_id_idx on public.khld_producer_survey (respondent_is_vendor_id);
create index khld_producer_survey_vendor_id_idx on public.khld_producer_survey (vendor_id);
create index khld_producer_survey_sex_id_idx on public.khld_producer_survey (sex_id);
create index khld_producer_survey_age_group_id_idx on public.khld_producer_survey (age_group_id);
create index khld_producer_survey_nationality_id_idx on public.khld_producer_survey (nationality_id);
create index khld_producer_survey_disability_id_idx on public.khld_producer_survey (disability_id);
create index khld_producer_survey_neighbourhood_id_idx on public.khld_producer_survey (neighbourhood_id);
create index khld_producer_survey_first_organised_market_id_idx on public.khld_producer_survey (first_organised_market_id);
create index khld_producer_survey_exposure_id_idx on public.khld_producer_survey (exposure_id);
create index khld_producer_survey_made_sales_id_idx on public.khld_producer_survey (made_sales_id);
create index khld_producer_survey_sales_last_market_id_idx on public.khld_producer_survey (sales_last_market_id);
create index khld_producer_survey_new_customers_id_idx on public.khld_producer_survey (new_customers_id);
create index khld_producer_survey_repeat_orders_id_idx on public.khld_producer_survey (repeat_orders_id);
create index khld_producer_survey_overall_opportunity_id_idx on public.khld_producer_survey (overall_opportunity_id);
create index khld_producer_survey_production_change_id_idx on public.khld_producer_survey (production_change_id);
create index khld_producer_survey_still_active_id_idx on public.khld_producer_survey (still_active_id);
create index khld_producer_survey_stop_reason_id_idx on public.khld_producer_survey (stop_reason_id);
create index khld_producer_survey_guidance_received_id_idx on public.khld_producer_survey (guidance_received_id);
create index khld_producer_survey_participate_again_id_idx on public.khld_producer_survey (participate_again_id);
create index khld_producer_survey_recontact_id_idx on public.khld_producer_survey (recontact_id);
comment on column public.khld_producer_survey.int_date is 'Date of interview';
comment on column public.khld_producer_survey.mode_id is 'Mode of interview';
comment on column public.khld_producer_survey.enumerator is 'Interviewer name';
comment on column public.khld_producer_survey.respondent_is_vendor_id is 'Is the respondent the registered producer?';
comment on column public.khld_producer_survey.vendor_id is 'Vendor or producer ID (from the vendor registration sheet)';
comment on column public.khld_producer_survey.sex_id is 'Sex';
comment on column public.khld_producer_survey.age_group_id is 'Age group';
comment on column public.khld_producer_survey.nationality_id is 'Nationality / status';
comment on column public.khld_producer_survey.disability_id is 'Disability status';
comment on column public.khld_producer_survey.neighbourhood_id is 'Neighbourhood';
comment on column public.khld_producer_survey.markets_count is 'In how many community market days or fairs in the park have you taken part?';
comment on column public.khld_producer_survey.first_organised_market_id is 'Was this your first time selling at an organised market or exhibition?';
comment on column public.khld_producer_survey.exposure_id is 'Did taking part in the market give you more opportunity to show your products to people?';
comment on column public.khld_producer_survey.made_sales_id is 'Did you make any sales at the market days you attended?';
comment on column public.khld_producer_survey.sales_last_market_id is 'Approximately what were your total sales at the most recent market day?';
comment on column public.khld_producer_survey.new_customers_id is 'How many new customers or buyers did you make contact with at the market?';
comment on column public.khld_producer_survey.repeat_orders_id is 'Did any customer contact you again after the market to buy from you?';
comment on column public.khld_producer_survey.overall_opportunity_id is 'Overall, did participation in the community markets increase your opportunities to promote or sell your products?';
comment on column public.khld_producer_survey.production_change_id is 'Has your production volume changed since you started taking part in the markets?';
comment on column public.khld_producer_survey.still_active_id is 'Are you still producing and selling?';
comment on column public.khld_producer_survey.stop_reason_id is 'If you stopped or reduced, what was the main reason?';
comment on column public.khld_producer_survey.stop_reason_other is 'free text for stop_reason';
comment on column public.khld_producer_survey.guidance_received_id is 'Have you received guidance sessions on licensing, hygiene, pricing or packaging?';
comment on column public.khld_producer_survey.participate_again_id is 'Would you take part in the next market day?';
comment on column public.khld_producer_survey.recontact_id is 'May we contact you again for the next follow-up round?';
comment on column public.khld_producer_survey.recontact_other is 'free text for recontact';
comment on column public.khld_producer_survey.quote is 'In your own words, what difference did the market make for you?';
comment on column public.khld_producer_survey.notes is 'Interviewer notes';
create trigger trg_khld_producer_survey_other before insert or update on public.khld_producer_survey
  for each row execute function public.guard_rmth_other(
    'stop_reason_id:ref_khld_so40_stop_reason:stop_reason_other',
    'recontact_id:ref_khld_recontact:recontact_other');

create table public.khld_producer_survey_option (
  survey_id        uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  question_code    text not null,
  option_id        uuid not null,
  option_other     text,
  created_at       timestamptz not null default now(),
  primary key (survey_id, question_code, option_id),
  constraint khld_producer_survey_option_survey_id_fkey foreign key (survey_id, municipality_id) references public.khld_producer_survey(id, municipality_id)
);
create index khld_producer_survey_option_municipality_idx on public.khld_producer_survey_option (municipality_id);
create trigger trg_khld_producer_survey_option_guard before insert or update on public.khld_producer_survey_option
  for each row execute function public.guard_khld_option();

-- ── khld_milestone_verification (SO1-A1, SO1-B1, SO3-E1, SO3-F1) ──

create table public.khld_milestone_verification (
  id                    uuid primary key default gen_random_uuid(),
  municipality_id       uuid not null references public.municipality(id) default public.my_municipality(),
  milestone_code        text not null check (milestone_code in ('SO1-A1', 'SO1-B1', 'SO3-E1', 'SO3-F1')),
  verif_date            date not null,
  verif_round_id        uuid references public.ref_khld_a1_verif_round(id),
  verif_by              text not null,
  period_covered_from   date,
  period_covered_to     date,
  coordinator_decision_no text,
  coordinator_decision_date date,
  coordinator_officer_name text,
  stakeholder_updated   date,
  tracking_format_id    uuid references public.ref_khld_a1_tracking_format(id),
  intro_meetings        int,
  council_decision_id   uuid references public.ref_khld_a1_council_decision(id),
  council_decision_other text,
  gaps                  text not null,
  countersign_name      text,
  countersign_date      date,
  protocol_ref          text,
  calendar_horizon_id   uuid references public.ref_khld_b1_calendar_horizon(id),
  requests_received     int,
  requests_approved     int,
  requests_declined     int,
  last_updated          date,
  founding_meeting_date date,
  founding_meeting_venue text,
  invited_count         int,
  attended_count        int,
  orgs_joined           text,
  orgs_withdrew         text,
  meeting_cycle_id      uuid references public.ref_khld_e1_meeting_cycle(id),
  meetings_held         int,
  meetings_with_minutes int,
  duplication_avoided_id uuid references public.ref_khld_e1_duplication_avoided(id),
  duplication_avoided_other text,
  committee_coordinator_name text,
  community_coordinator_name text,
  signed_on             date,
  launch_date           date,
  database_format_id    uuid references public.ref_khld_f1_database_format(id),
  registered_count      int,
  registered_women      int,
  registered_youth      int,
  registered_refugees   int,
  registered_pwd        int,
  recognition_delivered int,
  focal_point_id        uuid references public.ref_khld_f1_focal_point(id),
  focal_point_other     text,
  action_days_since_launch int,
  client_uuid           uuid unique,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid references auth.users(id) default auth.uid(),
  deleted_at            timestamptz,
  constraint khld_milestone_verification_id_municipality_key unique (id, municipality_id),
  constraint khld_milestone_verification_so1_a1_columns check (milestone_code <> 'SO1-A1' or (protocol_ref is null and calendar_horizon_id is null and requests_received is null and requests_approved is null and requests_declined is null and last_updated is null and founding_meeting_date is null and founding_meeting_venue is null and invited_count is null and attended_count is null and orgs_joined is null and orgs_withdrew is null and meeting_cycle_id is null and meetings_held is null and meetings_with_minutes is null and duplication_avoided_id is null and duplication_avoided_other is null and committee_coordinator_name is null and community_coordinator_name is null and signed_on is null and launch_date is null and database_format_id is null and registered_count is null and registered_women is null and registered_youth is null and registered_refugees is null and registered_pwd is null and recognition_delivered is null and focal_point_id is null and focal_point_other is null and action_days_since_launch is null)),
  constraint khld_milestone_verification_so1_b1_columns check (milestone_code <> 'SO1-B1' or (verif_round_id is null and period_covered_from is null and period_covered_to is null and coordinator_decision_no is null and coordinator_decision_date is null and coordinator_officer_name is null and stakeholder_updated is null and tracking_format_id is null and intro_meetings is null and council_decision_id is null and council_decision_other is null and founding_meeting_date is null and founding_meeting_venue is null and invited_count is null and attended_count is null and orgs_joined is null and orgs_withdrew is null and meeting_cycle_id is null and meetings_held is null and meetings_with_minutes is null and duplication_avoided_id is null and duplication_avoided_other is null and committee_coordinator_name is null and community_coordinator_name is null and signed_on is null and launch_date is null and database_format_id is null and registered_count is null and registered_women is null and registered_youth is null and registered_refugees is null and registered_pwd is null and recognition_delivered is null and focal_point_id is null and focal_point_other is null and action_days_since_launch is null)),
  constraint khld_milestone_verification_so3_e1_columns check (milestone_code <> 'SO3-E1' or (verif_round_id is null and period_covered_from is null and period_covered_to is null and coordinator_decision_no is null and coordinator_decision_date is null and coordinator_officer_name is null and stakeholder_updated is null and tracking_format_id is null and intro_meetings is null and council_decision_id is null and council_decision_other is null and countersign_name is null and countersign_date is null and protocol_ref is null and calendar_horizon_id is null and requests_received is null and requests_approved is null and requests_declined is null and last_updated is null and launch_date is null and database_format_id is null and registered_count is null and registered_women is null and registered_youth is null and registered_refugees is null and registered_pwd is null and recognition_delivered is null and focal_point_id is null and focal_point_other is null and action_days_since_launch is null)),
  constraint khld_milestone_verification_so3_f1_columns check (milestone_code <> 'SO3-F1' or (verif_round_id is null and period_covered_from is null and period_covered_to is null and coordinator_decision_no is null and coordinator_decision_date is null and coordinator_officer_name is null and stakeholder_updated is null and tracking_format_id is null and intro_meetings is null and council_decision_id is null and council_decision_other is null and countersign_name is null and countersign_date is null and protocol_ref is null and calendar_horizon_id is null and requests_received is null and requests_approved is null and requests_declined is null and last_updated is null and founding_meeting_date is null and founding_meeting_venue is null and invited_count is null and attended_count is null and orgs_joined is null and orgs_withdrew is null and meeting_cycle_id is null and meetings_held is null and meetings_with_minutes is null and duplication_avoided_id is null and duplication_avoided_other is null and committee_coordinator_name is null and community_coordinator_name is null and signed_on is null))
);
create index khld_milestone_verification_municipality_idx on public.khld_milestone_verification (municipality_id);
create index khld_milestone_verification_created_by_idx on public.khld_milestone_verification (created_by);
create index khld_milestone_verification_verif_round_id_idx on public.khld_milestone_verification (verif_round_id);
create index khld_milestone_verification_tracking_format_id_idx on public.khld_milestone_verification (tracking_format_id);
create index khld_milestone_verification_council_decision_id_idx on public.khld_milestone_verification (council_decision_id);
create index khld_milestone_verification_calendar_horizon_id_idx on public.khld_milestone_verification (calendar_horizon_id);
create index khld_milestone_verification_meeting_cycle_id_idx on public.khld_milestone_verification (meeting_cycle_id);
create index khld_milestone_verification_duplication_avoided_id_idx on public.khld_milestone_verification (duplication_avoided_id);
create index khld_milestone_verification_database_format_id_idx on public.khld_milestone_verification (database_format_id);
create index khld_milestone_verification_focal_point_id_idx on public.khld_milestone_verification (focal_point_id);
comment on column public.khld_milestone_verification.verif_date is 'Date of verification';
comment on column public.khld_milestone_verification.verif_round_id is 'Which verification is this?';
comment on column public.khld_milestone_verification.verif_by is 'Verified by (name and position)';
comment on column public.khld_milestone_verification.period_covered_from is 'From';
comment on column public.khld_milestone_verification.period_covered_to is 'to';
comment on column public.khld_milestone_verification.coordinator_decision_no is 'Decision number';
comment on column public.khld_milestone_verification.coordinator_decision_date is 'date';
comment on column public.khld_milestone_verification.coordinator_officer_name is 'name of the designated officer';
comment on column public.khld_milestone_verification.stakeholder_updated is 'Date the stakeholder list was last updated';
comment on column public.khld_milestone_verification.tracking_format_id is 'Format of the contribution register';
comment on column public.khld_milestone_verification.intro_meetings is 'Number of introductory meetings held with potential partners during the period';
comment on column public.khld_milestone_verification.council_decision_id is 'Has the Municipal Council issued a decision adopting the partnership mechanism?';
comment on column public.khld_milestone_verification.council_decision_other is 'free text for council_decision';
comment on column public.khld_milestone_verification.gaps is 'Gaps identified and follow-up actions agreed (what, who, by when)';
comment on column public.khld_milestone_verification.countersign_name is 'name';
comment on column public.khld_milestone_verification.countersign_date is 'date';
comment on column public.khld_milestone_verification.protocol_ref is 'Approval reference (Council or executive decision number and date)';
comment on column public.khld_milestone_verification.calendar_horizon_id is 'Period covered by the current calendar';
comment on column public.khld_milestone_verification.requests_received is 'Received';
comment on column public.khld_milestone_verification.requests_approved is 'Approved';
comment on column public.khld_milestone_verification.requests_declined is 'Declined';
comment on column public.khld_milestone_verification.last_updated is 'Date the arrangements were last reviewed or updated';
comment on column public.khld_milestone_verification.founding_meeting_date is 'Date';
comment on column public.khld_milestone_verification.founding_meeting_venue is 'Venue';
comment on column public.khld_milestone_verification.invited_count is 'Invited';
comment on column public.khld_milestone_verification.attended_count is 'Attended';
comment on column public.khld_milestone_verification.orgs_joined is 'Organisations joined';
comment on column public.khld_milestone_verification.orgs_withdrew is 'Organisations withdrew';
comment on column public.khld_milestone_verification.meeting_cycle_id is 'What meeting cycle has been agreed?';
comment on column public.khld_milestone_verification.meetings_held is 'Meetings held';
comment on column public.khld_milestone_verification.meetings_with_minutes is 'With minutes';
comment on column public.khld_milestone_verification.duplication_avoided_id is 'Has the committee helped unify efforts and avoid duplication between organisations?';
comment on column public.khld_milestone_verification.duplication_avoided_other is 'free text for duplication_avoided';
comment on column public.khld_milestone_verification.committee_coordinator_name is 'committee coordinator';
comment on column public.khld_milestone_verification.community_coordinator_name is 'municipal community coordinator';
comment on column public.khld_milestone_verification.signed_on is 'date';
comment on column public.khld_milestone_verification.launch_date is 'Date the programme was launched';
comment on column public.khld_milestone_verification.database_format_id is 'Format';
comment on column public.khld_milestone_verification.registered_count is 'Number registered';
comment on column public.khld_milestone_verification.registered_women is 'Of whom women';
comment on column public.khld_milestone_verification.registered_youth is 'Youth 15–24';
comment on column public.khld_milestone_verification.registered_refugees is 'Syrian refugees';
comment on column public.khld_milestone_verification.registered_pwd is 'Persons with disabilities';
comment on column public.khld_milestone_verification.recognition_delivered is 'Number of volunteers who have received recognition to date';
comment on column public.khld_milestone_verification.focal_point_id is 'Has a municipal focal point for volunteers been designated?';
comment on column public.khld_milestone_verification.focal_point_other is 'free text for focal_point';
comment on column public.khld_milestone_verification.action_days_since_launch is 'Number of volunteer action days organised since launch';
create trigger trg_khld_milestone_verification_other before insert or update on public.khld_milestone_verification
  for each row execute function public.guard_rmth_other(
    'council_decision_id:ref_khld_a1_council_decision:council_decision_other',
    'duplication_avoided_id:ref_khld_e1_duplication_avoided:duplication_avoided_other',
    'focal_point_id:ref_khld_f1_focal_point:focal_point_other');

create table public.khld_milestone_verification_option (
  verification_id  uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  question_code    text not null,
  option_id        uuid not null,
  option_other     text,
  created_at       timestamptz not null default now(),
  primary key (verification_id, question_code, option_id),
  constraint khld_milestone_verification_option_verification_id_fkey foreign key (verification_id, municipality_id) references public.khld_milestone_verification(id, municipality_id)
);
create index khld_milestone_verification_option_municipality_idx on public.khld_milestone_verification_option (municipality_id);
create trigger trg_khld_milestone_verification_option_guard before insert or update on public.khld_milestone_verification_option
  for each row execute function public.guard_khld_option();

create table public.khld_milestone_verification_count (
  verification_id  uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  field_code       text not null,
  cell_id          uuid not null,
  count            int not null check (count >= 0),
  created_at       timestamptz not null default now(),
  primary key (verification_id, field_code, cell_id),
  constraint khld_milestone_verification_count_verification_id_fkey foreign key (verification_id, municipality_id) references public.khld_milestone_verification(id, municipality_id)
);
create index khld_milestone_verification_count_municipality_idx on public.khld_milestone_verification_count (municipality_id);
create trigger trg_khld_milestone_verification_count_guard before insert or update on public.khld_milestone_verification_count
  for each row execute function public.guard_khld_count();

