-- ═══════════════════════════════════════════════════════════════════════════
--  0141 — Khalidiyah's option lists: one ref_khld_* table per response list
--
--  Every response-option list in Khalidiyah_Indicator_Data_Collection_Forms.xlsx,
--  one table each, BOTH labels verbatim from the sheet in the sheet's order:
--  this is the first framework to arrive with its Arabic written, so nothing
--  here is drafted (plan 5.7). 237 lists, 1250 options. Generated by
--  supabase/khalidiyah/gen_0141.py from workbook.py (the one reading of the
--  sheets) and catalogue.py (the structure); do not edit by hand. Split
--  across 0141, 0142 and 0143 only because each is applied through the MCP
--  as one pasted text: 0141 creates every table and seeds the first third
--  of the lists, 0142 and 0143 seed the rest, and 0143 carries the
--  verification over all 237.
--
--  ── WHY ONE TABLE PER LIST ──
--
--  0002, 0075 and 0122 made one table per list for the same reason: a
--  single-select column gets a real foreign key into the list it may hold,
--  and the application's ref machinery (useRefTable, refLabel, the "Other"
--  companion column) reads any table of this shape unchanged.
--
--  ── WHAT IS SHARED ──
--
--  13 lists are used by more than one sheet and exist once (sex,
--  age_group, nationality, disability, neighbourhood, agree_scale,
--  checklist_status, product_type, sales_band, partner_type, ...). Two
--  sheets share a table only when every option, English AND Arabic, matches;
--  a3's contributor_type differs from partner_type by one option and is its
--  own table. None of the shared Sahel Horan or Ramtha lists is reused
--  (plan 5.8): a row added to a shared list appears in the other two
--  municipalities' dropdowns.
--
--  ── THREE KINDS OF LIST ──
--
--  Response options (a single- or multi-select), the checklist statuses of
--  a milestone item (codes START with in_place / partly / not_in_place /
--  not_accepted, and khld_milestone_status in 0145 reads the status from the
--  code prefix, so an item whose sheet says "In place — written decision"
--  still evaluates as In place), and the CELLS of a "by ..." count field
--  (plan 5.2: a child row per cell, never a column per cell, never JSON) --
--  a2.orgs_by_type, d2.by_age_sex, e1.members_by_type and so on. The rating
--  matrix of SO2-0 is two cell lists (the nine facilities, the four ratings).
--
--  ── "OTHER" AND THE BLANKS ──
--
--  allows_free_text is true for 81 options: every option whose sheet
--  text carries a blank ("Yes — names: ____", "Cancelled — reason: ____"),
--  says (specify) or describe, or is a bare "Other". The blank is the
--  sheet's own signal that the option needs a detail, and the detail lives
--  in the record's <field>_other column, required by guard_rmth_other /
--  guard_khld_option when such an option is chosen (CLAUDE.md, "Other
--  (please specify)"). A bare "Other" is treated the same way as a
--  decision, recorded in 06_OPEN_QUESTIONS.md (OQ-53): an "Other" that
--  cannot say what it was is the OQ-28 defect, and the sheets are not
--  consistent about writing "(specify)". Where a blank is typed instead --
--  a date, a number, a second select -- the option list carries NO free
--  text and the typed column beside it holds the value (catalogue.py's
--  parts): the session dates of SO4-G1, the number of children on IMP-0,
--  the priority rank on SO2-C1.
--
--  ── THE DISABILITY QUESTION ──
--
--  Khalidiyah asks disability functionally (the Washington Group short
--  set: "Do you have difficulty doing any of the following — seeing,
--  hearing, walking or climbing steps, remembering or concentrating,
--  self-care, communicating?") with four degrees and "Prefer not to say".
--  Sahel Horan's list is plain labels, because that workbook named no
--  instrument; the asymmetry is deliberate and recorded (plan 5.8, OQ-54)
--  so nobody harmonises the two later.
-- ═══════════════════════════════════════════════════════════════════════════

do $outer$
declare t text;
begin
  foreach t in array array[
    'ref_khld_imp0_survey_round',
    'ref_khld_imp0_int_place',
    'ref_khld_imp0_consent',
    'ref_khld_sex',
    'ref_khld_age_group',
    'ref_khld_nationality',
    'ref_khld_disability',
    'ref_khld_neighbourhood',
    'ref_khld_imp0_has_children',
    'ref_khld_imp0_visit_freq',
    'ref_khld_imp0_activities_taken',
    'ref_khld_imp0_accompanied_by',
    'ref_khld_imp0_mixed_presence',
    'ref_khld_imp0_new_contact',
    'ref_khld_agree_scale',
    'ref_khld_imp0_joint_activity',
    'ref_khld_imp0_comfort_level',
    'ref_khld_yes_fully_partly_no',
    'ref_khld_imp0_relations_change',
    'ref_khld_imp0_barriers',
    'ref_khld_recontact',
    'ref_khld_so10_survey_round',
    'ref_khld_so10_areas_involved',
    'ref_khld_so10_focal_point',
    'ref_khld_so10_overall_rating',
    'ref_khld_so10_duplication',
    'ref_khld_so10_obstacles',
    'ref_khld_so10_continue_intent',
    'ref_khld_so10_evidence_ref',
    'ref_khld_a1_verif_round',
    'ref_khld_a1_coordinator_assigned',
    'ref_khld_checklist_status',
    'ref_khld_a1_stakeholder_count',
    'ref_khld_a1_tracking_format',
    'ref_khld_a1_partnerships_concluded',
    'ref_khld_a1_zaha_coordination',
    'ref_khld_a1_periodic_updates',
    'ref_khld_a1_council_decision',
    'ref_khld_a1_evidence_attached',
    'ref_khld_a2_venue',
    'ref_khld_a2_meeting_type',
    'ref_khld_a2_convened_by',
    'ref_khld_a2_pillars_discussed',
    'ref_khld_a2_orgs_by_type',
    'ref_khld_a2_attendees_breakdown',
    'ref_khld_a2_new_partners',
    'ref_khld_a2_prev_followup',
    'ref_khld_a2_contributions_pledged',
    'ref_khld_a2_minutes_prepared',
    'ref_khld_a3_status',
    'ref_khld_a3_source_meeting',
    'ref_khld_a3_contributor_type',
    'ref_khld_a3_csr_linked',
    'ref_khld_a3_first_contribution',
    'ref_khld_a3_contribution_type',
    'ref_khld_a3_valuation_basis',
    'ref_khld_a3_supports_objective',
    'ref_khld_a3_municipal_acceptance',
    'ref_khld_a3_conditions',
    'ref_khld_a3_acknowledged',
    'ref_khld_a3_evidence_attached',
    'ref_khld_b1_protocol_exists',
    'ref_khld_b1_activity_calendar',
    'ref_khld_b1_calendar_horizon',
    'ref_khld_b1_communicated',
    'ref_khld_b1_evidence_attached',
    'ref_khld_so20_collection_mode',
    'ref_khld_so20_overall_satisfaction',
    'ref_khld_so20_feel_safe',
    'ref_khld_so20_suitable_women_children',
    'ref_khld_so20_participate_freely',
    'ref_khld_so20_facility_item',
    'ref_khld_so20_facility_rating',
    'ref_khld_so20_activity_suitable',
    'ref_khld_so20_timing_convenient',
    'ref_khld_so20_how_heard',
    'ref_khld_so20_would_return',
    'ref_khld_c1_facility_type',
    'ref_khld_c1_on_priority_list',
    'ref_khld_c1_identified_how',
    'ref_khld_c1_status',
    'ref_khld_c1_modality',
    'ref_khld_c1_resource_source',
    'ref_khld_c1_accessibility_met',
    'ref_khld_c1_safety_check',
    'ref_khld_c1_handover',
    'ref_khld_c1_maintenance_owner',
    'ref_khld_c1_evidence_attached',
    'ref_khld_c2_is_first_campaign',
    'ref_khld_c2_focus',
    'ref_khld_c2_linked_item',
    'ref_khld_c2_lead_organiser',
    'ref_khld_c2_volunteers_breakdown',
    'ref_khld_c2_school_linked',
    'ref_khld_c2_safety_briefing',
    'ref_khld_incident',
    'ref_khld_c2_municipal_supervision',
    'ref_khld_c2_evidence_attached',
    'ref_khld_c2_recognition',
    'ref_khld_d1_location',
    'ref_khld_d1_activity_type',
    'ref_khld_d1_calendar_status',
    'ref_khld_d1_frequency_type',
    'ref_khld_d1_organiser',
    'ref_khld_d1_content_provider',
    'ref_khld_d1_target_group',
    'ref_khld_d1_announcement',
    'ref_khld_d1_inclusion_measures',
    'ref_khld_d1_feedback_collected',
    'ref_khld_d1_issues',
    'ref_khld_d1_evidence_attached',
    'ref_khld_d2_count_method',
    'ref_khld_d2_by_sex',
    'ref_khld_d2_by_age_sex',
    'ref_khld_d2_by_nationality',
    'ref_khld_d2_register_attached',
    'ref_khld_d2_consent_informed',
    'ref_khld_d2_photo_consent',
    'ref_khld_d2_duplicate_check',
    'ref_khld_so30_activity_types',
    'ref_khld_so30_status_end_period',
    'ref_khld_so30_inactive_reason',
    'ref_khld_so30_leadership_role',
    'ref_khld_so30_recognition_given',
    'ref_khld_so30_continue_intent',
    'ref_khld_so30_what_would_help',
    'ref_khld_so30_verified_against',
    'ref_khld_e1_formal_recognition',
    'ref_khld_e1_written_tasks',
    'ref_khld_e1_tasks_covered',
    'ref_khld_e1_coordinator_elected',
    'ref_khld_e1_municipal_focal',
    'ref_khld_e1_members_by_type',
    'ref_khld_e1_members_by_sex',
    'ref_khld_e1_inclusive_representation',
    'ref_khld_e1_meeting_cycle',
    'ref_khld_e1_outputs_delivered',
    'ref_khld_e1_duplication_avoided',
    'ref_khld_e1_evidence_attached',
    'ref_khld_f1_procedures_approved',
    'ref_khld_f1_database_established',
    'ref_khld_f1_database_format',
    'ref_khld_f1_safety_arrangements',
    'ref_khld_f1_minors_arrangements',
    'ref_khld_f1_recognition_scheme',
    'ref_khld_f1_recruitment_channels',
    'ref_khld_f1_focal_point',
    'ref_khld_f1_evidence_attached',
    'ref_khld_f2_reg_channel',
    'ref_khld_f2_support_needs',
    'ref_khld_f2_occupation_status',
    'ref_khld_f2_affiliation',
    'ref_khld_f2_interests',
    'ref_khld_f2_skills',
    'ref_khld_f2_availability_days',
    'ref_khld_f2_availability_times',
    'ref_khld_f2_transport',
    'ref_khld_f2_prior_experience',
    'ref_khld_f2_how_heard',
    'ref_khld_f3_location',
    'ref_khld_f3_theme',
    'ref_khld_f3_linked_records',
    'ref_khld_f3_called_by',
    'ref_khld_f3_volunteers_breakdown',
    'ref_khld_f3_roles_used',
    'ref_khld_f3_refreshments',
    'ref_khld_f3_safety',
    'ref_khld_f3_evidence_attached',
    'ref_khld_f3_recognition',
    'ref_khld_f3_volunteer_feedback',
    'ref_khld_so40_mode',
    'ref_khld_so40_respondent_is_vendor',
    'ref_khld_product_type',
    'ref_khld_so40_first_organised_market',
    'ref_khld_so40_sold_before_market',
    'ref_khld_so40_exposure',
    'ref_khld_so40_made_sales',
    'ref_khld_sales_band',
    'ref_khld_so40_new_customers',
    'ref_khld_so40_repeat_orders',
    'ref_khld_so40_new_channels',
    'ref_khld_so40_overall_opportunity',
    'ref_khld_so40_production_change',
    'ref_khld_so40_still_active',
    'ref_khld_so40_stop_reason',
    'ref_khld_so40_guidance_received',
    'ref_khld_so40_market_constraints',
    'ref_khld_so40_improvements_wanted',
    'ref_khld_so40_additional_support',
    'ref_khld_so40_participate_again',
    'ref_khld_g1_cycle_year',
    'ref_khld_g1_enterprise_status',
    'ref_khld_session_attendance',
    'ref_khld_g1_s3_hygiene',
    'ref_khld_g1_non_completion_reason',
    'ref_khld_g1_provider',
    'ref_khld_g1_venue',
    'ref_khld_g1_most_useful',
    'ref_khld_g1_peer_network',
    'ref_khld_g1_further_needs',
    'ref_khld_g1_referral_made',
    'ref_khld_g1_certificate',
    'ref_khld_g1_evidence_attached',
    'ref_khld_g2_priority_group',
    'ref_khld_g2_sup_hygiene',
    'ref_khld_g2_sup_referral_outcome',
    'ref_khld_g2_providers',
    'ref_khld_g2_status_last_contact',
    'ref_khld_g2_licensing_progress',
    'ref_khld_g2_evidence_attached',
    'ref_khld_h1_occasion',
    'ref_khld_h1_phase',
    'ref_khld_h1_location',
    'ref_khld_h1_organisers',
    'ref_khld_h1_announcement',
    'ref_khld_h1_selection_method',
    'ref_khld_h1_priority_share',
    'ref_khld_h1_refreshment_point',
    'ref_khld_h1_services_provided',
    'ref_khld_h1_accessibility',
    'ref_khld_h1_visitors_method',
    'ref_khld_h1_hygiene_check',
    'ref_khld_h1_parallel_activities',
    'ref_khld_h1_total_sales_method',
    'ref_khld_h1_cost_source',
    'ref_khld_h1_issues',
    'ref_khld_h1_feedback_collected',
    'ref_khld_h1_evidence_attached',
    'ref_khld_h2_priority_flags',
    'ref_khld_h2_vendor_type',
    'ref_khld_h2_licensed',
    'ref_khld_h2_health_certificate',
    'ref_khld_h2_nominated_by',
    'ref_khld_h2_equipment_provided',
    'ref_khld_h2_commitment_signed',
    'ref_khld_h2_attended',
    'ref_khld_h2_consent'
  ] loop
    execute format($f$
      create table public.%I (
        id               uuid primary key default gen_random_uuid(),
        code             text not null unique,
        label_en         text not null,
        label_ar         text not null,
        sort_order       int  not null default 0,
        is_active        boolean not null default true,
        allows_free_text boolean not null default false,
        created_at       timestamptz not null default now(),
        updated_at       timestamptz not null default now(),
        created_by       uuid references auth.users(id),
        deleted_at       timestamptz
      )$f$, t);

    perform public.attach_standard_triggers(t);

    execute format('alter table public.%I enable row level security', t);
    execute format($f$create policy ref_read on public.%I
      for select to authenticated using (true)$f$, t);
    execute format($f$create policy ref_write on public.%I
      for all to authenticated
      using (public.is_coordinator())
      with check (public.is_coordinator())$f$, t);
  end loop;
end $outer$;

-- ── ref_khld_imp0_survey_round (imp0.survey_round) ──
insert into public.ref_khld_imp0_survey_round (code, label_en, label_ar, sort_order, allows_free_text) values
  ('n_2027_round', '2027 round', 'جولة ٢٠٢٧', 1, false),
  ('n_2028_round', '2028 round', 'جولة ٢٠٢٨', 2, false),
  ('n_2029_round', '2029 (end of Plan) round', 'جولة ٢٠٢٩ (نهاية الخطة)', 3, false);

-- ── ref_khld_imp0_int_place (imp0.int_place) ──
insert into public.ref_khld_imp0_int_place (code, label_en, label_ar, sort_order, allows_free_text) values
  ('in_the_park_during_an_activity', 'In the park during an activity', 'في الحديقة أثناء نشاط', 1, false),
  ('in_the_park_on_an_ordinary_day', 'In the park on an ordinary day', 'في الحديقة في يوم عادي', 2, false),
  ('at_home_in_the_neighbourhood', 'At home in the neighbourhood', 'في المنزل داخل الحي', 3, false),
  ('at_a_local_association', 'At a local association', 'في إحدى الجمعيات المحلية', 4, false),
  ('by_telephone', 'By telephone', 'هاتفياً', 5, false);

-- ── ref_khld_imp0_consent (imp0.consent) ──
insert into public.ref_khld_imp0_consent (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes', 'Yes — continue', 'نعم — يُستكمل', 1, false),
  ('no', 'No — end interview', 'لا — تُنهى المقابلة', 2, false);

-- ── ref_khld_sex (imp0.sex, so10.resp_sex, so20.sex, f2.sex, so40.sex, g1.sex, g2.sex, h2.sex) ──
insert into public.ref_khld_sex (code, label_en, label_ar, sort_order, allows_free_text) values
  ('female', 'Female', 'أنثى', 1, false),
  ('male', 'Male', 'ذكر', 2, false);

-- ── ref_khld_age_group (imp0.age_group, so20.age_group, so40.age_group, g1.age_group, g2.age_group) ──
insert into public.ref_khld_age_group (code, label_en, label_ar, sort_order, allows_free_text) values
  ('under_12', 'Under 12', 'أقل من ١٢', 1, false),
  ('12_14', '12–14', '١٢–١٤', 2, false),
  ('15_24', '15–24 (youth)', '١٥–٢٤ (شباب)', 3, false),
  ('25_34', '25–34', '٢٥–٣٤', 4, false),
  ('35_49', '35–49', '٣٥–٤٩', 5, false),
  ('50_64', '50–64', '٥٠–٦٤', 6, false),
  ('age_65_plus', '65 and above', '٦٥ وأكثر', 7, false);

-- ── ref_khld_nationality (imp0.nationality, so20.nationality, f2.nationality, so40.nationality, g1.nationality, g2.nationality, h2.nationality) ──
insert into public.ref_khld_nationality (code, label_en, label_ar, sort_order, allows_free_text) values
  ('jordanian', 'Jordanian (host community)', 'أردني (المجتمع المضيف)', 1, false),
  ('syrian_registered', 'Syrian refugee registered with UNHCR', 'لاجئ سوري مسجل لدى المفوضية', 2, false),
  ('syrian_unregistered', 'Syrian, not registered', 'سوري غير مسجل', 3, false),
  ('other', 'Other nationality', 'جنسية أخرى', 4, false),
  ('prefer_not_to_say', 'Prefer not to say', 'يفضل عدم الإفصاح', 5, false);

-- ── ref_khld_disability (imp0.disability, so20.disability, f2.disability, so40.disability, g1.disability, g2.disability, h2.disability) ──
insert into public.ref_khld_disability (code, label_en, label_ar, sort_order, allows_free_text) values
  ('no_difficulty', 'No difficulty', 'لا صعوبة', 1, false),
  ('some_difficulty', 'Some difficulty', 'صعوبة بعض الشيء', 2, false),
  ('a_lot_of_difficulty', 'A lot of difficulty', 'صعوبة كبيرة', 3, false),
  ('cannot_do_at_all', 'Cannot do at all', 'لا أستطيع على الإطلاق', 4, false),
  ('prefer_not_to_say', 'Prefer not to say', 'يفضل عدم الإفصاح', 5, false);

-- ── ref_khld_neighbourhood (imp0.neighbourhood, f2.neighbourhood, so40.neighbourhood, g1.neighbourhood, h2.neighbourhood) ──
insert into public.ref_khld_neighbourhood (code, label_en, label_ar, sort_order, allows_free_text) values
  ('new_khaldiyah', 'New Khaldiyah (Al-Karama)', 'الخالدية الجديدة (الكرامة)', 1, false),
  ('al_mabrouka', 'Al-Mabrouka', 'المبروكة', 2, false),
  ('old_khaldiyah', 'Old Khaldiyah', 'الخالدية القديمة', 3, false),
  ('al_mashrafa', 'Al-Mashrafa', 'المشرفة', 4, false),
  ('outside_the_municipality', 'Outside the municipality', 'خارج حدود البلدية', 5, false);

-- ── ref_khld_imp0_has_children (imp0.has_children.has_children_id) ──
insert into public.ref_khld_imp0_has_children (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes', 'Yes — number: ____', 'نعم — العدد: ____', 1, false),
  ('no', 'No', 'لا', 2, false);

-- ── ref_khld_imp0_visit_freq (imp0.visit_freq) ──
insert into public.ref_khld_imp0_visit_freq (code, label_en, label_ar, sort_order, allows_free_text) values
  ('never', 'Never', 'ولا مرة', 1, false),
  ('once_or_twice', 'Once or twice', 'مرة أو مرتين', 2, false),
  ('every_few_months', 'Every few months', 'كل بضعة أشهر', 3, false),
  ('about_monthly', 'About once a month', 'مرة شهرياً تقريباً', 4, false),
  ('weekly_or_more', 'Weekly or more often', 'أسبوعياً أو أكثر', 5, false);

-- ── ref_khld_imp0_activities_taken (imp0.activities_taken) ──
insert into public.ref_khld_imp0_activities_taken (code, label_en, label_ar, sort_order, allows_free_text) values
  ('cultural_or_artistic_activity', 'Cultural or artistic activity', 'نشاط ثقافي أو فني', 1, false),
  ('childrens_recreational_activity', 'Children''s recreational activity', 'نشاط ترفيهي للأطفال', 2, false),
  ('sports_activity', 'Sports activity', 'نشاط رياضي', 3, false),
  ('community_market_or_fair', 'Community market or fair', 'سوق أو بازار مجتمعي', 4, false),
  ('volunteer_action_day', 'Volunteer action day', 'يوم عمل تطوعي', 5, false),
  ('open_day_or_community_celebration', 'Open day or community celebration', 'يوم مفتوح أو احتفال مجتمعي', 6, false),
  ('educational_or_awareness_session', 'Educational or awareness session', 'جلسة توعوية أو تعليمية', 7, false),
  ('i_only_used_the_park_informally', 'I only used the park informally', 'استخدمت الحديقة بشكل غير منظم فقط', 8, false),
  ('none', 'None', 'لا شيء', 9, false);

-- ── ref_khld_imp0_accompanied_by (imp0.accompanied_by) ──
insert into public.ref_khld_imp0_accompanied_by (code, label_en, label_ar, sort_order, allows_free_text) values
  ('alone', 'Alone', 'بمفردي', 1, false),
  ('with_my_children', 'With my children', 'مع أطفالي', 2, false),
  ('with_my_family', 'With my family', 'مع أسرتي', 3, false),
  ('with_neighbours_or_friends', 'With neighbours or friends', 'مع الجيران أو الأصدقاء', 4, false),
  ('with_a_group_from_an_association_or_school', 'With a group from an association or school', 'مع مجموعة من جمعية أو مدرسة', 5, false);

-- ── ref_khld_imp0_mixed_presence (imp0.mixed_presence) ──
insert into public.ref_khld_imp0_mixed_presence (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_both_regularly', 'Yes, both regularly', 'نعم، المجتمعان بانتظام', 1, false),
  ('yes_sometimes', 'Yes, sometimes', 'نعم، أحياناً', 2, false),
  ('mostly_one_community_only', 'Mostly one community only', 'مجتمع واحد في الغالب', 3, false),
  ('i_could_not_tell', 'I could not tell', 'لم أستطع التمييز', 4, false);

-- ── ref_khld_imp0_new_contact (imp0.new_contact) ──
insert into public.ref_khld_imp0_new_contact (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_several_times', 'Yes, several times', 'نعم، عدة مرات', 1, false),
  ('yes_once_or_twice', 'Yes, once or twice', 'نعم، مرة أو مرتين', 2, false),
  ('no', 'No', 'لا', 3, false),
  ('prefer_not_to_say', 'Prefer not to say', 'يفضل عدم الإفصاح', 4, false);

-- ── ref_khld_agree_scale (imp0.opportunity_increase, so10.q_communication, so10.q_roles, so10.q_joint_planning, so10.q_followup, so10.q_transparency, so10.q_improved) ──
insert into public.ref_khld_agree_scale (code, label_en, label_ar, sort_order, allows_free_text) values
  ('strongly_agree', 'Strongly agree', 'أوافق بشدة', 1, false),
  ('agree', 'Agree', 'أوافق', 2, false),
  ('neither', 'Neither agree nor disagree', 'محايد', 3, false),
  ('disagree', 'Disagree', 'لا أوافق', 4, false),
  ('strongly_disagree', 'Strongly disagree', 'لا أوافق على الإطلاق', 5, false);

-- ── ref_khld_imp0_joint_activity (imp0.joint_activity) ──
insert into public.ref_khld_imp0_joint_activity (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_more_than_once', 'Yes, more than once', 'نعم، أكثر من مرة', 1, false),
  ('yes_once', 'Yes, once', 'نعم، مرة واحدة', 2, false),
  ('no', 'No', 'لا', 3, false),
  ('dont_know', 'Don''t know', 'لا أعرف', 4, false);

-- ── ref_khld_imp0_comfort_level (imp0.comfort_level) ──
insert into public.ref_khld_imp0_comfort_level (code, label_en, label_ar, sort_order, allows_free_text) values
  ('very_comfortable', 'Very comfortable', 'مرتاح جداً', 1, false),
  ('comfortable', 'Comfortable', 'مرتاح', 2, false),
  ('neutral', 'Neutral', 'محايد', 3, false),
  ('uncomfortable', 'Uncomfortable', 'غير مرتاح', 4, false),
  ('very_uncomfortable', 'Very uncomfortable', 'غير مرتاح على الإطلاق', 5, false);

-- ── ref_khld_yes_fully_partly_no (imp0.suitable_women_children, so20.feel_welcome) ──
insert into public.ref_khld_yes_fully_partly_no (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_fully', 'Yes, fully', 'نعم، تماماً', 1, false),
  ('partly', 'Partly', 'جزئياً', 2, false),
  ('no', 'No', 'لا', 3, false);

-- ── ref_khld_imp0_relations_change (imp0.relations_change) ──
insert into public.ref_khld_imp0_relations_change (code, label_en, label_ar, sort_order, allows_free_text) values
  ('improved_a_lot', 'Improved a lot', 'تحسنت كثيراً', 1, false),
  ('improved_somewhat', 'Improved somewhat', 'تحسنت إلى حد ما', 2, false),
  ('no_change', 'No change', 'لا تغيير', 3, false),
  ('worsened_somewhat', 'Worsened somewhat', 'تراجعت إلى حد ما', 4, false),
  ('worsened_a_lot', 'Worsened a lot', 'تراجعت كثيراً', 5, false),
  ('dont_know', 'Don''t know', 'لا أعرف', 6, false);

-- ── ref_khld_imp0_barriers (imp0.barriers) ──
insert into public.ref_khld_imp0_barriers (code, label_en, label_ar, sort_order, allows_free_text) values
  ('distance_or_transport', 'Distance or transport', 'المسافة أو المواصلات', 1, false),
  ('timing_of_activities_is_not_suitable', 'Timing of activities is not suitable', 'مواعيد الأنشطة غير مناسبة', 2, false),
  ('no_activities_that_suit_me_or_my_family', 'No activities that suit me or my family', 'لا توجد أنشطة تناسبني أو تناسب أسرتي', 3, false),
  ('lack_of_information_about_activities', 'Lack of information about activities', 'نقص المعلومات عن الأنشطة', 4, false),
  ('i_do_not_feel_welcome', 'I do not feel welcome', 'لا أشعر بالترحيب', 5, false),
  ('safety_concerns', 'Safety concerns', 'مخاوف تتعلق بالسلامة', 6, false),
  ('the_space_is_not_accessible_for_a_person_with_a', 'The space is not accessible for a person with a disability', 'المكان غير مهيأ لذوي الإعاقة', 7, false),
  ('cost', 'Cost', 'الكلفة', 8, false),
  ('family_does_not_approve', 'Family does not approve', 'عدم موافقة الأسرة', 9, false),
  ('nothing_limits_me', 'Nothing limits me', 'لا شيء يحد من مشاركتي', 10, false),
  ('other', 'Other (specify)', 'أخرى (تُحدد)', 11, true);

-- ── ref_khld_recontact (imp0.recontact, so40.recontact) ──
insert into public.ref_khld_recontact (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_phone', 'Yes — phone: ____', 'نعم — الهاتف: ____', 1, true),
  ('no', 'No', 'لا', 2, false);

-- ── ref_khld_so10_survey_round (so10.survey_round) ──
insert into public.ref_khld_so10_survey_round (code, label_en, label_ar, sort_order, allows_free_text) values
  ('n_2027', '2027', '٢٠٢٧', 1, false),
  ('n_2028', '2028', '٢٠٢٨', 2, false),
  ('n_2029', '2029', '٢٠٢٩', 3, false);

-- ── ref_khld_so10_areas_involved (so10.areas_involved) ──
insert into public.ref_khld_so10_areas_involved (code, label_en, label_ar, sort_order, allows_free_text) values
  ('park_rehabilitation_works_or_volunteer_campaigns', 'Park rehabilitation works or volunteer campaigns', 'أعمال تأهيل الحديقة أو الحملات التطوعية', 1, false),
  ('community_cultural_or_sports_activities', 'Community, cultural or sports activities', 'الأنشطة المجتمعية أو الثقافية أو الرياضية', 2, false),
  ('volunteer_mobilisation_and_the_volunteer_program', 'Volunteer mobilisation and the volunteer programme', 'حشد المتطوعين وبرنامج التطوع', 3, false),
  ('community_markets_and_fairs', 'Community markets and fairs', 'الأسواق والبازارات المجتمعية', 4, false),
  ('guidance_and_support_to_home_based_enterprises', 'Guidance and support to home-based enterprises', 'إرشاد ودعم المشاريع المنزلية', 5, false),
  ('community_coordination_committee', 'Community coordination committee', 'لجنة التنسيق المجتمعي', 6, false),
  ('in_kind_technical_or_financial_contribution', 'In-kind, technical or financial contribution', 'مساهمة عينية أو فنية أو مالية', 7, false),
  ('outreach_and_identification_of_target_groups', 'Outreach and identification of target groups', 'التوعية وتحديد الفئات المستهدفة', 8, false);

-- ── ref_khld_so10_focal_point (so10.focal_point) ──
insert into public.ref_khld_so10_focal_point (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_and_they_respond_promptly', 'Yes, and they respond promptly', 'نعم، ويستجيب بسرعة', 1, false),
  ('yes_but_responses_are_slow', 'Yes, but responses are slow', 'نعم، لكن الاستجابة بطيئة', 2, false),
  ('no_designated_focal_point', 'No designated focal point', 'لا توجد جهة اتصال محددة', 3, false),
  ('dont_know', 'Don''t know', 'لا أعرف', 4, false);

-- ── ref_khld_so10_overall_rating (so10.overall_rating) ──
insert into public.ref_khld_so10_overall_rating (code, label_en, label_ar, sort_order, allows_free_text) values
  ('very_effective', 'Very effective', 'فعال جداً', 1, false),
  ('effective', 'Effective', 'فعال', 2, false),
  ('neither_effective_nor_ineffective', 'Neither effective nor ineffective', 'لا فعال ولا غير فعال', 3, false),
  ('ineffective', 'Ineffective', 'غير فعال', 4, false),
  ('very_ineffective', 'Very ineffective', 'غير فعال على الإطلاق', 5, false);

-- ── ref_khld_so10_duplication (so10.duplication) ──
insert into public.ref_khld_so10_duplication (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_clearly', 'Yes, clearly', 'نعم، بشكل واضح', 1, false),
  ('to_some_extent', 'To some extent', 'إلى حد ما', 2, false),
  ('no', 'No', 'لا', 3, false),
  ('too_early_to_say', 'Too early to say', 'من المبكر الحكم', 4, false);

-- ── ref_khld_so10_obstacles (so10.obstacles) ──
insert into public.ref_khld_so10_obstacles (code, label_en, label_ar, sort_order, allows_free_text) values
  ('slow_or_unclear_communication', 'Slow or unclear communication', 'تواصل بطيء أو غير واضح', 1, false),
  ('no_single_point_of_contact', 'No single point of contact', 'عدم وجود نقطة اتصال واحدة', 2, false),
  ('roles_overlap_with_other_actors', 'Roles overlap with other actors', 'تداخل الأدوار مع جهات أخرى', 3, false),
  ('decisions_are_not_followed_up', 'Decisions are not followed up', 'عدم متابعة القرارات', 4, false),
  ('administrative_or_approval_delays', 'Administrative or approval delays', 'تأخر الإجراءات أو الموافقات', 5, false),
  ('limited_municipal_staff_time', 'Limited municipal staff time', 'ضيق وقت كوادر البلدية', 6, false),
  ('our_own_limited_capacity', 'Our own limited capacity', 'محدودية قدراتنا نحن', 7, false),
  ('unclear_arrangements_for_using_the_park', 'Unclear arrangements for using the park', 'عدم وضوح ترتيبات استخدام الحديقة', 8, false),
  ('no_obstacles', 'No obstacles', 'لا توجد معوقات', 9, false),
  ('other', 'Other (specify)', 'أخرى (تُحدد)', 10, true);

-- ── ref_khld_so10_continue_intent (so10.continue_intent) ──
insert into public.ref_khld_so10_continue_intent (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_at_the_same_level_or_more', 'Yes, at the same level or more', 'نعم، بالمستوى ذاته أو أكثر', 1, false),
  ('yes_but_at_a_reduced_level', 'Yes, but at a reduced level', 'نعم، لكن بمستوى أقل', 2, false),
  ('yes_if_certain_conditions_are_met', 'Yes, if certain conditions are met (specify)', 'نعم، بشرط تحقق شروط معينة (تُحدد)', 3, true),
  ('no', 'No (specify why)', 'لا (يُحدد السبب)', 4, true),
  ('undecided', 'Undecided', 'لم نحدد بعد', 5, false);

-- ── ref_khld_so10_evidence_ref (so10.evidence_ref) ──
insert into public.ref_khld_so10_evidence_ref (code, label_en, label_ar, sort_order, allows_free_text) values
  ('meeting_minutes', 'Meeting minutes', 'محاضر اجتماعات', 1, false),
  ('signed_partnership_or_cooperation_record', 'Signed partnership or cooperation record', 'سجل شراكة أو تعاون موقع', 2, false),
  ('contribution_or_delivery_records', 'Contribution or delivery records', 'سجلات مساهمات أو تسليم', 3, false),
  ('activity_reports', 'Activity reports', 'تقارير أنشطة', 4, false),
  ('none', 'None', 'لا شيء', 5, false);

-- ── ref_khld_a1_verif_round (a1.verif_round) ──
insert into public.ref_khld_a1_verif_round (code, label_en, label_ar, sort_order, allows_free_text) values
  ('first_verification', 'First verification (within six months of adoption)', 'التحقق الأول (خلال ستة أشهر من الإقرار)', 1, false),
  ('annual_review_2027', 'Annual review 2027', 'مراجعة سنوية ٢٠٢٧', 2, false),
  ('annual_review_2028', 'Annual review 2028', 'مراجعة سنوية ٢٠٢٨', 3, false),
  ('annual_review_2029', 'Annual review 2029', 'مراجعة سنوية ٢٠٢٩', 4, false);

-- ── ref_khld_a1_coordinator_assigned (a1.coordinator_assigned) · checklist statuses ──
insert into public.ref_khld_a1_coordinator_assigned (code, label_en, label_ar, sort_order, allows_free_text) values
  ('in_place_written_decision', 'In place — written decision', 'متوفر — بقرار مكتوب', 1, false),
  ('partly_assigned_informally', 'Partly in place — assigned informally', 'متوفر جزئياً — تعيين غير رسمي', 2, false),
  ('not_in_place', 'Not in place', 'غير متوفر', 3, false);

-- ── ref_khld_checklist_status (a1.coordinator_tor, a1.stakeholder_map, a1.comms_arrangements, a1.contribution_tracking, a1.requirements_list, b1.spaces_defined, b1.layout_plan, b1.noncommercial_rule, b1.request_procedure, b1.equitable_access, b1.accessibility, b1.maintenance_split, b1.supervision, b1.feedback_channel, e1.membership_list, e1.minutes_template, f1.registration_form, f1.roles_defined, f1.assignment_procedure, f1.coordination_procedure, f1.inclusive_roles, f1.data_consent) · checklist statuses ──
insert into public.ref_khld_checklist_status (code, label_en, label_ar, sort_order, allows_free_text) values
  ('in_place', 'In place', 'متوفر', 1, false),
  ('partly', 'Partly in place', 'متوفر جزئياً', 2, false),
  ('not_in_place', 'Not in place', 'غير متوفر', 3, false);

-- ── ref_khld_a1_stakeholder_count (a1.stakeholder_count) · cells ──
insert into public.ref_khld_a1_stakeholder_count (code, label_en, label_ar, sort_order, allows_free_text) values
  ('associations', 'Associations', 'الجمعيات', 1, false),
  ('youth_initiatives', 'Youth initiatives', 'المبادرات الشبابية', 2, false),
  ('cultural', 'Cultural', 'الثقافية', 3, false),
  ('schools_universities', 'Schools/universities', 'المدارس/الجامعات', 4, false),
  ('private_sector', 'Private sector', 'القطاع الخاص', 5, false),
  ('government', 'Government', 'الحكومية', 6, false),
  ('donors', 'Donors', 'الجهات المانحة', 7, false),
  ('total', 'Total', 'المجموع', 8, false);

-- ── ref_khld_a1_tracking_format (a1.tracking_format) ──
insert into public.ref_khld_a1_tracking_format (code, label_en, label_ar, sort_order, allows_free_text) values
  ('paper_register', 'Paper register', 'سجل ورقي', 1, false),
  ('excel_file', 'Excel file', 'ملف إكسل', 2, false),
  ('digital_form', 'Digital form (e.g. Kobo)', 'نموذج إلكتروني (مثل كوبو)', 3, false),
  ('integrated_in_municipal_system', 'Integrated in municipal system', 'مدمج في نظام البلدية', 4, false),
  ('none', 'None', 'لا يوجد', 5, false);

-- ── ref_khld_a1_partnerships_concluded (a1.partnerships_concluded) · cells ──
insert into public.ref_khld_a1_partnerships_concluded (code, label_en, label_ar, sort_order, allows_free_text) values
  ('associations', 'Associations', 'الجمعيات', 1, false),
  ('cultural', 'Cultural', 'الثقافية', 2, false),
  ('schools_universities', 'Schools/universities', 'المدارس/الجامعات', 3, false),
  ('private_sector', 'Private sector', 'القطاع الخاص', 4, false),
  ('government', 'Government', 'الحكومية', 5, false),
  ('donors', 'Donors', 'الجهات المانحة', 6, false),
  ('total', 'Total', 'المجموع', 7, false);

-- ── ref_khld_a1_zaha_coordination (a1.zaha_coordination) · checklist statuses ──
insert into public.ref_khld_a1_zaha_coordination (code, label_en, label_ar, sort_order, allows_free_text) values
  ('in_place_calendar_issued', 'In place — calendar issued', 'متوفر — صدرت الروزنامة', 1, false),
  ('partly_discussions_held_no_calendar', 'Partly in place — discussions held, no calendar', 'متوفر جزئياً — عُقدت مباحثات دون روزنامة', 2, false),
  ('not_in_place', 'Not in place', 'غير متوفر', 3, false);

-- ── ref_khld_a1_periodic_updates (a1.periodic_updates) · checklist statuses ──
insert into public.ref_khld_a1_periodic_updates (code, label_en, label_ar, sort_order, allows_free_text) values
  ('in_place_regularly', 'In place — regularly', 'متوفر — بانتظام', 1, false),
  ('partly_occasionally', 'Partly in place — occasionally', 'متوفر جزئياً — بشكل متقطع', 2, false),
  ('not_in_place', 'Not in place', 'غير متوفر', 3, false);

-- ── ref_khld_a1_council_decision (a1.council_decision) ──
insert into public.ref_khld_a1_council_decision (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_decision_no_and_date', 'Yes — decision no. and date: ____', 'نعم — رقم القرار وتاريخه: ____', 1, true),
  ('submitted_pending_decision', 'Submitted, pending decision', 'مقدم وبانتظار القرار', 2, false),
  ('not_submitted', 'Not submitted', 'لم يُقدَّم', 3, false);

-- ── ref_khld_a1_evidence_attached (a1.evidence_attached) ──
insert into public.ref_khld_a1_evidence_attached (code, label_en, label_ar, sort_order, allows_free_text) values
  ('appointment_decision', 'Appointment decision', 'قرار التعيين', 1, false),
  ('terms_of_reference', 'Terms of reference', 'وصف المهام', 2, false),
  ('stakeholder_map_file', 'Stakeholder map file', 'ملف خريطة أصحاب المصلحة', 3, false),
  ('rehabilitation_requirements_list', 'Rehabilitation requirements list', 'قائمة احتياجات التأهيل', 4, false),
  ('contribution_register_extract', 'Contribution register extract', 'مستخرج سجل المساهمات', 5, false),
  ('minutes_of_introductory_meetings', 'Minutes of introductory meetings', 'محاضر اللقاءات التعريفية', 6, false),
  ('programming_calendar', 'Programming calendar', 'روزنامة البرامج', 7, false),
  ('council_decision', 'Council decision', 'قرار المجلس', 8, false),
  ('periodic_update_reports', 'Periodic update reports', 'تقارير التحديث الدورية', 9, false);

-- ── ref_khld_a2_venue (a2.venue) ──
insert into public.ref_khld_a2_venue (code, label_en, label_ar, sort_order, allows_free_text) values
  ('municipality_building', 'Municipality building', 'مبنى البلدية', 1, false),
  ('al_khalidiyah_public_park', 'Al Khalidiyah Public Park', 'حديقة الخالدية العامة', 2, false),
  ('premises_of_a_local_association', 'Premises of a local association', 'مقر إحدى الجمعيات المحلية', 3, false),
  ('zaha_cultural_centre', 'Zaha Cultural Centre', 'مركز زها الثقافي', 4, false),
  ('school_or_university', 'School or university', 'مدرسة أو جامعة', 5, false),
  ('online', 'Online', 'عن بُعد', 6, false),
  ('other', 'Other', 'أخرى', 7, true);

-- ── ref_khld_a2_meeting_type (a2.meeting_type) ──
insert into public.ref_khld_a2_meeting_type (code, label_en, label_ar, sort_order, allows_free_text) values
  ('regular_partner_coordination_meeting', 'Regular partner coordination meeting', 'اجتماع تنسيقي دوري مع الشركاء', 1, false),
  ('introductory_meeting_with_potential_partner', 'Introductory meeting with potential partner(s)', 'لقاء تعريفي مع شريك أو شركاء محتملين', 2, false),
  ('progress_review_with_the_community_coordination', 'Progress review with the community coordination committee', 'اجتماع مراجعة تقدم مع لجنة التنسيق المجتمعي', 3, false),
  ('joint_activity_planning_meeting', 'Joint activity planning meeting', 'اجتماع تخطيط مشترك لنشاط', 4, false),
  ('ad_hoc_problem_solving_meeting', 'Ad-hoc problem-solving meeting', 'اجتماع طارئ لمعالجة مشكلة', 5, false),
  ('meeting_with_donors_or_development_partners', 'Meeting with donors or development partners', 'اجتماع مع جهات مانحة أو شركاء تنمويين', 6, false);

-- ── ref_khld_a2_convened_by (a2.convened_by) ──
insert into public.ref_khld_a2_convened_by (code, label_en, label_ar, sort_order, allows_free_text) values
  ('mayor_head_of_municipal_committee', 'Mayor / head of municipal committee', 'رئيس البلدية / رئيس اللجنة البلدية', 1, false),
  ('executive_director', 'Executive Director', 'المدير التنفيذي', 2, false),
  ('community_coordinator', 'Community coordinator', 'المنسق المجتمعي', 3, false),
  ('community_coordination_committee', 'Community coordination committee', 'لجنة التنسيق المجتمعي', 4, false),
  ('jointly_with_a_partner', 'Jointly with a partner', 'بالتشارك مع أحد الشركاء', 5, false);

-- ── ref_khld_a2_pillars_discussed (a2.pillars_discussed) ──
insert into public.ref_khld_a2_pillars_discussed (code, label_en, label_ar, sort_order, allows_free_text) values
  ('so1_partnerships_and_institutional_sustainabilit', 'SO1 — Partnerships and institutional sustainability', 'الهدف ١ — الشراكات والاستدامة المؤسسية', 1, false),
  ('so2_park_rehabilitation_and_activation', 'SO2 — Park rehabilitation and activation', 'الهدف ٢ — تأهيل الحديقة وتفعيلها', 2, false),
  ('so3_community_participation_and_volunteerism', 'SO3 — Community participation and volunteerism', 'الهدف ٣ — المشاركة المجتمعية والتطوع', 3, false),
  ('so4_household_producers_and_community_markets', 'SO4 — Household producers and community markets', 'الهدف ٤ — المنتجون المنزليون والأسواق المجتمعية', 4, false),
  ('cross_cutting', 'Cross-cutting (risk, monitoring, resources)', 'قضايا شاملة (المخاطر، المتابعة، الموارد)', 5, false);

-- ── ref_khld_a2_orgs_by_type (a2.orgs_by_type) · cells ──
insert into public.ref_khld_a2_orgs_by_type (code, label_en, label_ar, sort_order, allows_free_text) values
  ('local_associations', 'Local associations', 'جمعيات محلية', 1, false),
  ('womens_organisations', 'Women''s organisations', 'مؤسسات نسائية', 2, false),
  ('youth_initiatives', 'Youth initiatives', 'مبادرات شبابية', 3, false),
  ('cultural_institutions', 'Cultural institutions', 'مؤسسات ثقافية', 4, false),
  ('schools_universities', 'Schools/universities', 'مدارس/جامعات', 5, false),
  ('private_sector', 'Private sector', 'القطاع الخاص', 6, false),
  ('government_entities', 'Government entities', 'جهات حكومية', 7, false),
  ('donors_development_partners', 'Donors/development partners', 'جهات مانحة/شركاء تنمويون', 8, false);

-- ── ref_khld_a2_attendees_breakdown (a2.attendees_breakdown) · cells ──
insert into public.ref_khld_a2_attendees_breakdown (code, label_en, label_ar, sort_order, allows_free_text) values
  ('women', 'Women', 'نساء', 1, false),
  ('men', 'Men', 'رجال', 2, false),
  ('syrian_refugees', 'Syrian refugees', 'لاجئون سوريون', 3, false),
  ('persons_with_disabilities', 'Persons with disabilities', 'ذوو إعاقة', 4, false),
  ('youth_15_24', 'Youth 15–24', 'شباب ١٥–٢٤', 5, false);

-- ── ref_khld_a2_new_partners (a2.new_partners) ──
insert into public.ref_khld_a2_new_partners (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_names', 'Yes — names: ____', 'نعم — الأسماء: ____', 1, true),
  ('no', 'No', 'لا', 2, false);

-- ── ref_khld_a2_prev_followup (a2.prev_followup) ──
insert into public.ref_khld_a2_prev_followup (code, label_en, label_ar, sort_order, allows_free_text) values
  ('all_implemented', 'All implemented', 'نُفذت جميعها', 1, false),
  ('most_implemented', 'Most implemented', 'نُفذ معظمها', 2, false),
  ('partly_implemented', 'Partly implemented', 'نُفذت جزئياً', 3, false),
  ('not_implemented', 'Not implemented', 'لم تُنفذ', 4, false),
  ('first_meeting_not_applicable', 'First meeting — not applicable', 'الاجتماع الأول — لا ينطبق', 5, false);

-- ── ref_khld_a2_contributions_pledged (a2.contributions_pledged) ──
insert into public.ref_khld_a2_contributions_pledged (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_record_each_on_form_khld_so1_a3', 'Yes — record each on form KHLD-SO1-A3', 'نعم — تُسجَّل كل مساهمة على نموذج المؤشر KHLD-SO1-A3', 1, false),
  ('no', 'No', 'لا', 2, false);

-- ── ref_khld_a2_minutes_prepared (a2.minutes_prepared) ──
insert into public.ref_khld_a2_minutes_prepared (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_filed', 'Yes, prepared and filed', 'نعم، أُعدّ وأُرشف', 1, false),
  ('prepared_not_signed', 'Prepared, not yet signed', 'أُعدّ ولم يُوقّع بعد', 2, false),
  ('not_prepared', 'Not prepared', 'لم يُعدّ', 3, false);

-- ── ref_khld_a3_status (a3.status) ──
insert into public.ref_khld_a3_status (code, label_en, label_ar, sort_order, allows_free_text) values
  ('pledged', 'Pledged, not yet received', 'مُتعهد بها ولم تُستلم بعد', 1, false),
  ('received_full', 'Received in full', 'مستلمة بالكامل', 2, false),
  ('partly_received', 'Partly received', 'مستلمة جزئياً', 3, false),
  ('cancelled', 'Cancelled or withdrawn', 'ملغاة أو مسحوبة', 4, false);

-- ── ref_khld_a3_source_meeting (a3.source_meeting) ──
insert into public.ref_khld_a3_source_meeting (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_meeting_reference', 'Yes — meeting reference: ____', 'نعم — المرجع: ____', 1, true),
  ('no_direct_approach', 'No — direct approach', 'لا — تواصل مباشر', 2, false),
  ('no_contributors_own_initiative', 'No — contributor''s own initiative', 'لا — بمبادرة من الجهة المساهمة', 3, false);

-- ── ref_khld_a3_contributor_type (a3.contributor_type) ──
insert into public.ref_khld_a3_contributor_type (code, label_en, label_ar, sort_order, allows_free_text) values
  ('local_charitable_or_development_association', 'Local charitable or development association', 'جمعية خيرية أو تنموية محلية', 1, false),
  ('womens_organisation', 'Women''s organisation', 'مؤسسة نسائية', 2, false),
  ('youth_initiative_or_volunteer_group', 'Youth initiative or volunteer group', 'مبادرة شبابية أو مجموعة تطوعية', 3, false),
  ('cultural_institution', 'Cultural institution (e.g. Zaha Cultural Centre)', 'مؤسسة ثقافية (مثل مركز زها الثقافي)', 4, false),
  ('school', 'School', 'مدرسة', 5, false),
  ('university', 'University', 'جامعة', 6, false),
  ('private_sector_business_or_trader', 'Private sector business or trader', 'منشأة أو تاجر من القطاع الخاص', 7, false),
  ('government_entity', 'Government entity', 'جهة حكومية', 8, false),
  ('donor_or_development_partner', 'Donor or development partner', 'جهة مانحة أو شريك تنموي', 9, false),
  ('other', 'Other', 'أخرى', 10, true),
  ('individual_community_member', 'Individual community member', 'فرد من أبناء المجتمع المحلي', 11, false);

-- ── ref_khld_a3_csr_linked (a3.csr_linked) ──
insert into public.ref_khld_a3_csr_linked (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes', 'Yes', 'نعم', 1, false),
  ('no', 'No', 'لا', 2, false),
  ('not_applicable', 'Not applicable', 'لا ينطبق', 3, false);

-- ── ref_khld_a3_first_contribution (a3.first_contribution) ──
insert into public.ref_khld_a3_first_contribution (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes', 'Yes', 'نعم', 1, false),
  ('no_number_of_previous_contributions', 'No — number of previous contributions: ____', 'لا — عدد المساهمات السابقة: ____', 2, true);

-- ── ref_khld_a3_contribution_type (a3.contribution_type) ──
insert into public.ref_khld_a3_contribution_type (code, label_en, label_ar, sort_order, allows_free_text) values
  ('cash_or_financial_grant', 'Cash or financial grant', 'نقد أو منحة مالية', 1, false),
  ('in_kind_goods_and_materials', 'In-kind goods and materials (plants, paint, benches, play equipment, cleaning tools, lighting)', 'مواد ومستلزمات عينية (أشتال، دهان، مقاعد، ألعاب أطفال، أدوات تنظيف، إنارة)', 2, false),
  ('in_kind_services', 'In-kind services (transport, printing, catering, waste removal)', 'خدمات عينية (نقل، طباعة، تغذية، ترحيل نفايات)', 3, false),
  ('technical_expertise', 'Technical expertise (design, engineering advice, training delivery)', 'خبرة فنية (تصميم، استشارة هندسية، تنفيذ تدريب)', 4, false),
  ('volunteer_labour', 'Volunteer labour', 'عمل تطوعي', 5, false),
  ('use_of_equipment_vehicle_or_venue', 'Use of equipment, vehicle or venue', 'إتاحة معدات أو مركبة أو مقر', 6, false),
  ('sponsorship_of_a_specific_activity_or_market_day', 'Sponsorship of a specific activity or market day', 'رعاية نشاط محدد أو يوم سوق', 7, false),
  ('cultural_or_educational_programming_content', 'Cultural or educational programming content', 'محتوى برامج ثقافية أو تعليمية', 8, false);

-- ── ref_khld_a3_valuation_basis (a3.valuation_basis) ──
insert into public.ref_khld_a3_valuation_basis (code, label_en, label_ar, sort_order, allows_free_text) values
  ('invoice_or_receipt_from_the_contributor', 'Invoice or receipt from the contributor', 'فاتورة أو إيصال من الجهة المساهمة', 1, false),
  ('local_market_price_estimate', 'Local market price estimate', 'تقدير بحسب سعر السوق المحلي', 2, false),
  ('value_declared_by_the_contributor', 'Value declared by the contributor', 'قيمة أعلنتها الجهة المساهمة', 3, false),
  ('municipal_engineers_estimate', 'Municipal engineer''s estimate', 'تقدير مهندس البلدية', 4, false),
  ('volunteer_hours_local_daily_wage_rate', 'Volunteer hours × local daily wage rate', 'ساعات التطوع × الأجر اليومي المحلي', 5, false),
  ('no_estimate_possible', 'No estimate possible', 'لا يمكن التقدير', 6, false);

-- ── ref_khld_a3_supports_objective (a3.supports_objective) ──
insert into public.ref_khld_a3_supports_objective (code, label_en, label_ar, sort_order, allows_free_text) values
  ('so1_partnerships', 'SO1 — Partnerships (Activity A or B)', 'الهدف ١ — الشراكات (النشاط أ أو ب)', 1, false),
  ('so2_park_rehabilitation', 'SO2 — Park rehabilitation (Activity C)', 'الهدف ٢ — تأهيل الحديقة (النشاط ج)', 2, false),
  ('so2_community_activities_in_the_park', 'SO2 — Community activities in the park (Activity D)', 'الهدف ٢ — الأنشطة المجتمعية في الحديقة (النشاط د)', 3, false),
  ('so3_committee_or_volunteer_programme', 'SO3 — Committee or volunteer programme (Activity E or F)', 'الهدف ٣ — اللجنة أو برنامج التطوع (النشاط هـ أو و)', 4, false),
  ('so4_enterprise_guidance', 'SO4 — Enterprise guidance (Activity G)', 'الهدف ٤ — إرشاد المشاريع (النشاط ز)', 5, false),
  ('so4_community_markets', 'SO4 — Community markets (Activity H)', 'الهدف ٤ — الأسواق المجتمعية (النشاط ح)', 6, false);

-- ── ref_khld_a3_municipal_acceptance (a3.municipal_acceptance) ──
insert into public.ref_khld_a3_municipal_acceptance (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_receipt_or_decision_no', 'Yes — receipt or decision no.: ____', 'نعم — رقم الإيصال أو القرار: ____', 1, true),
  ('pending_administrative_processing', 'Pending administrative processing', 'قيد الإجراء الإداري', 2, false),
  ('no_reason', 'No — reason: ____', 'لا — السبب: ____', 3, true);

-- ── ref_khld_a3_conditions (a3.conditions) ──
insert into public.ref_khld_a3_conditions (code, label_en, label_ar, sort_order, allows_free_text) values
  ('no_conditions', 'No conditions', 'بلا شروط', 1, false),
  ('yes_describe', 'Yes — describe: ____', 'نعم — تُوصف: ____', 2, true);

-- ── ref_khld_a3_acknowledged (a3.acknowledged) ──
insert into public.ref_khld_a3_acknowledged (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_both', 'Yes, both', 'نعم، الأمران', 1, false),
  ('acknowledged_to_the_contributor_only', 'Acknowledged to the contributor only', 'شُكرت الجهة المساهمة فقط', 2, false),
  ('recorded_in_the_update_only', 'Recorded in the update only', 'سُجلت في التحديث فقط', 3, false),
  ('not_yet', 'Not yet', 'لم يتم بعد', 4, false);

-- ── ref_khld_a3_evidence_attached (a3.evidence_attached) ──
insert into public.ref_khld_a3_evidence_attached (code, label_en, label_ar, sort_order, allows_free_text) values
  ('delivery_note_or_receipt', 'Delivery note or receipt', 'سند تسليم أو إيصال', 1, false),
  ('invoice', 'Invoice', 'فاتورة', 2, false),
  ('photographs_of_the_items_delivered', 'Photographs of the items delivered', 'صور للمواد المسلَّمة', 3, false),
  ('contributor_letter_or_mou', 'Contributor letter or MoU', 'مخاطبة الجهة المساهمة أو مذكرة تفاهم', 4, false),
  ('volunteer_attendance_sheet', 'Volunteer attendance sheet', 'كشف حضور المتطوعين', 5, false),
  ('municipal_acceptance_decision', 'Municipal acceptance decision', 'قرار البلدية بالقبول', 6, false),
  ('none', 'None', 'لا شيء', 7, false);

-- ── ref_khld_b1_protocol_exists (b1.protocol_exists) · checklist statuses ──
insert into public.ref_khld_b1_protocol_exists (code, label_en, label_ar, sort_order, allows_free_text) values
  ('in_place_approved', 'In place — approved', 'متوفر — معتمد', 1, false),
  ('partly_drafted_not_approved', 'Partly in place — drafted, not approved', 'متوفر جزئياً — مُعدّ ولم يُعتمد', 2, false),
  ('not_in_place', 'Not in place', 'غير متوفر', 3, false);

-- ── ref_khld_b1_activity_calendar (b1.activity_calendar) · checklist statuses ──
insert into public.ref_khld_b1_activity_calendar (code, label_en, label_ar, sort_order, allows_free_text) values
  ('in_place_prepared_and_published', 'In place — prepared and published', 'متوفرة — أُعدت وأُعلنت', 1, false),
  ('partly_prepared_not_published', 'Partly in place — prepared, not published', 'متوفرة جزئياً — أُعدت ولم تُعلن', 2, false),
  ('not_in_place', 'Not in place', 'غير متوفرة', 3, false);

-- ── ref_khld_b1_calendar_horizon (b1.calendar_horizon) ──
insert into public.ref_khld_b1_calendar_horizon (code, label_en, label_ar, sort_order, allows_free_text) values
  ('monthly', 'Monthly', 'شهرية', 1, false),
  ('quarterly', 'Quarterly', 'ربعية', 2, false),
  ('seasonal', 'Seasonal', 'موسمية', 3, false),
  ('annual', 'Annual', 'سنوية', 4, false),
  ('no_fixed_horizon', 'No fixed horizon', 'بدون أفق زمني محدد', 5, false);

-- ── ref_khld_b1_communicated (b1.communicated) ──
insert into public.ref_khld_b1_communicated (code, label_en, label_ar, sort_order, allows_free_text) values
  ('notice_board_at_the_municipality', 'Notice board at the Municipality', 'لوحة إعلانات في البلدية', 1, false),
  ('sign_or_notice_board_at_the_park', 'Sign or notice board at the park', 'لوحة أو لافتة في الحديقة', 2, false),
  ('municipal_social_media_page', 'Municipal social media page', 'صفحة البلدية على وسائل التواصل', 3, false),
  ('through_local_associations', 'Through local associations', 'من خلال الجمعيات المحلية', 4, false),
  ('mosque_or_community_announcements', 'Mosque or community announcements', 'إعلانات المساجد أو الإعلانات المجتمعية', 5, false),
  ('distributed_to_partners_in_writing', 'Distributed to partners in writing', 'وُزعت على الشركاء كتابةً', 6, false),
  ('not_yet_communicated', 'Not yet communicated', 'لم تُعمَّم بعد', 7, false);

-- ── ref_khld_b1_evidence_attached (b1.evidence_attached) ──
insert into public.ref_khld_b1_evidence_attached (code, label_en, label_ar, sort_order, allows_free_text) values
  ('approved_operational_protocol', 'Approved operational protocol', 'البروتوكول التشغيلي المعتمد', 1, false),
  ('council_or_executive_decision', 'Council or executive decision', 'قرار المجلس أو القرار التنفيذي', 2, false),
  ('activity_calendar', 'Activity calendar', 'روزنامة الأنشطة', 3, false),
  ('blank_use_request_form', 'Blank use-request form', 'نموذج طلب الاستخدام الفارغ', 4, false),
  ('site_layout_plan', 'Site layout plan', 'المخطط التوزيعي للموقع', 5, false),
  ('copies_of_public_notices', 'Copies of public notices', 'نسخ من الإعلانات العامة', 6, false),
  ('feedback_log_extract', 'Feedback log extract', 'مستخرج من سجل التغذية الراجعة', 7, false);

-- ── ref_khld_so20_collection_mode (so20.collection_mode) ──
insert into public.ref_khld_so20_collection_mode (code, label_en, label_ar, sort_order, allows_free_text) values
  ('written_form_completed_by_the_participant', 'Written form completed by the participant', 'نموذج مكتوب عبّأه المشارك', 1, false),
  ('short_interview_at_the_exit', 'Short interview at the exit', 'مقابلة قصيرة عند الخروج', 2, false),
  ('verbal_feedback_recorded_by_the_organiser', 'Verbal feedback recorded by the organiser', 'تغذية راجعة شفهية سجلها المنظم', 3, false),
  ('group_discussion_at_the_end_of_the_activity', 'Group discussion at the end of the activity', 'نقاش جماعي في ختام النشاط', 4, false),
  ('telephone_follow_up', 'Telephone follow-up', 'متابعة هاتفية', 5, false);

-- ── ref_khld_so20_overall_satisfaction (so20.overall_satisfaction) ──
insert into public.ref_khld_so20_overall_satisfaction (code, label_en, label_ar, sort_order, allows_free_text) values
  ('very_satisfied', 'Very satisfied', 'راضٍ جداً', 1, false),
  ('satisfied', 'Satisfied', 'راضٍ', 2, false),
  ('neither', 'Neither satisfied nor dissatisfied', 'لا راضٍ ولا غير راضٍ', 3, false),
  ('dissatisfied', 'Dissatisfied', 'غير راضٍ', 4, false),
  ('very_dissatisfied', 'Very dissatisfied', 'غير راضٍ على الإطلاق', 5, false);

-- ── ref_khld_so20_feel_safe (so20.feel_safe) ──
insert into public.ref_khld_so20_feel_safe (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_always', 'Yes, always', 'نعم، دائماً', 1, false),
  ('mostly', 'Mostly', 'في معظم الأوقات', 2, false),
  ('sometimes', 'Sometimes', 'أحياناً', 3, false),
  ('no', 'No', 'لا', 4, false);

-- ── ref_khld_so20_suitable_women_children (so20.suitable_women_children) ──
insert into public.ref_khld_so20_suitable_women_children (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes_fully', 'Yes, fully', 'نعم، تماماً', 1, false),
  ('partly', 'Partly', 'جزئياً', 2, false),
  ('no_why', 'No — why: ____', 'لا — السبب: ____', 3, true);

-- ── ref_khld_so20_participate_freely (so20.participate_freely) ──
insert into public.ref_khld_so20_participate_freely (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes', 'Yes', 'نعم', 1, false),
  ('partly', 'Partly', 'جزئياً', 2, false),
  ('no', 'No', 'لا', 3, false);

-- ── ref_khld_so20_facility_item (so20.rate_facilities) · cells ──
insert into public.ref_khld_so20_facility_item (code, label_en, label_ar, sort_order, allows_free_text) values
  ('cleanliness', 'cleanliness', 'النظافة', 1, false),
  ('childrens_play_equipment', 'children''s play equipment', 'ألعاب الأطفال', 2, false),
  ('seating_and_shade', 'seating and shade', 'المقاعد والظل', 3, false),
  ('lighting', 'lighting', 'الإنارة', 4, false),
  ('toilets', 'toilets', 'دورات المياه', 5, false),
  ('sports_field', 'sports field', 'الملعب', 6, false),
  ('drinking_water', 'drinking water', 'مياه الشرب', 7, false),
  ('accessibility_for_persons_with_disabilities', 'accessibility for persons with disabilities', 'تهيئة المكان لذوي الإعاقة', 8, false),
  ('suitability_of_the_space_for_women', 'suitability of the space for women', 'مناسبة المكان للنساء', 9, false);

-- ── ref_khld_so20_facility_rating (so20.rate_facilities) · cells ──
insert into public.ref_khld_so20_facility_rating (code, label_en, label_ar, sort_order, allows_free_text) values
  ('good', 'Good', 'جيد', 1, false),
  ('acceptable', 'Acceptable', 'مقبول', 2, false),
  ('poor', 'Poor', 'سيئ', 3, false),
  ('not_available', 'Not available', 'غير متوفر', 4, false);

-- ── ref_khld_so20_activity_suitable (so20.activity_suitable) ──
insert into public.ref_khld_so20_activity_suitable (code, label_en, label_ar, sort_order, allows_free_text) values
  ('very_suitable', 'Very suitable', 'مناسب جداً', 1, false),
  ('somewhat_suitable', 'Somewhat suitable', 'مناسب إلى حد ما', 2, false),
  ('not_suitable_why', 'Not suitable — why: ____', 'غير مناسب — السبب: ____', 3, true);

-- ── ref_khld_so20_timing_convenient (so20.timing_convenient) ──
insert into public.ref_khld_so20_timing_convenient (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes', 'Yes', 'نعم', 1, false),
  ('no_preferred_day', 'No — preferred day: ____ preferred time: morning / afternoon / evening', 'لا — اليوم المفضل: ____ الوقت المفضل: صباحاً / بعد الظهر / مساءً', 2, true);

-- ── ref_khld_so20_how_heard (so20.how_heard) ──
insert into public.ref_khld_so20_how_heard (code, label_en, label_ar, sort_order, allows_free_text) values
  ('municipal_announcement_or_notice_board', 'Municipal announcement or notice board', 'إعلان أو لوحة إعلانات البلدية', 1, false),
  ('municipal_social_media_page', 'Municipal social media page', 'صفحة البلدية على وسائل التواصل', 2, false),
  ('a_local_association', 'A local association', 'إحدى الجمعيات المحلية', 3, false),
  ('school', 'School', 'المدرسة', 4, false),
  ('mosque_announcement', 'Mosque announcement', 'إعلان المسجد', 5, false),
  ('family_neighbours_or_friends', 'Family, neighbours or friends', 'الأسرة أو الجيران أو الأصدقاء', 6, false),
  ('i_was_passing_by_the_park', 'I was passing by the park', 'كنت أمر بجانب الحديقة', 7, false),
  ('other', 'Other', 'أخرى', 8, true);

-- ── ref_khld_so20_would_return (so20.would_return) ──
insert into public.ref_khld_so20_would_return (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes', 'Yes', 'نعم', 1, false),
  ('maybe', 'Maybe', 'ربما', 2, false),
  ('no', 'No', 'لا', 3, false);

-- ── ref_khld_c1_facility_type (c1.facility_type) ──
insert into public.ref_khld_c1_facility_type (code, label_en, label_ar, sort_order, allows_free_text) values
  ('site_clearing_and_deep_cleaning', 'Site clearing and deep cleaning', 'تنظيف الموقع وتنظيف شامل', 1, false),
  ('seating_and_benches', 'Seating and benches', 'مقاعد وجلسات', 2, false),
  ('childrens_play_equipment', 'Children''s play equipment', 'ألعاب أطفال', 3, false),
  ('landscaping_and_planting', 'Landscaping and planting', 'تشجير وتنسيق حدائق', 4, false),
  ('irrigation_and_water_points', 'Irrigation and water points', 'شبكة ريّ ونقاط مياه', 5, false),
  ('sports_field_upgrade', 'Sports field upgrade', 'تطوير الملعب', 6, false),
  ('lighting', 'Lighting', 'إنارة', 7, false),
  ('fencing_and_gates', 'Fencing and gates', 'تسوير وبوابات', 8, false),
  ('toilets', 'Toilets', 'دورات مياه', 9, false),
  ('stormwater_drainage', 'Stormwater drainage', 'تصريف مياه الأمطار', 10, false),
  ('pavements_and_internal_pathways', 'Pavements and internal pathways', 'أرصفة وممرات داخلية', 11, false),
  ('shade_structures', 'Shade structures', 'مظلات', 12, false),
  ('accessibility_features', 'Accessibility features (ramps, accessible path, accessible toilet)', 'عناصر تهيئة البيئة لذوي الإعاقة (منحدرات، ممر مهيأ، دورة مياه مهيأة)', 13, false),
  ('waste_bins', 'Waste bins', 'حاويات نفايات', 14, false),
  ('signage_and_notice_board', 'Signage and notice board', 'لوحات إرشادية ولوحة إعلانات', 15, false),
  ('kiosk_or_market_area_preparation', 'Kiosk or market area preparation', 'تهيئة منطقة الأكشاك أو السوق', 16, false),
  ('other', 'Other', 'أخرى', 17, true);

-- ── ref_khld_c1_on_priority_list (c1.on_priority_list.on_priority_list_id) ──
insert into public.ref_khld_c1_on_priority_list (code, label_en, label_ar, sort_order, allows_free_text) values
  ('yes', 'Yes — priority rank: ____', 'نعم — ترتيب الأولوية: ____', 1, false),
  ('no', 'No — added later, justification: ____', 'لا — أُضيف لاحقاً، التبرير: ____', 2, false);

-- ── verification (this part) ─────────────────────────────────────────────
do $verify$
declare v_tables int;
begin
  select count(*) into v_tables from pg_tables where schemaname = 'public' and tablename like 'ref\_khld\_%';
  if v_tables <> 237 then
    raise exception '0141: expected 237 ref_khld_ tables, found %', v_tables;
  end if;
end $verify$;
