-- ═══════════════════════════════════════════════════════════════════════════
--  0149 — Khalidiyah's framework: 4 objectives, 8 activities, 21 indicators,
--         273 target rows -- every target null -- and the plan's own targets
--         as data (indicator_plan_target)
--
--  GENERATED by supabase/khalidiyah/gen_0149.py from Khaldia.xlsx (the
--  framework), Khalidiyah_Indicator_Data_Collection_Forms.xlsx (00_INDEX and
--  each form's head block) and catalogue.FORMS. Do not edit; edit the
--  generator and regenerate.
--
--  ── WHERE EACH VALUE COMES FROM ──
--
--  objective.name_en    Khaldia.xlsx, Objective/Activity column, the text
--                       after the sheet's "SO1 | " code separator, verbatim
--  objective.name_ar    DRAFTED for the platform -- neither workbook names
--                       the objectives in Arabic (the same position as
--                       Ramtha's activities in 0131; 09 Part 12 records it)
--  activity.name_en     the same column, after "Activity A | ", verbatim
--  activity.name_ar     DRAFTED, as above
--  indicator.name_en/ar 00_INDEX's statement, both languages, verbatim
--  indicator.definition the form's head block, Definition, verbatim
--  indicator.formula    the form's head block, "How the indicator is
--                       calculated", verbatim -- the specification the
--                       view implements. The framework sheet's own
--                       Calculation Formula column is shorter and, for
--                       IMP-0, different in kind ("Qualitative assessment
--                       based on documented evidence" against the form's
--                       numerator ÷ denominator): the form's governs, as
--                       plan Part 6 says, and the framework's text is kept
--                       in this header's table below
--  disaggregation       the form's head block, split on ';'
--  data_source          the table 0145-0147 built for the form
--  view_name            v_ind_khld_<code>, created by the views migration
--  indicator_type       the framework's Type column, corrected: the sheet
--                       writes 'Outocme' for KHLD-SO2-0 and 'Ouput' for
--                       KHLD-SO3-F3 (plan 4.1); outcomes are stored as
--                       'result', as Ramtha's are
--  unit                 INFERRED, every one (plan 4.3): the framework's
--                       Unit column is blank for all 21. '%' where the
--                       statement begins with a percentage or the
--                       calculation multiplies by 100 (the five outcome
--                       and impact statements); JOD for KHLD-SO1-A3, whose
--                       figure is a sum of money; '#' for every count and
--                       milestone. The unit check gains 'JOD' here
--  baseline             null: the framework's Baseline column is empty
--
--  ── WHAT IS DELIBERATELY NULL ──
--
--  Every quarterly target. The framework's 27/Q1..28/Q4 columns are empty
--  for all 21 indicators, and the targets the forms DO state are annual,
--  plan-period, a range or a percentage -- none is quarterly (plan 4.2).
--  273 indicator_target rows are seeded with target_value null so the
--  dashboard says "not set" and never 0; nothing is divided into quarters.
--
--  ── THE PLAN'S TARGETS, AS DATA ──
--
--  indicator_plan_target holds what the sources state, one row per figure:
--  the framework's Target column verbatim (source_en), the form's
--  "المستهدف ..." sentence verbatim where the form states one (source_ar,
--  13 of 21), the basis (percentage / annual / plan / range / narrative),
--  and a minimum and maximum only where the text is unambiguous. SO3-F2's
--  three shares are child rows of its count (parent_id); "including
--  persons with disabilities" is a child with no number. Nothing here is
--  enforced against a figure: the dashboard shows the row under the
--  indicator as a secondary line, and the seven narrative rows show their
--  text. The framework's Target column, per indicator:
--
--    KHLD-IMP-0   Evidence documented annually
--    KHLD-SO1-0   ≥ 70% of surveyed partners
--    KHLD-SO1-A1  One mechanism established
--    KHLD-SO1-A2  ≥ 4 per year (≥ 12 over the Plan period)
--    KHLD-SO1-A3  Contributions documented annually
--    KHLD-SO1-B1  One operational arrangement established and updated as needed
--    KHLD-SO2-0   ≥ 60%
--    KHLD-SO2-C1  Priority improvements completed according to available resources
--    KHLD-SO2-C2  At least 4 campaigns annually during active implementation
--    KHLD-SO2-D1  ≥ 12 events during the plan period (≥ 4 annually starting from December 2026)
--    KHLD-SO2-D2  Participation numbers documented for each activity
--    KHLD-SO3-0   ≥ 40%
--    KHLD-SO3-E1  Established/Not Established
--    KHLD-SO3-F1  1 programme launched by Apr 2027
--    KHLD-SO3-F2  ≥ 100 volunteers over the Plan period; of whom ≥ 40% women, ≥ 30% youth (15–24) and ≥ 15% refugees, including persons with disabilities
--    KHLD-SO3-F3  ≥ 12 action days during the Plan period
--    KHLD-SO4-0   ≥ 40%
--    KHLD-SO4-G1  20-30 enterprises
--    KHLD-SO4-G2  20-30 enterprises
--    KHLD-SO4-H1  10 markets (per Annex 1: JOD 2,000 × 10); pilot phase Apr–Dec 2027, continuing seasonally to 2029
--    KHLD-SO4-H2  100-150 vendor participations
--
--  Sahel Horan and Ramtha are untouched: their objective, activity,
--  indicator and target counts are asserted, and the five view hashes
--  captured before this file are asserted after it.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 0. the hashes, before ────────────────────────────────────────────────
create temp table _0149_before on commit drop as
select m.code as muni, 'actual' as v, md5(string_agg(t::text, E'\n' order by t::text)) as h
  from public.v_indicator_actual t join public.municipality m on m.id = t.municipality_id group by m.code
union all
select m.code, 'progress', md5(string_agg(t::text, E'\n' order by t::text))
  from public.v_indicator_progress t join public.municipality m on m.id = t.municipality_id group by m.code
union all
select m.code, 'disagg', md5(string_agg(t::text, E'\n' order by t::text))
  from public.v_indicator_disaggregated t join public.municipality m on m.id = t.municipality_id group by m.code
union all
select m.code, 'rmth_status', md5(string_agg(t::text, E'\n' order by t::text))
  from public.v_rmth_indicator_status t join public.municipality m on m.id = t.municipality_id group by m.code
union all
select m.code, 'rmth_unique', md5(string_agg(t::text, E'\n' order by t::text))
  from public.v_rmth_indicator_unique t join public.municipality m on m.id = t.municipality_id group by m.code;

-- ── 1. a third unit: money ───────────────────────────────────────────────
-- KHLD-SO1-A3 reports "the annual total value in JOD" (plan 4.3). The
-- check keeps its name; nothing on file changes.
alter table public.indicator drop constraint indicator_unit_check;
alter table public.indicator add constraint indicator_unit_check check (unit in ('#', '%', 'JOD'));

-- ── 2. objectives ────────────────────────────────────────────────────────

insert into public.objective (municipality_id, code, name_en, name_ar, sort_order)
values ('00000000-0000-4000-8000-0000000000b2', 'IMPACT', 'Impact', 'الأثر', 0);
insert into public.objective (municipality_id, code, name_en, name_ar, sort_order)
values ('00000000-0000-4000-8000-0000000000b2', 'SO1', 'Strengthening Community Partnerships and Institutional Sustainability', 'تعزيز الشراكات المجتمعية والاستدامة المؤسسية', 1);
insert into public.objective (municipality_id, code, name_en, name_ar, sort_order)
values ('00000000-0000-4000-8000-0000000000b2', 'SO2', 'Rehabilitation and Activation of Al Khalidiyah Public Park as a Shared Social Space', 'تأهيل حديقة الخالدية العامة وتفعيلها كمساحة اجتماعية مشتركة', 2);
insert into public.objective (municipality_id, code, name_en, name_ar, sort_order)
values ('00000000-0000-4000-8000-0000000000b2', 'SO3', 'Strengthening Community Participation and Volunteerism', 'تعزيز المشاركة المجتمعية والعمل التطوعي', 3);
insert into public.objective (municipality_id, code, name_en, name_ar, sort_order)
values ('00000000-0000-4000-8000-0000000000b2', 'SO4', 'Supporting Household Producers through Community Markets and Park Activities', 'دعم المنتجين المنزليين من خلال الأسواق المجتمعية وأنشطة الحديقة', 4);

-- ── 3. activities ────────────────────────────────────────────────────────

insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000b2', o.id, 'A', 'Establish a sustainable municipal partnership mechanism', 'إنشاء آلية شراكة بلدية مستدامة', 1
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO1';
insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000b2', o.id, 'B', 'Operationalise park coordination arrangements', 'تفعيل ترتيبات التنسيق الخاصة بالحديقة', 2
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO1';
insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000b2', o.id, 'C', 'Rehabilitation of park facilities', 'تأهيل مرافق الحديقة', 3
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO2';
insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000b2', o.id, 'D', 'Organise community, cultural, recreational, and sports activities', 'تنظيم أنشطة مجتمعية وثقافية وترفيهية ورياضية', 4
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO2';
insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000b2', o.id, 'E', 'Establish a community coordination committee', 'إنشاء لجنة تنسيق مجتمعي', 5
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO3';
insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000b2', o.id, 'F', 'Launch a volunteer programme', 'إطلاق برنامج تطوعي', 6
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO3';
insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000b2', o.id, 'G', 'Support home-based micro-enterprises through mentorship and marketing linkages', 'دعم المشاريع المنزلية الصغيرة من خلال الإرشاد والروابط التسويقية', 7
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO4';
insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000b2', o.id, 'H', 'Organize seasonal community markets and open market days for household producers', 'تنظيم أسواق مجتمعية موسمية وأيام سوق مفتوحة للمنتجين المنزليين', 8
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO4';

-- ── 4. indicators ────────────────────────────────────────────────────────

insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'IMP-0', 'KHLD-IMP-0', o.id, null,
       '% of surveyed participants reporting that the park provides increased opportunities for interaction and shared community participation between Syrian refugees and the host community',
       'نسبة المشاركين المشمولين بالمسح الذين يفيدون بأن الحديقة توفر فرصاً متزايدة للتفاعل والمشاركة المجتمعية المشتركة بين اللاجئين السوريين والمجتمع المضيف',
       'impact', '%',
       'Evidence from participant feedback, activity records and municipal observations showing that park activities create opportunities for members of both communities to participate together.',
       '(No. of respondents answering ''Strongly agree'' or ''Agree'' to Q15 ÷ total respondents who visited the park at least once in the last 12 months) × 100. Report alongside Q13, Q14, Q16 and Q19 as supporting evidence.',
       'khld_interaction_survey', 'v_ind_khld_imp_0', null, null, array['Sex', 'age group', 'nationality / status', 'disability', 'neighbourhood']::text[], 1
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'IMPACT';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'SO1-0', 'KHLD-SO1-0', o.id, null,
       '% of partner organisations reporting effective coordination and collaboration with the Municipality in implementing park activities',
       'نسبة المؤسسات الشريكة التي تفيد بوجود تنسيق وتعاون فعّالين مع البلدية في تنفيذ أنشطة الحديقة',
       'result', '%',
       'Share of surveyed partner organisations reporting that coordination, communication and joint planning with the Municipality improved during implementation of the Action Plan.',
       '(No. of partner organisations selecting ''Strongly agree'' or ''Agree'' on Q14 ÷ total partner organisations surveyed) × 100. Target ≥ 70%. Q9–Q13 reported as a sub-index.',
       'khld_partner_survey', 'v_ind_khld_so1_0', null, null, array['Partner type', 'sex of respondent where applicable']::text[], 2
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO1';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'A1', 'KHLD-SO1-A1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'A'),
       'Municipal partnership mechanisms established',
       'إنشاء آليات الشراكة البلدية',
       'milestone', '#',
       'A functioning coordination arrangement including a designated municipal focal point, stakeholder list, partner communication arrangements, and contribution tracking.',
       'Simple count — one mechanism established. Status = ''Established'' only when items 4, 7, 10 and 11 are all recorded ''In place''; otherwise ''Partly established'' or ''Not established''.',
       'khld_milestone_verification', 'v_ind_khld_a1', null, null, array['Not applicable (institutional indicator)']::text[], 3
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO1';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'A2', 'KHLD-SO1-A2', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'A'),
       'Number of coordination meetings held with partners',
       'عدد الاجتماعات التنسيقية المعقودة مع الشركاء',
       'output', '#',
       'Meetings conducted with community organisations, cultural institutions, schools, businesses and other relevant partners, documented through minutes or attendance records.',
       'Cumulative count of documented meetings. Target ≥ 4 per year (≥ 12 over the Plan period). Count only meetings where Q18 = ''Yes, prepared and filed''.',
       'khld_coordination_meeting', 'v_ind_khld_a2', null, null, array['By partner type (association / cultural / private sector / educational / government / donor)']::text[], 4
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO1';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'A3', 'KHLD-SO1-A3', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'A'),
       'Value and type of contributions mobilised from partners',
       'قيمة ونوع المساهمات المحشودة من الشركاء',
       'output', 'JOD',
       'Financial, in-kind, technical or volunteer contributions supporting park rehabilitation and activities.',
       'Simple record of contributions received. Report the annual total value in JOD by contribution type and by source type. Count only records with status ''Received'' or ''Partly received'' in the value total; report pledges separately.',
       'khld_contribution', 'v_ind_khld_a3', null, null, array['Type of contribution', 'source (partner type)']::text[], 5
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO1';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'B1', 'KHLD-SO1-B1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'B'),
       'Park use and activity arrangements established',
       'إرساء ترتيبات استخدام الحديقة وتنظيم أنشطتها',
       'milestone', '#',
       'Basic arrangements developed for park use, including activity scheduling, use of spaces, coordination procedures, and communication with partners.',
       'Simple count — one operational arrangement established and updated as needed. Status = ''Established'' when items 3, 4, 6, 7 and 8 are all ''In place''.',
       'khld_milestone_verification', 'v_ind_khld_b1', null, null, array['Not applicable (institutional indicator)']::text[], 6
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO1';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'SO2-0', 'KHLD-SO2-0', o.id, null,
       '% of surveyed park users satisfied with the park as a safe and welcoming shared community space',
       'نسبة مستخدمي الحديقة المشمولين بالمسح الراضين عن الحديقة كمساحة مجتمعية مشتركة آمنة ومرحّبة',
       'result', '%',
       'Participants providing positive feedback on the suitability of activities and on the park as a shared community space.',
       '(No. of respondents selecting ''Very satisfied'' or ''Satisfied'' on Q9 ÷ total respondents surveyed) × 100. Target ≥ 60%. Q10–Q13 reported as the supporting dimension scores.',
       'khld_user_feedback', 'v_ind_khld_so2_0', null, null, array['Sex', 'age group', 'nationality / status', 'disability']::text[], 7
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO2';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'C1', 'KHLD-SO2-C1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'C'),
       'Priority park improvements completed',
       'إنجاز التحسينات ذات الأولوية في الحديقة',
       'output', '#',
       'Rehabilitation or improvement works completed in the designated park section, including seating, play areas, landscaping, sports facilities, lighting, accessibility features and other agreed improvements.',
       'Simple count against the agreed rehabilitation list: number of items with status ''Completed'' ÷ number of items on the priority list. Report the count of completed items by facility type.',
       'khld_works_item', 'v_ind_khld_c1', null, null, array['Facility type']::text[], 8
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO2';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'C2', 'KHLD-SO2-C2', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'C'),
       'Volunteer rehabilitation activities conducted',
       'تنفيذ أنشطة التأهيل التطوعية',
       'output', '#',
       'Volunteer campaigns supporting cleaning, planting, minor improvements and preparation of the park for community use.',
       'Number of campaigns conducted. Target at least 4 campaigns annually during active implementation. Count only campaigns with a signed attendance sheet.',
       'khld_campaign', 'v_ind_khld_c2', null, null, array['Type of activity']::text[], 9
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO2';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'D1', 'KHLD-SO2-D1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'D'),
       'Number of community activities organised in the park',
       'عدد الأنشطة المجتمعية المنظمة في الحديقة',
       'output', '#',
       'Cultural, recreational, educational, sports and community events organised in cooperation with partners.',
       'Cumulative count of events held. Target ≥ 12 during the Plan period (≥ 4 annually from December 2026). Count only events with an activity report and either an attendance sheet or a documented count.',
       'khld_activity', 'v_ind_khld_d1', null, null, array['Activity type']::text[], 10
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO2';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'D2', 'KHLD-SO2-D2', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'D'),
       'Number of participants attending events and open days (disaggregated by age and sex)',
       'عدد المشاركين الحاضرين في الفعاليات والأيام المفتوحة (مصنفاً حسب العمر والجنس)',
       'output', '#',
       'Number of residents participating in organised park activities.',
       'Total recorded participants, summed across events and reported by sex and age band. Report attendance (total participations) and, where the register allows, the number of distinct individuals reached.',
       'khld_attendance', 'v_ind_khld_d2', null, null, array['Sex', 'age group', 'nationality where available', 'disability']::text[], 11
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO2';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'SO3-0', 'KHLD-SO3-0', o.id, null,
       '% of volunteers participating in two or more volunteer activities during the implementation period',
       'نسبة المتطوعين الذين شاركوا في نشاطين تطوعيين أو أكثر خلال فترة التنفيذ',
       'result', '%',
       'Share of registered volunteers who participate in at least two organised volunteer activities during implementation, demonstrating continued community engagement.',
       '(No. of volunteers with 2 or more verified participations ÷ total registered volunteers) × 100. Target ≥ 40%. Use Q12 as the numerator test.',
       'khld_volunteer_tracking', 'v_ind_khld_so3_0', null, null, array['Sex', 'age group', 'nationality', 'disability']::text[], 12
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO3';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'E1', 'KHLD-SO3-E1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'E'),
       'Community coordination committees established',
       'إنشاء لجان التنسيق المجتمعي',
       'milestone', '#',
       'Voluntary coordination mechanism involving local associations and community organisations supporting park activities.',
       'Simple count — established / not established. Status = ''Established'' when items 5, 6, 8 and 10 are all in place.',
       'khld_milestone_verification', 'v_ind_khld_e1', null, null, array['Composition by sex and organisation type']::text[], 13
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO3';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'F1', 'KHLD-SO3-F1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'F'),
       'Volunteer programme established',
       'إنشاء برنامج التطوع',
       'milestone', '#',
       'Volunteer arrangements including volunteer registration, activity roles, and coordination procedures.',
       'Simple count — one programme launched. Status = ''Established'' when items 3, 5, 7 and 9 are all in place.',
       'khld_milestone_verification', 'v_ind_khld_f1', null, null, array['Not applicable (institutional indicator)']::text[], 14
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO3';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'F2', 'KHLD-SO3-F2', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'F'),
       'Number of volunteers recruited',
       'عدد المتطوعين المستقطبين',
       'output', '#',
       'Individuals participating in volunteer activities supporting park rehabilitation, maintenance and events.',
       'Unique count of registered volunteers with at least one recorded participation. Target ≥ 100 over the Plan period, of whom ≥ 40% women, ≥ 30% youth (15–24) and ≥ 15% refugees, including persons with disabilities.',
       'khld_volunteer', 'v_ind_khld_f2', null, null, array['Sex', 'age group including youth 15–24', 'nationality (Jordanian / Syrian refugee)', 'disability', 'affiliation (school / university / CSO / community)']::text[], 15
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO3';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'F3', 'KHLD-SO3-F3', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'F'),
       'Number of volunteer action days conducted',
       'عدد أيام العمل التطوعي المنفذة',
       'output', '#',
       'Organised volunteer action days supporting park maintenance, rehabilitation, community events or environmental activities.',
       'Cumulative count of action days conducted. Target ≥ 12 during the Plan period. Count only days with a signed attendance sheet and documented tasks.',
       'khld_action_day', 'v_ind_khld_f3', null, null, array['Activity type']::text[], 16
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO3';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'SO4-0', 'KHLD-SO4-0', o.id, null,
       '% of participating household producers reporting that community markets increased their opportunities to promote or sell their products',
       'نسبة المنتجين المنزليين المشاركين الذين يفيدون بأن الأسواق المجتمعية زادت فرصهم في الترويج لمنتجاتهم أو بيعها',
       'result', '%',
       'Share of participating household producers reporting that participation in community markets increased opportunities to promote products, reach customers or generate sales.',
       '(No. of producers answering ''Yes, significantly'' or ''Yes, to some extent'' to Q20 ÷ total producers surveyed) × 100. Target ≥ 40%. Q14, Q17 and Q19 reported as the component dimensions.',
       'khld_producer_survey', 'v_ind_khld_so4_0', null, null, array['Sex', 'nationality', 'disability', 'product type']::text[], 17
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO4';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'G1', 'KHLD-SO4-G1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'G'),
       'Number of home-based enterprises completing mentoring / guidance sessions',
       'عدد المشاريع المنزلية التي أتمّت جلسات الإرشاد والتوجيه',
       'output', '#',
       'Home-based enterprises (snacks, refreshments, handicrafts, artisanal goods) whose owners attended the full cycle of brief guidance sessions on small business basics, licensing requirements, hygiene and health and safety standards, marketing and pricing.',
       'Count of enterprises meeting the completion threshold — attendance at all core sessions. Target 20–30 enterprises. Report attendance at each session separately.',
       'khld_guidance_completion', 'v_ind_khld_g1', null, null, array['Sex, age group, nationality and disability of the owner', 'product type']::text[], 18
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO4';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'G2', 'KHLD-SO4-G2', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'G'),
       'Number of home-based enterprises receiving business support',
       'عدد المشاريع المنزلية التي تلقت دعماً لأعمالها',
       'output', '#',
       'Unique enterprises receiving any form of support under the Plan: guidance sessions, simplified licensing information, referral to training or technical partners, or participation in peer-to-peer exchange networks among entrepreneurs.',
       'Unique count of supported enterprises. Target 20–30 enterprises. Report by type of support and by sex, age, nationality and disability of the owner.',
       'khld_enterprise_support', 'v_ind_khld_g2', null, null, array['Sex, age group, nationality and disability of the owner', 'type of support']::text[], 19
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO4';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'H1', 'KHLD-SO4-H1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'H'),
       'Number of community fairs and seasonal market days organised',
       'عدد البازارات المجتمعية وأيام السوق الموسمية المنظمة',
       'output', '#',
       'Market days organised inside Al Khalidiyah Public Park on Fridays, holidays and public occasions, leveraging foot traffic from the adjacent weekly Friday market, with spaces or kiosks for local food, handicrafts and artisanal goods.',
       'Cumulative count of market days held. Target 10 markets per Annex 1 of the Plan (JOD 2,000 × 10); pilot phase April–December 2027, continuing seasonally to 2029. Count only markets with an event record and a vendor registration sheet.',
       'khld_market', 'v_ind_khld_h1', null, null, array['By type / occasion (Friday / holiday / seasonal)']::text[], 20
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO4';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000b2', 'H2', 'KHLD-SO4-H2', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000b2' and a.code = 'H'),
       'Number of home-based enterprises and vendors participating in park hosted seasonal markets',
       'عدد المشاريع المنزلية والعارضين المشاركين في الأسواق الموسمية المستضافة في الحديقة',
       'output', '#',
       'Household producers and home-based businesses occupying a stall or space in at least one market day. Both total participations and unique vendors are tracked, with priority for under-represented groups per the Plan (women, low-income families, youth, refugees, persons with disabilities).',
       'Count of registered vendors per market (participations), and a unique count of vendor IDs across all markets. Target 100–150 vendor participations.',
       'khld_vendor_registration', 'v_ind_khld_h2', null, null, array['Sex', 'age group including youth 15–24', 'nationality (Jordanian / Syrian refugee)', 'disability', 'product type']::text[], 21
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000b2' and o.code = 'SO4';

-- ── 5. targets: one row per indicator per period, every value null ───────

insert into public.indicator_target (municipality_id, indicator_id, period_id, target_value)
select i.municipality_id, i.id, p.id, null
  from public.indicator i
  join public.reporting_period p on p.municipality_id = i.municipality_id
 where i.municipality_id = '00000000-0000-4000-8000-0000000000b2';

-- ── 6. the plan's targets as data ────────────────────────────────────────

create table public.indicator_plan_target (
  id               uuid primary key default gen_random_uuid(),
  municipality_id  uuid not null references public.municipality(id) default public.my_municipality(),
  indicator_id     uuid not null,
  parent_id        uuid references public.indicator_plan_target(id),
  source_en        text not null,
  source_ar        text,
  basis            text not null check (basis in ('percentage', 'annual', 'plan', 'range', 'narrative')),
  minimum          numeric,
  maximum          numeric,
  unit             text check (unit in ('#', '%', 'JOD')),
  subgroup         text,
  from_date        date,
  by_date          date,
  note_en          text,
  sort_order       int not null default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid references auth.users(id) default auth.uid(),
  deleted_at       timestamptz,
  constraint indicator_plan_target_id_municipality_key unique (id, municipality_id),
  constraint indicator_plan_target_indicator_id_fkey foreign key (indicator_id, municipality_id) references public.indicator(id, municipality_id),
  constraint indicator_plan_target_bounds check (minimum is null or maximum is null or minimum <= maximum),
  constraint indicator_plan_target_figure_has_unit check ((minimum is null and maximum is null) or unit is not null),
  constraint indicator_plan_target_narrative_has_no_figure check (basis <> 'narrative' or (minimum is null and maximum is null))
);
create index indicator_plan_target_municipality_idx on public.indicator_plan_target (municipality_id);
create index indicator_plan_target_indicator_idx on public.indicator_plan_target (indicator_id);
create index indicator_plan_target_parent_idx on public.indicator_plan_target (parent_id);
create index indicator_plan_target_created_by_idx on public.indicator_plan_target (created_by);
select public.attach_standard_triggers('indicator_plan_target');
alter table public.indicator_plan_target enable row level security;
create policy indicator_plan_target_read on public.indicator_plan_target for select to authenticated
  using (public.can_see_municipality(municipality_id));
create policy indicator_plan_target_write on public.indicator_plan_target for all to authenticated
  using (public.is_coordinator() and public.can_see_municipality(municipality_id))
  with check (public.is_coordinator() and public.can_see_municipality(municipality_id));

comment on table public.indicator_plan_target is
  'A target the plan or the forms state for an indicator, as the source states it: annual, over the '
  'Plan period, a range or a percentage -- never quarterly (plan 4.2). source_en is the framework''s '
  'Target column verbatim; source_ar the form''s target sentence verbatim where it has one. minimum and '
  'maximum only where the text is unambiguous; a narrative row has neither. A sub-target (SO3-F2''s '
  'shares) is a child row. Shown under the indicator; enforced against nothing. 0149.';
comment on column public.indicator_plan_target.basis is
  'percentage: a share of a denominator; annual: per year; plan: over the Plan period; range: between '
  'minimum and maximum; narrative: the source states no figure.';
comment on column public.indicator_plan_target.subgroup is
  'A sub-target''s population: women, youth_15_24, refugees, persons_with_disabilities. Null on the figure itself.';

insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, 'Evidence documented annually', null, 'narrative', null, null, null, null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-IMP-0';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '≥ 70% of surveyed partners', 'المستهدف ٧٠٪ أو أكثر.', 'percentage', 70, null, '%', null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO1-0';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, 'One mechanism established', null, 'plan', 1, null, '#', null, null, null, 'one mechanism established', 1
  from public.indicator i where i.full_code = 'KHLD-SO1-A1';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '≥ 4 per year (≥ 12 over the Plan period)', 'المستهدف ٤ اجتماعات سنوياً على الأقل (١٢ على الأقل خلال فترة الخطة).', 'annual', 4, null, '#', null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO1-A2';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '≥ 4 per year (≥ 12 over the Plan period)', 'المستهدف ٤ اجتماعات سنوياً على الأقل (١٢ على الأقل خلال فترة الخطة).', 'plan', 12, null, '#', null, null, null, null, 2
  from public.indicator i where i.full_code = 'KHLD-SO1-A2';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, 'Contributions documented annually', null, 'narrative', null, null, null, null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO1-A3';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, 'One operational arrangement established and updated as needed', null, 'plan', 1, null, '#', null, null, null, 'one operational arrangement established', 1
  from public.indicator i where i.full_code = 'KHLD-SO1-B1';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '≥ 60%', 'المستهدف ٦٠٪ أو أكثر.', 'percentage', 60, null, '%', null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO2-0';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, 'Priority improvements completed according to available resources', null, 'narrative', null, null, null, null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO2-C1';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, 'At least 4 campaigns annually during active implementation', 'المستهدف أربع حملات سنوياً على الأقل خلال مرحلة التنفيذ النشط.', 'annual', 4, null, '#', null, null, null, 'during active implementation', 1
  from public.indicator i where i.full_code = 'KHLD-SO2-C2';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '≥ 12 events during the plan period (≥ 4 annually starting from December 2026)', 'المستهدف ١٢ فعالية على الأقل خلال فترة الخطة (٤ سنوياً على الأقل ابتداءً من كانون الأول ٢٠٢٦).', 'plan', 12, null, '#', null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO2-D1';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '≥ 12 events during the plan period (≥ 4 annually starting from December 2026)', 'المستهدف ١٢ فعالية على الأقل خلال فترة الخطة (٤ سنوياً على الأقل ابتداءً من كانون الأول ٢٠٢٦).', 'annual', 4, null, '#', null, '2026-12-01', null, 'from December 2026', 2
  from public.indicator i where i.full_code = 'KHLD-SO2-D1';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, 'Participation numbers documented for each activity', null, 'narrative', null, null, null, null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO2-D2';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '≥ 40%', 'المستهدف ٤٠٪ أو أكثر.', 'percentage', 40, null, '%', null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO3-0';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, 'Established/Not Established', null, 'narrative', null, null, null, null, null, null, 'established / not established; no number in the source', 1
  from public.indicator i where i.full_code = 'KHLD-SO3-E1';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '1 programme launched by Apr 2027', null, 'plan', 1, null, '#', null, null, '2027-04-30', 'launched by April 2027', 1
  from public.indicator i where i.full_code = 'KHLD-SO3-F1';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '≥ 100 volunteers over the Plan period; of whom ≥ 40% women, ≥ 30% youth (15–24) and ≥ 15% refugees, including persons with disabilities', 'المستهدف ١٠٠ متطوع على الأقل خلال فترة الخطة، منهم ٤٠٪ على الأقل نساء، و٣٠٪ على الأقل شباب (١٥–٢٤)، و١٥٪ على الأقل لاجئون، بمن فيهم ذوو الإعاقة.', 'plan', 100, null, '#', null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO3-F2';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, (select p.id from public.indicator_plan_target p where p.indicator_id = i.id and p.parent_id is null and p.sort_order = 1),
       '≥ 100 volunteers over the Plan period; of whom ≥ 40% women, ≥ 30% youth (15–24) and ≥ 15% refugees, including persons with disabilities', 'المستهدف ١٠٠ متطوع على الأقل خلال فترة الخطة، منهم ٤٠٪ على الأقل نساء، و٣٠٪ على الأقل شباب (١٥–٢٤)، و١٥٪ على الأقل لاجئون، بمن فيهم ذوو الإعاقة.', 'percentage', 40, null, '%', 'women', null, null, 'share of the volunteers counted', 2
  from public.indicator i where i.full_code = 'KHLD-SO3-F2';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, (select p.id from public.indicator_plan_target p where p.indicator_id = i.id and p.parent_id is null and p.sort_order = 1),
       '≥ 100 volunteers over the Plan period; of whom ≥ 40% women, ≥ 30% youth (15–24) and ≥ 15% refugees, including persons with disabilities', 'المستهدف ١٠٠ متطوع على الأقل خلال فترة الخطة، منهم ٤٠٪ على الأقل نساء، و٣٠٪ على الأقل شباب (١٥–٢٤)، و١٥٪ على الأقل لاجئون، بمن فيهم ذوو الإعاقة.', 'percentage', 30, null, '%', 'youth_15_24', null, null, 'share of the volunteers counted', 3
  from public.indicator i where i.full_code = 'KHLD-SO3-F2';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, (select p.id from public.indicator_plan_target p where p.indicator_id = i.id and p.parent_id is null and p.sort_order = 1),
       '≥ 100 volunteers over the Plan period; of whom ≥ 40% women, ≥ 30% youth (15–24) and ≥ 15% refugees, including persons with disabilities', 'المستهدف ١٠٠ متطوع على الأقل خلال فترة الخطة، منهم ٤٠٪ على الأقل نساء، و٣٠٪ على الأقل شباب (١٥–٢٤)، و١٥٪ على الأقل لاجئون، بمن فيهم ذوو الإعاقة.', 'percentage', 15, null, '%', 'refugees', null, null, 'share of the volunteers counted', 4
  from public.indicator i where i.full_code = 'KHLD-SO3-F2';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, (select p.id from public.indicator_plan_target p where p.indicator_id = i.id and p.parent_id is null and p.sort_order = 1),
       '≥ 100 volunteers over the Plan period; of whom ≥ 40% women, ≥ 30% youth (15–24) and ≥ 15% refugees, including persons with disabilities', 'المستهدف ١٠٠ متطوع على الأقل خلال فترة الخطة، منهم ٤٠٪ على الأقل نساء، و٣٠٪ على الأقل شباب (١٥–٢٤)، و١٥٪ على الأقل لاجئون، بمن فيهم ذوو الإعاقة.', 'narrative', null, null, null, 'persons_with_disabilities', null, null, '"including persons with disabilities": no share stated', 5
  from public.indicator i where i.full_code = 'KHLD-SO3-F2';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '≥ 12 action days during the Plan period', 'المستهدف ١٢ يوماً على الأقل خلال فترة الخطة.', 'plan', 12, null, '#', null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO3-F3';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '≥ 40%', 'المستهدف ٤٠٪ أو أكثر.', 'percentage', 40, null, '%', null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO4-0';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '20-30 enterprises', 'المستهدف ٢٠–٣٠ مشروعاً.', 'range', 20, 30, '#', null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO4-G1';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '20-30 enterprises', 'المستهدف ٢٠–٣٠ مشروعاً.', 'range', 20, 30, '#', null, null, null, null, 1
  from public.indicator i where i.full_code = 'KHLD-SO4-G2';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '10 markets (per Annex 1: JOD 2,000 × 10); pilot phase Apr–Dec 2027, continuing seasonally to 2029', 'المستهدف ١٠ أسواق وفق الملحق الأول من الخطة (٢٠٠٠ دينار × ١٠)؛ المرحلة التجريبية نيسان–كانون الأول ٢٠٢٧، مع استمرار موسمي حتى ٢٠٢٩.', 'plan', 10, 10, '#', null, '2027-04-01', null, 'pilot phase April-December 2027, then seasonally to 2029; Annex 1 costs JOD 2,000 x 10', 1
  from public.indicator i where i.full_code = 'KHLD-SO4-H1';
insert into public.indicator_plan_target (municipality_id, indicator_id, parent_id, source_en, source_ar, basis, minimum, maximum, unit, subgroup, from_date, by_date, note_en, sort_order)
select '00000000-0000-4000-8000-0000000000b2', i.id, null, '100-150 vendor participations', 'المستهدف ١٠٠–١٥٠ مشاركة عارض.', 'range', 100, 150, '#', null, null, null, 'vendor participations, not unique vendors', 1
  from public.indicator i where i.full_code = 'KHLD-SO4-H2';

-- ── verification ─────────────────────────────────────────────────────────
do $verify$
declare
  v_khld uuid := '00000000-0000-4000-8000-0000000000b2';
  v_rmth uuid := '00000000-0000-4000-8000-0000000000a1';
  v_shm  uuid := '00000000-0000-4000-8000-00000000005a';
  v_n    int;
  v_txt  text;
  r      record;
begin
  select count(*) into v_n from public.objective where municipality_id = v_khld;
  if v_n <> 5 then raise exception '0149: expected 5 objectives, got %', v_n; end if;
  select count(*) into v_n from public.activity where municipality_id = v_khld;
  if v_n <> 8 then raise exception '0149: expected 8 activities, got %', v_n; end if;
  select count(*) into v_n from public.indicator where municipality_id = v_khld;
  if v_n <> 21 then raise exception '0149: expected 21 indicators, got %', v_n; end if;
  select count(*) into v_n from public.indicator_target where municipality_id = v_khld;
  if v_n <> 273 then raise exception '0149: expected 273 target rows, got %', v_n; end if;
  select count(*) into v_n from public.indicator_target where municipality_id = v_khld and target_value is not null;
  if v_n <> 0 then raise exception '0149: % Khalidiyah targets are not null', v_n; end if;
  -- every indicator names the table its form writes, and that table exists
  select string_agg(full_code, ',') into v_txt from public.indicator i where i.municipality_id = v_khld
     and not exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
                      where n.nspname = 'public' and c.relname = i.data_source);
  if v_txt is not null then raise exception '0149: indicators naming a table that does not exist: %', v_txt; end if;
  -- the types and units are the inferred ones
  if (select indicator_type from public.indicator where full_code = 'KHLD-SO2-0') <> 'result'
     or (select indicator_type from public.indicator where full_code = 'KHLD-SO3-F3') <> 'output' then
    raise exception '0149: a source typo reached the type column';
  end if;
  if (select unit from public.indicator where full_code = 'KHLD-SO1-A3') <> 'JOD'
     or (select count(*) from public.indicator where municipality_id = v_khld and unit = '%') <> 5
     or (select count(*) from public.indicator where municipality_id = v_khld and indicator_type = 'milestone') <> 4 then
    raise exception '0149: the units or types are not as inferred';
  end if;
  -- the Arabic statements are the index sheet's, not the English
  select count(*) into v_n from public.indicator where municipality_id = v_khld and (name_ar is null or name_ar = name_en or name_ar !~ '[؀-ۿ]');
  if v_n <> 0 then raise exception '0149: % indicators have no Arabic statement', v_n; end if;
  -- the plan targets: 27 rows, 4 of them sub-targets of SO3-F2, 6 narrative
  select count(*) into v_n from public.indicator_plan_target where municipality_id = v_khld;
  if v_n <> 27 then raise exception '0149: expected 27 plan target rows, got %', v_n; end if;
  select count(*) into v_n from public.indicator_plan_target t join public.indicator i on i.id = t.indicator_id
   where t.parent_id is not null and i.full_code = 'KHLD-SO3-F2';
  if v_n <> 4 then raise exception '0149: expected 4 SO3-F2 sub-targets, got %', v_n; end if;
  if exists (select 1 from public.indicator_plan_target where parent_id is not null and subgroup is null)
     or exists (select 1 from public.indicator_plan_target where parent_id is null and subgroup is not null) then
    raise exception '0149: a sub-target without a subgroup, or a figure with one';
  end if;
  select count(*) into v_n from public.indicator_plan_target where basis = 'narrative';
  if v_n <> 6 then raise exception '0149: expected 6 narrative rows, got %', v_n; end if;
  -- every indicator has at least one row, and the 13 the forms state carry the form's Arabic sentence
  select count(*) into v_n from public.indicator i where i.municipality_id = v_khld
     and not exists (select 1 from public.indicator_plan_target t where t.indicator_id = i.id);
  if v_n <> 0 then raise exception '0149: % indicators have no plan target row', v_n; end if;
  select count(distinct indicator_id) into v_n from public.indicator_plan_target where source_ar is not null;
  if v_n <> 13 then raise exception '0149: expected 13 indicators with an Arabic target sentence, got %', v_n; end if;
  if (select minimum from public.indicator_plan_target t join public.indicator i on i.id = t.indicator_id where i.full_code = 'KHLD-SO4-G1') <> 20
     or (select maximum from public.indicator_plan_target t join public.indicator i on i.id = t.indicator_id where i.full_code = 'KHLD-SO4-H2') <> 150 then
    raise exception '0149: a range was not read as stated';
  end if;
  -- nothing quarterly anywhere: no plan target names a period
  if exists (select 1 from information_schema.columns where table_name = 'indicator_plan_target' and column_name like '%period%') then
    raise exception '0149: a plan target carries a period';
  end if;

  -- Sahel Horan and Ramtha: counts and hashes unchanged
  select count(*) into v_n from public.indicator where municipality_id = v_shm;
  if v_n <> 20 then raise exception '0149: Sahel Horan no longer has 20 indicators'; end if;
  select count(*) into v_n from public.indicator where municipality_id = v_rmth;
  if v_n <> 18 then raise exception '0149: Ramtha no longer has 18 indicators'; end if;
  select count(*) into v_n from public.indicator_target where municipality_id = v_shm;
  if v_n <> 260 then raise exception '0149: Sahel Horan target rows changed'; end if;
  select count(*) into v_n from public.indicator_target where municipality_id = v_rmth;
  if v_n <> 234 then raise exception '0149: Ramtha target rows changed'; end if;
  for r in select b.muni, b.v, b.h as before_h,
                  case b.v
                    when 'actual' then (select md5(string_agg(t::text, E'\n' order by t::text)) from public.v_indicator_actual t where t.municipality_id = (select id from public.municipality where code = b.muni))
                    when 'progress' then (select md5(string_agg(t::text, E'\n' order by t::text)) from public.v_indicator_progress t where t.municipality_id = (select id from public.municipality where code = b.muni))
                    when 'disagg' then (select md5(string_agg(t::text, E'\n' order by t::text)) from public.v_indicator_disaggregated t where t.municipality_id = (select id from public.municipality where code = b.muni))
                    when 'rmth_status' then (select md5(string_agg(t::text, E'\n' order by t::text)) from public.v_rmth_indicator_status t where t.municipality_id = (select id from public.municipality where code = b.muni))
                    when 'rmth_unique' then (select md5(string_agg(t::text, E'\n' order by t::text)) from public.v_rmth_indicator_unique t where t.municipality_id = (select id from public.municipality where code = b.muni))
                  end as after_h
             from _0149_before b
  loop
    if r.before_h is distinct from r.after_h then
      raise exception '0149: % % moved: % -> %', r.muni, r.v, r.before_h, r.after_h;
    end if;
  end loop;
  -- Khalidiyah's 21 indicators appear in the progress view, every one "not set" and without a figure
  select count(*) into v_n from public.v_indicator_progress where municipality_id = v_khld;
  if v_n <> 273 then raise exception '0149: expected 273 Khalidiyah progress rows, got %', v_n; end if;
  if exists (select 1 from public.v_indicator_progress where municipality_id = v_khld and (status <> 'not_set' or actual is not null)) then
    raise exception '0149: a Khalidiyah progress row carries a status or a figure before its view exists';
  end if;
end $verify$;
