-- ═══════════════════════════════════════════════════════════════════════════
--  0030 — test accounts: app_user rows only, NO auth users, NO passwords
--
--  ── WHY THIS FILE NO LONGER CREATES ACCOUNTS ──
--
--  It used to insert six rows into auth.users with a shared password literal,
--  `crypt('...')`, written directly in this file. That was wrong for one
--  structural reason: MIGRATIONS ARE COMMITTED BY DESIGN. A password in a
--  migration is a password in the repository, in every clone, and in the git
--  history forever. When this repository became public that password became
--  public with it -- and the coordinator account it belonged to can read every
--  national ID in the database.
--
--  Rotating a password does not remove it from history. The only fix that
--  holds is for credentials never to enter the repository at all.
--
--  ── HOW TEST ACCOUNTS ARE CREATED NOW ──
--
--  Out of band, and never from a committed file:
--
--    • Supabase dashboard -> Authentication -> Users -> Add user, or
--    • a local script that reads passwords from app/.env.local (gitignored)
--
--  One generated password per account. Never a shared literal. The values live
--  in app/.env.local and nowhere else; app/.env.example carries placeholders.
--
--  The six accounts, for reference:
--
--    coordinator@shm.test   coordinator     reads and writes everything
--    dataentry@shm.test     data_entry
--    enumerator@shm.test    enumerator
--    viewer@shm.test        partner_viewer  aggregates only, no identities
--    producer@shm.test      participant     linked to Demo Person One
--    unlinked@shm.test      participant     deliberately NOT linked, so the
--                                           "no linked person" state is testable
--
--  ── WHAT THIS FILE STILL DOES ──
--
--  Nothing. It is kept as an applied, numbered migration so the sequence stays
--  contiguous and append-only (CLAUDE.md rule 5). The app_user rows for these
--  accounts are created by the handle_new_user trigger when each auth user is
--  created out of band, so there is nothing left for a migration to do.
--
--  Do not re-add credentials here. If a test account is needed, create it in
--  the dashboard.
-- ═══════════════════════════════════════════════════════════════════════════

-- Intentionally empty. See the header.
select 1;
