-- ═══════════════════════════════════════════════════════════════════════════
--  0031 — superseded: auth fixture repair, no longer applied from a migration
--
--  This file used to repair the auth.users rows that 0030 inserted: GoTrue
--  expects empty strings rather than NULL in its token columns, and expects a
--  matching auth.identities row per user. Without both, sign-in failed before
--  the password was even checked.
--
--  It carried the same shared password literal as 0030, and is emptied for the
--  same reason: MIGRATIONS ARE COMMITTED, so a credential in one is a
--  credential in the repository and in its history, permanently.
--
--  None of that repair work is needed any more. Accounts created through the
--  Supabase dashboard or the Admin API are shaped correctly by GoTrue itself --
--  the token columns and the identities row come out right without help. The
--  repair only existed because 0030 hand-wrote rows into auth.users, which is
--  exactly the practice being removed.
--
--  See 0030 for how test accounts are created now, and for the list of six.
--
--  Kept as an applied, numbered migration so the sequence stays contiguous and
--  append-only (CLAUDE.md rule 5). Do not re-add credentials here.
-- ═══════════════════════════════════════════════════════════════════════════

-- Intentionally empty. See the header.
select 1;
