-- ═══════════════════════════════════════════════════════════════════════════
--  0131 — Ramtha's framework: 4 objectives, 5 activities, 18 indicators,
--         13 reporting periods, 234 target rows -- every target null
--
--  GENERATED by supabase/ramtha/gen_0131.py from the two workbooks and
--  supabase/ramtha/forms.py. Do not edit; edit the generator and regenerate.
--
--  ── WHERE EACH VALUE COMES FROM ──
--
--  objective.name_en    RAMTHA Framework.xlsx, English_form, verbatim
--  objective.name_ar    the same workbook's Arabic Copy sheet, verbatim
--  activity.name_en     English_form, verbatim (the workbook labels
--                       RMTH-SO3-E "Activity D"; the CODE is E and is kept)
--  activity.name_ar     drafted -- the Arabic Copy has no activity rows
--  indicator.name_en    the form sheet's own statement, verbatim
--  indicator.name_ar    forms.STATEMENT_AR: the Arabic Copy's statement
--                       where the form's statement is the English Copy's,
--                       drafted and marked otherwise (see forms.py)
--  indicator.formula    the sheet's "How the indicator is calculated from
--                       this form", verbatim -- the specification the view
--                       in 0132 implements
--  indicator.definition English_form's Definition, present for A1.2 and A1.3
--                       only (and identical for both, which is the index's
--                       never-sum warning); null elsewhere, not invented
--  disaggregation       the sheet's "Required disaggregation", split on ';'
--
--  ── WHAT IS DELIBERATELY NULL ──
--
--  Every target. English_form has no targets at all; the English Copy has
--  them against a different indicator list (plan §6.2). They are NOT mapped
--  across: a 234-row target matrix is seeded with target_value null, so the
--  dashboard says "not set" and never 0. The reconciliation is OQ-48.
--
--  Baselines: English_form's Baseline column is empty. Null.
--
--  RMTH-SO1-A1 is seeded with a code, no statement, no formula and no view
--  (plan §6.3) -- its name says so in both languages, and 0132's status view
--  names the gap on the dashboard.
--
--  ── DECISIONS TAKEN HERE ──
--
--  Reporting periods: the same thirteen quarters as Sahel Horan, 26/Q3 to
--  29/Q3. Neither workbook states Ramtha's programme dates; English_form's
--  target columns run 27/Q1 to 28/Q4 exactly as Sahel Horan's do. Separate
--  rows, so the two plans lock independently (plan §1.2).
--
--  Units: '#' for counts, '%' for the three statements that begin with a
--  percentage (B1, SO2-0, C1). IMP-0 is a count -- the sheet says "A COUNT,
--  not a rate" -- while the Action Plan writes it as a ratio; OQ-47 item 1.
--
--  indicator.full_code: added here as a real column, NOT NULL and unique,
--  because 0113's header said 0116 would add it and 0116 did not. Backfilled
--  for Sahel Horan from its documented codes (03_INDICATORS.md: SHM-IMP-0,
--  SHM-SO1-A1 ... SHM-SO4-G0.4).
-- ═══════════════════════════════════════════════════════════════════════════

-- ── full_code ─────────────────────────────────────────────────────────────

alter table public.indicator add column full_code text;

update public.indicator i
   set full_code = 'SHM-' || case when o.code = 'IMPACT' then i.code else o.code || '-' || i.code end
  from public.objective o, public.municipality m
 where o.id = i.objective_id and m.id = i.municipality_id and m.code = 'SHM' and i.full_code is null;

-- ── objectives ───────────────────────────────────────────────────────────

insert into public.objective (municipality_id, code, name_en, name_ar, sort_order)
values ('00000000-0000-4000-8000-0000000000a1', 'IMPACT', 'Impact', 'الأثر', 0);
insert into public.objective (municipality_id, code, name_en, name_ar, sort_order)
values ('00000000-0000-4000-8000-0000000000a1', 'SO1', 'Specific Objective 1: Creating New Job Opportunities for Ramtha Residents', 'الهدف الخاص الأول: خلق فرص عمل جديدة لأبناء الرمثا', 1);
insert into public.objective (municipality_id, code, name_en, name_ar, sort_order)
values ('00000000-0000-4000-8000-0000000000a1', 'SO2', 'SO2: Providing Training Opportunities and Vocational Empowerment for Ramtha Residents according to Labor Market Needs', 'الهدف الخاص الثاني: توفير فرص التدريب والتمكين المهني لأبناء الرمثا وفق احتياجات سوق العمل', 2);
insert into public.objective (municipality_id, code, name_en, name_ar, sort_order)
values ('00000000-0000-4000-8000-0000000000a1', 'SO3', 'SO3: Support and strengthen entrepreneurial projects and small business incubators', 'الهدف الخاص الثالث: دعم وتعزيز المشاريع الريادية وحاضنات الأعمال الصغيرة', 3);

-- ── activities ───────────────────────────────────────────────────────────

insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000a1', o.id, 'A', 'Organising Regular Job Fairs and Career Guidance Events', 'تنظيم أيام وظيفية وفعاليات توجيه مهني بشكل دوري', 1
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO1';
insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000a1', o.id, 'B', 'Developing Local Projects Linked to the Labour Market', 'تطوير مشاريع محلية مرتبطة بسوق العمل', 2
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO1';
insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000a1', o.id, 'C', 'Supporting the Development of Practical Training Programmes in Collaboration with Local Educational Institutions', 'دعم تطوير برامج تدريب عملية بالتعاون مع المؤسسات التعليمية المحلية', 3
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO2';
insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000a1', o.id, 'E', 'Establishing Small Business Incubators in Collaboration with Universities and the Private Sector', 'إنشاء حاضنات أعمال صغيرة بالتعاون مع الجامعات والقطاع الخاص', 4
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO3';
insert into public.activity (municipality_id, objective_id, code, name_en, name_ar, sort_order)
select '00000000-0000-4000-8000-0000000000a1', o.id, 'F', 'Facilitating Access to Finance and Advisory Support through Stakeholder Coordination', 'تيسير الوصول إلى التمويل والدعم الاستشاري من خلال التنسيق بين أصحاب المصلحة', 5
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO3';

-- ── reporting periods ────────────────────────────────────────────────────

insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '26/Q3', '2026-07-01', '2026-09-30', false);
insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '26/Q4', '2026-10-01', '2026-12-31', false);
insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '27/Q1', '2027-01-01', '2027-03-31', false);
insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '27/Q2', '2027-04-01', '2027-06-30', false);
insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '27/Q3', '2027-07-01', '2027-09-30', false);
insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '27/Q4', '2027-10-01', '2027-12-31', false);
insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '28/Q1', '2028-01-01', '2028-03-31', false);
insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '28/Q2', '2028-04-01', '2028-06-30', false);
insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '28/Q3', '2028-07-01', '2028-09-30', false);
insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '28/Q4', '2028-10-01', '2028-12-31', false);
insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '29/Q1', '2029-01-01', '2029-03-31', false);
insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '29/Q2', '2029-04-01', '2029-06-30', false);
insert into public.reporting_period (municipality_id, code, start_date, end_date, is_locked) values ('00000000-0000-4000-8000-0000000000a1', '29/Q3', '2029-07-01', '2029-09-30', false);

-- ── indicators ───────────────────────────────────────────────────────────

insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'IMP-0', 'RMTH-IMP-0', o.id, null,
       'Number of targeted population who achieve sustained employment/income as a result of Municipality-facilitated economic opportunities',
       'عدد أفراد الفئة المستهدفة الذين يحققون عملاً أو دخلاً مستدامًا نتيجة للفرص الاقتصادية التي سهّلتها البلدية',
       'impact', '#', null,
       'A COUNT, not a rate: unique beneficiaries (by National ID) whose engagement is confirmed as sustained for at least X consecutive months. Counted once only, whatever the number of trainings or support mechanisms accessed. Target: 65 persons over 3 years. OPEN ITEM: the Action Plan writes the calculation formula as a ratio; confirm with ENABEL that a count is what is reported.',
       'rmth_outcome_survey', 'v_ind_rmth_imp_0', null, null, array['Gender', 'age', 'nationality', 'vulnerability category', 'type of pathway']::text[], 1
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'IMPACT';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'SO1-0', 'RMTH-SO1-0', o.id, null,
       '# of persons who demonstrate increased employability as a result of municipality facilitated networking opportunities',
       'عدد الأشخاص الذين يُظهرون قابلية تشغيل متزايدة نتيجة فرص التشبيك التي سهّلتها البلدية',
       'result', '#', null,
       'Count of unique persons meeting the employability threshold: a confirmed placement, OR at least one VERIFIABLE action (interview attended, offer received, internship or placement started, enrolled in training) plus one further action from the checklist. Counted once per person. OPEN ITEM: confirm this threshold with the Municipality - the Action Plan''s equivalent result indicator counts confirmed employment only.',
       'rmth_outcome_survey', 'v_ind_rmth_so1_0', null, null, array['Gender', 'age', 'nationality', 'vulnerability category', 'type of event attended']::text[], 2
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO1';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'A1', 'RMTH-SO1-A1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'A'),
       'RMTH-SO1-A1 carries a code and no indicator statement in the framework workbook (OQ-48)',
       'يحمل RMTH-SO1-A1 رمزاً دون نص مؤشر في مصنّف الإطار (OQ-48)',
       'output', '#', null,
       null,
       null, null, null, null, null, 3
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO1';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'A1.2', 'RMTH-SO1-A1.2', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'A'),
       '# of networking events including job fairs',
       'عدد فعاليات التشبيك، بما يشمل الأيام الوظيفية',
       'output', '#', 'This indicator measures the number of networking and coordination events organized to connect job seekers with employers and training providers, including job fairs, vocational guidance sessions, and employer–job seeker meetings.',
       'Count of documented networking events conducted. Each event is counted once. A combined event contributes 1 here AND 1 to RMTH-SO1-A1.3; the two indicators must never be added together, because the Action Plan treats them as one indicator with a single target of 4 per year.',
       'rmth_event', 'v_ind_rmth_a1_2', null, null, array['Type of event', 'gender and age of participants']::text[], 4
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO1';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'A1.3', 'RMTH-SO1-A1.3', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'A'),
       '# of vocational guidance sessions',
       'عدد جلسات التوجيه المهني',
       'output', '#', 'This indicator measures the number of networking and coordination events organized to connect job seekers with employers and training providers, including job fairs, vocational guidance sessions, and employer–job seeker meetings.',
       'Count of documented vocational guidance sessions delivered. Each session is counted once. A session held inside a larger networking event still counts as 1 here, and that event counts as 1 under RMTH-SO1-A1.2; the two indicators must never be added together.',
       'rmth_event', 'v_ind_rmth_a1_3', null, null, array['Topic of the session', 'target group', 'gender and age of participants']::text[], 5
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO1';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'B1', 'RMTH-SO1-B1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'B'),
       '% of supported project implementers reporting that at least one component of municipal support was essential to their ability to operate',
       'نسبة منفذي المشاريع المدعومة الذين يفيدون بأن مكوّناً واحداً على الأقل من الدعم البلدي كان أساسياً لقدرتهم على العمل',
       'intermediate', '%', null,
       'Numerator: implementers rating at least one support component ''Essential''. Denominator: implementers who received at least one component of municipal support, were approached, and responded. Implementers not reached or refusing are excluded from both. An implementer running several approved projects is counted ONCE. Multiply by 100.',
       'rmth_project_implementer', 'v_ind_rmth_b1', null, null, array['Sector', 'project type', 'type of support component']::text[], 6
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO1';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'B1.1', 'RMTH-SO1-B1.1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'B'),
       '# of specialized training programmes (industrial, agricultural, or administrative) tailored to the technical requirements of the approved projects',
       'عدد برامج التدريب المتخصصة (الصناعية أو الزراعية أو الإدارية) المصمَّمة وفق المتطلبات الفنية للمشاريع المعتمدة',
       'output', '#', null,
       'Count of programmes meeting BOTH tests: (a) specialisation is industrial, agricultural or administrative, AND (b) the programme is documented as tailored to the technical requirements of at least one approved project. Each programme is counted once.',
       'rmth_training_programme', 'v_ind_rmth_b1_1', null, null, array['Specialisation', 'sector of the linked project', 'partner type']::text[], 7
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO1';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'B1.2', 'RMTH-SO1-B1.2', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'B'),
       '# of proposals approved for implementation',
       'عدد المقترحات المعتمدة للتنفيذ',
       'output', '#', null,
       'Count of proposals with a decision of ''Approved for implementation'' or ''Approved with conditions''. Proposals deferred, rejected or still under review are recorded but not counted. Each proposal is counted once, on first approval.',
       'rmth_proposal', 'v_ind_rmth_b1_2', null, null, array['Sector', 'sub-sector', 'proposal type', 'type of submitting entity']::text[], 8
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO1';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'SO2-0', 'RMTH-SO2-0', o.id, null,
       '% of training completers placed into employment or an internship within three months of completing the cycle',
       'نسبة متمّي التدريب الذين أُلحقوا بعمل أو تدريب داخلي خلال ثلاثة أشهر من إتمام الدورة',
       'result', '%', null,
       'Numerator: completers whose placement into EMPLOYMENT OR AN INTERNSHIP started within three months of the cycle end date. Denominator: completers on the RMTH-SO2-C1.2 roster for that cycle who have reached the three-month point and were reached for follow-up. Multiply by 100. OPEN ITEM: confirm with the Municipality whether self-employment counts as a placement; the indicator statement says employment or internship.',
       'rmth_outcome_survey', 'v_ind_rmth_so2_0', null, null, array['Gender', 'age', 'nationality', 'vulnerability category', 'training cycle', 'type of placement']::text[], 9
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO2';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'C1', 'RMTH-SO2-C1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'C'),
       '% of trainees who report that training offered supported their employment journey',
       'نسبة المتدربين الذين يفيدون بأن التدريب المقدَّم دعم مسارهم نحو التشغيل',
       'intermediate', '%', null,
       'Numerator: trainees answering ''Yes, significantly'' or ''Yes, to some extent'' to the headline question. Denominator: trainees on the RMTH-SO2-C1.2 completion roster for the cycle who were approached AND reached. Those not reached or refusing are excluded from both. Multiply by 100.',
       'rmth_outcome_survey', 'v_ind_rmth_c1', null, null, array['Gender', 'age', 'training cycle', 'type of support reported']::text[], 10
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO2';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'C1.1', 'RMTH-SO2-C1.1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'C'),
       '# of short-term intensive training cycles delivered whose content was jointly developed with private sector establishments and academic or vocational institutions',
       'عدد دورات التدريب المكثفة قصيرة الأمد المنفَّذة التي طُوِّر محتواها بالاشتراك مع منشآت القطاع الخاص والمؤسسات الأكاديمية أو المهنية',
       'output', '#', null,
       'Count of cycles meeting BOTH tests: (a) short-term intensive per the agreed definition, and (b) content jointly developed with at least one private sector establishment AND at least one academic or vocational institution, with documentary evidence. OPEN ITEM: fix the short-term intensive thresholds with the Municipality before first use.',
       'rmth_training_cycle', 'v_ind_rmth_c1_1', null, null, array['Sector or occupation', 'partner type', 'delivery modality']::text[], 11
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO2';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'C1.2', 'RMTH-SO2-C1.2', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'C'),
       '# of trainees completing training programs related to employability',
       'عدد المتدربين الذين أتمّوا برامج تدريب مرتبطة بالتشغيل',
       'output', '#', null,
       'Count of records where ''Did this person meet the completion criteria?'' is Yes. The Action Plan defines a completer as someone who completes the training AND is assessed as job-ready. Report BOTH figures: total completions, and unique completers by National ID (the de-duplication field below gives the second).',
       'rmth_training_enrolment', 'v_ind_rmth_c1_2', null, null, array['Gender', 'age', 'nationality', 'vulnerability category', 'type of training']::text[], 12
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO2';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'SO3-0', 'RMTH-SO3-0', o.id, null,
       '# of persons who secure regular income as a result of Municipality-supported/facilitated entrepreneurship programming',
       'عدد الأشخاص الذين حصلوا على دخل منتظم نتيجة برامج ريادة الأعمال المدعومة من البلدية',
       'result', '#', null,
       'Count of unique persons (by National ID) confirmed to be earning income from a supported enterprise in at least four of the last six months. Counted once per person. OPEN ITEM: confirm the four-of-six-months rule with the Municipality.',
       'rmth_outcome_survey', 'v_ind_rmth_so3_0', null, null, array['Gender', 'age', 'nationality', 'vulnerability category', 'sector', 'type of support received']::text[], 13
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO3';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'E0.1', 'RMTH-SO3-E0.1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'E'),
       '# of specialised business incubators in high-impact fields such as urban development, infrastructure, food manufacturing, and professional services established',
       'عدد حاضنات الأعمال المتخصصة المُنشأة في مجالات عالية الأثر مثل التنمية الحضرية والبنية التحتية وتصنيع الأغذية والخدمات المهنية',
       'output', '#', null,
       'Count of incubators that are (a) specialised in a high-impact field and (b) confirmed as established and operational against criteria 1 to 5 below. Following the Action Plan definition, admission of a first cohort is tracked but is NOT required for the incubator to count as established.',
       'rmth_incubator', 'v_ind_rmth_e0_1', null, null, array['Specialisation field', 'host arrangement', 'partner type']::text[], 14
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO3';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'E0.2', 'RMTH-SO3-E0.2', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'E'),
       '# of participants receiving incubation services',
       'عدد المشاركين الذين يتلقون خدمات الاحتضان',
       'output', '#', null,
       'Count of unique participants (by National ID) who have received at least one incubation service. Counted once per participant, however many services they receive.',
       'rmth_incubation_service', 'v_ind_rmth_e0_2', null, null, array['Gender', 'age', 'nationality', 'vulnerability category', 'sector', 'type of service', 'enterprise stage']::text[], 15
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO3';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'E0.3', 'RMTH-SO3-E0.3', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'E'),
       '# of participants trained on incubator design',
       'عدد المشاركين المدرَّبين على تصميم الحاضنات',
       'output', '#', null,
       'Count of records where ''Did this person meet the completion criteria?'' is Yes. Report BOTH total completions and unique participants by National ID.',
       'rmth_training_enrolment', 'v_ind_rmth_e0_3', null, null, array['Gender', 'age', 'type of organisation', 'role of the participant']::text[], 16
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO3';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'F0.1', 'RMTH-SO3-F0.1', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'F'),
       '# of participants trained in entrepreneurship training',
       'عدد المشاركين الذين أتمّوا تدريبات في ريادة الأعمال',
       'output', '#', null,
       'Count of records where ''Did this person successfully complete the training?'' is Yes. The Action Plan defines these as participants who successfully complete training on production practices, quality standards and basic management skills relevant to their enterprise type. Report BOTH total completions and unique participants by National ID.',
       'rmth_training_enrolment', 'v_ind_rmth_f0_1', null, null, array['Gender', 'age', 'nationality', 'vulnerability category', 'type of training', 'enterprise stage']::text[], 17
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO3';
insert into public.indicator (municipality_id, code, full_code, objective_id, activity_id, name_en, name_ar, indicator_type, unit, definition, formula, data_source, view_name, baseline, final_target, disaggregation, sort_order)
select '00000000-0000-4000-8000-0000000000a1', 'F0.2', 'RMTH-SO3-F0.2', o.id, (select a.id from public.activity a where a.municipality_id = '00000000-0000-4000-8000-0000000000a1' and a.code = 'F'),
       '# of training programs developed for entrepreneurship',
       'عدد برامج التدريب المطوّرة في مجال ريادة الأعمال',
       'output', '#', null,
       'Count of programmes where ''Programme development complete?'' is Yes. Each programme is counted once. OPEN ITEM: the Action Plan defines the equivalent indicator as the number of training SESSIONS delivered, each counted once regardless of participants. The delivery log below records every cycle so the number can be reported either way once ENABEL and the Municipality agree which reading governs.',
       'rmth_training_programme', 'v_ind_rmth_f0_2', null, null, array['Sector', 'type of training (modality)', 'target group and level', 'partner type']::text[], 18
  from public.objective o where o.municipality_id = '00000000-0000-4000-8000-0000000000a1' and o.code = 'SO3';

-- ── targets: one row per indicator per period, every value null ──────────

insert into public.indicator_target (municipality_id, indicator_id, period_id, target_value)
select i.municipality_id, i.id, p.id, null
  from public.indicator i
  join public.reporting_period p on p.municipality_id = i.municipality_id
 where i.municipality_id = '00000000-0000-4000-8000-0000000000a1';

-- ── full_code becomes a column with rules ────────────────────────────────

alter table public.indicator
  alter column full_code set not null,
  add constraint indicator_full_code_key unique (full_code),
  add constraint indicator_full_code_shape check (full_code ~ '^[A-Z]+-[A-Z0-9.-]+$');

comment on column public.indicator.full_code is
  'The code the framework and the donor return use: municipality code, objective, short code (SHM-SO1-A1.2, RMTH-IMP-0). '
  'Stored rather than derived because a derivation cannot tell RMTH-SO1-0 from RMTH-SO1-SO1-0.';

-- ── verification ─────────────────────────────────────────────────────────
do $verify$
declare
  v_rmth uuid := '00000000-0000-4000-8000-0000000000a1';
  v_shm  uuid := '00000000-0000-4000-8000-00000000005a';
  v_n    int;
  v_txt  text;
begin
  select count(*) into v_n from public.objective where municipality_id = v_rmth;
  if v_n <> 4 then raise exception '0131: expected 4 objectives, got %', v_n; end if;
  select count(*) into v_n from public.activity where municipality_id = v_rmth;
  if v_n <> 5 then raise exception '0131: expected 5 activities, got %', v_n; end if;
  select count(*) into v_n from public.reporting_period where municipality_id = v_rmth;
  if v_n <> 13 then raise exception '0131: expected 13 periods, got %', v_n; end if;
  select count(*) into v_n from public.indicator where municipality_id = v_rmth;
  if v_n <> 18 then raise exception '0131: expected 18 indicators, got %', v_n; end if;
  select count(*) into v_n from public.indicator_target where municipality_id = v_rmth;
  if v_n <> 234 then raise exception '0131: expected 234 target rows, got %', v_n; end if;
  select count(*) into v_n from public.indicator_target where municipality_id = v_rmth and target_value is not null;
  if v_n <> 0 then raise exception '0131: % Ramtha targets are not null', v_n; end if;
  -- exactly one indicator with no statement, no formula and no view: A1
  select string_agg(code, ',') into v_txt from public.indicator where municipality_id = v_rmth and (formula is null or view_name is null);
  if v_txt <> 'A1' then raise exception '0131: indicators without a formula or view: %', v_txt; end if;
  -- every other Ramtha indicator names a view that 0132 has to create, and a source table that exists
  if exists (select 1 from public.indicator i where i.municipality_id = v_rmth and i.data_source is not null
               and not exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
                                where n.nspname = 'public' and c.relname = i.data_source)) then
    raise exception '0131: an indicator names a source table that does not exist';
  end if;
  -- Sahel Horan: full codes as documented, nothing else touched
  select count(*) into v_n from public.indicator where municipality_id = v_shm;
  if v_n <> 20 then raise exception '0131: Sahel Horan no longer has 20 indicators'; end if;
  if (select full_code from public.indicator where municipality_id = v_shm and code = 'B1.2') <> 'SHM-SO1-B1.2'
     or (select full_code from public.indicator where municipality_id = v_shm and code = 'IMP-0') <> 'SHM-IMP-0'
     or (select full_code from public.indicator where municipality_id = v_shm and code = 'G0.4') <> 'SHM-SO4-G0.4' then
    raise exception '0131: a Sahel Horan full code is not the documented one';
  end if;
  select count(*) into v_n from public.indicator_target where municipality_id = v_shm;
  if v_n <> 260 then raise exception '0131: Sahel Horan target rows changed'; end if;
  -- the Arabic statements from the workbook are the workbook's
  if (select name_ar from public.indicator where municipality_id = v_rmth and code = 'C1.2') <> 'عدد المتدربين الذين أتمّوا برامج تدريب مرتبطة بالتشغيل' then
    raise exception '0131: C1.2''s Arabic is not the Arabic Copy''s';
  end if;
end $verify$;
