-- ═══════════════════════════════════════════════════════════════════════════
--  0176 — Ramtha's option lists for the seven forms of
--         RMTH_Forms_and_Calculations_v2.xlsx
--
--  GENERATED by supabase/ramtha/gen_lists.py from workbook.py (the one
--  reading of the workbook) and catalogue.py. Do not edit; edit the
--  catalogue and regenerate.
--
--  One ref_rmth_* table per response list of the "Forms Needed" sheet, 14
--  lists and 59 options. Both labels are the sheet's own cells, VERBATIM:
--  this workbook, unlike the first one (0122), gives every option in
--  Arabic as well, so nothing here is drafted. The code beside each option
--  is the catalogue's; the generator checks the catalogue's English against
--  the cell before writing either.
--
--  Two sheets' fields share a list only where their options are identical,
--  option for option, in both languages: PJ-03 and AC-06 (sector) are one
--  table. "Yes - No" questions are boolean columns, not lists.
--
--  ── WHAT THE SHEET LEAVES OPEN ──
--
--  A bare "Other" (nationality, sector, training topic) takes a
--  specification -- 3 options allow free text, the convention of OQ-53:
--  an "Other" that cannot say what it was is a figure nobody can
--  disaggregate. "Other stakeholder" names a category and takes none.
--  "None" in AC-08 and FU-03 is exclusive (the sheet's Validation column);
--  save_rmth_record refuses it beside another tick (0178).
--
--  Like every other ref_ table: RLS on, read by every signed-in role,
--  written by a coordinator, the standard triggers, no hard delete.
-- ═══════════════════════════════════════════════════════════════════════════

do $outer$
declare t text;
begin
  foreach t in array array[
    'ref_rmth_sex',
    'ref_rmth_age_group',
    'ref_rmth_nationality',
    'ref_rmth_sector',
    'ref_rmth_activity_category',
    'ref_rmth_networking_type',
    'ref_rmth_joint_partner',
    'ref_rmth_training_type',
    'ref_rmth_training_topic',
    'ref_rmth_stakeholder_type',
    'ref_rmth_incubation_service',
    'ref_rmth_employability_outcome',
    'ref_rmth_placement_type',
    'ref_rmth_work_status'
  ] loop
    execute format($f$
      create table public.%I (
        id               uuid primary key default gen_random_uuid(),
        code             text not null unique,
        label_en         text not null,
        label_ar         text not null,
        sort_order       int  not null default 0,
        is_active        boolean not null default true,
        allows_free_text boolean not null default false,
        created_at       timestamptz not null default now(),
        updated_at       timestamptz not null default now(),
        created_by       uuid references auth.users(id),
        deleted_at       timestamptz
      )$f$, t);

    perform public.attach_standard_triggers(t);

    execute format('alter table public.%I enable row level security', t);
    execute format($f$create policy ref_read on public.%I
      for select to authenticated using (true)$f$, t);
    execute format($f$create policy ref_write on public.%I
      for all to authenticated
      using (public.is_coordinator())
      with check (public.is_coordinator())$f$, t);
  end loop;
end $outer$;

-- ── ref_rmth_sex (PR-02) ──
insert into public.ref_rmth_sex (code, label_en, label_ar, sort_order, allows_free_text) values
  ('male', 'Male', 'ذكر', 1, false),
  ('female', 'Female', 'أنثى', 2, false);

-- ── ref_rmth_age_group (PR-04) ──
insert into public.ref_rmth_age_group (code, label_en, label_ar, sort_order, allows_free_text) values
  ('under_18', 'Under 18', 'أقل من 18', 1, false),
  ('age_18_24', '18 to 24', 'من 18 إلى 24', 2, false),
  ('age_25_35', '25 to 35', 'من 25 إلى 35', 3, false),
  ('age_36_45', '36 to 45', 'من 36 إلى 45', 4, false),
  ('over_45', 'Over 45', 'أكثر من 45', 5, false);

-- ── ref_rmth_nationality (PR-05) ──
insert into public.ref_rmth_nationality (code, label_en, label_ar, sort_order, allows_free_text) values
  ('jordanian', 'Jordanian', 'أردني', 1, false),
  ('syrian', 'Syrian', 'سوري', 2, false),
  ('other', 'Other', 'أخرى', 3, true);

-- ── ref_rmth_sector (PJ-03, AC-06) ──
insert into public.ref_rmth_sector (code, label_en, label_ar, sort_order, allows_free_text) values
  ('industrial', 'Industrial', 'صناعي', 1, false),
  ('agricultural', 'Agricultural', 'زراعي', 2, false),
  ('administrative', 'Administrative', 'إداري', 3, false),
  ('urban_development', 'Urban development', 'التنمية الحضرية', 4, false),
  ('infrastructure', 'Infrastructure', 'البنية التحتية', 5, false),
  ('food_manufacturing', 'Food manufacturing', 'التصنيع الغذائي', 6, false),
  ('professional_services', 'Professional services', 'الخدمات المهنية', 7, false),
  ('other', 'Other', 'أخرى', 8, true);

-- ── ref_rmth_activity_category (AC-02) ──
insert into public.ref_rmth_activity_category (code, label_en, label_ar, sort_order, allows_free_text) values
  ('networking', 'Networking event', 'فعالية تشبيك', 1, false),
  ('specialised', 'Specialised training programme', 'برنامج تدريبي متخصص', 2, false),
  ('short_term', 'Short term training cycle', 'دورة تدريبية قصيرة مكثفة', 3, false),
  ('entrepreneurship', 'Entrepreneurship training programme', 'برنامج تدريب على الريادة', 4, false),
  ('incubator_design', 'Incubator design training', 'تدريب على تصميم الحاضنات', 5, false),
  ('business_incubator', 'Business incubator', 'حاضنة أعمال', 6, false);

-- ── ref_rmth_networking_type (AC-03) ──
insert into public.ref_rmth_networking_type (code, label_en, label_ar, sort_order, allows_free_text) values
  ('job_fair', 'Job fair', 'معرض توظيف', 1, false),
  ('guidance_session', 'Vocational guidance session', 'جلسة إرشاد مهني', 2, false),
  ('employer_meeting', 'Employer and job seeker meeting', 'لقاء بين أصحاب العمل والباحثين عن عمل', 3, false);

-- ── ref_rmth_joint_partner (AC-08) ──
insert into public.ref_rmth_joint_partner (code, label_en, label_ar, sort_order, allows_free_text) values
  ('private_sector', 'Private sector establishment', 'منشأة من القطاع الخاص', 1, false),
  ('academic', 'Academic institution', 'مؤسسة أكاديمية', 2, false),
  ('vocational', 'Vocational institution', 'مؤسسة تدريب مهني', 3, false),
  ('none', 'None', 'لا يوجد', 4, false);

-- ── ref_rmth_training_type (AC-10) ──
insert into public.ref_rmth_training_type (code, label_en, label_ar, sort_order, allows_free_text) values
  ('vocational', 'Vocational training (classroom or workshop)', 'تدريب مهني (قاعة أو مشغل)', 1, false),
  ('on_the_job', 'On the job training', 'تدريب أثناء العمل', 2, false),
  ('combined', 'Combined', 'مدمج', 3, false);

-- ── ref_rmth_training_topic (AC-12) ──
insert into public.ref_rmth_training_topic (code, label_en, label_ar, sort_order, allows_free_text) values
  ('production_practices', 'Production practices', 'ممارسات الإنتاج', 1, false),
  ('quality_standards', 'Quality standards', 'معايير الجودة', 2, false),
  ('management_skills', 'Basic management skills', 'مهارات الإدارة الأساسية', 3, false),
  ('other', 'Other', 'أخرى', 4, true);

-- ── ref_rmth_stakeholder_type (PA-04) ──
insert into public.ref_rmth_stakeholder_type (code, label_en, label_ar, sort_order, allows_free_text) values
  ('municipal_staff', 'Municipal staff', 'موظف بلدية', 1, false),
  ('university', 'University', 'جامعة', 2, false),
  ('private_sector', 'Private sector', 'القطاع الخاص', 3, false),
  ('other_stakeholder', 'Other stakeholder', 'جهة أخرى', 4, false);

-- ── ref_rmth_incubation_service (PA-05) ──
insert into public.ref_rmth_incubation_service (code, label_en, label_ar, sort_order, allows_free_text) values
  ('business_development', 'Business development support', 'دعم تطوير الأعمال', 1, false),
  ('mentorship', 'Mentorship', 'الإرشاد والتوجيه', 2, false),
  ('finance_guidance', 'Access to finance guidance', 'التوجيه للوصول إلى التمويل', 3, false),
  ('networking', 'Networking', 'التشبيك', 4, false),
  ('linkage', 'Linkage to national programmes or private sector', 'الربط بالبرامج الوطنية أو القطاع الخاص', 5, false);

-- ── ref_rmth_employability_outcome (FU-03) ──
insert into public.ref_rmth_employability_outcome (code, label_en, label_ar, sort_order, allows_free_text) values
  ('job_interview', 'Job interview', 'مقابلة عمل', 1, false),
  ('job_offer', 'Job offer', 'عرض عمل', 2, false),
  ('internship', 'Internship or on the job training placement', 'تدريب داخلي أو تدريب أثناء العمل', 3, false),
  ('paid_employment', 'Paid employment', 'عمل مدفوع الأجر', 4, false),
  ('self_employment', 'Self employment or own business', 'عمل حر أو مشروع خاص', 5, false),
  ('none', 'None', 'لا شيء', 6, false);

-- ── ref_rmth_placement_type (FU-05) ──
insert into public.ref_rmth_placement_type (code, label_en, label_ar, sort_order, allows_free_text) values
  ('paid_employment', 'Paid employment', 'عمل مدفوع الأجر', 1, false),
  ('internship', 'Internship or on the job training', 'تدريب داخلي أو تدريب أثناء العمل', 2, false);

-- ── ref_rmth_work_status (FU-06) ──
insert into public.ref_rmth_work_status (code, label_en, label_ar, sort_order, allows_free_text) values
  ('paid_employment', 'Paid employment', 'عمل مدفوع الأجر', 1, false),
  ('self_employment', 'Self employment or own business', 'عمل حر أو مشروع خاص', 2, false),
  ('internship', 'Internship or on the job training', 'تدريب داخلي أو تدريب أثناء العمل', 3, false),
  ('not_working', 'Not working', 'لا يعمل', 4, false);

-- ── verification ──────────────────────────────────────────────────────────
do $verify$
declare
  v_tables int;
  v_rows   int;
  v_bad    int;
  v_free   int;
begin
  select count(*) into v_tables from pg_tables where schemaname = 'public' and tablename like 'ref\_rmth\_%';
  if v_tables <> 14 then
    raise exception '0176: expected 14 ref_rmth_ tables, found %', v_tables;
  end if;

  -- every table has RLS, two policies, the four standard triggers, and rows
  select count(*) into v_bad
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relname like 'ref\_rmth\_%' and c.relkind = 'r'
     and (not c.relrowsecurity
          or (select count(*) from pg_policy p where p.polrelid = c.oid) <> 2
          or (select count(*) from pg_trigger tg where tg.tgrelid = c.oid and not tg.tgisinternal) <> 4);
  if v_bad <> 0 then
    raise exception '0176: % ref_rmth_ tables are missing RLS, a policy or a trigger', v_bad;
  end if;

  execute (
    select 'select ' || string_agg(format('(select count(*) from public.%I)', tablename), ' + ')
      from pg_tables where schemaname = 'public' and tablename in ('ref_rmth_sex', 'ref_rmth_age_group', 'ref_rmth_nationality', 'ref_rmth_sector', 'ref_rmth_activity_category', 'ref_rmth_networking_type', 'ref_rmth_joint_partner', 'ref_rmth_training_type', 'ref_rmth_training_topic', 'ref_rmth_stakeholder_type', 'ref_rmth_incubation_service', 'ref_rmth_employability_outcome', 'ref_rmth_placement_type', 'ref_rmth_work_status'))
    into v_rows;
  if v_rows <> 59 then
    raise exception '0176: expected 59 option rows, found %', v_rows;
  end if;

  execute (
    select 'select ' || string_agg(format('(select count(*) from public.%I where allows_free_text)', tablename), ' + ')
      from pg_tables where schemaname = 'public' and tablename in ('ref_rmth_sex', 'ref_rmth_age_group', 'ref_rmth_nationality', 'ref_rmth_sector', 'ref_rmth_activity_category', 'ref_rmth_networking_type', 'ref_rmth_joint_partner', 'ref_rmth_training_type', 'ref_rmth_training_topic', 'ref_rmth_stakeholder_type', 'ref_rmth_incubation_service', 'ref_rmth_employability_outcome', 'ref_rmth_placement_type', 'ref_rmth_work_status'))
    into v_free;
  if v_free <> 3 then
    raise exception '0176: expected 3 free-text options, found %', v_free;
  end if;
end $verify$;
