-- ═══════════════════════════════════════════════════════════════════════════
--  0179 — Ramtha's framework rows brought to RMTH_Forms_and_Calculations_v2.xlsx
--
--  GENERATED by supabase/ramtha/gen_framework.py from workbook.py (the
--  "Calculation Method" sheet). Do not edit; edit the generator and
--  regenerate.
--
--  ── THE CODES ──
--
--  The workbook numbers two indicators RMTH-SO1-A0.1 and RMTH-SO1-A0.2; both
--  framework workbooks (RAMTHA Framework.xlsx and its Arabic copy) call them
--  A1.2 and A1.3. The owner decided on 1 October 2026 that the new workbook
--  wins (OQ-79): code and full_code are renamed, the statements -- the same
--  in both -- are kept. Targets follow by indicator_id, and every one is
--  still null (OQ-48).
--
--  RMTH-SO1-A1 had a code and no statement (OQ-48). The workbook gives it
--  one -- "% of job fair and career guidance participants who report
--  improved knowledge ..." -- and a formula (FORM-05). Its Arabic is drafted
--  (OQ-78); its type, which no source states, is an intermediate result, as
--  B1 and C1 are at the same place in the framework (OQ-79); its unit is %.
--
--  ── THE FORMULAS ──
--
--  indicator.formula is the sheet's Formula cell, VERBATIM, line breaks
--  included: it is the specification 0180's views implement, written in the
--  Field IDs of the seven forms. disaggregation is the cell's "Disaggregate
--  by:" line, split on its bars. data_source is the table of the first form
--  the sheet's "Required Field(s)" names (FORM-01 aside: it supplies the
--  breakdowns, never the count). view_name is the leaf view 0180 creates.
--  The other statements stay as 0131 wrote them, from the framework.
--
--  ── THE OPEN DEFINITIONS ──
--
--  Four parameters of the new formulas are still undecided -- X months
--  (IMP-0), the short-term intensive thresholds (C1.1, now a maximum
--  duration and a minimum of TOTAL contact hours, AC-09), N months of six
--  (SO3-0), and programmes or sessions (F0.2) -- and stay rmth_threshold
--  rows, reworded from the sheet; c11_min_total_hours is added. Every value
--  is set back to null: what the ten rows held were the 16 September audit's
--  probe values ("AUD rule c12 ..."), not decisions (CLEANUP_PLAN.md), and a
--  dashboard computing from them computes from definitions nobody made.
--
--  Six rows are retired: the new forms answer them directly (PA-03 asks
--  whether the participant met the completion criteria; FU-03 is the
--  employability outcome; the sheet's formula for SO2-0 names its placement
--  types) or ask them differently (hours per week -> total hours). They are
--  soft-deleted. guard_soft_delete admits a coordinator only, and a schema
--  change run as the owner is not a coordinator's decision about a record,
--  so its trigger is disabled for that one statement and enabled again.
--  The questions the sheet marks REQUIRES CONFIRMATION without a parameter
--  are OQ-80.
-- ═══════════════════════════════════════════════════════════════════════════

create temp table _0179_others_before on commit drop as
  select i.* from public.indicator i join public.municipality m on m.id = i.municipality_id where m.code <> 'RMTH';

-- ── 1. the two codes the workbook renames ─────────────────────────────────
update public.indicator i set code = 'A0.1', full_code = 'RMTH-SO1-A0.1'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.code = 'A1.2';
update public.indicator i set code = 'A0.2', full_code = 'RMTH-SO1-A0.2'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.code = 'A1.3';

-- ── 2. every indicator's formula, source, view and breakdowns ──────────
-- RMTH-IMP-0 (Distinct count, Persons)
update public.indicator i set
  formula = 'Eligible person: PR-01 appears in FORM-04 (PA-02) for any activity OR latest FU-09 = Yes.
Use the latest FORM-06 record per person (MAX FU-02).
Sustained = FU-06 ∈ {Paid employment, Self employment or own business} AND months between FU-07 and FU-02 ≥ X.
Result = COUNT(DISTINCT FU-01 WHERE eligible AND sustained) — cumulative, each person once.
Disaggregate by: sex PR-02 | age group PR-04 | nationality PR-05 | vulnerability PR-06 | pathway (first match): FU-09 = Yes → Employment through projects; FU-06 = Self employment → Self-employment / entrepreneurship; FU-03 includes Internship/OJT → OJT → employment; PA-03 = Yes on a training → Employment after training.
REQUIRES CONFIRMATION: value of X. The framework''s own formula cell is garbled; restated as a de-duplicated count to match unit = Persons.',
  data_source = 'rmth_followup',
  view_name = 'v_ind_rmth_imp_0',
  disaggregation = array['sex PR-02', 'age group PR-04', 'nationality PR-05', 'vulnerability PR-06', 'pathway (first match): FU-09 = Yes → Employment through projects; FU-06 = Self employment → Self-employment / entrepreneurship; FU-03 includes Internship/OJT → OJT → employment; PA-03 = Yes on a training → Employment after training']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-IMP-0';

-- RMTH-SO1-0 (Distinct count, Persons)
update public.indicator i set
  formula = 'Eligible person: PA-02 linked to an activity with AC-02 = Networking event.
Outcome = FU-03 includes any of {Job interview, Job offer, Internship or OJT placement, Paid employment} on a follow-up with FU-02 in the reporting year.
Result = COUNT(DISTINCT FU-01 WHERE eligible AND outcome).
Disaggregate by: sex PR-02 | age group PR-04 | nationality PR-05 | vulnerability PR-06 | type of employability outcome: FU-03 (count per option; option totals can exceed the headline).
Self-employment is not in the framework''s outcome list and is excluded.',
  data_source = 'rmth_participation',
  view_name = 'v_ind_rmth_so1_0',
  disaggregation = array['sex PR-02', 'age group PR-04', 'nationality PR-05', 'vulnerability PR-06', 'type of employability outcome: FU-03 (count per option; option totals can exceed the headline)']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO1-0';

-- RMTH-SO1-A1 (Percentage, %)
update public.indicator i set
  name_en = '% of job fair and career guidance participants who report improved knowledge of available job opportunities and how to access them',
  name_ar = 'نسبة المشاركين في معارض التوظيف وفعاليات الإرشاد المهني الذين أفادوا بتحسّن معرفتهم بفرص العمل المتاحة وكيفية الوصول إليها',
  indicator_type = 'intermediate',
  formula = 'Filter: FB-01 activity has AC-02 = Networking event AND AC-04 in the reporting quarter; one response per FB-02 per FB-01.
Numerator = COUNT(FORM-05 WHERE FB-03 = Yes)
Denominator = COUNT(FORM-05 WHERE FB-03 answered)
Result = (Numerator ÷ Denominator) × 100
Disaggregate by: sex PR-02 | age group PR-04 | nationality PR-05 | type of event AC-03.',
  data_source = 'rmth_feedback',
  view_name = 'v_ind_rmth_a1',
  disaggregation = array['sex PR-02', 'age group PR-04', 'nationality PR-05', 'type of event AC-03']::text[],
  unit = '%'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO1-A1';

-- RMTH-SO1-A0.1 (Count, Events)
update public.indicator i set
  formula = 'Result = COUNT(FORM-03 WHERE AC-02 = Networking event AND AC-04 in the reporting quarter).
Disaggregate by: type of event AC-03 | gender of participants = COUNT(FORM-04 records for those events) split by PR-02.
Includes vocational guidance sessions, so RMTH-SO1-A0.2 is a subset of this count — never add the two.',
  data_source = 'rmth_activity',
  view_name = 'v_ind_rmth_a0_1',
  disaggregation = array['type of event AC-03', 'gender of participants = COUNT(FORM-04 records for those events) split by PR-02']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO1-A0.1';

-- RMTH-SO1-A0.2 (Count, Sessions)
update public.indicator i set
  formula = 'Result = COUNT(FORM-03 WHERE AC-02 = Networking event AND AC-03 = Vocational guidance session AND AC-04 in the reporting year).
REQUIRES CONFIRMATION: the framework''s definition, formula and ''Sector, sub-sector'' disaggregation for this row are copied from RMTH-SO1-B1.2 (approved projects). Calculated per the statement; no disaggregation applied until confirmed.',
  data_source = 'rmth_activity',
  view_name = 'v_ind_rmth_a0_2',
  disaggregation = null,
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO1-A0.2';

-- RMTH-SO1-B1 (Percentage, %)
update public.indicator i set
  formula = 'Filter: IS-03 in the reporting year; latest response per project (IS-01).
Numerator = COUNT(DISTINCT IS-01 WHERE IS-02 = Yes)
Denominator = COUNT(DISTINCT IS-01 WHERE IS-02 answered)
Result = (Numerator ÷ Denominator) × 100
Disaggregate by: sector PJ-03 (via IS-01 → PJ-01).
REQUIRES CONFIRMATION: the framework''s definition, formula and ''type of training'' disaggregation describe training programmes, not this % statement. Calculated per the statement; ''type of training'' not applicable to projects.',
  data_source = 'rmth_implementer_survey',
  view_name = 'v_ind_rmth_b1',
  disaggregation = array['sector PJ-03 (via IS-01 → PJ-01)']::text[],
  unit = '%'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO1-B1';

-- RMTH-SO1-B1.1 (Count, Programmes)
update public.indicator i set
  formula = 'Result = COUNT(FORM-03 WHERE AC-02 = Specialised training programme AND AC-07 is not blank AND AC-04 in the reporting quarter).
Disaggregate by: sector AC-06 (Industrial / Agricultural / Administrative) | type of training AC-10.
REQUIRES CONFIRMATION: the framework''s definition and formula here describe trainees completing training (duplicate of RMTH-SO2-C1.2). Calculated per the statement.',
  data_source = 'rmth_activity',
  view_name = 'v_ind_rmth_b1_1',
  disaggregation = array['sector AC-06 (Industrial / Agricultural / Administrative)', 'type of training AC-10']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO1-B1.1';

-- RMTH-SO1-B1.2 (Count, Proposals)
update public.indicator i set
  formula = 'Result = COUNT(FORM-02 WHERE PJ-02 in the reporting year).
Disaggregate by: sector PJ-03 | sub-sector PJ-04.',
  data_source = 'rmth_project',
  view_name = 'v_ind_rmth_b1_2',
  disaggregation = array['sector PJ-03', 'sub-sector PJ-04']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO1-B1.2';

-- RMTH-SO2-0 (Percentage, %)
update public.indicator i set
  formula = 'Completer = PA-03 = Yes on an activity with AC-02 in {Specialised training programme, Short term training cycle}. Due date = AC-05 + 3 months.
Denominator = COUNT(DISTINCT PA-02 completers WHERE due date falls in the reporting quarter)
Numerator = COUNT(DISTINCT completers in the denominator WITH a FORM-06 record where FU-03 includes {Internship or OJT placement, Paid employment} AND FU-04 ≤ AC-05 + 3 months)
Result = (Numerator ÷ Denominator) × 100
Disaggregate by: sex PR-02 | age group PR-04 | nationality PR-05 | vulnerability PR-06 | type of placement FU-05.
Completers not reached at follow-up stay in the denominator (counted as not placed).
REQUIRES CONFIRMATION: whether self-employment counts as a placement; completion / job-ready criteria behind PA-03.',
  data_source = 'rmth_participation',
  view_name = 'v_ind_rmth_so2_0',
  disaggregation = array['sex PR-02', 'age group PR-04', 'nationality PR-05', 'vulnerability PR-06', 'type of placement FU-05']::text[],
  unit = '%'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO2-0';

-- RMTH-SO2-C1 (Percentage, %)
update public.indicator i set
  formula = 'Filter: FB-01 activity has AC-02 in {Specialised training programme, Short term training cycle} AND AC-05 in the reporting quarter; one response per FB-02 per FB-01.
Numerator = COUNT(FORM-05 WHERE FB-04 = Yes)
Denominator = COUNT(FORM-05 WHERE FB-04 answered)
Result = (Numerator ÷ Denominator) × 100
Disaggregate by: sex PR-02 | age group PR-04 | nationality PR-05 | type of training AC-10 (and AC-02 programme vs cycle).
REQUIRES CONFIRMATION: whether entrepreneurship trainees are also in scope (currently excluded).',
  data_source = 'rmth_feedback',
  view_name = 'v_ind_rmth_c1',
  disaggregation = array['sex PR-02', 'age group PR-04', 'nationality PR-05', 'type of training AC-10 (and AC-02 programme vs cycle)']::text[],
  unit = '%'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO2-C1';

-- RMTH-SO2-C1.1 (Count, Training cycles)
update public.indicator i set
  formula = 'Result = COUNT(FORM-03 WHERE AC-02 = Short term training cycle AND AC-05 in the reporting year
AND AC-08 includes Private sector establishment
AND AC-08 includes (Academic institution OR Vocational institution)
AND (AC-05 − AC-04) ≤ max duration AND AC-09 ≥ min hours).
Disaggregate by: sector AC-06 | type of training AC-10.
REQUIRES CONFIRMATION: ''short-term intensive'' thresholds. Framework definition/formula here are a generic copy (''programs developed''); statement (cycles delivered) followed.',
  data_source = 'rmth_activity',
  view_name = 'v_ind_rmth_c1_1',
  disaggregation = array['sector AC-06', 'type of training AC-10']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO2-C1.1';

-- RMTH-SO2-C1.2 (Distinct count, Persons)
update public.indicator i set
  formula = 'Result = COUNT(DISTINCT PA-02 WHERE PA-03 = Yes AND activity AC-02 in {Specialised training programme, Short term training cycle} AND AC-05 in the reporting quarter).
Cumulative total = COUNT(DISTINCT PA-02) across all periods (a person completing two trainings counts once).
Disaggregate by: sex PR-02 | nationality PR-05 | age group PR-04.
REQUIRES CONFIRMATION: completion / job-ready criteria applied when recording PA-03.',
  data_source = 'rmth_participation',
  view_name = 'v_ind_rmth_c1_2',
  disaggregation = array['sex PR-02', 'nationality PR-05', 'age group PR-04']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO2-C1.2';

-- RMTH-SO3-0 (Distinct count, Persons)
update public.indicator i set
  formula = 'Eligible person: PA-02 linked to an activity with AC-02 ∈ {Entrepreneurship training programme, Business incubator}.
Use the latest FORM-06 record per person with FU-02 in the reporting year.
Result = COUNT(DISTINCT FU-01 WHERE eligible AND FU-06 = Self employment or own business AND FU-08 ≥ N).
Disaggregate by: sex PR-02 | age group PR-04 | nationality PR-05 | vulnerability PR-06.
REQUIRES CONFIRMATION: N months out of 6 that define ''regular income'' (working assumption 4).',
  data_source = 'rmth_participation',
  view_name = 'v_ind_rmth_so3_0',
  disaggregation = array['sex PR-02', 'age group PR-04', 'nationality PR-05', 'vulnerability PR-06']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO3-0';

-- RMTH-SO3-E0.1 (Count (cumulative), Incubators)
update public.indicator i set
  formula = 'Result = COUNT(FORM-03 WHERE AC-02 = Business incubator AND AC-04 ≤ end of the reporting year).
Disaggregate by: field AC-06.
''Established'' = core incubation services have started (AC-04). The framework''s ''type of training'' disaggregation is not applicable to an incubator.',
  data_source = 'rmth_activity',
  view_name = 'v_ind_rmth_e0_1',
  disaggregation = array['field AC-06']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO3-E0.1';

-- RMTH-SO3-E0.2 (Distinct count, Persons)
update public.indicator i set
  formula = 'Result = COUNT(DISTINCT PA-02 WHERE activity AC-02 = Business incubator AND PA-05 not empty AND PA-06 in the reporting quarter).
Disaggregate by: sex PR-02 | nationality PR-05 | sector AC-06 of the incubator | type of service PA-05 (distinct persons per option).',
  data_source = 'rmth_participation',
  view_name = 'v_ind_rmth_e0_2',
  disaggregation = array['sex PR-02', 'nationality PR-05', 'sector AC-06 of the incubator', 'type of service PA-05 (distinct persons per option)']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO3-E0.2';

-- RMTH-SO3-E0.3 (Distinct count, Persons)
update public.indicator i set
  formula = 'Result = COUNT(DISTINCT PA-02 WHERE activity AC-02 = Incubator design training AND PA-03 = Yes AND AC-05 in the reporting quarter).
Disaggregate by: sex PR-02 | institution / stakeholder type PA-04.',
  data_source = 'rmth_participation',
  view_name = 'v_ind_rmth_e0_3',
  disaggregation = array['sex PR-02', 'institution / stakeholder type PA-04']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO3-E0.3';

-- RMTH-SO3-F0.1 (Distinct count, Persons)
update public.indicator i set
  formula = 'Result = COUNT(DISTINCT PA-02 WHERE activity AC-02 = Entrepreneurship training programme AND PA-03 = Yes AND AC-05 in the reporting quarter).
Disaggregate by: sex PR-02 | nationality PR-05 | type of training AC-12 (per topic).
REQUIRES CONFIRMATION: completion criteria for ''successfully completed''.',
  data_source = 'rmth_participation',
  view_name = 'v_ind_rmth_f0_1',
  disaggregation = array['sex PR-02', 'nationality PR-05', 'type of training AC-12 (per topic)']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO3-F0.1';

-- RMTH-SO3-F0.2 (Count (alt. Sum), Programmes)
update public.indicator i set
  formula = 'Result (statement) = COUNT(FORM-03 WHERE AC-02 = Entrepreneurship training programme AND AC-04 in the reporting year).
Alternative (definition) = SUM(AC-11) for the same records = sessions delivered.
Disaggregate by: sector AC-06 | type of training AC-12.
REQUIRES CONFIRMATION: statement counts programmes developed (target 2) but definition counts sessions delivered — choose one; both are computable.',
  data_source = 'rmth_activity',
  view_name = 'v_ind_rmth_f0_2',
  disaggregation = array['sector AC-06', 'type of training AC-12']::text[],
  unit = '#'
  from public.municipality m
 where m.id = i.municipality_id and m.code = 'RMTH' and i.full_code = 'RMTH-SO3-F0.2';

-- ── 3. the open definitions ──────────────────────────────────────────────
alter table public.rmth_threshold disable trigger trg_rmth_threshold_soft_delete;
update public.rmth_threshold t set deleted_at = now()
  from public.municipality m
 where m.id = t.municipality_id and m.code = 'RMTH' and t.deleted_at is null
   and t.key in ('so10_employability_threshold', 'so20_self_employment_counts', 'c12_completion_rule', 'e03_completion_rule', 'f01_completion_rule', 'c11_min_hours_per_week');
alter table public.rmth_threshold enable trigger trg_rmth_threshold_soft_delete;

update public.rmth_threshold t set value_numeric = null, value_text = null, value_bool = null,
       decided_on = null, decided_by = null
  from public.municipality m
 where m.id = t.municipality_id and m.code = 'RMTH';

update public.rmth_threshold t set open_item = 'sustained_engagement', unit = 'months',
       label_en = 'Sustained employment: minimum months working or earning continuously (X)',
       label_ar = 'التشغيل المستدام: الحد الأدنى للأشهر المتواصلة من العمل أو الدخل (X)',
       note_en = 'RMTH-IMP-0. The Calculation Method sheet counts a person as sustained when their latest follow-up says paid employment or self-employment (FU-06) and the months from FU-07 (working continuously since) to FU-02 (the follow-up date) are at least X. The sheet marks X as REQUIRES CONFIRMATION. Until X is set the indicator is not computable.',
       note_ar = 'RMTH-IMP-0. تعدّ ورقة طريقة الاحتساب الشخص مستداماً عندما تفيد آخر متابعة له بعمل مدفوع الأجر أو عمل حر (FU-06)، وتكون الأشهر من FU-07 (يعمل بشكل متواصل منذ) إلى FU-02 (تاريخ المتابعة) X شهراً على الأقل. تشير الورقة إلى أن قيمة X تحتاج إلى تأكيد. إلى أن تُحدَّد X لا يمكن احتساب المؤشر.'
  from public.municipality m
 where m.id = t.municipality_id and m.code = 'RMTH' and t.key = 'imp0_sustained_months';

update public.rmth_threshold t set open_item = 'short_term_intensive', unit = 'weeks',
       label_en = 'Short-term intensive: maximum duration in weeks (AC-04 to AC-05)',
       label_ar = 'قصير الأمد ومكثف: الحد الأقصى للمدة بالأسابيع (من AC-04 إلى AC-05)',
       note_en = 'RMTH-SO2-C1.1. The sheet counts a short term training cycle when (AC-05 − AC-04) is at most the maximum duration and AC-09 is at least the minimum hours, and marks both thresholds REQUIRES CONFIRMATION. This row is the maximum duration, in weeks. Both rows must be set before C1.1 is computable.',
       note_ar = 'RMTH-SO2-C1.1. تعدّ الورقة الدورة التدريبية القصيرة عندما تكون (AC-05 − AC-04) لا تزيد على الحد الأقصى للمدة، ويكون AC-09 لا يقل عن الحد الأدنى للساعات، وتشير إلى أن الحدين يحتاجان إلى تأكيد. هذا الصف هو الحد الأقصى للمدة بالأسابيع. يجب تحديد الصفين قبل أن يصبح C1.1 قابلاً للاحتساب.'
  from public.municipality m
 where m.id = t.municipality_id and m.code = 'RMTH' and t.key = 'c11_max_weeks';

insert into public.rmth_threshold (municipality_id, key, open_item, label_en, label_ar, unit, note_en, note_ar)
select m.id, 'c11_min_total_hours', 'short_term_intensive', 'Short-term intensive: minimum total contact hours (AC-09)', 'قصير الأمد ومكثف: الحد الأدنى لإجمالي الساعات التدريبية (AC-09)', 'hours', 'RMTH-SO2-C1.1. The "AC-09 ≥ min hours" half of the threshold: AC-09 is the cycle''s total training contact hours. Both rows must be set before C1.1 is computable.', 'RMTH-SO2-C1.1. شطر "AC-09 ≥ الحد الأدنى للساعات" من الحد: AC-09 هو إجمالي الساعات التدريبية للدورة. يجب تحديد الصفين قبل أن يصبح C1.1 قابلاً للاحتساب.' from public.municipality m where m.code = 'RMTH';

update public.rmth_threshold t set open_item = 'regular_income', unit = 'months of six',
       label_en = 'Regular income: minimum months with income out of the last six (N)',
       label_ar = 'الدخل المنتظم: الحد الأدنى للأشهر ذات الدخل من الأشهر الستة الأخيرة (N)',
       note_en = 'RMTH-SO3-0. The sheet counts FU-08 ≥ N months out of the last six as regular income, with 4 as its working assumption, marked REQUIRES CONFIRMATION. The assumption is not applied until it is confirmed or changed here.',
       note_ar = 'RMTH-SO3-0. تعدّ الورقة FU-08 ≥ N شهراً من الأشهر الستة الأخيرة دخلاً منتظماً، مع افتراض عمل قدره 4، وتشير إلى أنه يحتاج إلى تأكيد. لا يُطبَّق الافتراض حتى يُؤكَّد أو يُعدَّل هنا.'
  from public.municipality m
 where m.id = t.municipality_id and m.code = 'RMTH' and t.key = 'so30_income_months_of_six';

update public.rmth_threshold t set open_item = 'programmes_or_sessions', unit = null,
       label_en = 'F0.2 counts programmes, or sessions delivered?',
       label_ar = 'هل يعدّ F0.2 البرامج أم الجلسات المنفذة؟',
       note_en = 'RMTH-SO3-F0.2. The statement counts entrepreneurship training programmes (FORM-03 records); the definition counts sessions delivered (the sum of AC-11). The sheet says choose one; both are computable. Value: "programmes" or "sessions". Until chosen, not computable.',
       note_ar = 'RMTH-SO3-F0.2. يعدّ نص المؤشر برامج التدريب على ريادة الأعمال (سجلات FORM-03)؛ ويعدّ التعريف الجلسات المنفذة (مجموع AC-11). تطلب الورقة اختيار أحدهما؛ وكلاهما قابل للاحتساب. القيمة: "programmes" أو "sessions". إلى أن يُختار لا يمكن الاحتساب.'
  from public.municipality m
 where m.id = t.municipality_id and m.code = 'RMTH' and t.key = 'f02_counting_reading';

-- ── verification ─────────────────────────────────────────────────────────
do $verify$
declare
  v_n int;
begin
  -- the eighteen, by the workbook's codes, each with a formula and a view name
  select count(*) into v_n from public.indicator i join public.municipality m on m.id = i.municipality_id
   where m.code = 'RMTH' and i.code in ('IMP-0', 'SO1-0', 'A1', 'A0.1', 'A0.2', 'B1', 'B1.1', 'B1.2', 'SO2-0', 'C1', 'C1.1', 'C1.2', 'SO3-0', 'E0.1', 'E0.2', 'E0.3', 'F0.1', 'F0.2') and i.formula is not null and i.view_name is not null;
  if v_n <> 18 then
    raise exception '0179: % Ramtha indicators carry the workbook''s codes, a formula and a view, expected 18', v_n;
  end if;
  if exists (select 1 from public.indicator i join public.municipality m on m.id = i.municipality_id
              where m.code = 'RMTH' and i.code in ('A1.2', 'A1.3')) then
    raise exception '0179: an old code remains';
  end if;
  if exists (select 1 from public.indicator i join public.municipality m on m.id = i.municipality_id
              where m.code = 'RMTH' and i.code = 'A1' and (i.unit <> '%' or i.name_en like '%no indicator statement%')) then
    raise exception '0179: SO1-A1 has no statement';
  end if;
  -- nobody else's framework moved
  select count(*) into v_n from (
    (select * from _0179_others_before except all
     select i.* from public.indicator i join public.municipality m on m.id = i.municipality_id where m.code <> 'RMTH')
    union all
    (select i.* from public.indicator i join public.municipality m on m.id = i.municipality_id where m.code <> 'RMTH'
     except all select * from _0179_others_before)) d;
  if v_n <> 0 then
    raise exception '0179: % indicator rows of another municipality changed', v_n;
  end if;
  -- five open definitions, live, undecided; six retired
  select count(*) into v_n from public.rmth_threshold t join public.municipality m on m.id = t.municipality_id
   where m.code = 'RMTH' and t.deleted_at is null and t.key in ('imp0_sustained_months', 'c11_max_weeks', 'c11_min_total_hours', 'so30_income_months_of_six', 'f02_counting_reading')
     and num_nonnulls(t.value_numeric, t.value_text, t.value_bool, t.decided_on) = 0;
  if v_n <> 5 then
    raise exception '0179: % open definitions live and undecided, expected 5', v_n;
  end if;
  select count(*) into v_n from public.rmth_threshold t join public.municipality m on m.id = t.municipality_id
   where m.code = 'RMTH' and t.deleted_at is null;
  if v_n <> 5 then
    raise exception '0179: % live rmth_threshold rows, expected 5', v_n;
  end if;
  -- and the guard is back on
  if not exists (select 1 from pg_trigger where tgname = 'trg_rmth_threshold_soft_delete' and tgenabled = 'O') then
    raise exception '0179: trg_rmth_threshold_soft_delete is not enabled';
  end if;
end $verify$;
