-- ═══════════════════════════════════════════════════════════════════════════
--  0159 — Khalidiyah's forms, the tables (the first 12 of 23; 0160 the rest)
--
--  GENERATED by supabase/khalidiyah/gen_schema.py from workbook.py (the one
--  reading of Khaldia_2_reviewed.xlsx) and catalogue.py. Do not edit.
--
--  ── ONE TABLE PER FORM ──
--
--  The reviewed workbook has 24 forms. FORM-03 holds one field (F010, the
--  attempt ID) and the reviewer's note says to merge it into FORM-04, so the
--  two are one table, khld_partner_contact, and F010 is its reference,
--  issued by the database (KHLD-ATT-NN). Every other form is its own table,
--  whose comment names it. Every column is a field of the form; which one is
--  catalogue.FIELDS (Field ID -> kind and column), from which the screens,
--  the locale files and this file are all generated.
--
--  ── WHAT IS NOT A COLUMN ──
--
--  A multi-select is a khld_<table>_option row per tick (question_code = the
--  Field ID in lower case, guard_khld_option). F118 and F131 (partners at a
--  meeting, on an activity) are junction rows. A file upload is an attachment
--  whose field_code is the Field ID (0158). The person fields of FORM-12,
--  FORM-15 and FORM-17 -- name, sex, date of birth, identifier, phone -- are
--  `person`, one person one row (hard rule 6), through khld_ensure_person
--  (0161); the record keeps the ID TYPE the form chose (F144 / F151 / F156),
--  which is how the shared definitions tell a refugee ("ID type = UNHCR
--  registration"). F069 and F111 are the name of the person picked, shown.
--  F012 and F159 ("(Auto gen.) date/time") default to the moment of saving.
--
--  ── THE SHEET'S VALIDATION COLUMN ──
--
--  CHECK constraints: the 0-100 percentages, F040 + F041 = 100 and F042 +
--  F043 = 100 (the reviewer's note on those fields), Jordanian% + Syrian%
--  <= 100, completed <= agreed, action days within the campaign's dates, the
--  1-5 scales, the minimums (>= 1, >= 0), dates in order, one contributor,
--  one occasion. The Dependency column is khld_field_rule (0158).
--
--  ── WHO WRITES WHAT ──
--
--  FORM-12 is also a public form: the municipality's owner decided on 26
--  September 2026 that volunteers register themselves. khld_volunteer
--  carries application_status: a staff entry is approved when saved, a
--  public one arrives 'submitted' (khld_register_volunteer, 0161) and counts
--  only once staff approve it -- SO3-0's denominator is "all registered
--  volunteers", and an unreviewed public form would let anyone move it.
--  F060 "if no then disqualified" is a CHECK: a volunteer is a resident. No
--  guardian block: the reviewed FORM-12 asks for none and the owner chose to
--  follow the sheet (06_OPEN_QUESTIONS.md). The three questionnaires
--  (FORM-19, -20, -24) are written by any staff role, enumerators included
--  (is_staff); every other table by coordinators and data entry (can_write).
--
--  ── UNIQUENESS ──
--
--  Entities are unique GLOBALLY, deleted rows included -- a partner per name,
--  a volunteer per person -- so re-entering a deleted one is a restore,
--  never a second row. Things someone took part in are unique while live: a
--  request per person per session, an application per person per market,
--  one attendance a day.
--
--  ── EVERY TABLE ──
--
--  municipality_id (default my_municipality(); the composite (id,
--  municipality_id) key; every link to another Khalidiyah table is a
--  COMPOSITE foreign key and the only key on that pair, so PostgREST sees one
--  relationship and never answers 300), the standard block, client_uuid. The
--  standard triggers, RLS, the junctions' DELETE policy and an index on
--  every foreign key are added in 0160, over all the tables at once.
-- ═══════════════════════════════════════════════════════════════════════════

create table public.khld_focal_point (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),
  focal_point_name text not null,
  phone text not null,
  assigned_on date not null,
  client_uuid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid(),
  deleted_at timestamptz,
  constraint khld_focal_point_id_municipality_key unique (id, municipality_id)
);
comment on table public.khld_focal_point is 'FORM-01 -- Responsible Officer (Focal point). 0159.';

create table public.khld_partner (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),
  name text not null,
  phone text not null,
  partner_type_id uuid not null references public.ref_khld_partner_type(id),
  expected_contribution text,
  contact_position text,
  email text,
  partner_category_id uuid not null references public.ref_khld_partner_category(id),
  partner_category_other text,
  client_uuid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid(),
  deleted_at timestamptz,
  constraint khld_partner_id_municipality_key unique (id, municipality_id)
);
create unique index khld_partner_name_key on public.khld_partner (municipality_id, lower(btrim(name)));
comment on table public.khld_partner is 'FORM-02 -- List of potential partners (Partners). 0159.';
create trigger trg_khld_partner_other before insert or update on public.khld_partner for each row execute function public.guard_rmth_other('partner_category_id:ref_khld_partner_category:partner_category_other');

create table public.khld_partner_contact (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),
  reference text,
  partner_id uuid not null,
  attempted_at timestamptz not null default now(),
  attempt_case_id uuid not null references public.ref_khld_attempt_case(id),
  notes text,
  evaluation_id uuid references public.ref_khld_attempt_evaluation(id),
  partnership_confirmed boolean,
  client_uuid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid(),
  deleted_at timestamptz,
  constraint khld_partner_contact_id_municipality_key unique (id, municipality_id),
  constraint khld_partner_contact_reference_key unique (municipality_id, reference),
  constraint khld_partner_contact_partner_id_fkey foreign key (partner_id, municipality_id) references public.khld_partner(id, municipality_id)
);
comment on table public.khld_partner_contact is 'FORM-03 + FORM-04 -- Reach out to partners (Partner outreach). 0159.';
create trigger trg_khld_partner_contact_reference before insert on public.khld_partner_contact for each row execute function public.khld_assign_reference('ATT', '2');
create trigger trg_khld_partner_contact_rules before insert or update on public.khld_partner_contact for each row execute function public.guard_khld_rules();

create table public.khld_meeting (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),
  reference text,
  meeting_date date not null,
  summary text,
  priorities_identified boolean not null,
  meeting_type_id uuid not null references public.ref_khld_meeting_type(id),
  meeting_type_other text,
  attendees_count int not null,
  client_uuid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid(),
  deleted_at timestamptz,
  constraint khld_meeting_id_municipality_key unique (id, municipality_id),
  constraint khld_meeting_reference_key unique (municipality_id, reference),
  constraint khld_meeting_attendees_count_min check (attendees_count >= 1)
);
comment on table public.khld_meeting is 'FORM-05 -- Stakeholder Meetings (Stakeholder meetings). 0159.';
create trigger trg_khld_meeting_reference before insert on public.khld_meeting for each row execute function public.khld_assign_reference('MTG', '2', 'meeting_date');
create trigger trg_khld_meeting_other before insert or update on public.khld_meeting for each row execute function public.guard_rmth_other('meeting_type_id:ref_khld_meeting_type:meeting_type_other');

create table public.khld_rehab_report (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),
  reference text,
  completion_pct numeric(5,2) not null,
  report_date date not null,
  accomplished text not null,
  agreed_total int not null,
  completed_count int not null,
  client_uuid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid(),
  deleted_at timestamptz,
  constraint khld_rehab_report_id_municipality_key unique (id, municipality_id),
  constraint khld_rehab_report_reference_key unique (municipality_id, reference),
  constraint khld_rehab_report_completion_pct_0_100 check (completion_pct between 0 and 100),
  constraint khld_rehab_report_agreed_total_min check (agreed_total >= 1),
  constraint khld_rehab_report_completed_count_min check (completed_count >= 0),
  constraint khld_rehab_report_completed_within_agreed check (completed_count <= agreed_total)
);
comment on table public.khld_rehab_report is 'FORM-06 -- Checklist (Rehabilitation progress). 0159.';
create trigger trg_khld_rehab_report_reference before insert on public.khld_rehab_report for each row execute function public.khld_assign_reference('REH', '2', 'report_date');

create table public.khld_campaign (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),
  reference text,
  campaign_name text not null,
  start_date date not null,
  end_date date not null,
  applications_open date not null,
  applications_close date not null,
  description text not null,
  has_sponsor boolean not null,
  sponsor_name text,
  status_id uuid not null references public.ref_khld_event_status(id),
  action_days int,
  client_uuid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid(),
  deleted_at timestamptz,
  constraint khld_campaign_id_municipality_key unique (id, municipality_id),
  constraint khld_campaign_reference_key unique (municipality_id, reference),
  constraint khld_campaign_action_days_min check (action_days >= 1),
  constraint khld_campaign_dates_in_order check (end_date >= start_date),
  constraint khld_campaign_window_in_order check (applications_close >= applications_open),
  constraint khld_campaign_action_days_within_dates check (action_days is null or action_days <= (end_date - start_date + 1))
);
comment on table public.khld_campaign is 'FORM-07 -- Volunteer Campaigns (Volunteer campaigns). 0159.';
create trigger trg_khld_campaign_reference before insert on public.khld_campaign for each row execute function public.khld_assign_reference('VC', '2', 'start_date');
create trigger trg_khld_campaign_rules before insert or update on public.khld_campaign for each row execute function public.guard_khld_rules();

create table public.khld_activity (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),
  reference text,
  start_date date not null,
  end_date date not null,
  description text not null,
  activity_type_id uuid not null references public.ref_khld_activity_type(id),
  target_audience_id uuid not null references public.ref_khld_target_audience(id),
  organiser_id uuid not null references public.ref_khld_organiser(id),
  organiser_other text,
  activity_name text not null,
  status_id uuid not null references public.ref_khld_event_status(id),
  is_published boolean not null default false,
  client_uuid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid(),
  deleted_at timestamptz,
  constraint khld_activity_id_municipality_key unique (id, municipality_id),
  constraint khld_activity_reference_key unique (municipality_id, reference),
  constraint khld_activity_dates_in_order check (end_date >= start_date)
);
comment on table public.khld_activity is 'FORM-08 -- Community Activities (Community activities). 0159.';
create trigger trg_khld_activity_reference before insert on public.khld_activity for each row execute function public.khld_assign_reference('EV', '2', 'start_date');
create trigger trg_khld_activity_other before insert or update on public.khld_activity for each row execute function public.guard_rmth_other('organiser_id:ref_khld_organiser:organiser_other');

create table public.khld_activity_attendance (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),
  report_date date not null,
  activity_id uuid not null,
  total_participants int not null,
  pct_children numeric(5,2) not null,
  pct_adults numeric(5,2) not null,
  pct_male numeric(5,2) not null,
  pct_female numeric(5,2) not null,
  pct_disability numeric(5,2) not null,
  social_media_links text,
  counting_method_id uuid not null references public.ref_khld_counting_method(id),
  pct_youth numeric(5,2) not null,
  pct_jordanian numeric(5,2) not null,
  pct_syrian numeric(5,2) not null,
  observed_interaction_id uuid not null references public.ref_khld_observed_interaction(id),
  client_uuid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid(),
  deleted_at timestamptz,
  constraint khld_activity_attendance_id_municipality_key unique (id, municipality_id),
  constraint khld_activity_attendance_activity_id_fkey foreign key (activity_id, municipality_id) references public.khld_activity(id, municipality_id),
  constraint khld_activity_attendance_total_participants_min check (total_participants >= 0),
  constraint khld_activity_attendance_pct_children_0_100 check (pct_children between 0 and 100),
  constraint khld_activity_attendance_pct_adults_0_100 check (pct_adults between 0 and 100),
  constraint khld_activity_attendance_pct_male_0_100 check (pct_male between 0 and 100),
  constraint khld_activity_attendance_pct_female_0_100 check (pct_female between 0 and 100),
  constraint khld_activity_attendance_pct_disability_0_100 check (pct_disability between 0 and 100),
  constraint khld_activity_attendance_pct_youth_0_100 check (pct_youth between 0 and 100),
  constraint khld_activity_attendance_pct_jordanian_0_100 check (pct_jordanian between 0 and 100),
  constraint khld_activity_attendance_pct_syrian_0_100 check (pct_syrian between 0 and 100),
  constraint khld_activity_attendance_age_split_is_100 check (pct_children + pct_adults = 100),
  constraint khld_activity_attendance_sex_split_is_100 check (pct_male + pct_female = 100),
  constraint khld_activity_attendance_nationality_within_100 check (pct_jordanian + pct_syrian <= 100)
);
comment on table public.khld_activity_attendance is 'FORM-09 -- Register your participation in garden activities (Activity participation). 0159.';

create table public.khld_committee_member (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),
  member_name text not null,
  phone text not null,
  appointed_on date not null,
  sex_id uuid not null references public.ref_khld_sex(id),
  organisation text not null,
  organisation_type_id uuid not null references public.ref_khld_organisation_type(id),
  role_id uuid not null references public.ref_khld_committee_role(id),
  client_uuid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid(),
  deleted_at timestamptz,
  constraint khld_committee_member_id_municipality_key unique (id, municipality_id)
);
comment on table public.khld_committee_member is 'FORM-10 -- Volunteer Management Committee (Committee members). 0159.';

create table public.khld_committee_meeting (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),
  reference text,
  meeting_date date not null,
  summary text,
  workplan_discussed boolean not null,
  is_founding boolean not null,
  members_present int not null,
  client_uuid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid(),
  deleted_at timestamptz,
  constraint khld_committee_meeting_id_municipality_key unique (id, municipality_id),
  constraint khld_committee_meeting_reference_key unique (municipality_id, reference),
  constraint khld_committee_meeting_members_present_min check (members_present >= 1)
);
comment on table public.khld_committee_meeting is 'FORM-11 -- Volunteer Management Committee Meeting Record (Committee meetings). 0159.';
create trigger trg_khld_committee_meeting_reference before insert on public.khld_committee_meeting for each row execute function public.khld_assign_reference('CMT', '2', 'meeting_date');

create table public.khld_volunteer (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),
  reference text,
  person_id uuid not null references public.person(id),
  id_type_id uuid not null references public.ref_khld_id_type(id),
  is_resident boolean not null,
  nationality_id uuid not null references public.ref_khld_nationality(id),
  nationality_other text,
  disability_id uuid not null references public.ref_khld_disability(id),
  situation_id uuid not null references public.ref_khld_situation(id),
  photo_consent boolean not null,
  affiliation_id uuid not null references public.ref_khld_affiliation(id),
  affiliation_other text,
  affiliation_name text,
  application_status text not null default 'approved' check (application_status in ('submitted', 'approved', 'rejected')),
  submitted_publicly boolean not null default false,
  reviewed_by uuid references auth.users(id),
  reviewed_on timestamptz,
  client_uuid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid(),
  deleted_at timestamptz,
  constraint khld_volunteer_id_municipality_key unique (id, municipality_id),
  constraint khld_volunteer_reference_key unique (municipality_id, reference),
  constraint khld_volunteer_is_resident_yes check (is_resident is true)
);
create unique index khld_volunteer_person_key on public.khld_volunteer (municipality_id, person_id);
comment on table public.khld_volunteer is 'FORM-12 -- Volunteer Database (Volunteers). 0159.';
create trigger trg_khld_volunteer_reference before insert on public.khld_volunteer for each row execute function public.khld_assign_reference('VOL', '4');
create trigger trg_khld_volunteer_other before insert or update on public.khld_volunteer for each row execute function public.guard_rmth_other('nationality_id:ref_khld_nationality:nationality_other', 'affiliation_id:ref_khld_affiliation:affiliation_other');
create trigger trg_khld_volunteer_rules before insert or update on public.khld_volunteer for each row execute function public.guard_khld_rules();
create trigger trg_khld_volunteer_review before update on public.khld_volunteer for each row execute function public.khld_stamp_review();

create table public.khld_volunteer_attendance (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipality(id) default public.my_municipality(),
  report_date date not null,
  volunteer_id uuid not null,
  assessment smallint not null,
  notes text,
  campaign_id uuid,
  activity_id uuid,
  role_id uuid references public.ref_khld_volunteer_interest(id),
  role_other text,
  client_uuid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid(),
  deleted_at timestamptz,
  constraint khld_volunteer_attendance_id_municipality_key unique (id, municipality_id),
  constraint khld_volunteer_attendance_volunteer_id_fkey foreign key (volunteer_id, municipality_id) references public.khld_volunteer(id, municipality_id),
  constraint khld_volunteer_attendance_campaign_id_fkey foreign key (campaign_id, municipality_id) references public.khld_campaign(id, municipality_id),
  constraint khld_volunteer_attendance_activity_id_fkey foreign key (activity_id, municipality_id) references public.khld_activity(id, municipality_id),
  constraint khld_volunteer_attendance_assessment_1_5 check (assessment between 1 and 5),
  constraint khld_volunteer_attendance_one_occasion check ((campaign_id is null) <> (activity_id is null))
);
create unique index khld_volunteer_attendance_once_a_day_live on public.khld_volunteer_attendance (volunteer_id, coalesce(campaign_id, activity_id), report_date) where deleted_at is null;
comment on table public.khld_volunteer_attendance is 'FORM-13 -- Volunteer attendance record (Volunteer attendance). 0159.';
create trigger trg_khld_volunteer_attendance_other before insert or update on public.khld_volunteer_attendance for each row execute function public.guard_rmth_other('role_id:ref_khld_volunteer_interest:role_other');
