-- ═══════════════════════════════════════════════════════════════════════════
--  0147 — Khalidiyah's domain tables, last part: the milestone catalogue and
--         rules, the checklist rows, the ratings, the participations, the
--         question map, RLS and the standard triggers on every table, and
--         the verification over 0145-0147
--
--  0145 says why and how. Generated by supabase/khalidiyah/gen_0145.py; do
--  not edit by hand.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── the milestone catalogue: every item of the four checklists, from the sheet ──
--
-- Read by the checklist-item guard (so an item must exist on that
-- milestone and carry a status from ITS list) and by the rule validator (a
-- critical item must be a checklist row). field_type is the sheet's own
-- type, so a broken rule can be named: "item 4 is period_covered (text)".
create table public.khld_milestone_item (
  milestone_code   text not null check (milestone_code in ('SO1-A1', 'SO1-B1', 'SO3-E1', 'SO3-F1')),
  item_no          int  not null,
  field_code       text not null,
  field_type       text not null,
  list_name        text,
  label_en         text not null,
  label_ar         text not null,
  primary key (milestone_code, item_no),
  unique (milestone_code, field_code)
);
alter table public.khld_milestone_item enable row level security;
create policy khld_milestone_item_read on public.khld_milestone_item for select to authenticated using (true);
revoke insert, update, delete on public.khld_milestone_item from anon, authenticated;

insert into public.khld_milestone_item (milestone_code, item_no, field_code, field_type, list_name, label_en, label_ar) values
  ('SO1-A1', 1, 'verif_date', 'date', null, 'Date of verification', 'تاريخ التحقق'),
  ('SO1-A1', 2, 'verif_round', 'single select', null, 'Which verification is this?', 'أي عملية تحقق هذه؟'),
  ('SO1-A1', 3, 'verif_by', 'text', null, 'Verified by (name and position)', 'أُجري التحقق بواسطة (الاسم والمنصب)'),
  ('SO1-A1', 4, 'period_covered', 'text', null, 'Reporting period covered', 'الفترة المشمولة بالتقرير'),
  ('SO1-A1', 5, 'coordinator_assigned', 'checklist', 'a1_coordinator_assigned', 'Has a community coordinator / municipal liaison officer been designated in writing?', 'هل تم تعيين منسق مجتمعي / ضابط ارتباط بلدي بقرار مكتوب؟'),
  ('SO1-A1', 6, 'coordinator_ref', 'text', null, 'Decision number, date, and name of the designated officer', 'رقم القرار وتاريخه واسم الموظف المعيَّن'),
  ('SO1-A1', 7, 'coordinator_tor', 'checklist', 'checklist_status', 'Does a written task description / terms of reference for the coordinator exist?', 'هل يوجد وصف مهام / اختصاصات مكتوبة للمنسق؟'),
  ('SO1-A1', 8, 'stakeholder_map', 'checklist', 'checklist_status', 'Has a stakeholder map / list been prepared covering local associations, youth initiatives, educational institutions, local businesses, government entities and donors?', 'هل أُعدت خريطة / قائمة بأصحاب المصلحة تشمل الجمعيات المحلية والمبادرات الشبابية والمؤسسات التعليمية ومنشآت الأعمال المحلية والجهات الحكومية والجهات المانحة؟'),
  ('SO1-A1', 9, 'stakeholder_count', 'number', null, 'Number of stakeholders listed, by type', 'عدد أصحاب المصلحة المدرجين حسب النوع'),
  ('SO1-A1', 10, 'stakeholder_updated', 'date', null, 'Date the stakeholder list was last updated', 'تاريخ آخر تحديث لقائمة أصحاب المصلحة'),
  ('SO1-A1', 11, 'comms_arrangements', 'checklist', 'checklist_status', 'Are partner communication arrangements defined (contact list, who convenes, meeting cycle, channel used)?', 'هل ترتيبات التواصل مع الشركاء محددة (قائمة اتصال، الجهة التي تدعو للاجتماع، دورية الاجتماعات، قناة التواصل المستخدمة)؟'),
  ('SO1-A1', 12, 'contribution_tracking', 'checklist', 'checklist_status', 'Is a contribution tracking system in place (register of in-kind, technical, financial and volunteer contributions)?', 'هل يوجد نظام لتتبع المساهمات (سجل للمساهمات العينية والفنية والمالية والتطوعية)؟'),
  ('SO1-A1', 13, 'tracking_format', 'single select', null, 'Format of the contribution register', 'صيغة سجل المساهمات'),
  ('SO1-A1', 14, 'requirements_list', 'checklist', 'checklist_status', 'Has a list of requirements for park rehabilitation and operation been prepared (structural maintenance, landscaping, lighting, seating, playground equipment, market logistics)?', 'هل أُعدت قائمة بالاحتياجات اللازمة لتأهيل الحديقة وتشغيلها (صيانة إنشائية، تشجير، إنارة، مقاعد، ألعاب أطفال، لوجستيات الأسواق)؟'),
  ('SO1-A1', 15, 'intro_meetings', 'number', null, 'Number of introductory meetings held with potential partners during the period', 'عدد اللقاءات التعريفية التي عُقدت مع الشركاء المحتملين خلال الفترة'),
  ('SO1-A1', 16, 'partnerships_concluded', 'number', null, 'Number of documented partnerships or cooperation arrangements concluded, by partner type', 'عدد الشراكات أو ترتيبات التعاون الموثقة المنجزة حسب نوع الشريك'),
  ('SO1-A1', 17, 'zaha_coordination', 'checklist', 'a1_zaha_coordination', 'Has coordination with the Zaha Cultural Centre or a similar specialised entity produced a programming calendar?', 'هل أثمر التنسيق مع مركز زها الثقافي أو جهة متخصصة مماثلة عن روزنامة برامج؟'),
  ('SO1-A1', 18, 'periodic_updates', 'checklist', 'a1_periodic_updates', 'Are concise periodic updates on support received, resource allocation and milestones produced and shared with partners?', 'هل تُعدّ تحديثات دورية موجزة عن الدعم المستلم وتوزيع الموارد والإنجازات وتُشارك مع الشركاء؟'),
  ('SO1-A1', 19, 'council_decision', 'single select', null, 'Has the Municipal Council issued a decision adopting the partnership mechanism?', 'هل أصدر المجلس البلدي قراراً بإقرار آلية الشراكة؟'),
  ('SO1-A1', 20, 'overall_status', 'calculated', null, 'Overall milestone status', 'الحالة العامة للإنجاز المرحلي'),
  ('SO1-A1', 21, 'evidence_attached', 'attachment', null, 'Evidence attached to this verification', 'الأدلة المرفقة بعملية التحقق هذه'),
  ('SO1-A1', 22, 'gaps', 'long text', null, 'Gaps identified and follow-up actions agreed (what, who, by when)', 'الثغرات المحددة وإجراءات المتابعة المتفق عليها (ما، من، بحلول أي تاريخ)'),
  ('SO1-A1', 23, 'countersign', 'text', null, 'Countersigned by (Executive Director / Mayor) — name, signature, date', 'مصادقة (المدير التنفيذي / رئيس البلدية) — الاسم والتوقيع والتاريخ'),
  ('SO1-B1', 1, 'verif_date', 'date', null, 'Date of verification', 'تاريخ التحقق'),
  ('SO1-B1', 2, 'verif_by', 'text', null, 'Verified by (name and position)', 'أُجري التحقق بواسطة (الاسم والمنصب)'),
  ('SO1-B1', 3, 'protocol_exists', 'checklist', 'b1_protocol_exists', 'Does a written arrangement / operational protocol for the use of the park exist?', 'هل يوجد ترتيب مكتوب / بروتوكول تشغيلي لاستخدام الحديقة؟'),
  ('SO1-B1', 4, 'protocol_ref', 'text', null, 'Approval reference (Council or executive decision number and date)', 'مرجع الاعتماد (رقم قرار المجلس أو القرار التنفيذي وتاريخه)'),
  ('SO1-B1', 5, 'spaces_defined', 'checklist', 'checklist_status', 'Does the arrangement define the designated spaces and their permitted uses (children''s play area, family seating, temporary kiosks, community market area, sports field)?', 'هل يحدد الترتيب المساحات المخصصة واستخداماتها المسموحة (منطقة ألعاب الأطفال، جلسات العائلات، الأكشاك المؤقتة، منطقة السوق المجتمعي، الملعب)؟'),
  ('SO1-B1', 6, 'layout_plan', 'checklist', 'checklist_status', 'Is a simple site layout plan for the rehabilitated section available?', 'هل يتوفر مخطط توزيعي بسيط للقسم المُؤهَّل من الحديقة؟'),
  ('SO1-B1', 7, 'noncommercial_rule', 'checklist', 'checklist_status', 'Does the arrangement state in writing that the park is a public, non-commercial space and prohibit private revenue generation and appropriation?', 'هل ينص الترتيب كتابةً على أن الحديقة مساحة عامة غير تجارية ويمنع توليد الدخل الخاص والاستحواذ عليها؟'),
  ('SO1-B1', 8, 'activity_calendar', 'checklist', 'b1_activity_calendar', 'Is an activity calendar prepared and published?', 'هل أُعدت روزنامة الأنشطة وأُعلنت؟'),
  ('SO1-B1', 9, 'calendar_horizon', 'single select', null, 'Period covered by the current calendar', 'الفترة التي تغطيها الروزنامة الحالية'),
  ('SO1-B1', 10, 'request_procedure', 'checklist', 'checklist_status', 'Is there a defined procedure for a community organisation to request use of the space?', 'هل يوجد إجراء محدد يتيح لمؤسسة مجتمعية طلب استخدام المساحة؟'),
  ('SO1-B1', 11, 'requests_received', 'number', null, 'Number of use requests received and approved during the period', 'عدد طلبات الاستخدام المستلمة والموافق عليها خلال الفترة'),
  ('SO1-B1', 12, 'equitable_access', 'checklist', 'checklist_status', 'Does the arrangement state that activities are open to both the host and Syrian refugee communities, to women and to persons with disabilities, without discrimination?', 'هل ينص الترتيب على أن الأنشطة مفتوحة للمجتمع المضيف ومجتمع اللاجئين السوريين وللنساء ولذوي الإعاقة دون تمييز؟'),
  ('SO1-B1', 13, 'accessibility', 'checklist', 'checklist_status', 'Are accessibility arrangements for persons with disabilities documented (ramps, accessible pathways, accessible toilet, assistance at activities)?', 'هل ترتيبات تهيئة البيئة لذوي الإعاقة موثقة (منحدرات، ممرات مهيأة، دورة مياه مهيأة، مساندة خلال الأنشطة)؟'),
  ('SO1-B1', 14, 'maintenance_split', 'checklist', 'checklist_status', 'Are maintenance responsibilities divided in writing between the Municipality and community organisations or volunteers?', 'هل مسؤوليات الصيانة موزعة كتابةً بين البلدية والمؤسسات المجتمعية أو المتطوعين؟'),
  ('SO1-B1', 15, 'supervision', 'checklist', 'checklist_status', 'Are supervision and safety arrangements for activities defined (who supervises, what happens in case of an incident, arrangements for activities involving children)?', 'هل ترتيبات الإشراف والسلامة خلال الأنشطة محددة (من يشرف، وما يجري في حال وقوع حادث، وترتيبات الأنشطة التي تشمل أطفالاً)؟'),
  ('SO1-B1', 16, 'feedback_channel', 'checklist', 'checklist_status', 'Is a channel defined for residents to give feedback or raise a complaint about the park and its activities?', 'هل توجد قناة محددة تتيح للسكان تقديم تغذية راجعة أو شكوى بشأن الحديقة وأنشطتها؟'),
  ('SO1-B1', 17, 'communicated', 'multi select', null, 'How have the arrangements been communicated to residents and partners?', 'كيف عُمّمت هذه الترتيبات على السكان والشركاء؟'),
  ('SO1-B1', 18, 'last_updated', 'date', null, 'Date the arrangements were last reviewed or updated', 'تاريخ آخر مراجعة أو تحديث للترتيبات'),
  ('SO1-B1', 19, 'overall_status', 'calculated', null, 'Overall milestone status', 'الحالة العامة للإنجاز المرحلي'),
  ('SO1-B1', 20, 'evidence_attached', 'attachment', null, 'Evidence attached', 'الأدلة المرفقة'),
  ('SO1-B1', 21, 'gaps', 'long text', null, 'Gaps identified and follow-up actions agreed (what, who, by when)', 'الثغرات المحددة وإجراءات المتابعة المتفق عليها (ما، من، بحلول أي تاريخ)'),
  ('SO1-B1', 22, 'countersign', 'text', null, 'Countersigned by (Executive Director / Mayor) — name, signature, date', 'مصادقة (المدير التنفيذي / رئيس البلدية) — الاسم والتوقيع والتاريخ'),
  ('SO3-E1', 1, 'verif_date', 'date', null, 'Date of verification', 'تاريخ التحقق'),
  ('SO3-E1', 2, 'verif_by', 'text', null, 'Verified by (name and position)', 'أُجري التحقق بواسطة (الاسم والمنصب)'),
  ('SO3-E1', 3, 'founding_meeting', 'date', null, 'Date and venue of the founding meeting', 'تاريخ ومكان الاجتماع التأسيسي'),
  ('SO3-E1', 4, 'invitations', 'number', null, 'Number of organisations invited to the founding meeting and number that attended', 'عدد المؤسسات المدعوة للاجتماع التأسيسي وعدد الحاضرة منها'),
  ('SO3-E1', 5, 'formal_recognition', 'checklist', 'e1_formal_recognition', 'Is the committee formally recognised by the Municipality?', 'هل اللجنة معترف بها رسمياً من البلدية؟'),
  ('SO3-E1', 6, 'written_tasks', 'checklist', 'e1_written_tasks', 'Are the committee''s tasks agreed in writing (terms of reference)?', 'هل مهام اللجنة متفق عليها كتابةً (الاختصاصات)؟'),
  ('SO3-E1', 7, 'tasks_covered', 'multi select', null, 'Which of the tasks set out in the Action Plan are included in the terms of reference?', 'أي من المهام الواردة في خطة العمل مدرجة في الاختصاصات؟'),
  ('SO3-E1', 8, 'coordinator_elected', 'checklist', 'e1_coordinator_elected', 'Has a coordinator been elected from among the member organisations?', 'هل تم انتخاب منسق من بين المؤسسات الأعضاء؟'),
  ('SO3-E1', 9, 'municipal_focal', 'checklist', 'e1_municipal_focal', 'Has the Municipality designated a contact point for the committee?', 'هل عيّنت البلدية جهة اتصال للجنة؟'),
  ('SO3-E1', 10, 'membership_list', 'checklist', 'checklist_status', 'Is a membership list available, showing each organisation and its representative?', 'هل تتوفر قائمة أعضاء تبين كل مؤسسة وممثلها؟'),
  ('SO3-E1', 11, 'members_by_type', 'number', null, 'Number of member organisations by type', 'عدد المؤسسات الأعضاء حسب النوع'),
  ('SO3-E1', 12, 'members_by_sex', 'number', null, 'Committee members by sex', 'أعضاء اللجنة حسب الجنس'),
  ('SO3-E1', 13, 'inclusive_representation', 'multi select', null, 'Does the committee include representation of the following?', 'هل تضم اللجنة تمثيلاً للفئات الآتية؟'),
  ('SO3-E1', 14, 'membership_changes', 'text', null, 'Changes in membership since the last verification', 'التغيرات في العضوية منذ التحقق السابق'),
  ('SO3-E1', 15, 'meeting_cycle', 'single select', null, 'What meeting cycle has been agreed?', 'أي دورة اجتماعات اتُّفق عليها؟'),
  ('SO3-E1', 16, 'meetings_held', 'number', null, 'Number of meetings held since establishment, and number with written minutes', 'عدد الاجتماعات المعقودة منذ التأسيس وعدد الاجتماعات التي لها محاضر مكتوبة'),
  ('SO3-E1', 17, 'minutes_template', 'checklist', 'checklist_status', 'Is a standard minutes template in use, recording decisions, recommendations and assigned responsibilities?', 'هل يُستخدم نموذج موحد للمحاضر يوثق القرارات والتوصيات والمسؤوليات المُسندة؟'),
  ('SO3-E1', 18, 'outputs_delivered', 'multi select', null, 'What has the committee actually produced during the period?', 'ما الذي أنتجته اللجنة فعلياً خلال الفترة؟'),
  ('SO3-E1', 19, 'duplication_avoided', 'single select', null, 'Has the committee helped unify efforts and avoid duplication between organisations?', 'هل ساعدت اللجنة في توحيد الجهود وتجنب التكرار بين المؤسسات؟'),
  ('SO3-E1', 20, 'overall_status', 'calculated', null, 'Overall milestone status', 'الحالة العامة للإنجاز المرحلي'),
  ('SO3-E1', 21, 'evidence_attached', 'attachment', null, 'Evidence attached', 'الأدلة المرفقة'),
  ('SO3-E1', 22, 'gaps', 'long text', null, 'Gaps identified and follow-up actions agreed (what, who, by when)', 'الثغرات المحددة وإجراءات المتابعة المتفق عليها (ما، من، بحلول أي تاريخ)'),
  ('SO3-E1', 23, 'signatures', 'text', null, 'Signed by the committee coordinator and the municipal community coordinator', 'موقعة من منسق اللجنة والمنسق المجتمعي في البلدية'),
  ('SO3-F1', 1, 'verif_date', 'date', null, 'Date of verification', 'تاريخ التحقق'),
  ('SO3-F1', 2, 'verif_by', 'text', null, 'Verified by (name and position)', 'أُجري التحقق بواسطة (الاسم والمنصب)'),
  ('SO3-F1', 3, 'procedures_approved', 'checklist', 'f1_procedures_approved', 'Has a written volunteer programme concept or set of procedures been approved?', 'هل أُقرّ مفهوم مكتوب لبرنامج التطوع أو مجموعة إجراءات له؟'),
  ('SO3-F1', 4, 'launch_date', 'date', null, 'Date the programme was launched', 'تاريخ إطلاق البرنامج'),
  ('SO3-F1', 5, 'database_established', 'checklist', 'f1_database_established', 'Is a volunteer database or register established?', 'هل أُنشئت قاعدة بيانات أو سجل للمتطوعين؟'),
  ('SO3-F1', 6, 'database_format', 'number', null, 'Format of the volunteer database and number registered at the date of verification', 'صيغة قاعدة بيانات المتطوعين وعدد المسجلين بتاريخ التحقق'),
  ('SO3-F1', 7, 'registration_form', 'checklist', 'checklist_status', 'Is a standard volunteer registration form in use, capturing skills and availability?', 'هل تُستخدم استمارة تسجيل موحدة للمتطوعين تسجل المهارات وأوقات الإتاحة؟'),
  ('SO3-F1', 8, 'roles_defined', 'checklist', 'checklist_status', 'Are volunteer roles defined across the functions the Plan names?', 'هل أدوار المتطوعين محددة على امتداد الوظائف التي حددتها الخطة؟'),
  ('SO3-F1', 9, 'assignment_procedure', 'checklist', 'checklist_status', 'Is there a procedure for assigning volunteers to tasks and calling them for action days?', 'هل يوجد إجراء لتوزيع المتطوعين على المهام ودعوتهم لأيام العمل التطوعي؟'),
  ('SO3-F1', 10, 'coordination_procedure', 'checklist', 'checklist_status', 'Are coordination procedures documented (who calls an action day, who supervises, how attendance is recorded, how it is reported)?', 'هل إجراءات التنسيق موثقة (من يدعو ليوم عمل تطوعي، ومن يشرف، وكيف يُسجَّل الحضور، وكيف يُبلَّغ عنه)؟'),
  ('SO3-F1', 11, 'inclusive_roles', 'checklist', 'checklist_status', 'Are volunteering roles tailored to match the abilities and interests of women, youth, refugees and persons with disabilities, and is this documented?', 'هل الأدوار التطوعية مصممة بما يناسب قدرات واهتمامات النساء والشباب واللاجئين وذوي الإعاقة، وهل ذلك موثق؟'),
  ('SO3-F1', 12, 'safety_arrangements', 'multi select', null, 'Which safety arrangements are in place for volunteer work?', 'أي ترتيبات سلامة متوفرة للعمل التطوعي؟'),
  ('SO3-F1', 13, 'minors_arrangements', 'checklist', 'f1_minors_arrangements', 'Are there arrangements for volunteers under 18 (guardian consent, age-appropriate tasks, supervision ratio)?', 'هل توجد ترتيبات للمتطوعين دون سن الثامنة عشرة (موافقة ولي الأمر، مهام مناسبة للعمر، نسبة إشراف)؟'),
  ('SO3-F1', 14, 'data_consent', 'checklist', 'checklist_status', 'Does the registration form include a data protection and consent statement?', 'هل تتضمن استمارة التسجيل بياناً لحماية البيانات والموافقة؟'),
  ('SO3-F1', 15, 'recognition_scheme', 'checklist', 'f1_recognition_scheme', 'Is a recognition scheme defined (certificates of appreciation or symbolic incentives), and which partner provides it?', 'هل نظام التقدير محدد (شهادات تقدير أو حوافز رمزية)، وأي شريك يقدمه؟'),
  ('SO3-F1', 16, 'recognition_delivered', 'number', null, 'Number of volunteers who have received recognition to date', 'عدد المتطوعين الذين حصلوا على تقدير حتى تاريخه'),
  ('SO3-F1', 17, 'recruitment_channels', 'multi select', null, 'Through which channels are volunteers recruited?', 'من خلال أي قنوات يُستقطب المتطوعون؟'),
  ('SO3-F1', 18, 'focal_point', 'single select', null, 'Has a municipal focal point for volunteers been designated?', 'هل عُيّنت جهة اتصال بلدية للمتطوعين؟'),
  ('SO3-F1', 19, 'action_days_since_launch', 'number', null, 'Number of volunteer action days organised since launch', 'عدد أيام العمل التطوعي المنظمة منذ الإطلاق'),
  ('SO3-F1', 20, 'overall_status', 'calculated', null, 'Overall milestone status', 'الحالة العامة للإنجاز المرحلي'),
  ('SO3-F1', 21, 'evidence_attached', 'attachment', null, 'Evidence attached', 'الأدلة المرفقة'),
  ('SO3-F1', 22, 'gaps', 'long text', null, 'Gaps identified and follow-up actions agreed (what, who, by when)', 'الثغرات المحددة وإجراءات المتابعة المتفق عليها (ما، من، بحلول أي تاريخ)');

-- ── the milestone rules: the sheet's critical items, as data ──
--
-- Plan Part 7: the numbers a rule names are DATA, validated at seed time
-- and on every change against the catalogue above. A rule whose numbers
-- do not all point at checklist rows cannot be stored, so SO1-A1 and
-- SO1-B1 are seeded with critical_items NULL and the source text kept:
-- their status reads not_computable and names the broken references
-- (khld_milestone_status, below). Deciding a rule is an UPDATE on this
-- row by a coordinator, never a migration -- the same shape as Ramtha's
-- thresholds (0123, OQ-47).
create table public.khld_milestone_rule (
  municipality_id  uuid not null references public.municipality(id) default public.my_municipality(),
  milestone_code   text not null check (milestone_code in ('SO1-A1', 'SO1-B1', 'SO3-E1', 'SO3-F1')),
  source_rule_en   text not null,
  source_rule_ar   text not null,
  source_items     int[] not null,
  critical_items   int[],
  decided_by       uuid references auth.users(id),
  decided_on       date,
  note_en          text,
  note_ar          text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  primary key (municipality_id, milestone_code)
);
create index khld_milestone_rule_municipality_idx on public.khld_milestone_rule (municipality_id);
create index khld_milestone_rule_decided_by_idx on public.khld_milestone_rule (decided_by);

create function public.guard_khld_milestone_rule()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_bad text;
begin
  if new.critical_items is null then
    return new;
  end if;
  if array_length(new.critical_items, 1) is null then
    raise exception 'critical_items must name at least one item or be null' using errcode = 'check_violation';
  end if;
  select string_agg(format('%s (%s, %s)', n, coalesce(i.field_code, 'no such item'), coalesce(i.field_type, '-')), ', ')
    into v_bad
    from unnest(new.critical_items) n
    left join public.khld_milestone_item i on i.milestone_code = new.milestone_code and i.item_no = n
   where i.field_type is distinct from 'checklist';
  if v_bad is not null then
    raise exception 'critical_items of % must all be checklist rows; not: %', new.milestone_code, v_bad
      using errcode = 'check_violation', constraint = 'khld_milestone_rule_items_are_checklist';
  end if;
  if tg_op = 'UPDATE' and new.critical_items is distinct from old.critical_items then
    new.decided_by := auth.uid();
    new.decided_on := current_date;
  end if;
  return new;
end $$;
revoke all on function public.guard_khld_milestone_rule() from public, anon, authenticated;
create trigger trg_khld_milestone_rule_guard before insert or update on public.khld_milestone_rule
  for each row execute function public.guard_khld_milestone_rule();

insert into public.khld_milestone_rule (municipality_id, milestone_code, source_rule_en, source_rule_ar, source_items, critical_items, note_en, note_ar) values
  ('00000000-0000-4000-8000-0000000000b2', 'SO1-A1', 'Simple count — one mechanism established. Status = ''Established'' only when items 4, 7, 10 and 11 are all recorded ''In place''; otherwise ''Partly established'' or ''Not established''.', 'عدّ بسيط — آلية واحدة مُنشأة. تُعدّ الحالة "منشأة" فقط عندما تُسجَّل البنود ٤ و٧ و١٠ و١١ جميعها "متوفر"؛ وإلا فتكون "منشأة جزئياً" أو "غير منشأة".', array[4, 7, 10, 11]::int[], null, 'The sheet''s rule names items 4, 7, 10 and 11. Item 4 is period_covered (text) and item 10 is stakeholder_updated (date); neither can be In place, so the rule cannot be evaluated as written and the status reads not computable. The notes column marks items 5, 8, 11 and 12 ''Required for Established'' — the rule''s numbers plus one — and those four are the definition''s four components. Not applied: a guess would put a milestone in a donor report. OQ-56.', 'تسمّي القاعدة في الورقة البنود ٤ و٧ و١٠ و١١. البند ٤ هو period_covered (نص) والبند ١٠ هو stakeholder_updated (تاريخ)؛ ولا يمكن لأي منهما أن يكون «متوفر»، فلا يمكن تقييم القاعدة كما كُتبت وتُقرأ الحالة على أنها غير قابلة للاحتساب. تشير خانة الملاحظات إلى البنود ٥ و٨ و١١ و١٢ بعبارة «مطلوب لاعتبار الآلية منشأة». لم تُطبَّق: التخمين يضع إنجازاً مرحلياً في تقرير المانح. OQ-56.'),
  ('00000000-0000-4000-8000-0000000000b2', 'SO1-B1', 'Simple count — one operational arrangement established and updated as needed. Status = ''Established'' when items 3, 4, 6, 7 and 8 are all ''In place''.', 'عدّ بسيط — ترتيب تشغيلي واحد مُرسى ويُحدَّث حسب الحاجة. تُعدّ الحالة "مُرساة" عندما تكون البنود ٣ و٤ و٦ و٧ و٨ جميعها "متوفر".', array[3, 4, 6, 7, 8]::int[], null, 'The sheet''s rule names items 3, 4, 6, 7 and 8. Item 4 is protocol_ref (text) and cannot be In place, so the rule cannot be evaluated as written. The notes column marks items 3, 5, 7, 8 and 10 ''Required for Established''. Not applied. OQ-56.', 'تسمّي القاعدة في الورقة البنود ٣ و٤ و٦ و٧ و٨. البند ٤ هو protocol_ref (نص) ولا يمكن أن يكون «متوفر»، فلا يمكن تقييم القاعدة كما كُتبت. تشير خانة الملاحظات إلى البنود ٣ و٥ و٧ و٨ و١٠. لم تُطبَّق. OQ-56.'),
  ('00000000-0000-4000-8000-0000000000b2', 'SO3-E1', 'Simple count — established / not established. Status = ''Established'' when items 5, 6, 8 and 10 are all in place.', 'عدّ بسيط — منشأة / غير منشأة. تُعدّ الحالة "منشأة" عندما تكون البنود ٥ و٦ و٨ و١٠ جميعها متوفرة.', array[5, 6, 8, 10]::int[], array[5, 6, 8, 10]::int[], 'Items 5, 6, 8 and 10 are all checklist rows, and the notes column marks exactly these four ''Required for Established''. Applied as written.', 'البنود ٥ و٦ و٨ و١٠ جميعها صفوف قائمة تحقق، وتشير خانة الملاحظات إلى هذه الأربعة تحديداً. طُبِّقت كما كُتبت.'),
  ('00000000-0000-4000-8000-0000000000b2', 'SO3-F1', 'Simple count — one programme launched. Status = ''Established'' when items 3, 5, 7 and 9 are all in place.', 'عدّ بسيط — برنامج واحد مُطلق. تُعدّ الحالة "منشأ" عندما تكون البنود ٣ و٥ و٧ و٩ جميعها متوفرة.', array[3, 5, 7, 9]::int[], array[3, 5, 7, 9]::int[], 'Items 3, 5, 7 and 9 are all checklist rows and the rule is applied as written. The notes column marks 3, 5, 8 and 10 ''Required for Established'' instead (roles_defined and coordination_procedure rather than registration_form and assignment_procedure), which is closer to the definition''s three elements. Recorded for the M&E lead; changing it is an update of this row. OQ-56.', 'البنود ٣ و٥ و٧ و٩ جميعها صفوف قائمة تحقق وطُبِّقت القاعدة كما كُتبت. تشير خانة الملاحظات إلى ٣ و٥ و٨ و١٠ بدلاً منها. مسجَّل لمسؤول المتابعة والتقييم؛ وتغييره تحديث لهذا الصف. OQ-56.');

-- ── the checklist rows of a verification ──
create table public.khld_milestone_checklist_item (
  verification_id  uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  item_no          int  not null,
  field_code       text not null,
  status_id        uuid not null,
  detail           text,
  status_date      date,
  evidence_ref     text,
  created_at       timestamptz not null default now(),
  primary key (verification_id, item_no),
  constraint khld_milestone_checklist_item_verification_id_fkey foreign key (verification_id, municipality_id)
    references public.khld_milestone_verification(id, municipality_id)
);
create index khld_milestone_checklist_item_municipality_idx on public.khld_milestone_checklist_item (municipality_id);

create function public.guard_khld_checklist_item()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_code text;
  v_item public.khld_milestone_item%rowtype;
  v_ok   boolean;
begin
  select milestone_code into v_code from public.khld_milestone_verification where id = new.verification_id;
  select * into v_item from public.khld_milestone_item i where i.milestone_code = v_code and i.item_no = new.item_no;
  if v_item.item_no is null or v_item.field_code <> new.field_code then
    raise exception 'item % (%) is not a row of the % checklist', new.item_no, new.field_code, v_code
      using errcode = 'check_violation';
  end if;
  if v_item.field_type <> 'checklist' then
    raise exception 'item % (%) of % is a % field, not a checklist row', new.item_no, new.field_code, v_code, v_item.field_type
      using errcode = 'check_violation';
  end if;
  execute format('select exists (select 1 from public.%I where id = $1 and deleted_at is null)', 'ref_khld_' || v_item.list_name)
    into v_ok using new.status_id;
  if not v_ok then
    raise exception 'status % is not a live row of ref_khld_%, the list for item % of %', new.status_id, v_item.list_name, new.item_no, v_code
      using errcode = 'foreign_key_violation';
  end if;
  return new;
end $$;
revoke all on function public.guard_khld_checklist_item() from public, anon, authenticated;
create trigger trg_khld_milestone_checklist_item_guard before insert or update on public.khld_milestone_checklist_item
  for each row execute function public.guard_khld_checklist_item();

-- The status of one checklist item, read from its option's code prefix
-- (0141: in_place… / partly… / not_in_place / not_accepted).
create function public.khld_checklist_status(p_status_id uuid, p_list text)
returns text
language plpgsql
stable
set search_path = public, pg_temp
as $$
declare v_code text;
begin
  execute format('select code from public.%I where id = $1', 'ref_khld_' || p_list) into v_code using p_status_id;
  return case when v_code like 'in_place%' then 'in_place'
              when v_code like 'partly%' then 'partly'
              when v_code like 'not_in_place%' then 'not_in_place'
              when v_code = 'not_accepted' then 'not_accepted'
              else null end;
end $$;
grant execute on function public.khld_checklist_status(uuid, text) to authenticated;

-- The milestone's overall status, from its rule and its checklist rows.
-- Plan 7.3: Established when every critical item is In place; Not
-- established when no critical item is In place or Partly in place;
-- Partly established otherwise; not_computable (with the reason) when the
-- rule cannot be evaluated or a critical item has no row yet.
create function public.khld_milestone_status(p_verification_id uuid)
returns jsonb
language plpgsql
stable
set search_path = public, pg_temp
as $$
declare
  v_ver   public.khld_milestone_verification%rowtype;
  v_rule  public.khld_milestone_rule%rowtype;
  v_n     int;
  v_in    int := 0;
  v_part  int := 0;
  v_none  int := 0;
  v_miss  int[] := '{}';
  v_item  int;
  v_st    text;
  v_bad   text;
begin
  select * into v_ver from public.khld_milestone_verification where id = p_verification_id;
  if v_ver.id is null then
    return jsonb_build_object('status', 'not_computable', 'reason', 'not_found');
  end if;
  select * into v_rule from public.khld_milestone_rule r
   where r.municipality_id = v_ver.municipality_id and r.milestone_code = v_ver.milestone_code;
  if v_rule.milestone_code is null then
    return jsonb_build_object('status', 'not_computable', 'reason', 'no_rule');
  end if;
  if v_rule.critical_items is null then
    select string_agg(format('%s = %s (%s)', n, coalesce(i.field_code, '?'), coalesce(i.field_type, '?')), ', ' order by n)
      into v_bad
      from unnest(v_rule.source_items) n
      left join public.khld_milestone_item i on i.milestone_code = v_ver.milestone_code and i.item_no = n
     where i.field_type is distinct from 'checklist';
    return jsonb_build_object('status', 'not_computable', 'reason', 'rule_not_evaluable',
                              'source_items', to_jsonb(v_rule.source_items), 'broken', v_bad);
  end if;
  foreach v_item in array v_rule.critical_items loop
    select public.khld_checklist_status(c.status_id, i.list_name) into v_st
      from public.khld_milestone_checklist_item c
      join public.khld_milestone_item i on i.milestone_code = v_ver.milestone_code and i.item_no = c.item_no
     where c.verification_id = p_verification_id and c.item_no = v_item;
    if v_st is null then
      v_miss := v_miss || v_item;
    elsif v_st = 'in_place' then v_in := v_in + 1;
    elsif v_st = 'partly' then v_part := v_part + 1;
    else v_none := v_none + 1;
    end if;
  end loop;
  if array_length(v_miss, 1) is not null then
    return jsonb_build_object('status', 'not_computable', 'reason', 'items_missing', 'missing', to_jsonb(v_miss),
                              'critical_items', to_jsonb(v_rule.critical_items));
  end if;
  v_n := array_length(v_rule.critical_items, 1);
  return jsonb_build_object(
    'status', case when v_in = v_n then 'established'
                   when v_in = 0 and v_part = 0 then 'not_established'
                   else 'partly_established' end,
    'in_place', v_in, 'partly', v_part, 'not_in_place', v_none, 'critical_items', to_jsonb(v_rule.critical_items));
end $$;
grant execute on function public.khld_milestone_status(uuid) to authenticated;

-- ── SO2-0's facility ratings ──
create table public.khld_user_feedback_rating (
  feedback_id      uuid not null,
  municipality_id  uuid not null default public.my_municipality(),
  item_id          uuid not null references public.ref_khld_so20_facility_item(id),
  rating_id        uuid not null references public.ref_khld_so20_facility_rating(id),
  created_at       timestamptz not null default now(),
  primary key (feedback_id, item_id),
  constraint khld_user_feedback_rating_feedback_id_fkey foreign key (feedback_id, municipality_id)
    references public.khld_user_feedback(id, municipality_id)
);
create index khld_user_feedback_rating_municipality_idx on public.khld_user_feedback_rating (municipality_id);
create index khld_user_feedback_rating_item_idx on public.khld_user_feedback_rating (item_id);
create index khld_user_feedback_rating_rating_idx on public.khld_user_feedback_rating (rating_id);

-- ── a volunteer's participations ──
--
-- One row per volunteer per occasion: a campaign (SO2-C2), an action day
-- (SO3-F3), an activity supported, a market day supported, a committee
-- task or outreach (SO3-0's participation log names all six). The
-- occasions with a record link to it by composite key; the others carry
-- the sheet's reference text. SO3-0 counts a volunteer with two or more
-- VERIFIED participations; SO3-F2 counts a volunteer with at least one.
create table public.khld_volunteer_participation (
  id               uuid primary key default gen_random_uuid(),
  municipality_id  uuid not null references public.municipality(id) default public.my_municipality(),
  volunteer_id     uuid not null,
  kind             text not null check (kind in ('campaign', 'action_day', 'activity', 'market', 'committee', 'outreach')),
  campaign_id      uuid,
  action_day_id    uuid,
  activity_id      uuid,
  market_id        uuid,
  participated_on  date not null,
  hours            numeric(6,2) check (hours is null or hours >= 0),
  verified         boolean not null default false,
  reference_text   text,
  notes            text,
  client_uuid      uuid unique,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid references auth.users(id) default auth.uid(),
  deleted_at       timestamptz,
  constraint khld_volunteer_participation_id_municipality_key unique (id, municipality_id),
  constraint khld_volunteer_participation_volunteer_id_fkey foreign key (volunteer_id, municipality_id) references public.khld_volunteer(id, municipality_id),
  constraint khld_volunteer_participation_campaign_id_fkey foreign key (campaign_id, municipality_id) references public.khld_campaign(id, municipality_id),
  constraint khld_volunteer_participation_action_day_id_fkey foreign key (action_day_id, municipality_id) references public.khld_action_day(id, municipality_id),
  constraint khld_volunteer_participation_activity_id_fkey foreign key (activity_id, municipality_id) references public.khld_activity(id, municipality_id),
  constraint khld_volunteer_participation_market_id_fkey foreign key (market_id, municipality_id) references public.khld_market(id, municipality_id),
  constraint khld_volunteer_participation_kind_link check (
    (kind = 'campaign'   and campaign_id   is not null and action_day_id is null and activity_id is null and market_id is null) or
    (kind = 'action_day' and action_day_id is not null and campaign_id   is null and activity_id is null and market_id is null) or
    (kind = 'activity'   and activity_id   is not null and campaign_id   is null and action_day_id is null and market_id is null) or
    (kind = 'market'     and market_id     is not null and campaign_id   is null and action_day_id is null and activity_id is null) or
    (kind in ('committee', 'outreach') and campaign_id is null and action_day_id is null and activity_id is null and market_id is null))
);
create index khld_volunteer_participation_municipality_idx on public.khld_volunteer_participation (municipality_id);
create index khld_volunteer_participation_volunteer_idx on public.khld_volunteer_participation (volunteer_id);
create index khld_volunteer_participation_campaign_idx on public.khld_volunteer_participation (campaign_id);
create index khld_volunteer_participation_action_day_idx on public.khld_volunteer_participation (action_day_id);
create index khld_volunteer_participation_activity_idx on public.khld_volunteer_participation (activity_id);
create index khld_volunteer_participation_market_idx on public.khld_volunteer_participation (market_id);
create index khld_volunteer_participation_created_by_idx on public.khld_volunteer_participation (created_by);
-- one participation per volunteer per occasion, while live (plan 5.10)
create unique index khld_volunteer_participation_campaign_live on public.khld_volunteer_participation (volunteer_id, campaign_id) where deleted_at is null and campaign_id is not null;
create unique index khld_volunteer_participation_action_day_live on public.khld_volunteer_participation (volunteer_id, action_day_id) where deleted_at is null and action_day_id is not null;
create unique index khld_volunteer_participation_activity_live on public.khld_volunteer_participation (volunteer_id, activity_id) where deleted_at is null and activity_id is not null;
create unique index khld_volunteer_participation_market_live on public.khld_volunteer_participation (volunteer_id, market_id) where deleted_at is null and market_id is not null;

-- ── a correction to one applied list row (catalogue.LIST_FIXES) ──
--
-- 0142 seeded ref_khld_d2_duplicate_check.yes with allows_free_text = true,
-- read off the blank in "Yes — number of repeat participants identified:
-- ____". The blank is a NUMBER -- the one the distinct-individuals figure
-- subtracts -- so it has its own column (khld_attendance.repeat_participants)
-- and the option takes no free text. gen_0141 still reproduces 0142 as
-- applied; this is the row's later state, and the form reads it from here.
-- the blank is the number of repeat participants; it has its own typed column (repeat_participants)
update public.ref_khld_d2_duplicate_check set allows_free_text = false where code = 'yes';

-- ── SO2-D2: reconciliation and distinct individuals, computed, never stored ──
--
-- "Do the entrance tally, the register and the section B totals agree?" is
-- typed text on the sheet with a Yes/No; here it is worked out from the
-- rows: the by-sex cells must sum to the total, and the by-age-and-sex
-- cells, when any are given, must too. "Distinct individuals ... where the
-- register allows" is total minus the repeat participants identified, and
-- only when duplicate_check says the register WAS checked; otherwise it is
-- not available, never estimated (plan Part 6).
create function public.khld_attendance_figures(p_attendance_id uuid)
returns jsonb
language sql
stable
set search_path = public, pg_temp
as $$
  with a as (select * from public.khld_attendance where id = p_attendance_id),
       s as (select coalesce(sum(c.count), 0) as n, count(*) as cells
               from public.khld_attendance_count c where c.attendance_id = p_attendance_id and c.field_code = 'by_sex'),
       g as (select coalesce(sum(c.count), 0) as n, count(*) as cells
               from public.khld_attendance_count c where c.attendance_id = p_attendance_id and c.field_code = 'by_age_sex'),
       d as (select dc.code from a join public.ref_khld_d2_duplicate_check dc on dc.id = a.duplicate_check_id)
  select jsonb_build_object(
    'total', a.total_participants,
    'by_sex_sum', s.n,
    'by_age_sex_sum', case when g.cells > 0 then g.n end,
    'agrees', (s.cells = 0 or s.n = a.total_participants) and (g.cells = 0 or g.n = a.total_participants),
    'distinct_individuals', case when (select code from d) = 'yes' and a.repeat_participants is not null
                                 then greatest(a.total_participants - a.repeat_participants, 0) end,
    'distinct_reason', case when (select code from d) = 'yes' and a.repeat_participants is not null then null
                            when (select code from d) = 'yes' then 'repeat_count_missing'
                            else coalesce((select code from d), 'not_checked') end)
    from a, s, g;
$$;
grant execute on function public.khld_attendance_figures(uuid) to authenticated;

-- ── the milestone's option and count rows name their milestone ──
--
-- Four forms share khld_milestone_verification, and khld_question_list is
-- keyed on (table, question_code): evidence_attached alone would name four
-- lists. So on this table the code carries the form id (a1_, b1_, e1_,
-- f1_), which is what the question map below stores, and this guard
-- requires the prefix to be the PARENT's milestone -- an a1_ option on an
-- SO3-F1 verification is a row of another checklist, not an answer.
create function public.guard_khld_milestone_child()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_code   text;
  v_prefix text;
  v_qcode  text := coalesce(to_jsonb(new)->>'question_code', to_jsonb(new)->>'field_code');
begin
  select milestone_code into v_code from public.khld_milestone_verification where id = new.verification_id;
  v_prefix := lower(split_part(v_code, '-', 2)) || '_';
  if v_code is null or left(v_qcode, length(v_prefix)) <> v_prefix then
    raise exception '% is not a question of % (the code must start with %)', v_qcode, coalesce(v_code, 'a missing verification'), v_prefix
      using errcode = 'check_violation';
  end if;
  return new;
end $$;
revoke all on function public.guard_khld_milestone_child() from public, anon, authenticated;
create trigger trg_khld_milestone_verification_option_milestone before insert or update on public.khld_milestone_verification_option
  for each row execute function public.guard_khld_milestone_child();
create trigger trg_khld_milestone_verification_count_milestone before insert or update on public.khld_milestone_verification_count
  for each row execute function public.guard_khld_milestone_child();

-- ── the question -> list map the two guards read (0144) ──
insert into public.khld_question_list (table_name, question_code, list_name, kind) values
  ('khld_works_item_option', 'identified_how', 'c1_identified_how', 'option'),
  ('khld_works_item_option', 'resource_source', 'c1_resource_source', 'option'),
  ('khld_works_item_option', 'evidence_attached', 'c1_evidence_attached', 'option'),
  ('khld_coordination_meeting_option', 'pillars_discussed', 'a2_pillars_discussed', 'option'),
  ('khld_coordination_meeting_count', 'orgs_by_type', 'a2_orgs_by_type', 'count'),
  ('khld_coordination_meeting_count', 'attendees_breakdown', 'a2_attendees_breakdown', 'count'),
  ('khld_contribution_option', 'supports_objective', 'a3_supports_objective', 'option'),
  ('khld_contribution_option', 'evidence_attached', 'a3_evidence_attached', 'option'),
  ('khld_campaign_option', 'focus', 'c2_focus', 'option'),
  ('khld_campaign_option', 'evidence_attached', 'c2_evidence_attached', 'option'),
  ('khld_campaign_count', 'volunteers_breakdown', 'c2_volunteers_breakdown', 'count'),
  ('khld_activity_option', 'content_provider', 'd1_content_provider', 'option'),
  ('khld_activity_option', 'target_group', 'd1_target_group', 'option'),
  ('khld_activity_option', 'announcement', 'd1_announcement', 'option'),
  ('khld_activity_option', 'inclusion_measures', 'd1_inclusion_measures', 'option'),
  ('khld_activity_option', 'issues', 'd1_issues', 'option'),
  ('khld_activity_option', 'evidence_attached', 'd1_evidence_attached', 'option'),
  ('khld_market_option', 'organisers', 'h1_organisers', 'option'),
  ('khld_market_option', 'announcement', 'h1_announcement', 'option'),
  ('khld_market_option', 'services_provided', 'h1_services_provided', 'option'),
  ('khld_market_option', 'parallel_activities', 'h1_parallel_activities', 'option'),
  ('khld_market_option', 'issues', 'h1_issues', 'option'),
  ('khld_market_option', 'evidence_attached', 'h1_evidence_attached', 'option'),
  ('khld_market_count', 'priority_share', 'h1_priority_share', 'count'),
  ('khld_action_day_option', 'theme', 'f3_theme', 'option'),
  ('khld_action_day_option', 'roles_used', 'f3_roles_used', 'option'),
  ('khld_action_day_option', 'safety', 'f3_safety', 'option'),
  ('khld_action_day_option', 'evidence_attached', 'f3_evidence_attached', 'option'),
  ('khld_action_day_option', 'recognition', 'f3_recognition', 'option'),
  ('khld_action_day_count', 'volunteers_breakdown', 'f3_volunteers_breakdown', 'count'),
  ('khld_volunteer_option', 'support_needs', 'f2_support_needs', 'option'),
  ('khld_volunteer_option', 'interests', 'f2_interests', 'option'),
  ('khld_volunteer_option', 'skills', 'f2_skills', 'option'),
  ('khld_volunteer_option', 'availability_days', 'f2_availability_days', 'option'),
  ('khld_volunteer_option', 'availability_times', 'f2_availability_times', 'option'),
  ('khld_attendance_count', 'by_sex', 'd2_by_sex', 'count'),
  ('khld_attendance_count', 'by_age_sex', 'd2_by_age_sex', 'count'),
  ('khld_attendance_count', 'by_nationality', 'd2_by_nationality', 'count'),
  ('khld_guidance_completion_option', 'product_type', 'product_type', 'option'),
  ('khld_guidance_completion_option', 'provider', 'g1_provider', 'option'),
  ('khld_guidance_completion_option', 'further_needs', 'g1_further_needs', 'option'),
  ('khld_guidance_completion_option', 'evidence_attached', 'g1_evidence_attached', 'option'),
  ('khld_enterprise_support_option', 'product_type', 'product_type', 'option'),
  ('khld_enterprise_support_option', 'priority_group', 'g2_priority_group', 'option'),
  ('khld_enterprise_support_option', 'providers', 'g2_providers', 'option'),
  ('khld_enterprise_support_option', 'licensing_progress', 'g2_licensing_progress', 'option'),
  ('khld_enterprise_support_option', 'evidence_attached', 'g2_evidence_attached', 'option'),
  ('khld_vendor_registration_option', 'priority_flags', 'h2_priority_flags', 'option'),
  ('khld_vendor_registration_option', 'product_categories', 'product_type', 'option'),
  ('khld_vendor_registration_option', 'equipment_provided', 'h2_equipment_provided', 'option'),
  ('khld_interaction_survey_option', 'activities_taken', 'imp0_activities_taken', 'option'),
  ('khld_interaction_survey_option', 'accompanied_by', 'imp0_accompanied_by', 'option'),
  ('khld_interaction_survey_option', 'barriers', 'imp0_barriers', 'option'),
  ('khld_partner_survey_option', 'areas_involved', 'so10_areas_involved', 'option'),
  ('khld_partner_survey_option', 'obstacles', 'so10_obstacles', 'option'),
  ('khld_partner_survey_option', 'evidence_ref', 'so10_evidence_ref', 'option'),
  ('khld_user_feedback_option', 'how_heard', 'so20_how_heard', 'option'),
  ('khld_volunteer_tracking_option', 'activity_types', 'so30_activity_types', 'option'),
  ('khld_volunteer_tracking_option', 'what_would_help', 'so30_what_would_help', 'option'),
  ('khld_volunteer_tracking_option', 'verified_against', 'so30_verified_against', 'option'),
  ('khld_producer_survey_option', 'product_type', 'product_type', 'option'),
  ('khld_producer_survey_option', 'sold_before_market', 'so40_sold_before_market', 'option'),
  ('khld_producer_survey_option', 'new_channels', 'so40_new_channels', 'option'),
  ('khld_producer_survey_option', 'market_constraints', 'so40_market_constraints', 'option'),
  ('khld_producer_survey_option', 'improvements_wanted', 'so40_improvements_wanted', 'option'),
  ('khld_producer_survey_option', 'additional_support', 'so40_additional_support', 'option'),
  ('khld_milestone_verification_option', 'a1_evidence_attached', 'a1_evidence_attached', 'option'),
  ('khld_milestone_verification_option', 'b1_communicated', 'b1_communicated', 'option'),
  ('khld_milestone_verification_option', 'b1_evidence_attached', 'b1_evidence_attached', 'option'),
  ('khld_milestone_verification_option', 'e1_tasks_covered', 'e1_tasks_covered', 'option'),
  ('khld_milestone_verification_option', 'e1_inclusive_representation', 'e1_inclusive_representation', 'option'),
  ('khld_milestone_verification_option', 'e1_outputs_delivered', 'e1_outputs_delivered', 'option'),
  ('khld_milestone_verification_option', 'e1_evidence_attached', 'e1_evidence_attached', 'option'),
  ('khld_milestone_verification_option', 'f1_safety_arrangements', 'f1_safety_arrangements', 'option'),
  ('khld_milestone_verification_option', 'f1_recruitment_channels', 'f1_recruitment_channels', 'option'),
  ('khld_milestone_verification_option', 'f1_evidence_attached', 'f1_evidence_attached', 'option'),
  ('khld_milestone_verification_count', 'a1_stakeholder_count', 'a1_stakeholder_count', 'count'),
  ('khld_milestone_verification_count', 'a1_partnerships_concluded', 'a1_partnerships_concluded', 'count'),
  ('khld_milestone_verification_count', 'e1_members_by_type', 'e1_members_by_type', 'count'),
  ('khld_milestone_verification_count', 'e1_members_by_sex', 'e1_members_by_sex', 'count');

-- ── the four standard triggers, RLS, and the DELETE policy on the children ──
do $secure$
declare
  r record;
  v_writer text;
begin
  for r in
    select * from (values
      ('khld_partner', 'can_write', false),
      ('khld_enterprise', 'can_write', false),
      ('khld_vendor', 'can_write', false),
      ('khld_works_item', 'can_write', false),
      ('khld_coordination_meeting', 'can_write', false),
      ('khld_contribution', 'can_write', false),
      ('khld_campaign', 'can_write', false),
      ('khld_activity', 'can_write', false),
      ('khld_market', 'can_write', false),
      ('khld_action_day', 'can_write', false),
      ('khld_volunteer', 'can_write', false),
      ('khld_attendance', 'can_write', false),
      ('khld_guidance_completion', 'can_write', false),
      ('khld_enterprise_support', 'can_write', false),
      ('khld_vendor_registration', 'can_write', false),
      ('khld_interaction_survey', 'is_staff', false),
      ('khld_partner_survey', 'is_staff', false),
      ('khld_user_feedback', 'is_staff', false),
      ('khld_volunteer_tracking', 'is_staff', false),
      ('khld_producer_survey', 'is_staff', false),
      ('khld_milestone_verification', 'can_write', false),
      ('khld_volunteer_participation', 'can_write', false),
      ('khld_works_item_option', 'can_write', true),
      ('khld_coordination_meeting_option', 'can_write', true),
      ('khld_coordination_meeting_count', 'can_write', true),
      ('khld_contribution_option', 'can_write', true),
      ('khld_campaign_option', 'can_write', true),
      ('khld_campaign_count', 'can_write', true),
      ('khld_activity_option', 'can_write', true),
      ('khld_market_option', 'can_write', true),
      ('khld_market_count', 'can_write', true),
      ('khld_action_day_option', 'can_write', true),
      ('khld_action_day_count', 'can_write', true),
      ('khld_volunteer_option', 'can_write', true),
      ('khld_attendance_count', 'can_write', true),
      ('khld_guidance_completion_option', 'can_write', true),
      ('khld_enterprise_support_option', 'can_write', true),
      ('khld_vendor_registration_option', 'can_write', true),
      ('khld_interaction_survey_option', 'is_staff', true),
      ('khld_partner_survey_option', 'is_staff', true),
      ('khld_user_feedback_option', 'is_staff', true),
      ('khld_volunteer_tracking_option', 'is_staff', true),
      ('khld_producer_survey_option', 'is_staff', true),
      ('khld_milestone_verification_option', 'can_write', true),
      ('khld_milestone_verification_count', 'can_write', true),
      ('khld_milestone_checklist_item', 'can_write', true),
      ('khld_user_feedback_rating', 'is_staff', true)
    ) as t(tbl, writer, is_child)
  loop
    v_writer := format('public.%I()', r.writer);

    if r.is_child then
      -- children: replaced by delete-then-insert; audit only, hard delete allowed
      execute format('drop trigger if exists trg_%1$s_audit on public.%1$I', r.tbl);
      execute format('create trigger trg_%1$s_audit after insert or update or delete on public.%1$I '
                     'for each row execute function public.audit_row()', r.tbl);
    else
      perform public.attach_standard_triggers(r.tbl);
    end if;

    execute format('alter table public.%I enable row level security', r.tbl);
    execute format('create policy %1$s_read on public.%1$I for select to authenticated '
                   'using (public.can_see_municipality(municipality_id))', r.tbl);
    execute format('create policy %1$s_insert on public.%1$I for insert to authenticated '
                   'with check (%2$s and public.can_see_municipality(municipality_id))', r.tbl, v_writer);
    execute format('create policy %1$s_update on public.%1$I for update to authenticated '
                   'using (%2$s and public.can_see_municipality(municipality_id)) '
                   'with check (%2$s and public.can_see_municipality(municipality_id))', r.tbl, v_writer);
    if r.is_child then
      execute format('create policy %1$s_delete on public.%1$I for delete to authenticated '
                     'using (%2$s and public.can_see_municipality(municipality_id))', r.tbl, v_writer);
    end if;
  end loop;

  -- the rule table: read by everyone who sees the municipality, decided by a coordinator
  perform public.attach_standard_triggers('khld_milestone_rule');
  execute 'alter table public.khld_milestone_rule enable row level security';
  execute 'create policy khld_milestone_rule_read on public.khld_milestone_rule for select to authenticated using (public.can_see_municipality(municipality_id))';
  execute 'create policy khld_milestone_rule_update on public.khld_milestone_rule for update to authenticated using (public.is_coordinator() and public.can_see_municipality(municipality_id)) with check (public.is_coordinator() and public.can_see_municipality(municipality_id))';
end $secure$;

-- ── verification ──────────────────────────────────────────────────────────
do $verify$
declare
  v_bad   int;
  v_khld  uuid := '00000000-0000-4000-8000-0000000000b2';
  v_shm   uuid := '00000000-0000-4000-8000-00000000005a';
  v_ok    boolean;
  v_id    uuid;
  v_p     uuid;
  v_vol   uuid;
  v_act   uuid;
  v_st    jsonb;
begin
  -- 1. shape: 48 tables carrying municipality_id, RLS on and a read policy on each,
  --    a DELETE policy on exactly the 25 children, every FK indexed
  select count(*) into v_bad
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'r' and c.relname like 'khld\_%'
     and c.relname not in ('khld_reference_counter', 'khld_question_list', 'khld_milestone_item');
  if v_bad <> 48 then
    raise exception '0145: expected 48 khld tables, found %', v_bad;
  end if;
  select count(*) into v_bad
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'r' and c.relname like 'khld\_%'
     and c.relname not in ('khld_reference_counter', 'khld_question_list', 'khld_milestone_item')
     and (not c.relrowsecurity
          or not exists (select 1 from pg_policy p where p.polrelid = c.oid and p.polcmd = 'r'));
  if v_bad <> 0 then
    raise exception '0145: % tables lack RLS or a read policy', v_bad;
  end if;
  select count(*) into v_bad from pg_policy p join pg_class c on c.oid = p.polrelid
   where p.polcmd = 'd' and c.relname like 'khld\_%';
  if v_bad <> 25 then
    raise exception '0145: expected 25 DELETE policies (the children), found %', v_bad;
  end if;
  select count(*) into v_bad
    from pg_constraint k join pg_class c on c.oid = k.conrelid
   where k.contype = 'f' and c.relname like 'khld\_%'
     and not exists (select 1 from pg_index i
                      where i.indrelid = k.conrelid and i.indkey[0] = k.conkey[1]);
  if v_bad <> 0 then
    raise exception '0145: % foreign keys have no index on their first column', v_bad;
  end if;
  -- every soft-deletable khld table has the soft-delete guard and the no-hard-delete guard
  select count(*) into v_bad
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'r' and c.relname like 'khld\_%'
     and exists (select 1 from pg_attribute a where a.attrelid = c.oid and a.attname = 'deleted_at' and not a.attisdropped)
     and (not exists (select 1 from pg_trigger t where t.tgrelid = c.oid and t.tgname = 'trg_' || c.relname || '_soft_delete')
          or not exists (select 1 from pg_trigger t where t.tgrelid = c.oid and t.tgname = 'trg_' || c.relname || '_no_hard_delete'));
  if v_bad <> 0 then
    raise exception '0145: % soft-deletable tables lack a guard', v_bad;
  end if;

  -- 2. the rules: the two broken ones refuse their source numbers; the two
  --    valid ones hold them
  begin
    update public.khld_milestone_rule set critical_items = source_items where milestone_code = 'SO1-A1';
    raise exception '0145: SO1-A1 accepted items 4, 7, 10, 11';
  exception when check_violation then null; end;
  begin
    update public.khld_milestone_rule set critical_items = source_items where milestone_code = 'SO1-B1';
    raise exception '0145: SO1-B1 accepted items 3, 4, 6, 7, 8';
  exception when check_violation then null; end;
  if (select critical_items from public.khld_milestone_rule where milestone_code = 'SO3-E1') <> array[5,6,8,10]
     or (select critical_items from public.khld_milestone_rule where milestone_code = 'SO3-F1') <> array[3,5,7,9] then
    raise exception '0145: the valid rules were not seeded';
  end if;

  -- 3. behaviour, as the owner, in a discarded savepoint: a milestone whose
  --    rule is broken reads not_computable naming the fields; SO3-F1
  --    computes; a checklist row with the wrong list is refused; a minor
  --    without a guardian is refused and with one is accepted; the
  --    completion derivation has three outcomes; a reference is issued
  begin
    insert into public.khld_milestone_verification (municipality_id, milestone_code, verif_date, verif_by, gaps)
    values (v_khld, 'SO1-A1', current_date, 'probe', 'probe') returning id into v_id;
    v_st := public.khld_milestone_status(v_id);
    if v_st->>'status' <> 'not_computable' or v_st->>'reason' <> 'rule_not_evaluable' or v_st->>'broken' !~ 'period_covered' then
      raise exception '0145: SO1-A1 status came back as %', v_st;
    end if;

    insert into public.khld_milestone_verification (municipality_id, milestone_code, verif_date, verif_by, gaps)
    values (v_khld, 'SO3-F1', current_date, 'probe', 'probe') returning id into v_id;
    if (public.khld_milestone_status(v_id))->>'reason' <> 'items_missing' then
      raise exception '0145: SO3-F1 with no rows should be items_missing';
    end if;
    insert into public.khld_milestone_checklist_item (verification_id, municipality_id, item_no, field_code, status_id)
    select v_id, v_khld, 3, 'procedures_approved', id from public.ref_khld_f1_procedures_approved where code = 'in_place_decision_no_and_date';
    insert into public.khld_milestone_checklist_item (verification_id, municipality_id, item_no, field_code, status_id)
    select v_id, v_khld, 5, 'database_established', id from public.ref_khld_f1_database_established where code = 'in_place';
    insert into public.khld_milestone_checklist_item (verification_id, municipality_id, item_no, field_code, status_id)
    select v_id, v_khld, 7, 'registration_form', id from public.ref_khld_checklist_status where code = 'in_place';
    insert into public.khld_milestone_checklist_item (verification_id, municipality_id, item_no, field_code, status_id)
    select v_id, v_khld, 9, 'assignment_procedure', id from public.ref_khld_checklist_status where code = 'partly';
    if (public.khld_milestone_status(v_id))->>'status' <> 'partly_established' then
      raise exception '0145: SO3-F1 with three In place and one Partly should be partly_established, got %', public.khld_milestone_status(v_id);
    end if;
    update public.khld_milestone_checklist_item set status_id = (select id from public.ref_khld_checklist_status where code = 'in_place')
     where verification_id = v_id and item_no = 9;
    if (public.khld_milestone_status(v_id))->>'status' <> 'established' then
      raise exception '0145: SO3-F1 with four In place should be established';
    end if;
    begin
      insert into public.khld_milestone_checklist_item (verification_id, municipality_id, item_no, field_code, status_id)
      select v_id, v_khld, 4, 'launch_date', id from public.ref_khld_checklist_status where code = 'in_place';
      raise exception '0145: a date field was accepted as a checklist row';
    exception when check_violation then null; end;
    begin
      insert into public.khld_milestone_checklist_item (verification_id, municipality_id, item_no, field_code, status_id)
      select v_id, v_khld, 8, 'roles_defined', id from public.ref_khld_a1_periodic_updates where code = 'in_place_regularly';
      raise exception '0145: a status from another item''s list was accepted';
    exception when foreign_key_violation then null; end;
    -- an option of another milestone's checklist is refused on this one; its own is taken
    begin
      insert into public.khld_milestone_verification_option (verification_id, municipality_id, question_code, option_id)
      select v_id, v_khld, 'a1_evidence_attached', id from public.ref_khld_a1_evidence_attached where not allows_free_text limit 1;
      raise exception '0145: an SO1-A1 option was accepted on an SO3-F1 verification';
    exception when check_violation then null; end;
    begin
      insert into public.khld_milestone_verification_count (verification_id, municipality_id, field_code, cell_id, count)
      select v_id, v_khld, 'a1_stakeholder_count', id, 1 from public.ref_khld_a1_stakeholder_count limit 1;
      raise exception '0145: an SO1-A1 count was accepted on an SO3-F1 verification';
    exception when check_violation then null; end;
    insert into public.khld_milestone_verification_option (verification_id, municipality_id, question_code, option_id)
    select v_id, v_khld, 'f1_evidence_attached', id from public.ref_khld_f1_evidence_attached where not allows_free_text limit 1;
    if not exists (select 1 from public.khld_milestone_verification_option where verification_id = v_id) then
      raise exception '0145: the SO3-F1 option was not written';
    end if;

    -- a minor: refused without the guardian block, accepted with it, the
    -- reference issued, the consents stamped, the data consent mandatory
    insert into public.person (national_id, full_name, date_of_birth) values ('399000997', '0145 probe child', current_date - interval '12 years')
    returning id into v_p;
    begin
      insert into public.khld_volunteer (municipality_id, person_id, reg_date, reg_channel_id, nationality_id, disability_id, neighbourhood_id,
                                         affiliation_id, transport_id, consent_data, consent_photo, safety_commitment)
      select v_khld, v_p, current_date, (select id from public.ref_khld_f2_reg_channel where code = 'at_the_municipality'),
             (select id from public.ref_khld_nationality where code = 'jordanian'), (select id from public.ref_khld_disability where code = 'no_difficulty'),
             (select id from public.ref_khld_neighbourhood where code = 'al_mabrouka'), (select id from public.ref_khld_f2_affiliation where code = 'none_individual_volunteer'),
             (select id from public.ref_khld_f2_transport where code = 'yes'), true, false, true;
      raise exception '0145: a twelve-year-old was registered without a guardian';
    exception when check_violation then null; end;
    insert into public.khld_volunteer (municipality_id, person_id, reg_date, reg_channel_id, nationality_id, disability_id, neighbourhood_id,
                                       affiliation_id, transport_id, consent_data, consent_photo, safety_commitment,
                                       guardian_name, guardian_relationship, guardian_phone, guardian_consent_given, guardian_consent_date)
    select v_khld, v_p, current_date, (select id from public.ref_khld_f2_reg_channel where code = 'at_the_municipality'),
           (select id from public.ref_khld_nationality where code = 'jordanian'), (select id from public.ref_khld_disability where code = 'no_difficulty'),
           (select id from public.ref_khld_neighbourhood where code = 'al_mabrouka'), (select id from public.ref_khld_f2_affiliation where code = 'none_individual_volunteer'),
           (select id from public.ref_khld_f2_transport where code = 'yes'), true, false, true,
           'A guardian', 'mother', '0790000000', true, current_date
    returning id into v_vol;
    if (select reference from public.khld_volunteer where id = v_vol) !~ '^KHLD-VOL-\d{4}$' then
      raise exception '0145: the volunteer reference is %', (select reference from public.khld_volunteer where id = v_vol);
    end if;
    if (select consent_photo_recorded_on from public.khld_volunteer where id = v_vol) is null
       or (select consent_data_recorded_on from public.khld_volunteer where id = v_vol) is null then
      raise exception '0145: the consents were not stamped';
    end if;
    begin
      update public.khld_volunteer set consent_data = false where id = v_vol;
      raise exception '0145: registration without data consent was accepted';
    exception when check_violation then null; end;
    -- a second registration of the same person is refused, deleted or not
    -- (plan 5.10). The soft delete is a coordinator's act (guard_soft_delete),
    -- so it is done as the Khalidiyah admin, through RLS, and read back:
    -- an update RLS filters affects no row and raises nothing
    perform set_config('request.jwt.claims', json_build_object('sub', (select id from public.app_user where email = 'admin@khalidiyah.test'), 'role', 'authenticated')::text, true);
    set local role authenticated;
    update public.khld_volunteer set deleted_at = now() where id = v_vol;
    reset role;
    perform set_config('request.jwt.claims', '', true);
    if (select deleted_at from public.khld_volunteer where id = v_vol) is null then
      raise exception '0145: the Khalidiyah admin could not soft-delete a volunteer';
    end if;
    begin
      insert into public.khld_volunteer (municipality_id, person_id, reg_date, reg_channel_id, nationality_id, disability_id, neighbourhood_id,
                                         affiliation_id, transport_id, consent_data, consent_photo, safety_commitment,
                                         guardian_name, guardian_relationship, guardian_phone, guardian_consent_given, guardian_consent_date)
      select v_khld, v_p, current_date, reg_channel_id, nationality_id, disability_id, neighbourhood_id, affiliation_id, transport_id,
             true, false, true, guardian_name, guardian_relationship, guardian_phone, true, current_date
        from public.khld_volunteer where id = v_vol;
      raise exception '0145: a deleted volunteer was recreated instead of restored';
    exception when unique_violation then null; end;

    -- the completion derivation: three outcomes, and a client value overwritten
    insert into public.khld_enterprise (municipality_id, owner_name) values (v_khld, '0145 probe enterprise') returning id into v_id;
    if (select reference from public.khld_enterprise where id = v_id) !~ '^KHLD-ENT-\d{3}$' then
      raise exception '0145: the enterprise reference is wrong';
    end if;
    insert into public.khld_guidance_completion (municipality_id, enterprise_id, cycle_year, age_group_id, nationality_id, enterprise_status_id,
                                                 peer_network_id, non_completion_reason_id, referral_made_id, certificate_id,
                                                 s1_status_id, s2_status_id, s3_status_id, s4_status_id, s5_status_id)
    select v_khld, v_id, (select id from public.ref_khld_g1_cycle_year where code = 'n_2027'),
           (select id from public.ref_khld_age_group where code = '35_49'),
           (select id from public.ref_khld_nationality where code = 'jordanian'),
           (select id from public.ref_khld_g1_enterprise_status where code = 'operating_and_licensed'),
           (select id from public.ref_khld_g1_peer_network where code = 'no'),
           (select id from public.ref_khld_g1_non_completion_reason where code = 'not_applicable_completed'),
           (select id from public.ref_khld_g1_referral_made where code = 'no'),
           (select id from public.ref_khld_g1_certificate where code = 'due_but_not_yet_issued'),
           (select id from public.ref_khld_session_attendance where code = 'attended'),
           (select id from public.ref_khld_session_attendance where code = 'attended'),
           (select id from public.ref_khld_g1_s3_hygiene where code = 'not_applicable'),
           (select id from public.ref_khld_session_attendance where code = 'attended'),
           null
    returning id into v_act;
    if (select completion from public.khld_guidance_completion where id = v_act) <> 'not_yet_decided'
       or (select sessions_attended_count from public.khld_guidance_completion where id = v_act) <> 3 then
      raise exception '0145: completion with one session open should be not_yet_decided / 3';
    end if;
    update public.khld_guidance_completion set s5_status_id = (select id from public.ref_khld_session_attendance where code = 'attended') where id = v_act;
    if (select completion from public.khld_guidance_completion where id = v_act) <> 'completed' then
      raise exception '0145: completion with every applicable session attended should be completed';
    end if;
    update public.khld_guidance_completion set s2_status_id = (select id from public.ref_khld_session_attendance where code = 'did_not_attend') where id = v_act;
    if (select completion from public.khld_guidance_completion where id = v_act) <> 'not_completed' then
      raise exception '0145: completion with a missed session should be not_completed';
    end if;
    update public.khld_guidance_completion set completion = 'completed' where id = v_act;
    if (select completion from public.khld_guidance_completion where id = v_act) <> 'not_completed' then
      raise exception '0145: a client value for completion survived the trigger';
    end if;

    -- an activity, its attendance sheet, the count cells and the derived figures
    insert into public.khld_activity (municipality_id, event_title, event_date, location_id, activity_type_id, calendar_status_id, frequency_type_id,
                                      organiser_id, partner_count, content_summary, participants_planned, participants_actual,
                                      cash_cost_jod, feedback_collected_id, lessons)
    select v_khld, '0145 probe activity', current_date, (select id from public.ref_khld_d1_location where code = 'sports_field'),
           (select id from public.ref_khld_d1_activity_type where code = 'sports_activity_or_tournament'),
           (select id from public.ref_khld_d1_calendar_status where code = 'no_ad_hoc_or_one_off'),
           (select id from public.ref_khld_d1_frequency_type where code = 'one_off'),
           (select id from public.ref_khld_d1_organiser where code = 'municipality_alone'), 0, 'probe', 10, 12,
           0, (select id from public.ref_khld_d1_feedback_collected where code = 'no'), 'probe'
    returning id into v_act;
    if (select reference from public.khld_activity where id = v_act) !~ '^KHLD-EV-\d{4}-\d{2}$' then
      raise exception '0145: the activity reference is wrong';
    end if;
    insert into public.khld_attendance (municipality_id, activity_id, count_method_id, counters, total_participants, repeat_participants, staff_volunteers,
                                        register_attached_id, consent_informed_id, photo_consent_id, duplicate_check_id)
    select v_khld, v_act, (select id from public.ref_khld_d2_count_method where code = 'tally_by_activity_station'), 'probe', 12, 2, 0,
           (select id from public.ref_khld_d2_register_attached where code = 'partly'),
           (select id from public.ref_khld_d2_consent_informed where code = 'no'),
           (select id from public.ref_khld_d2_photo_consent where code = 'no_photographs_taken'),
           (select id from public.ref_khld_d2_duplicate_check where code = 'yes')
    returning id into v_id;
    insert into public.khld_attendance_count (attendance_id, municipality_id, field_code, cell_id, count)
    select v_id, v_khld, 'by_sex', c.id, case c.code when 'female' then 7 when 'male' then 5 else 0 end
      from public.ref_khld_d2_by_sex c;
    v_st := public.khld_attendance_figures(v_id);
    if (v_st->>'agrees')::boolean is not true or (v_st->>'distinct_individuals')::int <> 10 then
      raise exception '0145: attendance figures came back as %', v_st;
    end if;
    update public.khld_attendance_count set count = 6 where attendance_id = v_id and field_code = 'by_sex'
       and cell_id = (select id from public.ref_khld_d2_by_sex where code = 'male');
    if ((public.khld_attendance_figures(v_id))->>'agrees')::boolean is not false then
      raise exception '0145: a by-sex sum of 13 against a total of 12 should not agree';
    end if;
    update public.khld_attendance set duplicate_check_id = (select id from public.ref_khld_d2_duplicate_check where code = 'not_yet') where id = v_id;
    if (public.khld_attendance_figures(v_id))->'distinct_individuals' is distinct from 'null'::jsonb then
      raise exception '0145: distinct individuals should be unavailable when the register was not checked';
    end if;
    -- a cell from the wrong list, and a field that is not a count field, are refused
    begin
      insert into public.khld_attendance_count (attendance_id, municipality_id, field_code, cell_id, count)
      select v_id, v_khld, 'by_sex', id, 1 from public.ref_khld_d2_by_nationality where code = 'other';
      raise exception '0145: a cell from another list was accepted';
    exception when foreign_key_violation then null; end;
    begin
      insert into public.khld_attendance_count (attendance_id, municipality_id, field_code, cell_id, count)
      select v_id, v_khld, 'total_participants', id, 1 from public.ref_khld_d2_by_sex where code = 'female';
      raise exception '0145: a non-count field was accepted as a count';
    exception when check_violation then null; end;
    -- a second live attendance sheet for the same activity is refused; a deleted one is not in the way
    begin
      insert into public.khld_attendance (municipality_id, activity_id, count_method_id, counters, total_participants, staff_volunteers,
                                          register_attached_id, consent_informed_id, photo_consent_id, duplicate_check_id)
      select v_khld, v_act, count_method_id, counters, 1, 0, register_attached_id, consent_informed_id, photo_consent_id, duplicate_check_id
        from public.khld_attendance where id = v_id;
      raise exception '0145: two live attendance sheets on one activity were accepted';
    exception when unique_violation then null; end;

    -- a child in another municipality than its parent is refused by the
    -- composite key. Probed on an option row, not a second attendance sheet:
    -- the sheet's per-activity unique index answers before the key does
    begin
      insert into public.khld_activity_option (activity_id, municipality_id, question_code, option_id)
      select v_act, v_shm, 'issues', id from public.ref_khld_d1_issues where not allows_free_text limit 1;
      raise exception '0145: a child in another municipality than its parent was accepted';
    exception when foreign_key_violation then null; end;

    -- an option on the wrong table, and an "Other" with nothing specified, are refused
    begin
      insert into public.khld_activity_option (activity_id, municipality_id, question_code, option_id)
      select v_act, v_khld, 'focus', id from public.ref_khld_c2_focus where code = 'minor_repairs';
      raise exception '0145: a campaign question was accepted on an activity';
    exception when check_violation then null; end;
    begin
      insert into public.khld_activity_option (activity_id, municipality_id, question_code, option_id)
      select v_act, v_khld, 'issues', id from public.ref_khld_d1_issues where code = 'other';
      raise exception '0145: Other without its text was accepted';
    exception when check_violation then null; end;
    insert into public.khld_activity_option (activity_id, municipality_id, question_code, option_id, option_other)
    select v_act, v_khld, 'issues', id, 'the probe' from public.ref_khld_d1_issues where code = 'other';
    raise exception using errcode = 'P0145', message = 'rollback the probe';
  exception
    when sqlstate 'P0145' then null;
  end;
  if exists (select 1 from public.person where national_id = '399000997')
     or exists (select 1 from public.khld_milestone_verification) or exists (select 1 from public.khld_volunteer)
     or exists (select 1 from public.khld_enterprise) or exists (select 1 from public.khld_activity)
     or exists (select 1 from public.khld_attendance) or exists (select 1 from public.khld_reference_counter) then
    raise exception '0145: probe rows survived the rollback';
  end if;
end $verify$;
