-- Applied via the Supabase MCP; this file records that it ran and in what
-- order. The authoritative text is in supabase_migrations.schema_migrations on
-- the linked project. See the migration's own header comment there for the
-- reasoning, which is deliberately long -- these encode counting rules.
