-- ═══════════════════════════════════════════════════════════════════════════
--  0158 — Khalidiyah's forms, what the tables share: a third identifier on
--         person, the field a file answers, the question map, the file
--         fields, and the rules between fields as data
--
--  GENERATED by supabase/khalidiyah/gen_schema.py from the catalogue.
--
--  ── person.other_id_number ──
--
--  The three ID-type lists (F144, F151, F156) offer "Other ID", and a person
--  with neither a national ID nor a UNHCR number could not be saved
--  (person_has_identifier). A third identifier is added beside the other
--  two: normalised like the UNHCR number, unique, immutable like them
--  (guard_person_national_id, extended from its LIVE body), no format
--  checked -- no source gives one (06_OPEN_QUESTIONS.md). Sahel Horan and
--  Ramtha never write it, and nothing they read changes.
--
--  ── attachment.field_code ──
--
--  A file-upload field (F017 meeting minutes, F120 attendance sheet ...) is
--  evidence on the record, and the row says which field it answers. Null for
--  every attachment outside Khalidiyah. khld_file_field says which fields
--  take files and how many ("5 max"); guard_khld_attachment_field holds an
--  attachment to it. attachment_entity_type_known gains the new tables,
--  appended to its live definition (a name the retired forms already used
--  is not named twice; the retired names stay for the row that names one).
--
--  ── the rules between fields ──
--
--  Every "Dependency" the sheet states ("if F029 = Yes", "if F126 = Held",
--  "if F194 in (Established, Updated)" ...) is one row of khld_field_rule,
--  generated from the catalogue entry the screen reads too: the field is
--  required while its answer is chosen (when the sheet marks it required),
--  and BLANK while it is not -- a stray value on a branch not taken is
--  refused (the lesson of the first forms, KHALIDIYAH_REPORT.md section 7).
--  FORM-19's consent (F158, "if no then end survey") governs every other
--  answer on that form the same way. guard_khld_rules reads the rows for
--  the table it fires on, so the rule lives once, as data; each refusal is
--  named khld_<field>_required / khld_<field>_not_applicable. The three
--  rules that look at another table -- a person registered on the form the
--  sheet names, a partner who confirmed (F174), a market that was held
--  (F207) -- are written out below. The rules a row trigger cannot see (a
--  multi-select or a partner list that must or must not have rows) are
--  checked by save_khld_record after the children are written (0161).
-- ═══════════════════════════════════════════════════════════════════════════

create temp table _0158_attachment_check_before on commit drop as
  select pg_get_constraintdef(oid) as def
    from pg_constraint where conrelid = 'public.attachment'::regclass and conname = 'attachment_entity_type_known';

-- ── 1. person: a third identifier ─────────────────────────────────────────
alter table public.person add column other_id_number text;
alter table public.person add constraint other_id_number_not_blank check (other_id_number is null or btrim(other_id_number) <> '');
alter table public.person drop constraint person_has_identifier;
alter table public.person add constraint person_has_identifier
  check (national_id is not null or unhcr_number is not null or other_id_number is not null);
create unique index person_other_id_number_key on public.person (other_id_number) where other_id_number is not null;
comment on column public.person.other_id_number is
  'An identity document that is neither a Jordanian national ID nor a UNHCR registration '
  '("Other ID", Khalidiyah FORM-12 / -15 / -17). Trimmed, upper-cased, inner spaces '
  'collapsed; no format checked. Unique; immutable once set. 0158.';

create function public.normalise_person_other_id_number()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.other_id_number is not null then
    new.other_id_number := nullif(upper(regexp_replace(btrim(new.other_id_number), '\s+', ' ', 'g')), '');
  end if;
  return new;
end $$;
revoke all on function public.normalise_person_other_id_number() from public, anon, authenticated;
create trigger trg_person_other_id_normalise before insert or update of other_id_number on public.person
  for each row execute function public.normalise_person_other_id_number();

-- from its LIVE body (pg_get_functiondef, 26 September 2026), a third branch
create or replace function public.guard_person_national_id()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
begin
  if new.national_id is distinct from old.national_id
     and coalesce(public.current_role()::text, 'participant') not in ('coordinator', 'super_admin') then
    raise exception 'national_id cannot be changed';
  end if;
  if new.unhcr_number is distinct from old.unhcr_number
     and coalesce(public.current_role()::text, 'participant') not in ('coordinator', 'super_admin') then
    raise exception 'unhcr_number cannot be changed';
  end if;
  if new.other_id_number is distinct from old.other_id_number
     and coalesce(public.current_role()::text, 'participant') not in ('coordinator', 'super_admin') then
    raise exception 'other_id_number cannot be changed';
  end if;
  return new;
end $function$;

-- ── 2. evidence: the field a file answers ─────────────────────────────────
alter table public.attachment add column field_code text
  constraint attachment_field_code_shape check (field_code is null or field_code ~ '^F[0-9]{3}$');
create index attachment_entity_field_idx on public.attachment (entity_type, entity_id, field_code);
comment on column public.attachment.field_code is
  'The Khalidiyah Field ID a file answers (F017, F120 ...); null for every other attachment. 0158.';

do $check$
declare
  v_def  text;
  v_add  text := '';
  v_name text;
begin
  select def into v_def from _0158_attachment_check_before;
  if v_def !~ '^CHECK \(\(entity_type = ANY \(ARRAY\[' or v_def !~ '\]\)\)\)$' then
    raise exception '0158: attachment_entity_type_known is not the shape this migration appends to: %', v_def;
  end if;
  foreach v_name in array array['khld_focal_point', 'khld_partner', 'khld_partner_contact', 'khld_meeting', 'khld_rehab_report', 'khld_campaign', 'khld_activity', 'khld_activity_attendance', 'khld_committee_member', 'khld_committee_meeting', 'khld_volunteer', 'khld_volunteer_attendance', 'khld_guidance_session', 'khld_enterprise_request', 'khld_market', 'khld_vendor_application', 'khld_market_attendance', 'khld_park_survey', 'khld_partner_survey', 'khld_contribution', 'khld_milestone_record', 'khld_enterprise_support', 'khld_producer_survey'] loop
    if position(format('''%s''::text', v_name) in v_def) = 0 then
      v_add := v_add || format(', %L::text', v_name);
    end if;
  end loop;
  v_def := regexp_replace(v_def, '\]\)\)\)$', v_add || '])))');
  execute 'alter table public.attachment drop constraint attachment_entity_type_known';
  execute 'alter table public.attachment add constraint attachment_entity_type_known ' || v_def;
end $check$;

create table public.khld_file_field (
  table_name  text not null,
  field_code  text not null check (field_code ~ '^F[0-9]{3}$'),
  max_files   int  not null check (max_files between 1 and 20),
  required    boolean not null,
  primary key (table_name, field_code)
);
alter table public.khld_file_field enable row level security;
create policy khld_file_field_read on public.khld_file_field for select to authenticated using (true);
revoke insert, update, delete on public.khld_file_field from anon, authenticated;
comment on table public.khld_file_field is
  'The file-upload fields of the Khalidiyah forms: table, Field ID, how many files (the sheet''s '
  '"5 max"), whether the sheet requires one. Generated from the catalogue. 0158.';
insert into public.khld_file_field (table_name, field_code, max_files, required) values
  ('khld_meeting', 'F017', 5, true),
  ('khld_meeting', 'F120', 5, true),
  ('khld_contribution', 'F188', 5, false),
  ('khld_milestone_record', 'F196', 5, true),
  ('khld_rehab_report', 'F124', 5, true),
  ('khld_campaign', 'F128', 5, false),
  ('khld_activity_attendance', 'F047', 5, false),
  ('khld_activity_attendance', 'F137', 5, false),
  ('khld_committee_meeting', 'F052', 5, true);

create function public.guard_khld_attachment_field()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_max int;
  v_n   int;
begin
  if new.field_code is null or new.deleted_at is not null then
    return new;
  end if;
  select f.max_files into v_max from public.khld_file_field f
   where f.table_name = new.entity_type and f.field_code = new.field_code;
  if v_max is null then
    raise exception '% is not a file field of %', new.field_code, new.entity_type
      using errcode = 'check_violation', constraint = 'attachment_field_code_known';
  end if;
  select count(*) into v_n from public.attachment a
   where a.entity_type = new.entity_type and a.entity_id = new.entity_id and a.field_code = new.field_code
     and a.deleted_at is null and a.id <> new.id;
  if v_n >= v_max then
    raise exception '% takes at most % files', new.field_code, v_max
      using errcode = 'check_violation', constraint = 'attachment_field_code_max_files';
  end if;
  return new;
end $$;
revoke all on function public.guard_khld_attachment_field() from public, anon, authenticated;
create trigger trg_attachment_khld_field before insert or update of field_code, deleted_at on public.attachment
  for each row execute function public.guard_khld_attachment_field();

-- ── 3. the question map (read by guard_khld_option, 0144) ─────────────────
create table public.khld_question_list (
  table_name    text not null,
  question_code text not null,
  list_name     text not null,
  kind          text not null check (kind in ('option')),
  primary key (table_name, question_code)
);
alter table public.khld_question_list enable row level security;
create policy khld_question_list_read on public.khld_question_list for select to authenticated using (true);
revoke insert, update, delete on public.khld_question_list from anon, authenticated;
comment on table public.khld_question_list is
  'Which ref_khld_ list each multi-select question of each khld_*_option junction reads. '
  'Read by guard_khld_option (0144). Generated from the catalogue. 0158.';
insert into public.khld_question_list (table_name, question_code, list_name, kind) values
  ('khld_rehab_report_option', 'f123', 'facility_type', 'option'),
  ('khld_campaign_option', 'f125', 'campaign_activity_type', 'option'),
  ('khld_activity_attendance_option', 'f045', 'nationality', 'option'),
  ('khld_volunteer_option', 'f064', 'volunteer_interest', 'option'),
  ('khld_volunteer_option', 'f065', 'weekday', 'option'),
  ('khld_volunteer_option', 'f066', 'time_of_day', 'option'),
  ('khld_milestone_record_option', 'f190', 'components_a1', 'option'),
  ('khld_milestone_record_option', 'f191', 'components_b1', 'option'),
  ('khld_milestone_record_option', 'f192', 'components_e1', 'option'),
  ('khld_milestone_record_option', 'f193', 'components_f1', 'option');

-- ── 4. the rules between fields, as data ──────────────────────────────────
create table public.khld_field_rule (
  table_name   text not null,
  field_code   text not null,
  column_name  text not null,
  required     boolean not null,
  conditions   jsonb not null,
  when_text    text not null,
  primary key (table_name, field_code)
);
alter table public.khld_field_rule enable row level security;
create policy khld_field_rule_read on public.khld_field_rule for select to authenticated using (true);
revoke insert, update, delete on public.khld_field_rule from anon, authenticated;
comment on table public.khld_field_rule is
  'One row per sheet Dependency, and per required multi-select: the field belongs to the answer '
  'the conditions describe -- [{column, list, codes}] a select whose code is one of these, '
  '[{column, bool}] a boolean, [{column, present}] a link that is set -- all of which must hold '
  '(none: always). Required while they hold when the sheet marks it required; blank while they '
  'do not. column_name is a column (guard_khld_rules), option:<question> (the rows of that '
  'multi-select) or partners (the partner junction), both checked by save_khld_record after the '
  'children are written (0161). Generated from the catalogue. 0158.';
insert into public.khld_field_rule (table_name, field_code, column_name, required, conditions, when_text) values
  ('khld_partner_contact', 'F015', 'evaluation_id', true, '[{"column":"attempt_case_id","list":"attempt_case","codes":["contacted"]}]', 'F013 is Contacted'),
  ('khld_partner_contact', 'F116', 'partnership_confirmed', true, '[{"column":"evaluation_id","list":"attempt_evaluation","codes":["interested"]}]', 'F015 is Interested'),
  ('khld_meeting', 'F118', 'partners', true, '[]', 'always'),
  ('khld_milestone_record', 'F190', 'option:f190', true, '[{"column":"milestone_id","list":"milestone","codes":["so1_a1"]}]', 'F189 is Partnership mechanism (SO1-A1)'),
  ('khld_milestone_record', 'F191', 'option:f191', true, '[{"column":"milestone_id","list":"milestone","codes":["so1_b1"]}]', 'F189 is Park use & activity arrangements (SO1-B1)'),
  ('khld_milestone_record', 'F192', 'option:f192', true, '[{"column":"milestone_id","list":"milestone","codes":["so3_e1"]}]', 'F189 is Community coordination committee (SO3-E1)'),
  ('khld_milestone_record', 'F193', 'option:f193', true, '[{"column":"milestone_id","list":"milestone","codes":["so3_f1"]}]', 'F189 is Volunteer programme (SO3-F1)'),
  ('khld_milestone_record', 'F195', 'status_date', true, '[{"column":"status_id","list":"milestone_status","codes":["established","updated"]}]', 'F194 is Established or Updated'),
  ('khld_rehab_report', 'F123', 'option:f123', true, '[]', 'always'),
  ('khld_campaign', 'F030', 'sponsor_name', true, '[{"column":"has_sponsor","bool":true}]', 'F029 is Yes'),
  ('khld_campaign', 'F125', 'option:f125', true, '[]', 'always'),
  ('khld_campaign', 'F127', 'action_days', true, '[{"column":"status_id","list":"event_status","codes":["held"]}]', 'F126 is Held'),
  ('khld_activity', 'F131', 'partners', true, '[{"column":"organiser_id","list":"organiser","codes":["municipality_with_partner"]}]', 'F036 is Municipality with partner'),
  ('khld_activity_attendance', 'F045', 'option:f045', true, '[]', 'always'),
  ('khld_park_survey', 'F160', 'activity_id', false, '[{"column":"consent","bool":true}]', 'F158 is Yes'),
  ('khld_park_survey', 'F161', 'sex_id', true, '[{"column":"consent","bool":true}]', 'F158 is Yes'),
  ('khld_park_survey', 'F162', 'age_group_id', true, '[{"column":"consent","bool":true}]', 'F158 is Yes'),
  ('khld_park_survey', 'F163', 'nationality_id', true, '[{"column":"consent","bool":true}]', 'F158 is Yes'),
  ('khld_park_survey', 'F164', 'disability_id', true, '[{"column":"consent","bool":true}]', 'F158 is Yes'),
  ('khld_park_survey', 'F165', 'is_resident', true, '[{"column":"consent","bool":true}]', 'F158 is Yes'),
  ('khld_park_survey', 'F166', 'interaction_score', true, '[{"column":"consent","bool":true}]', 'F158 is Yes'),
  ('khld_park_survey', 'F167', 'shared_participation', true, '[{"column":"consent","bool":true}]', 'F158 is Yes'),
  ('khld_park_survey', 'F168', 'safe_score', true, '[{"column":"consent","bool":true}]', 'F158 is Yes'),
  ('khld_park_survey', 'F169', 'welcoming_score', true, '[{"column":"consent","bool":true}]', 'F158 is Yes'),
  ('khld_park_survey', 'F170', 'satisfaction_score', true, '[{"column":"consent","bool":true}]', 'F158 is Yes'),
  ('khld_park_survey', 'F171', 'suitability_score', false, '[{"column":"consent","bool":true},{"column":"activity_id","present":true}]', 'F158 is Yes and F160 names an activity'),
  ('khld_park_survey', 'F172', 'suggestions', false, '[{"column":"consent","bool":true}]', 'F158 is Yes'),
  ('khld_volunteer', 'F064', 'option:f064', true, '[]', 'always'),
  ('khld_volunteer', 'F065', 'option:f065', true, '[]', 'always'),
  ('khld_volunteer', 'F066', 'option:f066', true, '[]', 'always'),
  ('khld_volunteer', 'F146', 'affiliation_name', false, '[{"column":"affiliation_id","list":"affiliation","codes":["school","university","cso","other"]}]', 'F145 is School or University / college or CSO / association or Other'),
  ('khld_enterprise_support', 'F200', 'session_id', true, '[{"column":"support_type_id","list":"support_type","codes":["guidance"]}]', 'F199 is Guidance session'),
  ('khld_enterprise_support', 'F201', 'attended', true, '[{"column":"support_type_id","list":"support_type","codes":["guidance"]}]', 'F199 is Guidance session'),
  ('khld_enterprise_support', 'F202', 'referred_to', true, '[{"column":"support_type_id","list":"support_type","codes":["referral"]}]', 'F199 is Referral to training / technical partner'),
  ('khld_market', 'F099', 'sponsor_name', true, '[{"column":"has_sponsor","bool":true}]', 'F098 is Yes'),
  ('khld_producer_survey', 'F211', 'sales_value_jod', false, '[{"column":"made_sales","bool":true}]', 'F210 is Yes');

-- Do the conditions of a rule hold for a row? An unanswered governing
-- answer means "not chosen": the field it governs must then be blank.
create function public.khld_rule_on(p_row jsonb, p_conditions jsonb)
returns boolean
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  c      jsonb;
  v_code text;
begin
  for c in select value from jsonb_array_elements(p_conditions) loop
    if c ? 'list' then
      v_code := null;
      if p_row ->> (c ->> 'column') is not null then
        execute format('select code from public.%I where id = $1', 'ref_khld_' || (c ->> 'list'))
          into v_code using (p_row ->> (c ->> 'column'))::uuid;
      end if;
      if not coalesce(v_code in (select jsonb_array_elements_text(c -> 'codes')), false) then
        return false;
      end if;
    elsif c ? 'bool' then
      if not coalesce((p_row ->> (c ->> 'column'))::boolean = (c ->> 'bool')::boolean, false) then
        return false;
      end if;
    elsif (p_row ->> (c ->> 'column')) is null then
      return false;
    end if;
  end loop;
  return true;
end $$;
revoke all on function public.khld_rule_on(jsonb, jsonb) from public, anon;
grant execute on function public.khld_rule_on(jsonb, jsonb) to authenticated;

create function public.guard_khld_rules()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row  jsonb := to_jsonb(new);
  r      record;
  v_on   boolean;
begin
  for r in select * from public.khld_field_rule
            where table_name = tg_table_name and column_name !~ ':' and column_name <> 'partners' loop
    v_on := public.khld_rule_on(v_row, r.conditions);
    if v_on and r.required and (v_row ->> r.column_name) is null then
      raise exception '% is required when %', r.field_code, r.when_text
        using errcode = 'check_violation', constraint = 'khld_' || lower(r.field_code) || '_required';
    end if;
    if not v_on and (v_row ->> r.column_name) is not null then
      raise exception '% belongs to the answer "%", which is not chosen, so it must be blank', r.field_code, r.when_text
        using errcode = 'check_violation', constraint = 'khld_' || lower(r.field_code) || '_not_applicable';
    end if;
  end loop;

  -- The four rules that look at another table. Each reads NEW's columns
  -- inside its own table's branch: PL/pgSQL prepares a whole condition, so a
  -- column another table does not have may not appear in a test that fires
  -- on it, even behind a false tg_table_name.
  if tg_table_name in ('khld_market_attendance', 'khld_producer_survey') then
    -- F112 / F206: a vendor registered on FORM-17
    if not exists (select 1 from public.khld_vendor_application s
                    where s.person_id = new.person_id and s.municipality_id = new.municipality_id and s.deleted_at is null) then
      raise exception '%: the person must be registered on FORM-17', case tg_table_name when 'khld_market_attendance' then 'F112' else 'F206' end
        using errcode = 'check_violation', constraint = 'khld_person_registered';
    end if;
  end if;
  if tg_table_name = 'khld_enterprise_support' then
    -- F197: an owner who asked on FORM-15
    if not exists (select 1 from public.khld_enterprise_request s
                    where s.person_id = new.person_id and s.municipality_id = new.municipality_id and s.deleted_at is null) then
      raise exception 'F197: the enterprise owner must have an attendance request on FORM-15'
        using errcode = 'check_violation', constraint = 'khld_person_registered';
    end if;
  end if;
  if tg_table_name = 'khld_partner_survey' then
    -- F174: "prepopulated <F004> where F116 = Yes"
    if not exists (select 1 from public.khld_partner_contact c
                    where c.partner_id = new.partner_id and c.partnership_confirmed and c.deleted_at is null) then
      raise exception 'F174: the partner must have confirmed the partnership (FORM-04 F116 = Yes)'
        using errcode = 'check_violation', constraint = 'khld_f174_confirmed_partner';
    end if;
  end if;
  if tg_table_name = 'khld_producer_survey' then
    -- F207: "prepopulated FORM-16 <F091> where F154 = Held"
    if not exists (select 1 from public.khld_market k join public.ref_khld_event_status s on s.id = k.status_id
                    where k.id = new.market_id and s.code = 'held' and k.deleted_at is null) then
      raise exception 'F207: the market must be one that was held (FORM-16 F154 = Held)'
        using errcode = 'check_violation', constraint = 'khld_f207_market_held';
    end if;
  end if;
  return new;
end $$;
revoke all on function public.guard_khld_rules() from public, anon, authenticated;
comment on function public.guard_khld_rules() is
  'BEFORE INSERT OR UPDATE on the Khalidiyah tables: the khld_field_rule rows of the table, '
  'and the four rules that look at another table. 0158.';

-- ── 5. the review of a public volunteer registration, stamped ─────────────
create function public.khld_stamp_review()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.application_status is distinct from old.application_status then
    new.reviewed_by := auth.uid();
    new.reviewed_on := now();
  end if;
  return new;
end $$;
revoke all on function public.khld_stamp_review() from public, anon, authenticated;

-- ── verification ─────────────────────────────────────────────────────────
do $verify$
declare
  v_old text;
  v_new text;
  v_name text;
begin
  -- the attachment check kept every table it named, in order, and names the new ones
  select def into v_old from _0158_attachment_check_before;
  select pg_get_constraintdef(oid) into v_new from pg_constraint
   where conrelid = 'public.attachment'::regclass and conname = 'attachment_entity_type_known';
  if position(regexp_replace(v_old, '\]\)\)\)$', '') in v_new) <> 1 then
    raise exception '0158: the attachment check was not appended to: %', v_new;
  end if;
  foreach v_name in array array['khld_focal_point', 'khld_partner', 'khld_partner_contact', 'khld_meeting', 'khld_rehab_report', 'khld_campaign', 'khld_activity', 'khld_activity_attendance', 'khld_committee_member', 'khld_committee_meeting', 'khld_volunteer', 'khld_volunteer_attendance', 'khld_guidance_session', 'khld_enterprise_request', 'khld_market', 'khld_vendor_application', 'khld_market_attendance', 'khld_park_survey', 'khld_partner_survey', 'khld_contribution', 'khld_milestone_record', 'khld_enterprise_support', 'khld_producer_survey'] loop
    if position(format('''%s''::text', v_name) in v_new) = 0 then
      raise exception '0158: the attachment check does not name %', v_name;
    end if;
  end loop;
  -- a person with an other ID alone can be saved and is normalised; one with none cannot
  begin
    insert into public.person (full_name, other_id_number, date_of_birth) values ('0158 probe', ' ab  12 ', '1990-01-01');
    if not exists (select 1 from public.person where other_id_number = 'AB 12') then
      raise exception '0158: other_id_number was not normalised';
    end if;
    raise exception using errcode = 'P0158', message = 'rollback';
  exception when sqlstate 'P0158' then null;
  end;
  begin
    insert into public.person (full_name, date_of_birth) values ('0158 probe', '1990-01-01');
    raise exception '0158: a person with no identifier was saved';
  exception when check_violation then
    if sqlerrm !~ 'person_has_identifier' then raise; end if;
  end;
  if exists (select 1 from public.person where full_name = '0158 probe') then
    raise exception '0158: probe rows survived the rollback';
  end if;
  if (select count(*) from public.khld_field_rule) <> 36 or (select count(*) from public.khld_file_field) <> 9
     or (select count(*) from public.khld_question_list) <> 10 then
    raise exception '0158: the rule, file-field or question rows are not the catalogue''s';
  end if;
end $verify$;
